### ISSUE TITLE
Vaadin 24.4.12 @Push and iOS18 Problem

### ISSUE THREAD

**Issue by janarbis** [vaadin/flow#20010] opened 2024-09-20 08:07 UTC
### Description of the bug

Since the new iOS18 Update on iPhone we get the following Warning when using push():
`WARN com.vaadin.flow.server.communication.ServerRpcHandler -- Resynchronizing UI by client's request. A network message was lost before reaching the client and the client is reloading the full UI state. This typically happens because of a bad network connection with packet loss or because of some part of the network infrastructure (load balancer, proxy) terminating a push (websocket or long-polling) connection. If you are using push with a proxy, make sure the push timeout is set to be smaller than the proxy connection timeout
`
wich leads into a white screen. The App needs to be refreshed after that.

In my dev machine I only use tomcat 10, no vpn, no loadbalancer or similar. The Connection is stable as well.
The problem only occures if i use the ssl connector of the tomcat. With HTTP their is no problem, but this is not the solution.

### Expected behavior

No Warning 

### Minimal reproducible example

We use the @Push annotation at our main route. The problem occures if we want to update the UI from an backround task with 
`		UI.getCurrent().access(() -> {
			UI.getCurrent().push()
		});`

### Versions

- Vaadin / Flow version: 24.4.12
- Java version: 17
- OS version: iOS18 (iPhone)
- Browser version: Safari 
- Application Server: Tomcat 10
- IDE:  Eclipse

**Comment by janarbis** [comment] 2024-10-05 09:51
Maybe this small example helps you to investigate the problem:
````
@Viewport("width=device-width, initial-scale=1, maximum-scale=1")
@Push(PushMode.MANUAL) 
public class PushTestAppShellConfigurator implements AppShellConfigurator {
}
````
````
@Route("")
public class PushTestView extends Div {

	private VerticalLayout vl;

	public PushTestView() {
		vl = new VerticalLayout();
		NativeButton button = new NativeButton("Add labels via push",
				event -> addLabel());
//				event -> new Thread(this::addLabel).start());
		add(button, vl);
	}

	private void addLabel() {
		long threadId = Thread.currentThread().getId();
//		getUI().ifPresent(ui -> ui.access(() -> {
		UI.getCurrent().access(() -> {
			
			vl.removeAll();
			for (int i = 0; i < 10; i++) {
				vl.add(new NativeLabel("Label " + i + " added via push by thread " + threadId));
//				ui.push();
				UI.getCurrent().push();
			}
		});
//		}));
//		Thread.currentThread().interrupt();
	}
}
````

If you press the Button on iPhone (iOs18) multiple times the problem will occures.
I also get the following error when putting the app in background:
````
11:49:04.887 [https-openssl-nio-8443-exec-7] DEBUG org.atmosphere.container.JSR356Endpoint -- Problem in web socket session
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at org.apache.tomcat.util.net.SecureNioChannel.read(SecureNioChannel.java:601)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1294)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1247)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1191)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:74)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

**Comment by cedricopfermann** [comment] 2024-10-23 16:38
Hi,
Have you managed to solve this issue ? We are having the same problem which is happening very often.
Regards,

**Comment by janarbis** [comment] 2024-10-24 09:22
Hello,
unfortunately not. We hope for the next ios 18.1 update. In the meantime the users are using chrome/edge.
Regards

**Comment by janarbis** [comment] 2024-10-29 08:13
Same Problems with iOS 18.1.

**Comment by cedricopfermann** [comment] 2024-10-29 08:33
I managed to find the cause of our resynchronization issue.
It was caused by some ui.access calls in a separate Thread (not in the UI thread), so I just removed the the async part, which is not synch-ed with the UI thread and everything is fine, even on a flaky connection. 
My understanding is that when a page is loaded (navigation), the thread ends and calls the ui.access and pushes the content to the client, but on a bad connection, le page may not be loaded yet, which causes a resynch...

**Comment by cedricopfermann** [comment] 2024-10-29 09:04
@TatuLund 
A solution would be to detect the end of the page load on the client side and buffer up all the 'push' messages till the client has not finished page load.

**Comment by janarbis** [comment] 2024-10-31 14:21
I have found the problem. It was a apple bug. Go to safari settings and open the webKit-Feature Flags. Search for "Enable experimental network loader". It seems that it is not active, but it is. Enable it and disable it directly.

https://forums.developer.apple.com/forums/thread/764420

**Comment by mshabarov** [comment] 2024-11-05 11:43
@cedricopfermann I'd like to close this issue because @janarbis found the solution for Safari (thanks for your investigation @janarbis by the way 👍 ). Let's create a new issue if you still experiencing these resync warnings.

**Closed by mshabarov** 2024-11-05 11:43 UTC
Labels: investigation
