### ISSUE TITLE
Consider supporting @Nullable in Java-to-TypeScript type mapping

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7371] opened 2020-01-16 12:54 UTC
When exporting a Java method that returns a nullable value, I want to use the `@Nullable` annotation on the return value type, so that I can use `List<@Nullable User>` instead of `List<Optional<User>>` in Java in order to have an `Array<User | undefined>` in TypeScript.

As mentioned in https://vaadin.com/docs/v15/flow/typescript/type-conversion.html, the TypeScript type generator in the Vaadin Maven plugin by default assumes _non-null_ when generating TypeScript types from Java types. For example, Java `User` is mapped to `User` in TypeScript and not to `User | undefined` or `User | null`.

In order to generate a _nullable_ TS type, the Java type needs to be somehow marked as nullable so that the TS generator does not apply the default type mapping rules. In Vaadin 15 this is done by wrapping the Java type into an `Optional`. However, that leads to `List<Optional<User>>` which is not ideal because it invites methods taking `Optional` as an argument, which is [a bad practice](https://rules.sonarsource.com/java/RSPEC-3553). It would be great if, in addition to `Optional`, the Vaadin TypeScript type generator was accepting the `@Nullable` annotation on types, as in `List<@Nullable User>`.

As of Vaadin 15, the TS generator does support the `javax.annotation.Nullable` annotation, but that does not apply to types. This task is to investigate other options that would make it possible:
 - create an own `Nullable` annotation
 - find an existing `Nullable` annotation that, unlike `javax.annotation.Nullable`, can be placed on types

[SO suggests](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use) that `org.eclipse.jdt.annotation.Nullable` could be used for this purpose. Another option would be [`org.checkerframework.checker.nullness.qual.Nullable`](https://checkerframework.org/api/org/checkerframework/checker/nullness/qual/Nullable.html)

NOTE: the `@Null` and `@NotNull` annotations from the `javax.validation.constraints` package do not seem to be a good fit here because they require exactly null or exactly non-null. See https://docs.oracle.com/javaee/7/api/index.html?javax/validation/constraints/Null.html

**Comment by vlukashov** [comment] 2020-06-15 13:58
**Java `Optional` is not serializable**

[`@fluorumlabs`](https://github.com/fluorumlabs) has [pointed out](https://vaadin.slack.com/archives/CDNTYMS9H/p1592226597202000) that the Java `Optional` type is not serializable. That is, if I want my POJO to be serializable for any reason, and I also want to handle this POJO's possible `null` property values in TypeScript, I cannot do both (I'll have to choose one). Alternatively, I would have to create a `PojoWrapper` type in Java that is same as `Pojo`, but not serializable, and with `Optional` properties. This is boilerplate, and is another reason to consider alternatives to the use of `Optional` for signalling nullability.

The most common use case for Serializable POJOs in this context would probably be JPA entities.

**Comment by haijian-vaadin** [comment] 2020-10-02 12:32
Closed as a duplicate of #8849

**Closed by haijian-vaadin** 2020-10-02 12:32 UTC
Labels: ccdm
