### ISSUE TITLE
frontend compilation fails after upgrading to vaadin 23.1.0

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#13952] opened 2022-06-13 03:00 UTC
### Description of the bug

After upgrading to vaadin 23.1.0 I ran:

rm -rf target
rm -rf node_modules
npm i
mvn install

When I try to restart tomcat I get the following error:

```
13 12:57:22,617 http-nio-8080-exec-1 USER: [ERROR] (CustomExceptionHandler.java:36) - Uncaught UI exception
[m java.lang.IllegalStateException: Startup of Webpack failed. Output was:
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/home/bsutton/git/onepub/onepub_vaadin/node_modules/.pnpm/@webpack-cli+serve@1.7.0_8b27d5839a2bdf89ba2338e4c89fea10/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/home/bsutton/git/onepub/onepub_vaadin/node_modules/.pnpm/webpack-cli@4.9.2_9c3dcbfb57ee5c2fcb4d4b626946cc9c/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)

	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:219) ~[vaadin-dev-server-23.1.0.jar:?]
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:171) ~[vaadin-dev-server-23.1.0.jar:?]
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:162) ~[vaadin-dev-server-23.1.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

### Expected behavior

tomcat should start without an error.

### Minimal reproducible example

After upgrading to vaadin 23.1.0 I ran:

rm -rf target
rm -rf node_modules
npm i
mvn install

### Versions

- Vaadin / Flow version: 23.1.0
- Java version: OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
- OS version: Ubuntu: 22.04
- Browser version (if applicable):
- Application Server (if applicable): Apache Tomcat/9.0.36 
- IDE (if applicable): eclipse

**Comment by bsutton** [comment] 2022-06-13 03:16
So I switch to vite (by manually configuring the properties file) which bypassed the above error. 
However I'm now getting the following error:

```
13 13:14:12,980 ForkJoinPool.commonPool-worker-1 USER: [INFO] (TaskCopyFrontendFiles.java:66) - Copying frontend resources from jar files ...
[m[39m13 13:14:13,002 ForkJoinPool.commonPool-worker-1 USER: [INFO] (TaskCopyFrontendFiles.java:91) - Visited 27 resources. Took 22 ms.
[m[39m13 13:14:13,095 ForkJoinPool.commonPool-worker-1 USER: [INFO] (AbstractDevServerRunner.java:205) - Starting Vite
[m[39m13 13:14:13,123 ForkJoinPool.commonPool-worker-1 USER: [INFO] (FrontendTools.java:541) - The globally installed Node.js version 12.22.9 is older than the required minimum version 16.14.0. Using Node.js from /home/bsutton/.vaadin.
[m[38;5;35m
------------------ Starting Frontend compilation. ------------------
[0m[39m13 13:14:13,321 ForkJoinPool.commonPool-worker-1 USER: [INFO] (AbstractDevServerRunner.java:389) - Running Vite to compile frontend resources. This may take a moment, please stand by...
[m[39m13 13:14:13,863 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - Searching themes folder '/home/bsutton/git/onepub/onepub-vaadin/frontend/themes' for theme 'OnePub'
[m[39m13 13:14:13,863 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - no assets to handle no static assets were copied
[m[39m13 13:14:13,874 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - Found theme files from '/home/bsutton/git/onepub/onepub-vaadin/frontend/themes'
[m[39m13 13:14:14,036 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
[m[39m13 13:14:14,380 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:14,380 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -   vite v2.9.1 dev server running at:
[m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -   > Local: http://localhost:35661/VAADIN/
[m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -   > Network: use `--host` to expose
[m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -   ready in 1031ms.
[m[38;5;35m
----------------- Frontend compiled successfully. -----------------

[0m[39m13 13:14:14,381 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:14,381 ForkJoinPool.commonPool-worker-1 USER: [INFO] (AbstractDevServerRunner.java:223) - Started Vite. Time: 1286ms
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -  ERROR(TypeScript)  Cannot find module './theme' or its corresponding type declarations.
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -  FILE  /home/bsutton/git/onepub/onepub_vaadin/frontend/generated/vaadin.ts:7:28
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -     5 | import '@vaadin/flow-frontend/vaadin-dev-tools.js';
[m[39m13 13:14:16,119 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -     6 |
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -   > 7 | import { applyTheme } from './theme';
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -       |                            ^^^^^^^^^
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -     8 | applyTheme(document);
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) -     9 |
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:14:16,120 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - Found 1 error. Watching for file changes.
[m
```

I have had this error with earlier versions of vaadin 23, but it seems to come and go.

**Comment by bsutton** [comment] 2022-06-13 03:23
Possibly helpful?

I have a file theme.js:
```
import {applyTheme as _applyTheme} from './theme-OnePub.generated.js';
export const applyTheme = _applyTheme;
```
There is a largis generated file called
theme-OnePub.generated.js

And vaadin.ts contains:
```
import './vaadin-featureflags.ts';

import './index';

import '@vaadin/flow-frontend/vaadin-dev-tools.js';

import { applyTheme } from './theme';
applyTheme(document);

```

**Comment by bsutton** [comment] 2022-06-13 03:25
I deleted frontend/generated.
After running mvn install I ended up with an index.ts which contained an error:

  imports: () => import('../../target/frontend/generated-flow-imports')

The generated-flow-imports file doesn't exist.

**Comment by bsutton** [comment] 2022-06-13 03:29
I ignored the above error and tried to start tomcat.
I'm now getting:

```
13 13:26:04,537 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - The request url "/home/bsutton/git/onepub/onepub_vaadin/frontend/generated/vaadin.ts" is outside of Vite serving allow list.
[m[39m13 13:26:04,537 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:26:04,537 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub-vaadin/frontend
[m[39m13 13:26:04,538 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub_vaadin/target/flow-frontend
[m[39m13 13:26:04,538 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub_vaadin/target/frontend
[m[39m13 13:26:04,538 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub-vaadin/node_modules
[m[39m13 13:26:04,538 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub-vaadin/frontend
[m[39m13 13:26:04,539 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub_vaadin/target/flow-frontend
[m[39m13 13:26:04,539 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub_vaadin/target/frontend
[m[39m13 13:26:04,539 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub-vaadin/node_modules
[m[39m13 13:26:04,539 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - - /home/bsutton/git/onepub/onepub_vaadin/node_modules/.pnpm/vite@2.9.1/node_modules/vite/dist/client
[m[39m13 13:26:04,540 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:26:04,540 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.
[m[39m13 13:26:04,540 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - 
[m[39m13 13:26:04,637 dev-server-output USER: [INFO] (DevServerOutputTracker.java:110) - The request url "/home/bsutton/git/onepub/onepub_vaadin/frontend/generated/vaadin.ts" is outside of Vite serving allow list.
```

**Comment by caalador** [comment] 2022-06-13 08:17
It would seem that webpack 4.9 is not compatible with cli 1.7 see https://github.com/webpack/webpack-cli/issues/3294

As a workaround before a fix, defining the @webpack-cli/serve package.json dependency to v1.6.1 should fix the initial problem.

**Comment by enver-haase** [comment] 2022-06-13 13:07
> It would seem that webpack-cli 4.9 is not compatible with cli/serve 1.7 see [webpack/webpack-cli#3294](https://github.com/webpack/webpack-cli/issues/3294)
> 
> As a workaround before a fix, defining the @webpack-cli/serve package.json dependency to v1.6.1 should fix the initial problem.

I had more luck with version 4.10.0 as in https://github.com/vaadin/flow/pull/13954.

**Comment by rlsutton1** [comment] 2022-06-14 01:43
> It would seem that webpack-cli 4.9 is not compatible with cli/serve 1.7 see [webpack/webpack-cli#3294](https://github.com/webpack/webpack-cli/issues/3294)
> 
> As a workaround before a fix, defining the @webpack-cli/serve package.json dependency to v1.6.1 should fix the initial problem.

To help others that come after, the file is package.json in the root of your project.

The syntax is "@webpack-cli/serve": "1.6.1"

and adding it to all of these sections seems to work...

"dependencies": {
...
"@webpack-cli/serve": "1.6.1"
} 

"devDependencies": {
...
"@webpack-cli/serve": "1.6.1"
} 

"vaadin: {dependencies: {
...
"@webpack-cli/serve": "1.6.1"
} }" 

"vaadin: {devDependencies: {
...
"@webpack-cli/serve": "1.6.1"
} }"

**Comment by caalador** [comment] 2022-06-14 03:44
The change to make in the package.json would be:
```
"devDependencies": {
   "@webpack-cli/serve" : "1.6.1"
   ...
}
```
Or run `npm i @webpack-cli/serve@1.6.1 --save-dev`

One thing to note on manual changes to package.json is that you shouldn't touch the `vaadin{}` object as that is used by the framework to check if the dependencies are manually altered or added to the package.json.

So if a item and version match in both dependencies and vaadin - dependencies or devDependencies and vaadin - devDependencies then the framework can automatically update or remove dependencies, which it will not do if the item is missing or has another version inside the vaadin object

**Comment by TatuLund** [comment] 2022-06-14 05:20
> I've reverted to 23.0.11

The problem is not related to Vaadin 23.1.0. The fix will be introduced also in Vaadin 23.0 and Vaadin 14.8.

**Comment by bsutton** [comment] 2022-06-14 06:30
I think this command is problematic:

```
npm i @webpack-cli/serve@1.6.1 --save-dev
```
I ended up with 
```
"@webpack-cli/serve": "^1.6.1",
```
Note the ^, which seems to result in it still running 1.7.x

I was flailing about somewhat to get this to work so can't be certain the --save-dev command did the damage.

**Comment by Artur-** [comment] 2022-06-14 07:36
Instead of downgrading, maybe upgrading is easier
```
npm i webpack-cli@^4.10.0
```

**Comment by stefanuebe** [comment] 2022-06-15 04:54
Since Vaadin 22 is also still maintained, we also need to provide the fix there.

**Comment by stefanuebe** [comment] 2022-06-15 05:13
> Instead of downgrading, maybe upgrading is easier
> 
> ```
> npm i webpack-cli@^4.10.0
> ```

Works also for Vaadin 22.

**Comment by enver-haase** [comment] 2022-06-16 09:53
Dear Vaadin-Bot, which version is this in Vaadin 23 terms?

**Comment by mstahv** [comment] 2022-06-17 07:56
23.1.1 is fresh out of oven.

**Comment by mshabarov** [comment] 2022-06-17 07:57
This issue has been fixed in [V23.1.1](https://github.com/vaadin/platform/releases/tag/23.1.1), [V23.0.12](https://github.com/vaadin/platform/releases/tag/23.0.12) and [V22.0.17](https://github.com/vaadin/platform/releases/tag/22.0.17). 

Vaadin 14.8 and 10.0 have no such an issue.

Please let us know if you still experience any issues with `webpack-cli` by commenting to this ticket or creating a new one.

**Comment by mshabarov** [comment] 2022-06-17 08:00
@bsutton could you create a separate ticket for the Vite errors you've experienced ?

I'm going to close this ticket.

**Comment by bsutton** [comment] 2022-06-17 08:00
Will do.

**Closed by mshabarov** 2022-06-17 08:00 UTC
Labels: bug, workaround, Impact: High, Severity: Blocker, Released with Vaadin 22.0.17
