### ISSUE TITLE
Creating a Custom Theme 14.6.beta.01

### ISSUE THREAD

**Issue by aze-kool** [vaadin/flow#10717] opened 2021-04-19 10:14 UTC
**What I am doing?** 
I have a Vaadin-Spring Boot project setup as Gradle project in eclipse. 
I am trying to create a custome theme As discussed in the article : https://vaadin.com/docs/v14/flow/styling/custom-theme.

**Whats the Problem ?** 
Unfortunatley, the frontend throws an error saying 

![image](https://user-images.githubusercontent.com/525056/115220365-bbf2e480-a108-11eb-94fa-14cfe30bc168.png)

I think the GradlePlugin is not compiling the theme. Is there something i missed?

Thanks and Best Regards

**Comment by miguelatvaadin** [comment] 2021-04-19 12:10
Hi @aze-kool ,

could you please provide more details so we can easily reproduce the issue? perhaps the project itself, if it was just a test project?

Thanks and best regards

**Comment by pleku** [comment] 2021-04-20 08:52
Discussed internally and this is because [the old unofficial gradle plugin](https://github.com/vaadin/vaadin-gradle-plugin) for v14 does not support this new v14.6 feature yet. We're taking a look on how to make it happen, but I cannot say when it will work. And as it is mentioned that the plugin's v14 version is _unofficial_, I'll downgrade the severity.

**Comment by caalador** [comment] 2021-05-06 06:09
This will be fixed with a new plugin release after 2.6.0 is out so that we build it against a release version.

In the meantime it is possible to try out the theme feature by downloading https://github.com/vaadin/vaadin-gradle-plugin/ and then having in the application project `./settings.gradle` file an include to the plugin download for instance `includeBuild("D:\\Code\\vaadin-gradle-plugin")`.

**Comment by mstahv** [comment] 2021-05-12 08:32
This should now be fixed with 0.14.6.0 version. Let us know if it is still an issue!

**Closed by mstahv** 2021-05-12 08:32 UTC
Labels: Impact: Low, Severity: Major, bug, gradle, theming

**Comment by pleku** [comment] 2021-05-12 10:28
https://plugins.gradle.org/plugin/com.vaadin/0.14.6.0
