### ISSUE TITLE
client-side exception when using callFunction from beforeClientResponse

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#2987] opened 2017-11-20 15:12 UTC
This happens when using `callFunction` in `beforeClientResponse` from a `Component` injected with `@Id` in a sub-template.
This is related to #2873 and #2817, verified with flow `1.0.0.alpha10`

### To reproduce this issue you need:
* A simple Component with some client-side API:
```
@Tag("example-component")
@HtmlImport("ExampleComponent.html")
public class ExampleComponent extends Component {
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        attachEvent.getUI().beforeClientResponse(this, () -> greet());
    }
    public void greet() {
        getElement().callFunction("greet");
    }
}
```
```
<dom-module id="example-component">
    <template>
    </template>
    <script>
        class ExampleComponent extends Polymer.Element {
            static get is() {
                return 'example-component'
            }
            greet(){
              window.alert('👋');
            }
        }
        customElements.define(ExampleComponent.is, ExampleComponent);
    </script>
</dom-module>
```

* One `PolymerTemplate` that will be a sub-template
```
@Tag("example-sub-template")
@HtmlImport("subtemplate/ExampleSubTemplate.html")
public class SubTemplate extends PolymerTemplate<TemplateModel> {
    @Id("component-id")
    private ExampleComponent component;
}
```
```
<dom-module id="example-sub-template">
    <template>
      <example-component id="component-id"></example-component>
    </template>

    <script>
        class ExampleSubTemplate extends Polymer.Element {
            static get is() {
                return 'example-sub-template'
            }
        }
        customElements.define(ExampleSubTemplate.is, ExampleSubTemplate);
    </script>
</dom-module>
```

* And a simple `PolymerTemplate` view including the sub-template
```
@Tag("example-super-template")
@HtmlImport("subtemplate/ExampleSuperTemplate.html")
@Route("nestedtemplate")
public class SuperTemplateView extends PolymerTemplate<TemplateModel> {
    public SuperTemplateView() {
    }
}
```

```
<dom-module id="example-super-template">
    <template>
      <example-sub-template></example-sub-template>
    </template>

    <script>
        class ExampleSuperTemplate extends Polymer.Element {
            static get is() {
                return 'example-super-template'
            }
        }
        customElements.define(ExampleSuperTemplate.is, ExampleSuperTemplate);
    </script>
</dom-module>
```

Expected result when navigating to the `nestedtemplate` route is to only see the result of `alert('👋')`.
Actual result is the greeting and the following exception:
>(TypeError) : Cannot read property 'greet' of undefined

Note: Adding `@Id`for the `SubTemplate` in `SuperTemplateView` has the same result

**Comment by denis-anisimov** [comment] 2017-11-27 10:33
In reality this bug is not about developer JS call at all.
The reported issue hides the original client-side exception which is caused by our internal code: the second level of "injection" doesn't work entirely.
We are calling our internal JS function to attach existing node on the client side for the `StateNode` which has not been yet bound because it's also a subject to attach. And out code doesn't expect this at all. So any nested injection is broken.

This has a number of causes:
- On the server side the order of calls makes it almost impossible to implement the feature via JS call. Attach listeners are called from the bottom to top. It means that `attachExistingElement`  will be called on the client side for the bottom leaf child before this function is called for the template-in-template element.
- On the client side even the correct order of calls won't work because async nature of the binding for this kind of nodes.

So we need to reimplement this "inject by id" and "template-in-template" features entirely.
I will create the tickets about this.

This one was an investigation ticket and I'm closing it.

**Closed by denis-anisimov** 2017-11-27 10:33 UTC
Labels: 0-team, app starter, bug, investigation

**Comment by denis-anisimov** [comment] 2017-11-27 11:19
#3057 and #3057 issues are created about the overall injecting functionality. 
We have to reimplement those features.

**Comment by denis-anisimov** [comment] 2017-11-27 11:20
Unfortunately there is no workaround for this at all.
Several level injection just doesn't work.
