### ISSUE TITLE
Binder issue with vaadin-12

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/flow#4877] opened 2018-12-17 10:22 UTC
![capture-vaadin12](https://user-images.githubusercontent.com/3875788/50081145-06d55800-01ee-11e9-9401-075063ff6087.PNG)

My combo-box field status is read only and prefilled but I have the message "Please enter a value" on UI.

```
statusComboBox.setItems(StatusEnum.values());       
binder.forField(statusComboBox)
        .asRequired(Phrase.ENTER_VALUE_MESSAGE)
        .bind(MyClass::getStatus, MyClass::setStatus);

binder.readBean(object);
```

The message disappear when I click on the label "Please enter a value"
It's work correclty with vaadin 10 and 11
Someone have an idea how to fix that on vaadin-12 ?

**Comment by denis-anisimov** [comment] 2018-12-17 12:34
Please provide s steps to reproduce which includes either a  code snippet which I may copy-paste as is or just an attached complete project based on https://github.com/vaadin/skeleton-starter-flow.

I cannot use your code as is since it has two classes whose declaration is absent.
As a result I have to either do reverse eng of your code our make the example from scratch.

**Comment by pleku** [comment] 2020-04-30 12:58
Since there has not been any response on this issue, I'm closing this one.

If the issue still persists, please open a new issue with instructions to reproduce the issue here or to https://github.com/vaadin/vaadin-combo-box-flow

**Closed by pleku** 2020-04-30 12:58 UTC
Labels: question
