### ISSUE TITLE
"Unexpected message id from the client" regularly

### ISSUE THREAD

**Issue by tfleige** [vaadin/flow#10190] opened 2021-03-04 06:31 UTC
### Description of the bug / feature
Regularly occurence of "Unexpected message id from the client" in logfile:

`2021-03-03 19:05:45,104 WARN  [com.vaadin.flow.server.communication.ServerRpcHandler] (default task-1993) Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues
2021-03-03 19:05:45,823 SEVERE [de.materna.msmc.flexx.servlet.FlexxRootServlet$FlexxExceptionHandler] (default task-1996) Unexpected message id from the client. Expected sync id: 47, got 46. Message start: {"csrfToken":"a68e008e-5def-455b-af87-4500ccb83743","rpc":[{"type":"event","node":475,"event":"value-changed","data":{}},{"type":"event","node":6,"event":"value-changed","data":{}},{"type":"event","node":1018,"event":"value-changed","data":{}},{"type":"event","node":1098,"event":"opened-changed"},{"type":"mSync","node":1018,"feature":1,"property":"filter","value":""},{"type":"mSync","node":1018,"feature":1,"property":"invalid","value":false},{"type":"mSync","node":1018,"feature":1,"property":"opened","value":false}],"syncId":61,"clientId":46}: java.lang.UnsupportedOperationException: Unexpected message id from the client. Expected sync id: 47, got 46. Message start: {"csrfToken":"a68e008e-5def-455b-af87-4500ccb83743","rpc":[{"type":"event","node":475,"event":"value-changed","data":{}},{"type":"event","node":6,"event":"value-changed","data":{}},{"type":"event","node":1018,"event":"value-changed","data":{}},{"type":"event","node":1098,"event":"opened-changed"},{"type":"mSync","node":1018,"feature":1,"property":"filter","value":""},{"type":"mSync","node":1018,"feature":1,"property":"invalid","value":false},{"type":"mSync","node":1018,"feature":1,"property":"opened","value":false}],"syncId":61,"clientId":46}
	at deployment.jh.ear.flexx.war//com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:307)
	at deployment.jh.ear.flexx.war//com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at deployment.jh.ear.flexx.war//com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at deployment.jh.ear.flexx.war//com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1547)
	at deployment.jh.ear.flexx.war//com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
	at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet@2.0.15.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.15.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.0.15.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet@2.0.15.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.15.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.jh.ear//waffle.servlet.NegotiateSecurityFilter.doFilterPrincipal(NegotiateSecurityFilter.java:295)
	at deployment.jh.ear//waffle.servlet.NegotiateSecurityFilter.doFilter(NegotiateSecurityFilter.java:157)
	at deployment.jh.ear.flexx.war//de.materna.msmc.flexx.sso.WaffleSSOFilter.doFilter(WaffleSSOFilter.java:75)
`

### Minimal reproducible example
n/a
### Expected behavior
no exception logging
### Actual behavior
Regularly occurence of "Unexpected message id from the client" in logfile
### Versions:
    - Vaadin / Flow version: 14.4.7
    - Java version: 11.0.10+8-jvmci-21.0-b06 / GraalVM CE 21.0.0.2
    - OS version: Windows
    - Browser version (if applicable): n/a
    - Application Server (if applicable): Wildfly 15.0.1
    - IDE (if applicable): n/a

**Comment by pleku** [comment] 2021-03-04 06:54
Thanks for the reported issue, but without any hints to when/how this occurs, we don't have anything to start the investigation with. I'm closing this as a duplicate of #9778.

**Closed by pleku** 2021-03-04 06:54 UTC
