### ISSUE TITLE
Error checking existance of static resources in Vaadin 24.3.5 and Jetty server 12

### ISSUE THREAD

**Issue by vlotarev** [vaadin/flow#18689] opened 2024-02-13 11:07 UTC
### Description of the bug

An errors like below occured on any static resource request preventing application from working normally. The problematic URI is resolved to (VaadinServletService at line  331 (!File.exists(...)) ):

`jar:file:///C:/Development/project/bin/project.jar!/BOOT-INF/lib/flow-push-24.3.5.jar!/META-INF/resources/VAADIN/static/push/vaadinPush-min.js`

`Feb 13 13:56:56.053 WARN  [qtp1076966140-92]  /sap/ui/VAADIN/static/push/vaadinPush-min.js (org.eclipse.jetty.ee10.servlet.ServletChannel:647) 
java.nio.file.FileSystemNotFoundException
	at jdk.zipfs@17.0.6/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:173) ~[jdk.zipfs:?]
	at jdk.zipfs@17.0.6/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:159) ~[jdk.zipfs:?]
	at java.base/java.nio.file.Path.of(Path.java:208) ~[?:?]
	at com.vaadin.flow.server.VaadinServletService.getStaticResource(VaadinServletService.java:331) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.server.VaadinServletService.getStaticResource(VaadinServletService.java:246) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.spring.SpringVaadinServletService.getStaticResource(SpringVaadinServletService.java:125) ~[vaadin-spring-24.3.5.jar!/:?]
	at com.vaadin.flow.server.StaticFileServer.getStaticResource(StaticFileServer.java:451) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.server.StaticFileServer.serveStaticResource(StaticFileServer.java:334) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:430) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:385) ~[flow-server-24.3.5.jar!/:24.3.5]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.3.5.jar!/:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195) ~[jetty-ee10-websocket-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at com.versonix.integrations.common.config.mvc.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:93) ~[sw-integrations-common-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.3.jar!/:6.1.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.3.jar!/:6.1.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar!/:6.1.3]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547) ~[jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:805) [jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:431) [jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464) [jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571) [jetty-security-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703) [jetty-ee10-servlet-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:763) [jetty-server-12.0.6.jar!/:12.0.6]
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:716) [jetty-server-12.0.6.jar!/:12.0.6]
`

### Expected behavior

No error is expected

### Minimal reproducible example

Not available (may be created if required)

### Versions

- Vaadin / Flow version: 24.3.5
- Java version: 17
- OS version: Windows 10

**Comment by mshabarov** [comment] 2024-02-13 12:03
This might be a regression from recently applied fix for Jetty 12, let us investigate.

**Comment by mcollovati** [comment] 2024-02-13 16:00
@vlotarev looks like the issue is because of resource in nested JAR.
Nested JAR support has been changed in Spring Boot 3.2.
I cannot reproduce the issue with the default configuration of Spring Boot Maven plugin, but I get the same error if I set `loaderImplementation=CLASSIC`.
Do you perhaps have set this plugin property?

**Comment by vlotarev** [comment] 2024-02-14 08:05
@mcollovati , I used Gradle to build application with Spring Boot Gradle plugin 3.1.5

**Comment by mcollovati** [comment] 2024-02-14 08:09
Make sense. The nested resource handling has been introduced in Spring Boot 3.2.
It is likely that if you upgrade to Spring Boot 3.2 the issue will disappear

**Comment by vlotarev** [comment] 2024-02-14 08:17
Yes, the problem goes away with Spring Boot plugin 3.2. Thank you @mcollovati! We can close this issue.

**Comment by mcollovati** [comment] 2024-02-14 08:18
I'll keep it open, since the Spring Boot plugin allows to fallback to legacy resource loader.
I'll check with the team if we may try to apply a fix anyway

**Comment by mcollovati** [comment] 2024-02-14 11:37
We discussed internally and agreed to close the issue without applying any change.
The reasons are:
* Vaadin 24.3 requires Spring Boot 3.2, that works with the default configuration
* hopefully future releases of Jetty 12 will fix the resource resolution, not returning a URL for non-existing resources, so the Flow patch could be removed

**Closed by mcollovati** 2024-02-14 11:37 UTC
Labels: investigation
