### ISSUE TITLE
Java example for "Grid with sortable columns" throws an exception when sort order is cleared

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#4482] opened 2018-08-03 12:01 UTC
Steps to reproduce:
1. Open https://vaadin.com/components/vaadin-grid/java-examples/sorting
2. Click any column three times
3. On the third click exception is thrown and page is reloaded

```
Caused by: java.lang.ClassCastException: elemental.json.impl.JreJsonNull cannot be cast to elemental.json.JsonString
	at elemental.json.impl.JreJsonObject.getString(JreJsonObject.java:113)
	at com.vaadin.flow.component.grid.Grid.sortersChanged(Grid.java:2013)
```

**Comment by Legioth** [comment] 2018-08-07 08:39
Already fixed in Grid 2.0 through https://github.com/vaadin/vaadin-grid-flow/pull/249. Should maybe be backported to the 1.0 series of Grid?

**Comment by denis-anisimov** [comment] 2018-08-18 10:50
I cannot reproduce it with the latest version.

I've added an IT test for this case and one more check in the code to avoid exception if `direction` value is `null`. May be this change is extra but anyway there is an IT test.

**Comment by pekam** [comment] 2018-08-20 12:33
Issue moved to [vaadin/vaadin-grid-flow #318](https://github.com/vaadin/vaadin-grid-flow/issues/318) via [**ZenHub**](https://www.zenhub.com/)

**Closed by pekam** 2018-08-20 12:33 UTC
Labels: bug
