### ISSUE TITLE
Custom Validator error message is removed on blur

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3230] opened 2017-12-30 08:39 UTC
when I have a custom validator and the text field is errored, the error should remain when I blur, but it is removed instead

For example given this code
```
binder.forField(customerNumber)
	.withValidator(number -> number.replaceAll("[ -]", "").matches("^\\+?(?:[0-9] ?){6,14}[0-9]$"),
		"type a valid phone number")
	.bind("customer.phoneNumber");
```

The error is removed on blur as shown in this screenshot

<img src="http://g.recordit.co/5midIT4iWa.gif">

**Comment by brp-jimmy** [comment] 2018-03-22 10:14
We have this problem as well in our project.

**Comment by ZheSun88** [comment] 2018-08-15 08:33
This behavior is caused because:

`Binder` is only called when there is value changing, meanwhile `Binder` disabled the `field`'s client side validation and enable it after the binder is used. 

For the `blur` event, the value in the field hasnt been changed, so `binder` is not called in this case, only the client side validation works which it doesn't apply the rules from users. in this case the the value just passes the check and the `invalid` attribute has been removed, together with `error message. ` 

From this point of view, the problem is not about `Binder`, but the client side needs some check logic to detect:
if former `Invalid` state is `true` and there is not value change event, the `Invalid` should stay `true` still.

**Comment by Klaudeta** [comment] 2019-02-19 11:05
@denis-anisimov 
fix introduced from [61bf823](https://github.com/vaadin/vaadin-text-field-flow/commit/61bf8236148ccc6f87be819679f49d5c08d19e45) seems to fix this issue here and also this other one [vaadin/flow/issues/4597](https://github.com/vaadin/flow/issues/4597).

But I can see that the changes weren't imported when the js file content was added inline the java class. Is there any specific reason?

**Comment by denis-anisimov** [comment] 2019-02-19 11:15
If the issues are not reproducible anymore then you may close them.

The fix is very specific for Binder and `setRequiredIndicatorVisible`  method.
If it's not mentioned in the ticket then it's either another issue or bad issue description.

>But I can see that the changes weren't imported when the js file content was added inline the java class. Is there any specific reason?

Which changes ? I don't understand what you are talking about.

**Comment by Klaudeta** [comment] 2019-02-19 11:19
It is still reproducible when the field is required and has a custom validation and if you go through this issue here, Zhe Sun did a commit that seemed to fix it, but that change is not in the latest JS code of the vaadin-text-field-flow (JS function disableClientValidation)

**Comment by denis-anisimov** [comment] 2019-02-19 11:25
`required` enables the client side validation.
It's expected and not an issue.

Either you use server side validation along with `Binder` (and may be `asRequired` which delegates to 
`setRequiredIndicatorVisible` ) or you use client side validation with `required`  (but then no server side validation).
You can't use both.

Zhe made a PR which has been closed as invalid. So it has never been committed into the code base.

I don't really know which change you mean.
Please refer to exact change with a link/code snippet to avoid misunderstanding and confusion in your comments. Otherwise it's kind of waste of time.

**Comment by Klaudeta** [comment] 2019-02-19 11:40
Ok, now I see the PR was closed as not valid and the explanation in there makes sense while nothing mentioned in here.

**Comment by Klaudeta** [comment] 2019-02-22 09:16
Fixed as a result of fixing [vaadin-text-field/issues/321](https://github.com/vaadin/vaadin-text-field/issues/321)

**Closed by Klaudeta** 2019-02-22 09:16 UTC
Labels: BFP, awaits another ticket, binder, bug, components
