### ISSUE TITLE
Support to clear a Binder and its fields

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#4780] opened 2018-11-14 14:44 UTC
Currently there's no public API to reset a binder to its initial state, i.e. clearing its fields *and* their validation state.

For example, this code:

```java
var nameField = new TextField();
var binder = new Binder<Person>();
binder.forField(nameField).asRequired().bind(Person::getName, Person::setName);

layout.add(nameField, new Button("Submit", event -> {
    respository.createPerson(binder::writeBeanIfValid);
    binder.getFields().forEach(HasValue::clear);
});
```

will clear the text field, but will also set it as invalid (red background), since its required.

There is a `private void clearFields()` method in `Binder`, which clears the fields *and* reset their validation state: it's invoked only when the binder has a bean set and it is removed.

In cases where the binder has no bean set (e.g. when using the binder to write multiple beans, or when you have no direct access to the bean instance as in the example), it would be very useful to have this method public.

**Comment by pleku** [comment] 2018-11-14 20:21
Related to https://github.com/vaadin/framework/issues/8997, and as said there, calling `setBean(null)` should be the thing to, instead of calling `clear()` method for the `HasValue` fields themselves. So the example you've provided work as indented from `Binder`'s perspective - if the field value is cleared, `Binder` will consider that value change event to cause an invalid value.

(Useless trivia: There was at some point during 8 beta an API for clearing the binder fields, but I think that it was reverted since it was a bit confusing https://github.com/vaadin/framework/commit/b11fa9c8007445817418a692770048ac7b0e08c7)

So if `setBean(null)` is not clearing the field errors or causes error to be shown for required fields - that is a bug. I think the root cause of this bug is that the `setComponentError` method is missing from Flow `Component` API whereas it was inbuilt to the old framework. The corresponding thing in Flow is https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasValidation.java#L41 and I can't see it being called from `Binder`, only `setInvalid(false)` is called on `clearError(...)` which is called from `clearFields()`.

So looks like a bug to me and quite straight forward to fix in https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L2299 with a call to `setErrorMessage(null)` and you can use your own case as a test. If you're up for it, just ping me for the PR. (I should be doing other things)

**Comment by heruan** [comment] 2018-11-16 07:31
Thank you @pleku for the feedback! Well, if I *do not set* a bean, it wouldn't make sense to use `setBean(null)` to clear the fields; I'd look for a `binder.clear()` or `binder.reset()` method instead.

**Comment by Kalomo** [comment] 2019-03-14 11:09
We are facing the same issue and also want to have a better API to reset() or clear() the binder back to its initial state.

**Comment by Artur-** [comment] 2020-05-29 12:39
Is there anything that needs to be done for this except changing
```
private void clearFields()
```
to
```
public void clear()
```
?

**Comment by denis-anisimov** [comment] 2021-04-22 11:33
I would like to summarize the request in the ticket and possible solutions:
- when you use `Binder::setBean`  then it's enough to call `Binder::setBean` : `null` value will remove the bean and clear all fields. If you want to reset the `Binder` state to the initial then you may call `Binder::setBean`  again with the same bean (which you always may access via Binder::getBean). `Binder::setBean` effectively resets everything and requested `clear`  method is not needed.
- when you use `readBean`  you don't have access to a bean (outside a place where it has been used). And the request for `clear`  has sense except that `readBean(null)` does what you need already: 
```
public void readBean(BEAN bean) {
        checkBindingsCompleted("readBean");
        if (bean == null) {
            clearFields();
```

So when you are using `readBean` you may get `clear`  functionality via `readBean(null)`.

In both cases `clear`  is either `setBean(null)` or `readBean(null)`  and I don't see a point to introduce a  new `clear` method.

I'm closing the ticket since it looks like the requested functionality is already available.
Please comment if you want to reopen the ticket.

**Closed by denis-anisimov** 2021-04-22 11:33 UTC
Labels: Impact: High, Severity: Minor, binder, bug
