### ISSUE TITLE
Make it possible to detect the difference between 0 instance candidates or >1 instance candidates from Instantiator.

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#9818] opened 2021-01-15 08:34 UTC
When `Instantiator` is used in Spring or CDI with an abstract target type, then an instance will be returned if there's exactly one available bean type that implements that type. This is used in Collaboration Engine to allow the application developer to publish custom configuration for Collaboration Engine as a bean, without including any code in Collaboration Engine that would directly depend on Spring or CDI.

Since the configuration type itself is abstract, `Instantiator.getOrCreate` will fail if no bean is available (or if not using a DI container) or if there are multiple candidate beans. We would like to see the difference between those two cases: no bean probably means that the developer isn't even trying to define configuration as a bean and should thus not be reported as a problem whereas the presence of multiple candidate beans is most likely a mistake in the application and it would be very useful if Collaboration Engine could let the developer know which beans are causing the conflict.

I can see two different ways of implementing this:
 1. `getOrCreate` could be enhanced to use a custom exception type that explicitly gives information to this kind of information
 2. Introduce a new method in `Instantiator` that is designed specifically for this purpose. The method could return a collection of candidates where each candidate would have some kind of identifier (String and/or Class) as well as a callback to actually create a specific instance.

**Comment by denis-anisimov** [comment] 2021-01-15 08:43
Do you want to use `Instantiator`  (with its existing methods) which is 1:1 to `VaadinService`  (mainly for UI components) or you want to use something which is 1:1 to the web application (mainly singleton service) ?

There is `Lookup`  which gives already something you want here.
`Lookup:lookupAll` gives all the service objects for the given service interface.
`Lookup:lookup` is convenience  method which requires exactly one service object for the service interface.

I would get rid of `Instantiator`  at some point completely since it's not extendable: it contains quite many methods which are not related to each other. Instead `Lookup` should be used to get one service impl per SPI (so each method will go into one service interface and Lookup should be used to get service with the method).
Every time when we add a new method into `Instantiator`  we a making a breaking change.

Splitting out  `Instantiator`  to a number of services which which may be asked dynamically allows to add services on demand without breaking API.

**Comment by Legioth** [comment] 2021-01-15 08:53
The main problem with using `Lookup` in this case is that I assume it won't be backported to Vaadin 14.

The difference between 1:1 with `VaadinService` or 1:1 with the web application doesn't matter in this case.

**Comment by denis-anisimov** [comment] 2021-01-15 08:58
>The main problem with using Lookup in this case is that I assume it won't be backported to Vaadin 14.

There is a ticket about this (backporting). 
It might be that backporting of changes for `Instantiator`  will be equivalent to backporting of `Lookup`.
(even though we may just make a default method impl in the interface).

>The difference between 1:1 with VaadinService or 1:1 with the web application doesn't matter in this case.

Ok.

**Comment by denis-anisimov** [comment] 2021-01-15 08:59
So it might be worth to clarify: this ticket targets `2.4` Flow version in fact.

**Comment by Legioth** [comment] 2021-01-15 11:04
This tickets targets all the Vaadin versions that we want Collaboration Engine to support, i.e. the latest Vaadin 14 and the latest non-LTS release train.

**Comment by pleku** [comment] 2021-01-25 12:28
Closing as a duplicate of #9756 as we're not going to likely do much specifically for instantiators anymore just for Flow 2.x and this is not a blocker but an improvement for collaboration engine.

**Closed by pleku** 2021-01-25 12:28 UTC
Labels: enhancement
