### ISSUE TITLE
Regression: scanner does not visit class fields when looking for imports

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6653] opened 2019-10-09 12:40 UTC
## Reproduce
1.- checkout `bakery-app-starter-flow-spring#master` branch
2.- replace platform version `14.0-SNAPSHOT` -> `14.1-SNAPSHOT` 
3.- replace flow maven plugin version `2.0-SNAPSHOT` -> `2.1-SNAPSHOT`
4.- login into the application and go to storefront

The application fails, and server throws the following exception:
```
java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'order-editor' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
```

## Cause
The following entries are not added to the `target/frontend/generated-flow-imports.js` file

```
import 'Frontend/src/views/orderedit/order-editor.js';
import 'Frontend/src/views/orderedit/order-details.js';
```

They should be added since in the `StorefrontView` class which is annotated with a `@Route` there are fields for the classes importing those modules, thus the scanner should visit them as it happens in `14.0-SNAPSHOT`

```
private final OrderEditor orderEditor;
private final OrderDetails orderDetails = new OrderDetails();
```

## Workaround
Add the following lines to `StorefrontView.java`
```
@JsModule("./src/views/orderedit/order-editor.js")
@JsModule("./src/views/orderedit/order-details.js")
```

**Comment by denis-anisimov** [comment] 2019-10-10 06:19
`14.1-SNAPSHOT` doesn't use byte code scanner anymore for dev mode.
It uses full classpath scanner.
Full CP scanner doesn't care about `@Route`s and discoverability of classes.
It scans for `JsModule` annotations.
So the required js modules should have been found.

It might be that this issue is related to the Spring add-on: it has its own scanning logic.
But until it's proven let's keep in in Flow repo.

This is a regression anyway which we have to fix ASAP.

**Comment by mehdi-vaadin** [comment] 2019-10-10 12:03
The problem is that Platform 14.1 doesn't use vaadin-spring 12.1. It still uses 12.0. After upgrading to 12.1, this issue was solved. However, a new exception is thrown in Bakery which will be reported as a separate issue later.

**Comment by manolo** [comment] 2019-10-11 12:22
what is the version of vaadin-spring that I should set in my pom for workaround this? apparently in maven repos latest is 12.0.6 and in vaadin-prereleases 11.1.0.alpha2, but I cannot find 12.1

**Comment by denis-anisimov** [comment] 2019-10-11 12:25
@mehdi-vaadin : https://github.com/vaadin/flow/issues/6653#issuecomment-541041718

**Comment by mehdi-vaadin** [comment] 2019-10-11 12:26
`vaadin-spring 12.1.beta1` will be released soon. Until then `12.1-SNAPSHOT` should be used.

**Comment by mehdi-vaadin** [comment] 2019-10-14 11:14
vaadin-spring 12.1.beta1 has been released

**Closed by mehdi-vaadin** 2019-10-14 11:14 UTC
Labels: bug
