### ISSUE TITLE
Custom styles are loaded before Lumo styles

### ISSUE THREAD

**Issue by lolytxd** [vaadin/flow#4240] opened 2018-06-06 12:29 UTC
From vaadin forum [https://vaadin.com/forum/thread/17086803/custom-styles-are-loaded-before-lumo-styles](https://vaadin.com/forum/thread/17086803/custom-styles-are-loaded-before-lumo-styles)

I have a WidokGlowny(MainView) class:
```
@HtmlImport(value = "styles/vaadin-textfield.html")
@HtmlImport(value = "styles/vaadin-textarea.html")
@HtmlImport(value = "styles/vaadin-checkbox.html")
@HtmlImport(value = "styles/vaadin-radiobutton.html")
public class WidokGlowny extends FlexLayout implements RouterLayout {
***
}
```

I'm importing there a few custom styles for vaadin components. 
For example this is a preview of what is inside a vaadin-textfield.html:
```
<dom-module id="my-text-field-styles" theme-for="vaadin-text-field">
  <template>
    <style>      
		:host(.wrap-label) [part="label"]{
		     white-space: normal;
		}
		 [part="input-field"] {
		     background-color: white;
		     border: 1px var(--lumo-contrast-5pct) solid;
		}
		 :host([disabled]) [part="input-field"] {
		     background-color: var(--lumo-contrast-10pct);
		}

    </style>
  </template>
</dom-module>
```

I'm not adding any of vaadin input components to WidokGlowny.

Next I have another class:
```
@ParentLayout(WidokGlowny.class)
@Route(value = "wnioski", layout = WidokGlowny.class)
public class Wnioski extends Div implements RouterLayout, LocaleChangeObserver {
***
}
```

I'm only adding here vaadin buttons.

And finally I have:
```
@Route(value = "wnioski/wymiana", layout = Wnioski.class)
public class WymianaKartyPobytu extends Wniosek implements LocaleChangeObserver {
***
}
```

I'm adding here vaadin input components, text-fields, text-areas, radiobuttons, checkboxes

Everything on page looks like this:
![](https://vaadin.com/attachment/4cc514b5-ecc8-4808-a3f4-ae7ce6d157ec/Bez%C2%A0tytu%C5%82u.png)

And here goes the problem. When I go directly to page [http://domain.com/wnioski/wymiana](http://domain.com/wnioski/wymiana) everything looks good. My styles are added after vaadin styles:
![](https://vaadin.com/attachment/d92c4763-b8bd-4e07-b500-b4a41fe21865/Bez%C2%A0tytu%C5%82u1.png)
![](https://vaadin.com/attachment/c57c2dfb-ddf7-45d3-9594-efa6f06dc901/Przechwytywanie.PNG)

But when I go to [http://domain.com/wnioski](http://domain.com/wnioski) and then when I click button, which navigates me to [http://domain.com/wnioski/wymiana](http://domain.com/wnioski/wymiana), my styles are added before vaadin styles, so nothing looks like I wanted.
![](https://vaadin.com/attachment/267be5ee-171f-4cc8-a1dc-3ae8f1b8f374/Bez%C2%A0tytu%C5%82u2.png)
![](https://vaadin.com/attachment/48125804-c4cd-4452-a99f-46d398323f74/Przechwytywanie2.PNG)

### Additional info about layouts:
I have MainLayout(WidokGlowny), I have there menu, footer etc., also I override method showRouterLayoutContent to add elements in specific place (between top menu and bottom footer).

Then I have class Wnioski. I override here method showRouterLayoutContent too. When someone go to page [http://domain.com/wnioski](http://domain.com/wnioski) parameter 'HasElement' of the method showRouterLayoutContent is null, so I know that I can add only buttons (each button navigates to other view (children layouts of Wnioski layout for eg. WymianaKartyPobytu)). But when somebody goes to [http://domain.com/wnioski/wymiana](http://domain.com/wnioski/wymiana) parameter is not null, so I remove all children of Wnioski (buttons), and I add corresponding component (example WymianaKartyPobytu).

Situation, when user is on [http://domain.com/wnioski](http://domain.com/wnioski):
![](https://vaadin.com/attachment/f04e6fa8-1213-427e-b231-fa070a0d550e/zzz.png)

Then when user clicks button, which navigates to WymianaKartyPobytu ([http://domain.com/wnioski/wymiana](http://domain.com/wnioski/wymiana)), the layouts looks like this:

![](https://vaadin.com/attachment/ddfb653c-4554-4511-88fd-095cfdae293a/zzz1.png)

**Comment by jouni** [comment] 2018-08-17 12:29
The problem is most probably with Polymer style modules and [`ThemableMixin`](https://github.com/vaadin/vaadin-themable-mixin) that it doesn’t guarantee the order in which the style modules are applied. You just need to use a stronger selector than Lumo to get around it.

**Comment by pleku** [comment] 2018-08-22 11:05
At minimum, we should document this case much better along with the lines of Jouni's comments.

Another thing is to make it more easier to create your own theme that extends eg. Lumo or Material and there you just want to specify some custom theming for certain components, and get those applied if there eg. is a style module present somewhere. I've created a separate issue for this https://github.com/vaadin/flow/issues/4548

**Comment by samie** [comment] 2020-03-05 08:56
Are we going to address this one? Sounds like people just get used to this bug in their application development.

**Comment by jouni** [comment] 2020-03-05 09:28
This has been fixed in ThemableMixin so that any `vaadin-` and `material-` prefixed style modules are guaranteed to be added before any other modules. Can’t remember in which exact Vaadin version it was released, but I believe it was 13.

So, this should not be an issue anymore (that custom style modules are added before build-in Vaadin-specific ones).

**Closed** 2020-03-06 11:44 UTC
Labels: DX, bug, theming, tutorial
