### ISSUE TITLE
Version information warning when building for production

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#16032] opened 2023-02-24 12:11 UTC
### Description of the bug

```
mvn install -Pproduction
```

logs `Unable to determine version information. No vaadin-core-versions.json found`

```
[INFO] --- vaadin:24.0.0.beta4:build-frontend (default) @ spring-skeleton ---
[INFO] Reflections took 198 ms to scan 132 urls, producing 5454 keys and 28593 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 2345 classes. Took 861 ms.
[INFO] Visited 102 classes. Took 38 ms.
[INFO] Unable to determine version information. No vaadin-core-versions.json found
[INFO] Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
```

### Expected behavior

It should find what it needs or expects

### Minimal reproducible example

https://github.com/vaadin/skeleton-starter-flow-spring

### Versions

- Vaadin / Flow version: 24 beta 4

**Comment by czp13** [comment] 2023-04-02 13:28
Not happening to me anymore. Executed today.
`mvn install -Pproduction` on `V24` branch.

With these properties from the pom.xml:
```
    <properties>
        <java.version>17</java.version>
        <vaadin.version>24.0.2</vaadin.version>
        <selenium.version>4.8.1</selenium.version>
    </properties>
```

I guess 24.0.2 fixed this. Maybe we can close this?

**Comment by Artur-** [comment] 2023-04-02 13:30
```
% npx @vaadin/cli init test-prod
% cd test-prod
% mvn install -Pproduction
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.example.application:test-prod >------------------
[INFO] Building test-prod 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/webjars/npm/mobile-drag-drop/maven-metadata.xml
Downloading from Vaadin Directory: https://maven.vaadin.com/vaadin-addons/org/webjars/npm/mobile-drag-drop/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/webjars/npm/mobile-drag-drop/maven-metadata.xml (456 B at 2.0 kB/s)
[INFO] 
[INFO] --- resources:3.3.0:resources (default-resources) @ test-prod ---
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- compiler:3.10.1:compile (default-compile) @ test-prod ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/artur/test/test-prod/target/classes
[INFO] 
[INFO] --- vaadin:24.0.2:prepare-frontend (default) @ test-prod ---
[INFO] Reflections took 671 ms to scan 127 urls, producing 5471 keys and 28823 values
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 126 resources. Took 54 ms.
[INFO] 
[INFO] --- vaadin:24.0.2:build-frontend (default) @ test-prod ---
[INFO] Reflections took 251 ms to scan 127 urls, producing 5471 keys and 28823 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 2442 classes. Took 859 ms.
[INFO] Visited 106 classes. Took 26 ms.
[INFO] Added 19 default dependencies to main package.json
[INFO] Unable to determine version information. No vaadin-core-versions.json found
```

**Comment by Artur-** [comment] 2023-04-02 13:32
It also happens with 23.3.7 so it is not new for V24
```
[INFO] --- vaadin:23.3.7:build-frontend (default) @ spring-skeleton ---
[INFO] Reflections took 197 ms to scan 125 urls, producing 5399 keys and 28553 values
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 2178 classes. Took 798 ms.
[INFO] Visited 121 classes. Took 36 ms.
[INFO] Unable to determine version information. No vaadin-core-versions.json found
```

**Comment by Artur-** [comment] 2023-04-02 13:36
I don't see it with 22.0.28 but I do see it with 23.0.0

**Comment by Artur-** [comment] 2023-04-02 13:42
It is introduced in 23.0.0.beta4

**Comment by Artur-** [comment] 2023-04-02 13:56
except it was logged as "no vaadin_versions.json" found back then, now "No vaadin-core-versions.json found"

**Comment by Artur-** [comment] 2023-04-02 13:57
Probably because the file in platform is `vaadin-versions.json` and not `vaadin_versions.json`..

**Comment by czp13** [comment] 2023-04-02 14:47
NodeUpdater also building on this file:

```Java
    JsonObject getPlatformPinnedDependencies() throws IOException {
        URL coreVersionsResource = finder
                .getResource(Constants.VAADIN_CORE_VERSIONS_JSON);
        if (coreVersionsResource == null) {
            log().info(
                    "Couldn't find {} file to pin dependency versions for core components."
                            + " Transitive dependencies won't be pinned for npm/pnpm.",
                    Constants.VAADIN_CORE_VERSIONS_JSON);
            return Json.createObject();
        }
```

But it is using   `final ClassFinder finder;` It is a custom ClassLoader by Vaadin, maybe it is a bit smarter, for first I will/would use this classFinder/loader and see what happens. (also I believe not good for consistency reasons to use separate code/logic for the same mechanism/feature). Both `NodeUpdater` and `Platform` are parts of `flow-server`.

**Comment by Artur-** [comment] 2023-04-02 14:57
Yeah it seems the naming problem was resolved earlier and now it is a classloading problem when running the Maven plugin

**Comment by czp13** [comment] 2023-04-02 15:05
**I agree, I hope I can solve this :) soonish** with the new/different class loader will check it, just now need to take a break.

BTW: I was working on SpringBootTest this week and had a similar solution to yours in my local repo, but you are unfortunately way faster, for me it was just 3-4 hours to investigate, try out some things for the linked minimal repo, get the root cause, and come up with some kind of solution... So TLDR: I have a long way/path to catch up :(

**Comment by czp13** [comment] 2023-04-28 10:47
As said here, and approved that PR as well:
- https://github.com/vaadin/flow/pull/16694

Thanks for your fix @caalador. My proposed and stashed changes related to this were much more complex, and not so straightforward, which is why I postponed the PR creation, because needed to make manual tests more, and test fixes as well, and I have more urgent issues/work as well.

**Comment by Artur-** [comment] 2023-05-26 06:11
With 24.1 beta2 you still see
```
[INFO] Unable to determine version information. No vaadin-core-versions.json found
```

when doing
```
npx @vaadin/cli init hello
cd hello
mvn install -Pproduction
```

**Comment by caalador** [comment] 2023-05-29 06:05
So there is also a `Platform` class that tries to load the versions file and that uses `Platform.class.getClassLoader`. This is apparently used in npm install task where it is an issue.

**Closed** 2023-05-29 07:14 UTC
Labels: bug, Impact: High, Severity: Minor
