### ISSUE TITLE
setProperty cleans the value

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/flow#4709] opened 2018-10-18 08:45 UTC
Setting the same property twice with the same value cleaning it.

To reproduce:
```
Div div = new Div();
Button btn = new Button("Set value", e -> {
  div.getElement().setProperty("innerHTML", "<p>Foo</p>");
});
```

Desired behaviour:
![flow-desired](https://user-images.githubusercontent.com/29372419/47142252-2f62d380-d2cb-11e8-85f5-98fc6088b80c.gif)

Actual outcome:
![flow-bug](https://user-images.githubusercontent.com/29372419/47142092-d004c380-d2ca-11e8-90a6-4f27d0e7442b.gif)

**Comment by Legioth** [comment] 2018-10-18 08:47
Duplicate of https://github.com/vaadin/flow/issues/4644

**Closed by Legioth** 2018-10-18 08:47 UTC
