### ISSUE TITLE
Unable to import style from npm dependency in theme css file in a sub directory

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10619] opened 2021-04-12 10:20 UTC
### Description of the bug / feature
Importing a CSS file from an npm dependency in a CSS file in `themes/my-theme` works fine. Importing the same dependency from a CSS file in `themes/my-theme/sub/` does not work

### Minimal reproducible example

styles.css
```css
@import url('leaflet/dist/leaflet.css');
```

Importing the same thing from another file in the `theme` folder also works fine:

styles.css
```css
@import url("./other.css")
```

other.css
```css
@import url('leaflet/dist/leaflet.css');
```

However, if you move `other.css` into a sub folder, you get
```
ERROR in ./themes/my-theme/styles.css
Module build failed (from ../node_modules/.pnpm/extract-loader@5.1.0/node_modules/extract-loader/lib/extractLoader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../node_modules/@vaadin/theme-loader/theme-loader.js' in '.../frontend/themes/my-theme'
    at .../node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/lib/Compilation.js:925:10
    at .../node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at .../node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at .../node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at .../node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at .../node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6877:13
    at .../node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2830:7
    at done (.../node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:2925:13)
    at .../node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/lib/NormalModuleFactory.js:449:23
    at .../node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/Resolver.js:213:14
 @ ./generated/theme-my-theme.generated.js 38:0-50 50:20-29
 @ ./generated/theme.js
 @ ./generated/vaadin.ts
```

### Versions:
    - Vaadin / Flow version: Tested with 20 alpha6

**Comment by caalador** [comment] 2021-04-12 10:29
This is a duplicate of #9794 and documented as a known limitation `At the moment all @import statements need to be in style sheets in the theme root folder.`

**Closed** 2021-04-13 07:40 UTC
