### ISSUE TITLE
Running jetty:run -pl <flow-module-name> does not run maven plugin

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5655] opened 2019-05-10 09:09 UTC
1) Checkout bookstore starter
2) run `mvn install -pl bookstore-starter-flow-backend` to build the backend project
3) run `mvn jetty:run -pl bookstore-starter-flow-ui` 

Expected: jetty is started and the app works

Actual: jetty is started but nothing work because flow maven plugins are not run

Things work after running `install` though.

**Comment by eriklumme** [comment] 2019-05-21 08:50
Would this be deemed the same as changes in e.g. a Polymer template not being reloaded by stopping and starting a `spring-boot:run` server, unless `mvn install` is run in between?

**Comment by pleku** [comment] 2019-05-21 11:16
>Would this be deemed the same as changes in e.g. a JS module Polymer template not being reloaded by stopping and starting a spring-boot:run server, unless mvn install is run in between?

Nope. What you've described should just work if the template file is available in the project.

Template changes should only need to save the file (some IDEs don't automatically) and refresh browser or use automatic refresh plugin (for Chrome one exists). I tested this last week for jetty and it worked so, if it is not the case for `spring-boot` then things are broken.

**Comment by Legioth** [comment] 2019-05-21 11:21
`spring-boot:run` will most likely be broken without manually disabling Bower mode until https://github.com/vaadin/flow/pull/5695 has been merged.

**Comment by eriklumme** [comment] 2019-05-21 11:24
In my case, I run `spring-boot:run` with `-Dvaadin.bowerMode=false`.

I have a `frontend/styles/styles.js` that appends some styles to the head of the document, and I import it with `@JsImport`.

If I make changes to it, save it, stop and re-run `spring-boot:run`, the changes are not reflected to the browser. They are, however, if I run `mvn install`, and I actually don't need to stop and re-run the app, as changes are re-deployed automatically.

**Comment by Legioth** [comment] 2019-05-21 11:28
You also need https://github.com/vaadin/spring/pull/438 which wasn't in beta1 but should be in the latest snapshots.

**Comment by eriklumme** [comment] 2019-05-21 11:32
I see, I'm running beta1 so might be that. Will test with beta2 whenever it's released.

**Comment by denis-anisimov** [comment] 2019-06-04 09:53
Not sure why this is in Flow repo since it's about bookstore.
As I understand bookstore had no vaadin maven plugin in build section.
Now it has and everything works fine.
I cannot reproduce the issue.
Please reopen if I missed something.

**Closed by denis-anisimov** 2019-06-04 09:53 UTC
Labels: bug, npm
