### ISSUE TITLE
Frontend compilation failed V14.0.0

### ISSUE THREAD

**Issue by ljosevr** [vaadin/flow#6286] opened 2019-08-19 23:51 UTC
Vaadin 14.0.0
open Jdk11
Windows

I download de app Start in https://vaadin.com/start/latest
With Spring Boot
mvn package
mvn clean install

and after That
I got an error. please Help

**Frontend compilation failed**
ERROR 8464 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
ERROR 8464 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in 'F:\Desarrollo\Proyectos\x-finance-app\target\frontend'
ERROR 8464 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 12:0-58

ERROR 8464 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
ERROR 8464 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in 'F:\Desarrollo\Proyectos\x-finance-app\target\frontend'

ERROR 8464 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 12:0-58

ERROR 8464 --- [        webpack] dev-webpack                              : i ?wdm?: Failed to compile.

![image](https://user-images.githubusercontent.com/39562093/63306952-4343e100-c2b2-11e9-88fa-fc54bf1a3a53.png)

**Comment by Legioth** [comment] 2019-08-20 07:13
Could you retest this with Vaadin 14.0.1 which was released yesterday? This might be caused by https://github.com/vaadin/flow/issues/6204 which was fixed in that release.

**Comment by ljosevr** [comment] 2019-08-21 01:45
> Could you retest this with Vaadin 14.0.1 which was released yesterday? This might be caused by #6204 which was fixed in that release.

Thanks. It Works with 14.0.1

**Comment by Legioth** [comment] 2019-08-21 08:42
Duplicate of #6204

**Closed by Legioth** 2019-08-21 08:42 UTC
