### ISSUE TITLE
SpringRouteNotFoundError is still active when a custom NotFoundException Handler exists.

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/flow#8948] opened 2020-09-05 22:58 UTC
### Description of the bug
InvalidRouteConfigurationException when a custom NotFoundException Handler is in use.
### Minimal reproducible example
Just create a custom Error 404 Page on Vaadin 17.
### Expected behavior
It should work.
### Actual behavior
`com.vaadin.flow.server.InvalidRouteLayoutConfigurationException: Only one target for an exception should be defined. Found 'com.vaadin.flow.spring.router.SpringRouteNotFoundError' and 'de.goehring.page.Error404Page' for exception 'com.vaadin.flow.router.NotFoundException'`
### Versions:
    - 17.0.0
    - Adopt JDK 14.0.2
    - Windows 10 2004

**Comment by joheriks** [comment] 2020-09-07 12:38
Duplicate of https://github.com/vaadin/spring/issues/658. Fixed in Spring 14.0.2.

**Closed by joheriks** 2020-09-07 12:38 UTC
