### ISSUE TITLE
Http session invalidate throws exception

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#5414] opened 2019-04-04 08:09 UTC
Call VaadinSession.getCurrent().getSession().invalidate(); and following exception ensues. Calling VaadinSession.getCurrent().close() first or not does not change this. Using platform version 13.0.0 with MPR and framework 7.7.16.

`java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1178)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:103)
	at com.vaadin.server.WrappedHttpSession.getAttribute(WrappedHttpSession.java:54)
	at com.vaadin.mpr.core.MprServletService.getFlowSession(MprServletService.java:184)
	at com.vaadin.mpr.core.MprServletService.accessSession(MprServletService.java:159)
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1401)
	at com.vaadin.server.VaadinService.fireSessionDestroy(VaadinService.java:460)
	at com.vaadin.server.VaadinSession.valueUnbound(VaadinSession.java:324)
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1819)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:879)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:766)
	at org.apache.catalina.session.StandardSession.invalidate(StandardSession.java:1266)
	at org.apache.catalina.session.StandardSessionFacade.invalidate(StandardSessionFacade.java:171)
	at com.vaadin.flow.server.WrappedHttpSession.invalidate(WrappedHttpSession.java:101)`

**Comment by peholmst** [comment] 2019-06-04 05:53
I'm trying to reproduce this. Some additional questions:
- Which VaadinSession are you using, the one from Flow or the one from Vaadin 7?
- Are you calling the invalidate method from Vaadin 7 or from Flow?
- Are you using server push?

**Comment by peholmst** [comment] 2019-06-04 06:08
Never mind, I managed to reproduce it after switching the application server from Jetty to Tomcat.

**Comment by samulivaadin** [comment] 2019-06-04 06:10
Good. Anyways. We were using VaadinSession from flow package and call came from flow button click event. MPR is not directly involved in this call chain.

**Comment by peholmst** [comment] 2019-06-04 06:15
I just discovered that if you remove MPR from the view, then session invalidation works as expected but if you add it, you get the exception even though the call chain does not involve MPR.

**Comment by peholmst** [comment] 2019-06-04 08:17
The problem seems to be the following: When the HTTP session is invalidated, the Vaadin 7 session is unbound and its session binding listener is invoked. This binding listener fails to recognise that the current request is related to the session and tries to explicitly destroy it again. This in turn leads to MPR trying to get a hold of the Flow session from the HTTP session that no longer exists and the exception is thrown.

**Comment by mehdi-vaadin** [comment] 2019-06-06 14:33
Fixed in MPR https://github.com/vaadin/multiplatform-runtime-internal/pull/315

**Closed by mehdi-vaadin** 2019-06-06 14:33 UTC
Labels: BFP, MPR
