### ISSUE TITLE
[Grid] sorting not working with grid lazy loading created from designer

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#14172] opened 2022-07-14 16:42 UTC
### Description of the bug

Just take example from [starter](https://start.vaadin.com/app).
Sorting is not working using designer implementation. 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/13396193/179033090-12cc612c-408b-4bfc-ad1f-cbd502ac8158.png">

code:
https://github.com/letrthang/vaadin23-flow-pro-components/blob/main/src/main/java/com/example/application/views/masterdetaildesigner/MasterDetailDesignerView.java

https://github.com/letrthang/vaadin23-flow-pro-components/blob/main/frontend/views/masterdetaildesigner/master-detail-designer-view.ts

<img width="889" alt="image" src="https://user-images.githubusercontent.com/13396193/179033450-cc8d54d7-c791-419a-9021-a9317f3d858d.png">

**Note**: pure java still works:
https://github.com/letrthang/vaadin23-flow-pro-components/blob/main/src/main/java/com/example/application/views/masterdetailjava/MasterDetailJavaView.java

### Expected behavior

can sort

### Minimal reproducible example

https://github.com/letrthang/vaadin23-flow-pro-components

### Versions

- Vaadin / Flow version:23
- Java version:17
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment] 2022-07-15 10:34
On the `MasterDetailDesignerView` columns are specified with `addColumn(ValueProvider)`, so you have to configure them as sortable explicitly
```
grid.addColumn(SamplePerson::getFirstName).setHeader("First Name").setAutoWidth(true).setSortable(true);
```

On 'MasterDetailJavaView' instead the columns are defined by the name of the property, so the grid can automatically apply the sort function according to the type of property inferred by inspecting the type of bean explicitly specified when creating 'Grid'.

It is actually misleading that the downloaded code produces a different result from the online preview

**Comment by letrthang** [comment] 2022-07-15 15:44
oh, i tried `setSortable(true)` and it doesn't work. and wonder `setSortProperty("firstName")` will work. 
so still a bug :)).

**Comment by mcollovati** [comment] 2022-07-15 16:07
It is not a bug.
As state in the documentation, `setSortable()` is used to enable or disable column sorting and toggle the sorter element on and off.
To actually apply sort, you should use `setSortProperty`, `setComparator` or `setSortOrderProvider`.

Here's the relevant docs:
https://vaadin.com/docs/latest/components/grid/flow/#column-sorting
https://vaadin.com/docs/latest/components/grid/flow/#enabling-and-disabling-column-sorting

I apologize for providing wrong information with my first comment.

**Comment by letrthang** [comment] 2022-07-15 17:31
Thanks for clarification, then only need fix on `start.vaadin.com`

**Comment by mcollovati** [comment] 2022-07-15 17:43
> Thanks for clarification, then only need fix on start.vaadin.com

Thanks for reporting. I'm closing this one, as the issue has been internally notified to the team

**Closed by mcollovati** 2022-07-15 17:43 UTC
