### ISSUE TITLE
Add support for Material theme and release 1.1.0.alpha1

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4238] opened 2018-06-06 11:28 UTC
Needs a `Material` theme class similar to `com.vaadin.flow.theme.lumo.Lumo`

Probably depends on https://github.com/vaadin/vaadin-material-styles/issues/49

**Comment by pleku** [comment] 2018-06-20 11:53
### Acceptance Criteria
- There is a material theme module with the integration in Flow that is released as 1.1-SNAPSHOT of
- When the material theme has been added, we release Flow 1.1.0.alpha1 with the material theme module
- We add & update the material theme module & component 1.1.0.alpha1 versions to the platform
- We add documentation about material theme being available to the users in addition to Lumo

**Comment by SomeoneToIgnore** [comment] 2018-07-03 07:13
Material theme support had been added in https://github.com/vaadin/flow/pull/4322
The documentation needs to be added.

The documentation is not added, since the support is not available for testing: due to the issue described in https://github.com/webjars/webjars/issues/1781 it is impossible to publish current prerelease Vaadin WebJars: we either need to wait until the issue is resolved or change the bower.json in all components with Material theme support.

**Comment by SomeoneToIgnore** [comment] 2018-07-16 14:29
Documentation is added in: https://github.com/vaadin/flow/issues/4238

Now the release is what's left to be done.

**Closed** 2018-07-18 10:59 UTC
Labels: enhancement, theming, tutorial
