### ISSUE TITLE
lit/quoted-expressions rule in eslint-plugin-lit v1.5.0 breaks flow-client

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#11181] opened 2021-06-08 11:20 UTC
This error happens in CI after a  eslint-plugin-lit  1.5.0 was released
![Screenshot 2021-06-08 at 07 33 52](https://user-images.githubusercontent.com/161853/121176206-3cf27080-c85c-11eb-9549-9d38e5e0ece6.png)

**Comment by knoobie** [comment] 2021-06-08 11:22
@manolo could that be a duplicate of https://github.com/vaadin/flow/issues/11176?

**Comment by Haprog** [comment] 2021-06-08 11:26
Duplicate of #11176

**Closed by Haprog** 2021-06-08 11:26 UTC
