### ISSUE TITLE
LiveReaload does not work and does not log any error message

### ISSUE THREAD

**Issue by gianluca-valentini** [vaadin/flow#8818] opened 2020-08-05 07:58 UTC
### Description of the bug
Currently I update Vaadin version from V14.2.2 to V14.3.2 in my project. 
When I start the application (Vaadin + Spring Boot), although I entered it correctly the **spring-boot-devtools** in my pom, the live update does not work and log does give me any information about the problem. Another aspect is that is not possible to find in the documentation how disable it in dev environment (so I don't know if it is possible)

### Actual behavior
I'm runnign Application.java class to start the application on my local machine.
When I start the application I have the login form:
![image](https://user-images.githubusercontent.com/3224592/89385688-4a9d0e00-d700-11ea-9db4-d16d6e899616.png)

After login I have the error message in the image below:
![image](https://user-images.githubusercontent.com/3224592/89385723-5c7eb100-d700-11ea-9e03-3eb3b9a10956.png)

Looking TCPView on my local machine, the port **35729** is not present, also using **netstat -noa**
I also add some additional params in the _application.properties_ file: 

> logging.level.com.vaadin.flow.internal=debug
> logging.level.org.springframework.boot.devtools=debug

That give me only 2 additional log information:

> [DEBUG] 2020-08-04 11:24:10.439 [http-nio-8080-exec-10] Class org.hotswap.agent.plugin.vaadin.VaadinIntegration not found, excluding HOTSWAP_AGENT
> [DEBUG] 2020-08-04 11:24:10.440 [http-nio-8080-exec-10] Class com.vaadin.flow.server.jrebel.JRebelInitializer not found, excluding JREBEL

So no error messages are present. I think that Vaadin should be more verbose on output log in order to detect the error information
### Versions:
    - Vaadin / Flow version: 14.3.2 
    - Java version: 1.8.0_211
    - OS version: Windows 10
    - Browser version (if applicable):
    - Application Server (if applicable): 
    - IDE (if applicable): IntelliJ Ultimate 2019.2.4

**Comment by denis-anisimov** [comment] 2020-08-07 05:53
Unfortunately it's impossible to diagnose the problem without the project sample which can be used to reproduce the issue.
Also we can't say whether it's fixed or not without exact steps to reproduce.
We tested the simplest scenario and it works for us. So additional info is required apart only actual behavior.

**Comment by gianluca-valentini** [comment] 2020-08-07 07:09
Hi @denis-anisimov ,
I understand your reason but currently the problem is that vaadin **does not give** me any **log** info to understand what is the problem.
I cannot give you a simple project as the current one is coming from **V10 migration**, so in my opinion a new one, for example the bakery, is not a good test in this scenario. 

My project worked fine till the 14.2. Then I updated Vaadin version to the latest one adding the required dependency but the live reload does not work.

Without error log I cannot give more details. In this situation the critical  step is to understand why live reload does not work correctly and then how to hide it if we don't find a solution

If you know how to trace any execution information, please let me know.
Thanks
Gianluca

**Comment by denis-anisimov** [comment] 2020-08-07 07:18
OK, it might be that the author of Live reload may say something based on the provided info.
But it's highly possible that we won't be able to do anything with this.

The project source code should not matter completely. The only meaningful thing is the project structure/config.
So it should be possible to repeat this config and structure based on some simple project e.g. `skeleton-starter-flow-spring`.

During localizing the issue you may find the reason why it doesn't work on your side (that quite often situation).

**Comment by gianluca-valentini** [comment] 2020-08-08 16:21
Ok,
I can share my pom,xml. Can it be useful?

**Comment by denis-anisimov** [comment] 2020-08-10 05:00
No, we need a working project.

**Comment by gianluca-valentini** [comment] 2020-08-10 07:42
Ok. I'm trying to share it.
in the meantime, can you tell me how disable it in my current project?

**Comment by pleku** [comment] 2020-09-08 12:19
One way to disable it is by setting the system property `vaadin.devmode.liveReload.enabled` to `false`.
An example on how to do it in `pom.xml`:
```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>set-system-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>vaadin.devmode.liveReload.enabled
                                    </name>
                                    <value>true</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by pleku** [comment] 2020-11-23 14:17
Closing the issue as there has not been any feedback on this for over two months.

**Closed by pleku** 2020-11-23 14:17 UTC
Labels: waiting for author
