### ISSUE TITLE
Location.getPath() discrepancy when rerouteTo or forwardTo is used

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#5899] opened 2019-06-13 07:58 UTC
Reported version: 13

When navigating to view having `UrlParameter` via `event.rerouteTo` or `event.forwardTo`, `event.getLocation().getPath()` in the target view `setParameter()` method does not contain parameter, only the route.

With the example app below:
1. Navigating to `http://localhost:8080/test/parameter` will show:
    `Location.getPath()`: `"test/parameter"` - OK
    `Parameter`: `"parameter"` - OK
2. Navigating to `http://localhost:8080/reroute` will show:
    `Location.getPath()`: `"test"` - FAIL, EXPECTED `"test/parameter"`
    `Parameter`: `"parameter"` - OK
3. Navigating to `http://localhost:8080/forward` will show (failure):
    `Location.getPath()`: `"test"` - FAIL, EXPECTED `"test/parameter"`
    `Parameter`: `"parameter"` - OK

```java
@Route("")
public class DemoView extends VerticalLayout implements RouterLayout {

    public DemoView() {
        add(new Anchor("/test/parameter", "Navigate to test view directly"));
        add(new Anchor("/reroute", "Navigate to test view via reroute"));
        add(new Anchor("/forward", "Navigate to test via forward"));
    }
}

@Route(value = "test", layout = DemoView.class)
public class TestView extends VerticalLayout implements HasUrlParameter<String> {

    TextField locationField = new TextField("Location.getPath()");
    TextField parameterField = new TextField("Parameter");

    public TestView() {
        add(locationField,parameterField);
    }

    @Override
    public void setParameter(BeforeEvent event, String parameter) {
        locationField.setValue(event.getLocation().getPath());
        parameterField.setValue(parameter);
    }
}

@Route(value = "reroute")
public class RerouteView extends Div implements BeforeEnterObserver {
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        UI.getCurrent().getRouter().resolveNavigationTarget("/test/parameter", Collections.emptyMap())
                .ifPresent(event::rerouteTo);
    }
}

@Route(value = "forward")
public class ForwardView extends Div implements BeforeEnterObserver {
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        UI.getCurrent().getRouter().resolveNavigationTarget("/test/parameter", Collections.emptyMap())
                .ifPresent(event::forwardTo);
    }
}
```

**Comment by ujoni** [comment] 2019-06-13 12:07
Cannot reproduce the issues for `forwardTo` using platform `14.0.0.beta2` nor `14.0-SNAPSHOT`. Please provide version number where the issue is present.

**Comment by gilberto-torrezan** [comment] 2019-06-13 12:34
Versions used in project: platform version `13.0.8` and flow version `1.4.5`.

**Comment by ujoni** [comment] 2019-06-13 12:45
Alright, I am able to replicate `forwardTo` case with platform `13.0.8`. Seems like #5667 fixes this for `forwardTo` but it has not been cherry-picked.

**Comment by Legioth** [comment] 2019-06-14 09:27
#5667 cannot be cherry-picked as-is since it adds new API.

**Comment by pleku** [comment] 2019-08-06 07:05
Since this issue has been fixed in 14 and it is possible to go from 13 to 14 with version bump + using the compatibility mode, I'm closing this issue as I'm afraid this will never be a priority to fix for 13.

**Closed by pleku** 2019-08-06 07:05 UTC
Labels: bug, needs design

**Comment by fluorumlabs** [comment] 2019-08-06 09:18
But V14 is not released yet :)
