### ISSUE TITLE
Documentation for reverse proxy using NGINX / APACHE

### ISSUE THREAD

**Issue by JasonTheDynamite** [vaadin/flow#17628] opened 2023-09-14 15:35 UTC
### Describe your motivation

Currently I am trying to configure VAADIN with NGINX + CloudFlare. Requests which end with "?v=rheartbeat&uiId=0" fail with 403 forbidden or other errors. Getting to event this point was a disaster. 7 day disaster of constant try & fail. I wanted to achieve simple reverse proxy using proxy_pass from NGINX to change subdomain in URL.
If I turn off NGINX everything works. ☹️ There is absolutely no help on the internet regarding this subject.

### Describe the solution you'd like

Precise EXACT documentation with examples for NGINX & Apache

### Describe alternatives you've considered

No alternatives. This has to be made,

### Additional context

Do it please ASAP

**Comment by mcollovati** [comment] 2023-09-14 15:45
Closing as this is a duplicate of vaadin/docs#1776

@JasonTheDynamite please add your comments and notes on that ticket

**Closed by mcollovati** 2023-09-14 15:45 UTC
Labels: duplicate, enhancement
