### ISSUE TITLE
Browser giving up to wait for response with grid

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#10511] opened 2021-03-30 15:00 UTC
I have a (mariadb-)database table that holds about 50k items. Put a standard grid on top of it to show items with a 50item-page size. When the page tries to load it takes about 5 minutes until the response is there, and then when I scroll down there is no further server request to load more pages.

My dataProvider is implemented like this:

```
	@Bean
	public FilterablePageableDataProvider occurrenceDataProvider(OccurrenceRepository repository) {
		return new FilterablePageableDataProvider() {
			@Override
			protected int sizeInBackEnd(Query query) {
				return (int) repository.count();
			}

			@Override
			protected Page fetchFromBackEnd(Query query, Pageable pageable) {
				return repository.findAll(pageable);
			}

			@Override
			protected List<QuerySortOrder> getDefaultSortOrders() {
				return Collections.emptyList();
			}
		};
	}

```

The grid is like

```
		Grid grid = new Grid(Occurrence.class);
		grid.setDataProvider(occurrenceDataProvider);
```
where the occurrenceDataProvider gets injected.
Found this comment in DataCommunicator.collectKeysToFlush():
```
    private Activation collectKeysToFlush(final Range previousActive,
            final Range effectiveRequested) {
        /*
         * Collecting all items even though only some small sub range would
         * actually be useful can be optimized away once we have some actual
         * test coverage for the logic here.
         */
        if (resendEntireRange) {
            […];
        } else {
            List<String> newActiveKeyOrder = new ArrayList<>();
            boolean sizeRecheckNeeded = false;

            Range[] partitionWith = effectiveRequested
                    .partitionWith(previousActive);

            Activation activation = activate(partitionWith[0]);
            newActiveKeyOrder.addAll(activation.getActiveKeys());
            sizeRecheckNeeded |= activation.isSizeRecheckNeeded();

            // Pick existing items from the current list
            Range overlap = partitionWith[1].offsetBy(-activeStart);
            if (overlap.getStart() < 0) {
                // If getStart is negative there is no data and empty Activation
                // needs to be returned
                return Activation.empty();
            }          
            newActiveKeyOrder.addAll(activeKeyOrder.subList(overlap.getStart(),
                    overlap.getEnd()));

            activation = activate(partitionWith[2]);
            newActiveKeyOrder.addAll(activation.getActiveKeys());
            sizeRecheckNeeded |= activation.isSizeRecheckNeeded();
            return new Activation(newActiveKeyOrder, sizeRecheckNeeded);
        }
    }

```
after minutes of waiting (because the json for 50.000 grid-cell-content elements has to be sent out and processed) the second call to activate(partitionWith[2])-tends to pass a range that goes until the very end - like 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/16917619/113009376-2c48be80-9178-11eb-9335-506fe40e1a55.png">

    - Vaadin / Flow version: 14.5.1/2.5.1
    - Java version: 11.0.10
    - OS version: McOS 11.2
    - Browser version (if applicable): Chrome Version 89.0.4389.90 (Official Build) (x86_64)
    - Application Server (if applicable): spring-boot
    - IDE (if applicable): IntelliJ 2020.3

**Comment by pleku** [comment] 2021-03-31 12:35
The usage code seems similar to what was done for example in bakery with the spring data provider add-on https://github.com/vaadin/bakery-app-starter-flow-spring/blob/v14/src/main/java/com/vaadin/starter/bakery/ui/dataproviders/OrdersGridDataProvider.java#L78 that is the way to do things in v14. 

What I just don't get is that how this has been missed / overlooked or when specifically this can occur, since the code is the same as for V17+ when we worked on "making the count query optional". So the third partition from `effectiveRequested.partitionWith(previousActive);` results to
```java
     * <li>Elements in this range that occur after elements in
     * <code>other</code>.
```
which means that the `effectiveRequested` has, for some reason, `[0...count]` which should **never make sense** (at least I think so). This is because the `effectiveRequested` is created before calling `collectKeysToFlush` from
```java
effectiveRequested = requestedRange
                .restrictTo(Range.withLength(0, assumedSize));
```
which means that the grid has requested basically all the items to be sent to the client side. **This should not be how grid is working by default,** so @wfischlein are how are you creating the `Grid` ? One thing to look for is the following code (c/p from component demo)
```java
// When using heightByRows, all items are fetched and
// Grid uses all the space needed to render everything.
//
// Note: heightByRows disables the grid's virtual scrolling so that all
// the rows are rendered in the DOM at once.
// If the grid has a large number of items, using the feature is
// discouraged to avoid performance issues.
grid.setHeightByRows(true);
```

**Comment by wfischlein** [comment] 2021-04-01 08:17
Yes, I'm using setHeightByRows(true) because setHeight("100%") - or setMaxHeight() - resulted in  zero-height component, and not trying to explicitly tell the grid something about height made it fixed by (as far as I remember) about 10 rows.

**Comment by pleku** [comment] 2021-04-01 08:51
> Yes, I'm using setHeightByRows(true)

Like I suspected - this is not a bug but how the component works. If you set it to show all the rows, then it will do so.

> setHeight("100%") - or setMaxHeight() - resulted in zero-height component

Usually that is symptom of broken layouting - 100 % of undefined is 0. Somewhere in the layout hierarchy you have undefined size (not 100 % nor defined).

Closing as invalid.

**Closed by pleku** 2021-04-01 08:51 UTC
