### ISSUE TITLE
Vaadin 14 on IBM WAS log full of warnings

### ISSUE THREAD

**Issue by aleuC** [vaadin/flow#11035] opened 2021-05-19 15:20 UTC
We have a Vaadin 14 (Vaadin 14.4.7) application running on IBM WAS, that uses vaadin push.
The log is full of these warnings (which makes it difficult to analyze any other issues):

> 
> 14/05/21 0.54.35:084 CEST] 0004ba2e SystemErr     R   [WebContainer : 30] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4680
> [14/05/21 0.54.41:527 CEST] 0004ba70 SystemErr     R   [WebContainer : 33] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4694
> [14/05/21 0.55.53:191 CEST] 0000062b SystemErr     R   [WebContainer : 3] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4788
> [14/05/21 0.56.01:837 CEST] 00050453 SystemErr     R   [WebContainer : 35] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4802
> [14/05/21 0.56.46:832 CEST] 0004ba51 SystemErr     R   [WebContainer : 31] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4896
> [14/05/21 0.56.50:396 CEST] 0002284e SystemErr     R   [WebContainer : 20] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 4910
> [14/05/21 0.57.23:684 CEST] 0004ba2e SystemErr     R   [WebContainer : 30] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 5004
> [14/05/21 0.57.27:457 CEST] 0004ba19 SystemErr     R   [WebContainer : 28] WARN com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler - Got an RPC for non-existent node: 5018

Do you know the problem? Do you know if it can be solved in any way?

**Comment by miguelatvaadin** [comment] 2021-05-20 07:32
Hi @aleuC ,

thanks a lot for submitting this issue.

The "Got an RPC for non-existent node" message basically complains because we are getting an rpc call (e.g. as a result of a user click) for a component which does not exist in the server side anymore. It can be due to several reasons (e.g. https://github.com/vaadin/flow/issues/7152).

We would need more info in order to reproduce the issue, so we can sort it out. Could you please provide a minimal reproduceable use case?

Best,

**Comment by pleku** [comment] 2021-06-15 12:46
No code and steps to reproduce provided so there is nothing that we do about this - closing the issue.

In case this is still a problem, please provide the code and steps to reproduce the issue and open a new ticket. In case you need hands-on help in investigating the problem, I recommend contacting the commercial support https://vaadin.com/solutions/support

**Closed** 2021-06-15 12:47 UTC
Labels: question, waiting for author
