### ISSUE TITLE
BeforeLeaveEvent.postpone does not postpone router actions

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8920] opened 2020-08-31 08:45 UTC
### Description of the bug

When you navigate away from a view, you want to use 
```
    @Override
    public void beforeLeave(BeforeLeaveEvent event) {
       event.postpone();
       // ...
   }
```
to postpone navigation e.g. if the user has unsaved input in a form. You show a popup and if the user confirms that she wants to discard the input, navigation happens.

When you have a TS router configuration, this does not work as expected. It seems like navigation partially takes place:
- The actual view component is not replaced (good)
- Route actions are triggered as if navigation happened (bad)

This leads to lazy loading bundles for views which you are not entering and also incorrect updates of headers or other view related texts outside the view itself

### Minimal reproducible example
```
git clone https://github.com/Artur-/java-ts-routing-postpone
cd java-ts-routing-postpone
mvn
open http://localhost:8080/
```

### Expected behavior
When you click on 'about', no UI changes should take place. 
* The header should say 'Hello World' 
* The menu should highlight "Hello World"

When you click on "Navigation postponed. Click to proceed.":
* The header should change
* The menu highlight should change

### Actual behavior

When you click on 'about', the menu highlight is moved to 'about' and the header says 'About' but you are still on the "Hello World" view

### Versions:
    - Vaadin version: 17.0.0.rc1

**Comment by Artur-** [comment] 2020-08-31 08:50
Live example here https://artur.app.fi/postpone-routing/

**Comment by Artur-** [comment] 2020-09-02 11:24
This is also a problem when not using `postpone` but have a slow connection. The actions are run way before the view component is updated, making it seem that navigation ended up in a broken view. In reality the navigation is still in progress. the view component is the old one but elements updated by actions are replaced with the new ones and no loading indicator is visible

**Comment by haijian-vaadin** [comment] 2020-09-04 13:40
This turns out to be a bit unintended use of the route action, the problem is gone when moving the code to another place, see this [PR](https://github.com/vaadin/cookbook/pull/72). 

I propose to close this ticket as won't fix for now, so that the team can focus on the coming release.

**Closed by haijian-vaadin** 2020-09-04 13:40 UTC
Labels: Impact: Low, Severity: Major, bug, ccdm
