### ISSUE TITLE
14.1.0.beta2 fails to find imports in node_modules tree for vaadin-combo-box & vaadin-time-picker 

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/flow#7000] opened 2019-11-21 22:59 UTC
When I do a Maven `clean` & `install` and then run my app from IntelliJ 2019.3 Ultimate edition EAP using external Tomcat 9.0.x, I see this message about missing `vaadin-combo-box` & `vaadin-time-picker`. 

    [RMI TCP Connection(2)-127.0.0.1] INFO dev-updater - 

      Failed to find the following imports in the `node_modules` tree:
          - @vaadin/vaadin-combo-box/src/vaadin-combo-box.js
          - @vaadin/vaadin-time-picker/src/vaadin-time-picker.js
      If the build fails, check that npm packages are installed.

      To fix the build remove `node_modules` directory to reset modules.
      In addition you may run `npm install` to fix `node_modules` tree structure.

Taking that advice to delete the `node_modules` folder from my project, and rebuild, does not help. The folder is recreated, but the error message appears again after a clean, install, and run.

I presume the failure above is the cause of further error messages:

    [webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js
    [webpack] ERROR dev-webpack - Module not found: Error: Can't resolve '@vaadin/vaadin-combo-box/src/vaadin-combo-box-placeholder.js' in '/Users/basilbourque/IdeaProjects/pics2go/node_modules/@vaadin/flow-frontend'
    [webpack] ERROR dev-webpack -  @ ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js 4:0-99 7:36-55
    [webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js
    [webpack] ERROR dev-webpack - 
    [webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js
    [webpack] ERROR dev-webpack - Module not found: Error: Can't resolve '@vaadin/vaadin-combo-box/src/vaadin-combo-box-placeholder.js' in '/Users/basilbourque/IdeaProjects/pics2go/node_modules/@vaadin/flow-frontend'
    [webpack] ERROR dev-webpack -  @ ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js 4:0-99 7:36-55
    [webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js
    [webpack] ERROR dev-webpack - ℹ ｢wdm｣: Failed to compile.
    [webpack] ERROR dev-webpack - 
    ------------------ Frontend compilation failed. -----------------

**Comment by caalador** [comment] 2019-11-22 09:19
Does removing package-lock.jsonm fix the issue?
I tried to replicate using base-starter updating from 14.0.13 to 14.1.0-beta3, but couldn't replicate the issue so that I could figure out the actual cause.

Could you do a `npm ls` in the project directory and give the output in this ticket so I can compare the packages.

**Comment by caalador** [comment] 2019-11-22 10:11
You could check that if you have an extra node_modules in `target/frontend/` and thus in `node_modules/@vaadin/flow-deps`.
This would be caused by 2 incompatible versions. Then just for interest if they are there could you run `npm ddp` to dedupe and then try to execute the project again.

**Comment by caalador** [comment] 2019-11-25 08:07
Is there in the logs the exception 
`Could not remove [path://]package-lock.json file. This file has been generated with a different platform version. Try to remove it manually.`

**Comment by juhopiirainen** [comment] 2019-11-27 13:44
Got a similar situation. Running; 

mvn clean install
npm ddp
mvn clean install
mvn package tomee:run

worked for my project.

**Comment by caalador** [comment] 2019-12-04 08:02
This state could be reliably duplicated using the base-starter-spring with 14.1.0.rc1 by:
• Run mvn spring-boot:run (things work as expected)
• Stop the server
• Delete folders `node_modules` and `target`
• Run mvn package -Pproduction

This will for some reason leave the project in a state where we are missing vaadin-custom-field in the package-lock.json and thus it is not dowloaded to node_modules but only under the shrinkwrap targets.

to fix the situation a `npm ddp` or deletion of `package-lock.json` and `target` (should be fine with `mvn clean package -Pproduction`) should be done until an automatic solution can be found.

**Comment by denis-anisimov** [comment] 2019-12-16 07:59
I'm able to reproduce the latest issue from @caalador with spring boot application and `14.1.2`.
But I cannot reproduce it anymore if I use `2.1.2`  Flow dependencies in the project.
So apparently the issue with `custom-field` is related to the issue in Spring about not finding abstract classes during frontend resources discovering.
It's fixed in `2.1.2`  and it's not an issue anymore.

So returning back to the original ticket (which is created in Flow repo not in Spring) it looks like it's not a Spring issue originally.

And to to able to detect the reason we need the exact steps to reproduce.
I'm not able to reproduce this with plain skeleton starter.
So could you @juhopiirainen , @basil-bourque provide steps to reproduce ?

**Comment by denis-anisimov** [comment] 2019-12-20 08:45
Since there is no any new information I close the ticket.
Please let me know if I should reopen it.

**Closed by denis-anisimov** 2019-12-20 08:45 UTC
Labels: bug, waiting for author

**Comment by Silock1** [comment] 2022-10-01 07:47
> This state could be reliably duplicated using the base-starter-spring with 14.1.0.rc1 by: • Run mvn spring-boot:run (things work as expected) • Stop the server • Delete folders `node_modules` and `target` • Run mvn package -Pproduction
> 
> This will for some reason leave the project in a state where we are missing vaadin-custom-field in the package-lock.json and thus it is not dowloaded to node_modules but only under the shrinkwrap targets.
> 
> to fix the situation a `npm ddp` or deletion of `package-lock.json` and `target` (should be fine with `mvn clean package -Pproduction`) should be done until an automatic solution can be found.

Thanks ! It worked for ne.
