### ISSUE TITLE
Flow beta9 requires vaadin manifest in production mode

### ISSUE THREAD

**Issue by johndevs** [vaadin/flow#4168] opened 2018-05-24 16:46 UTC
Since beta9 the ``vaadin-flow-bundle-manifest.json`` is no longer optional when running in production mode. I really don't understand why it is now required instead of optional. Beta 8 seems to work fine without it as well...

Could you please document these files somehow and mark which ones are required and what purpose they serve. The bundle manifest is a Vaadin specific feature so I think a documentation with a JSON schema would better explain its usefulness. 

(Relevant PR  https://reviewable.io/reviews/vaadin/flow/3941#-)

Thanks!

**Comment by SomeoneToIgnore** [comment] 2018-05-24 20:12
Seems to be the duplicate of https://github.com/vaadin/flow/issues/4090 please feel free to reopen if I'm wrong.

**Closed by SomeoneToIgnore** 2018-05-24 20:12 UTC

**Comment by johndevs** [comment] 2018-05-25 04:18
@SomeoneToIgnore Yeah, seems to be a duplicate of that ticket. Thanks for linking them!
