### ISSUE TITLE
Upgrading to workbox 6 breaks the PwaTestIT

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9944] opened 2021-02-02 07:45 UTC
Upgrading workbox to 6.1 with [this PR](https://github.com/vaadin/flow/pull/9937) breaks the `PwaTestIT.testPwaResourcesOffline` test. 

Maybe the logic in the `waitForServiceWorkerReady` needs to change.

**Comment by Artur-** [comment] 2021-02-15 11:38
Turns out the problem is this workbox change
```
workbox-routing
The setDefaultHandler() method now takes an optional second parameter corresponding to the HTTP method that it applies to, defaulting to 'GET'. It no longer applies to requests with any HTTP method. If you were using setDefaultHandler() and all of your web app's requests are 'GET', then no changes need to be made. [#2463]
```

The test uses `HEAD` instead of `GET` and the test is fixed in the mentioned PR

**Closed by Artur-** 2021-02-15 11:38 UTC
Labels: fusion, internal improvement
