### ISSUE TITLE
Random failure in TS compilation of BinderNode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10381] opened 2021-03-24 07:22 UTC
### Description of the bug / feature
Once in a while a start.vaadin.com build fails with
```
../target/flow-frontend/form/BinderNode.ts
[tsl] ERROR in /.../target/flow-frontend/form/BinderNode.ts(135,3)
      TS7023: 'for' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

ERROR in /.../target/flow-frontend/form/BinderNode.ts
../target/flow-frontend/form/BinderNode.ts
[tsl] ERROR in /.../target/flow-frontend/form/BinderNode.ts(136,11)
      TS7022: 'binderNode' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

Running the build again typically resolves the issue.

### Minimal reproducible example
Right now it can be reproduced by running
```
mvn install -Dunit.skipTests -DskipTests -Pproduction
```
TWICE for the the change 2589027ebfd4fb in the repository

### Expected behavior
Compilation should be deterministict and always work

### Versions:
    - Vaadin / Flow version: 19

**Comment by platosha** [comment] 2021-03-30 14:50
Does not reproduce to me anymore, seems to be fixed with #10382

**Closed by platosha** 2021-03-30 14:50 UTC
Labels: Impact: High, Severity: Major, bug, fusion
