### ISSUE TITLE
PiT 24.2: custom styles in spring-petclinic does not work for production

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#17490] opened 2023-08-23 14:52 UTC
### Description of the bug

When running the project in dev-mode, customized styles for green styling works, but in production it does not.

**Dev Mode**
![Screenshot 2023-08-23 at 16 35 22](https://github.com/vaadin/flow/assets/161853/38032a56-35fc-4d3b-98bc-4094573d0f1f)

**Prod Mode**

![Screenshot 2023-08-23 at 16 47 22](https://github.com/vaadin/flow/assets/161853/bc054490-d805-4337-85b5-67ebac8e9e31)

### Expected behavior

Custom styles work in dev and production modes

### Minimal reproducible example

1. clone the project
```
git clone https://github.com/spring-petclinic/spring-petclinic-vaadin-flow.git
cd spring-petclinic-vaadin-flow
```
2. set latest v22.0 version since the configured one is broken for dev-mode
```
 mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=22.0.28
```

3. run the project in dev-mode and see that the app looks fine 
```
mvn  spring-boot:run
```

4. abort, and compile the project for production
```
mvn package -Pproduction
```

5. run the project in prod-mode and see that it use default theme colors
```
java -jar target/*jar
```

If you want to check v23 or v24 series you can use these branches in my fork

https://github.com/manolo/spring-petclinic-vaadin-flow/tree/update-v23.3
https://github.com/manolo/spring-petclinic-vaadin-flow/tree/update-v24.1

### Versions

- Vaadin / Flow version: 22.0.0 - 24.2.alpha7

**Comment by caalador** [comment] 2023-09-01 12:33
I had a problem with no packages found in production mode build, but I can't replicate the style missing issue.
Is it on some specific browser?

**Comment by mshabarov** [comment] 2023-09-07 12:21
Tried with Vaadin 24.1.8 on top of the `update-v24.1` branch and have identical styles applied for dev mode and prod mode.
Tested with :
- Safari, version 16.3 (18614.4.6.1.6)
- FireFox, 117.0 (64-bit)
- Chromre, version 116.0.5845.179 (Official Build) (x86_64)

**Comment by mshabarov** [comment] 2023-09-20 07:11
Cannot reproduce, so propose to close it.

**Closed by mshabarov** 2023-09-20 07:11 UTC
Labels: waiting for author
