### ISSUE TITLE
Displaying a Grid is very slow

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#5256] opened 2019-03-13 10:04 UTC
Displaying a simple Grid takes more than one second.

Steps to reproduce:

1. open the Vaadin UI defined in the code below.
2. switch to 'Grid' tab and back to 'Empty tab' to make browser load all needed dependencies
3. switch again to the 'Grid' tab and measure the time it takes the grid to be visible.

Actual result: it takes about 1.5 seconds for the grid to be visible

Expected result: Grid is visible in less than 100ms

Looks like most of the time (~1 second) is spent on the server side as highlighted in the screenshot.

Minimal code to reproduce the issue:
```java
@Route("")
@Theme(Lumo.class)
@HtmlImport("frontend://bower_components/vaadin-lumo-styles/presets/compact.html")
public class MainView extends VerticalLayout {

	private static final int COUNT = 16;

	public MainView() {
		Tabs mainTabs = new Tabs();
		add(mainTabs);
		mainTabs.setWidthFull();

		VerticalLayout firstTabContent = new VerticalLayout();
		firstTabContent.setSizeFull();
		VerticalLayout secondTabContent = new VerticalLayout();
		secondTabContent.setSizeFull();
		VerticalLayout thirdTabContent = new VerticalLayout();
		thirdTabContent.setSizeFull();
		VerticalLayout fourthTabContent = new VerticalLayout();
		fourthTabContent.setSizeFull();
		Tab firstTab = new Tab("Empty tab");
		Tab secondTab = new Tab("Grid");
		Tab thirdTab = new Tab("Datepickers in a layout");
		Tab fourthTab = new Tab("Datepickers in a Grid");
		mainTabs.add(firstTab, secondTab, thirdTab, fourthTab);

		mainTabs.addSelectedChangeListener(change -> {
			remove(firstTabContent);
			remove(secondTabContent);
			remove(thirdTabContent);
			remove(fourthTabContent);
			if (mainTabs.getSelectedTab() == firstTab) {
				add(firstTabContent);
				expand(firstTabContent);
			} else if (mainTabs.getSelectedTab() == secondTab) {
				add(secondTabContent);
				expand(secondTabContent);
			} else if (mainTabs.getSelectedTab() == thirdTab) {
				add(thirdTabContent);
				expand(thirdTabContent);
			} else {
				add(fourthTabContent);
				expand(fourthTabContent);
			}
		});

		Grid<Dto> grid = new Grid<>(Dto.class);
		List<Dto> data = new ArrayList<>();
		for (int i = 0; i < COUNT; i++) {
			data.add(getNewMockDto());
		}
		grid.setItems(data);
		grid.setSelectionMode(SelectionMode.MULTI);
		secondTabContent.add(grid);
		secondTabContent.expand(grid);

		for (int i = 0; i < COUNT; i++) {
			thirdTabContent.add(new DatePicker(LocalDate.now()));
		}
		thirdTabContent.setSpacing(false);

		Grid<Dto> datepickerGrid = new Grid<>(Dto.class);
		datepickerGrid.setItems(data);
		datepickerGrid.setSelectionMode(SelectionMode.MULTI);
		datepickerGrid.setColumns("property1");
		datepickerGrid.addComponentColumn(item -> {
			return new DatePicker(item.getDate().atZone(ZoneId.systemDefault()).toLocalDate());
		}).setHeader("Date");
		fourthTabContent.add(datepickerGrid);
		fourthTabContent.expand(datepickerGrid);

		setSizeFull();
	}

	private Dto getNewMockDto() {
		return new Dto(UUID.randomUUID().toString(), LocalDate.now().atStartOfDay().toInstant(ZoneOffset.UTC));
	}

	public static class Dto {

		private String property1;
		private Instant date;

		public Dto(String property1, Instant date) {
			super();
			this.property1 = property1;
			this.date = date;
		}

		public String getProperty1() {
			return property1;
		}

		public void setProperty1(String property1) {
			this.property1 = property1;
		}

		public Instant getDate() {
			return date;
		}

		public void setDate(Instant date) {
			this.date = date;
		}

	}
}
```
and here's the whole test project: https://github.com/Wnt/vaadin-slowness-test

![image](https://user-images.githubusercontent.com/886091/54270003-1bc04e00-4587-11e9-8ace-f84d85b1e422.png)

On server side most time seems to be spent in `VaadinServletService.getThemedOrRawPath`:
![image](https://user-images.githubusercontent.com/886091/54280411-17545f00-45a0-11e9-9ae2-68d90d116e07.png)

![image](https://user-images.githubusercontent.com/886091/54280261-b593f500-459f-11e9-926a-eeb9615529f2.png)

Using Windows 10, Chrome 72, Oracle JDK 11.0.1, Vaadin 13.0.1.
Hardware:
https://ssd.userbenchmark.com/SpeedTest/160272/NVMe-THNSN5512GPUK-NV
https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-7820HQ+%40+2.90GHz&id=2952

**Comment by Wnt** [comment] 2019-03-13 13:43
Running the same application in Tomcat does not suffer from the same slowness. In Tomcat the server-roundtrip takes less than 50 ms on the same machine.

Maybe Vaadin could show a disclaimer about known slow application server during startup? E.g.
```
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
Looks like you are running Vaadin on Jetty on Windows. This combination is known to lead to extremely slow server-side performance.
===========================================================
```

**Comment by pleku** [comment] 2019-03-19 06:34
Duplicate of https://github.com/vaadin/flow/issues/4928

**Closed by pleku** 2019-03-19 06:34 UTC
Labels: bug
