### ISSUE TITLE
Flow 24 alpha does not work on payara-micro due to ASM incompatibility

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/flow#15625] opened 2023-01-05 08:38 UTC
### Description of the bug

From [StackOverflow](https://stackoverflow.com/questions/75013503/vaadin-flow-24-0-0-alpha7-doesnt-work-with-payara-micro):

> I tried to run Vaadin Flow 24.0.0.alpha7 (because it supports Jakarta EE 9) on Payara Micro but Vaadin servlet didn't deploy.
> 
> I believe Payara Micro 6.2022.2 should support it theoretically however when I tried to run it on Java 17 I got multiple errors of this sort:
> 
> Exception while visiting com/vaadin/flow/data/provider/SortDirection.class of size 1425
> java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
> When I switched to Java 19 I got the same ASM9 errors plus a bunch of new ones like this:
> 
> Exception while visiting WEB-INF/classes/one/esng/ang/ui/views/MainLayout.class of size 3967
> java.lang.IllegalArgumentException: Unsupported class file major version 63
> Is there any way to make it work?

### Expected behavior

Should work

### Minimal reproducible example

we should add payara-micro example to one of skeleton starter modules

### Versions

- Vaadin / Flow version: 24 alpha8
- Java version: 17
- Application Server (if applicable): payara-micro 6.xx

**Comment by Artur-** [comment] 2023-01-05 08:58
Payara issue: https://github.com/payara/Payara/issues/6127

**Comment by knoobie** [comment] 2023-01-05 10:41
How about changing the enum to something like, to remove the need of the kinda fancy stuff ;) 

```java
public enum SortDirection {

  /**
   * Ascending (e.g. A-Z, 1..9) sort order
   */
  ASCENDING(Constants.ASCENDING_OPPOSITE),

  /**
   * Descending (e.g. Z-A, 9..1) sort order
   */
  DESCENDING(Constants.DESCENDING_OPPOSITE);

  private final SortDirection opposite;

  SortDirection(SortDirection opposite) {
    this.opposite = opposite;
  }

  /**
   * Get the sort direction that is the direct opposite to this one.
   *
   * @return a sort direction value
   */
  public SortDirection getOpposite() {
    return opposite;
  }

  private static class Constants {

    public static final SortDirection ASCENDING_OPPOSITE = DESCENDING;
    public static final SortDirection DESCENDING_OPPOSITE = ASCENDING;
  }
}

```

**Comment by MarcinVaadin** [comment] 2023-01-10 14:41
Same issue for `com/vaadin/flow/component/grid/Grid$SelectionMode.class`.

**Comment by Artur-** [comment] 2023-01-24 15:45
Is there anything for us to do here or should we close this issue and wait for Payara to fix their deps?

**Comment by mshabarov** [comment] 2023-01-24 16:00
I suggest first to try change the Flow codes for SortDirection, ComponentTracker$Location and Grid$SelectionMode and see if there Payara would start then.

Example to reproduce https://github.com/vaadin/skeleton-starter-flow-cdi/tree/v24-payara :
`mvn clean package payara-micro:start`

**Comment by mshabarov** [comment] 2023-01-24 17:35
Tested the above starter with patched Flow https://github.com/vaadin/flow/tree/flow-payara and Flow Grid https://github.com/vaadin/flow-components/tree/grid-payara 
I got basically only one error:

```
[2023-01-24T19:25:42.714+0200] [] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1674581142714] [levelValue: 1000] Exception while visiting sun.security.util.KnownOIDs
```
and a blank page:
![Screenshot 2023-01-24 at 19 29 55](https://user-images.githubusercontent.com/61410877/214366059-f91e64d4-6abc-4001-9557-f446b694a0ab.png)

No errors in the browser console or network tab.
Will set a verbose logging level for the server and see.

**Comment by mcollovati** [comment] 2023-01-27 16:47
The problem seems to be that `MainView` is not considered a CDI bean, and thus its `@PostConstructor` is not invoked, so child components are not added to the view

**Comment by mcollovati** [comment] 2023-01-27 17:29
The same happens with wildfly 27 (alpha), so the problem is with Jakarta EE 10 and CDI 4, that changed the default bean discovery mode to `annotated`, as mentioned in vaadin/cdi#411

**Comment by mcollovati** [comment] 2023-02-06 08:53
Just tested against latest Flow and grid modules and the ASM issues seems to be resolved.
For the blank page issue I will create a PR on `skeleton-starter-flow-cdi` repository to add the `@CdiComponent` to `MainView`, so it will be detected as a CDI bean and lifecycle hooks will be correctly invoked

**Closed by mcollovati** 2023-02-06 08:53 UTC
Labels: external dependency
