### ISSUE TITLE
Components with id bindings are not working correctly

### ISSUE THREAD

**Issue by centenico** [vaadin/flow#11391] opened 2021-07-08 09:28 UTC
### Description of the bug / feature

Using components declared on the .js side, trying to set a value on the server-side via id binding doesn't seems to work correctly.

### Minimal reproducible example

```

class MyCustomCard extends PolymerElement {
    static get template() {

        return html`

        <div>
              <vaadin-text-field id="labelid" label="label" value="{{filterData.field}}"></vaadin-text-field>
        </div>

        <div id="labelDiv">
                //here I'll add a TextField via Java server-side.
        </div>

        `;
    }

Java Server-side:
    
public class MyCustomCard extends PolymerTemplate<MyCustomCard.Model> {

      //textField i'll add later to labelDiv
      private TextField labelTextField = new TextField();
  
      @Id("labelid")
      private TextField labelIdTextField;
  
      public MyCustomCard (FilterData data) {

            this.labelTextField.setValue(data.getField);    //this works correctly
            getModel().setFilterData(data);     // this leaves the TextField empty
         
      }

      public interface Model extends TemplateModel {

            @Include({"field", "fieldValues", "isWhiteList"})
            void setFilterData(FilterData filterData);
            FilterData getFilterData();

      }
}

```

### Actual behavior
Components, like ComboBox, TextFields and such do not retain/updates their values while using id binding.

### Versions:
    - Vaadin / Flow version:  14.6.5
    - Java version: 1.8

**Comment by denis-anisimov** [comment] 2021-07-08 09:36
```
@Id("labelid")
private TextField labelIdTextField = new TextField();
```

The code is invalid: at least it won't work as you expects in the ticket description.

It should be 
```
```
@Id("labelid")
private TextField labelIdTextField;
```

It might be this is a typo.
But regardless of this fact please provide the complete code snippet which I may copy-paste and see the behavior to avoid any kind of typos.
Another way : use https://github.com/vaadin/skeleton-starter-flow and just make a project which I may use to reproduce.
There are plenty of open questions:
- the complete template source code.
- Polymer or Lit template
- mode
- etc....

The complete source code allow to answer to all such questions

**Comment by centenico** [comment] 2021-07-08 09:51
@denis-anisimov You are right, I've made the wrong example. I've modified the original post using the same code/objects with my real issue. If I'm setting the value via double-binding using the model, it won't update the TextField correctly, but it'll leave it empty.

**Comment by centenico** [comment] 2021-07-08 11:28
@denis-anisimov 
Here is the skeleton project with the issue:

[skeleton-starter-flow-14.zip](https://github.com/vaadin/flow/files/6784079/skeleton-starter-flow-14.zip)

**Comment by denis-anisimov** [comment] 2021-07-08 12:39
Very good.
Now I can clearly see the bug.

For some reasons the model value ( `filterData` property ) for the template instance MyCustom is not set even though the metadata is populated.
I have to investigate this.

**Comment by denis-anisimov** [comment] 2021-07-12 11:44
After spending a lot of time with this I can say that this is not really a bug even though I totally agree that this is unexpected:  it's how `@Id` mapping is designed (I would say it's not designed anyhow and causes a lot of issues all the time).

Let's start from the scenario: what you are trying to achieve with this ?
The issue with this quite weird example is:
- Two way model binding is used in template
- _AT THE SAME TIME_ you bind the text field via `@Id` .

Why do you bind the element with `@Id` if you are using client side two way model binding ?
I don't see any reason to use `@Id` with text field here. The value of text field is already made so that it dynamically calculated based on template (sub)property .
`@Id` mapping is used to be able to update properties/attributes of the element directly from the server side.
As a result you are getting conflict: the `value` is bound on the client side and the same `value` can be ( and in fact IS ) updated from the server side.
The update from the server side destroys the two way model data binding on the client side since if ( and when) the `value` property is set  directly it totally overrides the two way model data binding.
So : 
- it's dangerous 
- and in fact is invalid because this is what happens.

The model value `filterData` with all its fields is set for the template correctly .
And the text field value gets the expected value.
BUT then everything is destroyed by your `@Id` mapping whose usage  I don't here at all.
`TextField` component sets `""` value for `value` property in its constructor.
As a result when `@Id` mapping happens the `value` of the text field is set to "".
So it overrides the value which has been set properly via client side two way data binding.

So everything works as it should.

The thing which you don't expect is: `TextField` constructor (which as I said set `""` as a value for `value`).
You may make a ticket for `TextField` about this behavior but I cannot see how this can be fixed: `TextField` has no info whether the `value` should be set to `""` or it should not touch it at all. By default `""` is a proper initial value for text field and  it's OK to be set in the constructor.
But not in some `@Id` mapping case.
And this is a general problem with `@id`  mapped components.

Again: I don't understand a reason to use client side two way model data binding along with `@id` mapping. It causes an issue from the very beginning.
The `value` is already calculated based on the client side binding. So it's invalid to set `value` from the server side.

If you want to set another properties like `label`  then you should also use client side model data binding.
So : use either only `@Id` mapping or client side model data binding. Not both.

Your specific case can be solved like this :

```
public class MyTextField extends TextField {

    @Override
    protected void setModelValue(String newModelValue, boolean fromClient) {
    }

    @Override
    protected void setPresentationValue(String newPresentationValue) {
    }
}
```

and binding should be changed to 
```
 @Id("labelid")
    private MyTextField labelIdTextField;
```

In this case "value" is not updated on the server side and it doesn't override the client side binding.

I don't see how this corner use case can be solved generally.
In any case this should be done on the component side: the default component constructor should be aware of cases when it should not update the property anyhow with initial value. So as I already mentioned you may make a ticket in the `flow-components` about this . Additional info will be needed from Flow how to inform the component that the property value should not get any initial value but I would like to see a suggestion how this contract can be made.

At the moment: I close this as invalid and there are proper ways top make it work with workarounds.

**Closed by denis-anisimov** 2021-07-12 11:44 UTC
Labels: waiting for author
