### ISSUE TITLE
Fusion: A validation error message hook

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/flow#11305] opened 2021-06-22 09:03 UTC
### Description of the feature
You can't use custom error messages in fusion.
It would be great to have a hook for the message:
```
protected async getMessage(message: string): string {
  return message;
}
```
So I could implement my binder and overload the method with what ever I want.

Any other solution that solve this problem would be also good. :)

### Versions:
    - Vaadin / Flow version: 20.0.3

**Comment by haijian-vaadin** [comment] 2021-08-24 11:51
Thanks for the proposed solution, the issue is the same as https://github.com/vaadin/flow/issues/10688. Would prefer to close this one in favor of the other.

**Closed by haijian-vaadin** 2021-08-24 11:51 UTC
Labels: enhancement, fusion
