### ISSUE TITLE
Spring UIScoped beans are created every time when navigating by HTML links inside the same browser tab 

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4171] opened 2018-05-25 09:05 UTC
The `@UIScope` annotation should create only one bean per UI / tab. Currently this is not working, when changing routes by using simple html anchors `<a href="...">`. Since they are common elements, this can become critical when having a Polymer design, that uses html links for navigation instead of buttons.

The following simple code snippets plus output demonstrate the behavior:
```
// First view
@SpringComponent
@Route("")
@UIScope
public class Number1 extends VerticalLayout {

	public Number1() {
		System.out.println(this);
		add(new Button("Go to 2 by Button", event -> getUI().get().navigate("no2")));
		add(new Anchor("no2", "Go to 2 by Link"));
	}
}

// Second view
@SpringComponent
@Route("no2")
@UIScope
public class Number2 extends VerticalLayout {

	public Number2() {
		System.out.println(this);
		add(new Button("Go back by Button", event -> getUI().get().navigate("")));
		add(new Anchor("", "Go back by Link"));
	}
}

// Application starter
@SpringBootApplication
public class ExampleServletInitializer extends SpringBootServletInitializer {

    public static void main(String[] args) {
        SpringApplication.run(ExampleServletInitializer.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
        return builder.sources(ExampleServletInitializer.class);
    }

}
```

The output, when navigating by html links, is 
```
org.vaadin.stefan.spring.Number1@4bd887a2
org.vaadin.stefan.spring.Number2@131b4e8c
org.vaadin.stefan.spring.Number1@5efe29ac
org.vaadin.stefan.spring.Number2@6d4b1e98
org.vaadin.stefan.spring.Number1@10582e49
```

The problem seems to be, that the UI can not be set to "preserve on refresh", as it could be in V8.

**Comment by stefanuebe** [comment] 2018-05-25 09:15
My bad, forgot the `@SpringComponent`.

**Comment by Legioth** [comment] 2018-05-25 09:37
Duplicate of https://github.com/vaadin/flow/issues/3522.

Recommended to use `<a router-link>` instead of plain links if you want to avoid refreshing the page.

**Closed by Legioth** 2018-05-25 09:37 UTC
