### ISSUE TITLE
Polymer Tabs cause IllegalArgumentException

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#4713] opened 2018-10-21 23:08 UTC
In Vaadin 12 alpha 3 and 4 polymer tabs cause java exception whenever a tab is clicked.

This is identical to the issue reported in https://github.com/vaadin/flow/issues/4564

**Comment by caalador** [comment] 2018-10-24 06:29
Closing as duplicate of https://github.com/vaadin/vaadin-tabs-flow/issues/67

**Closed by caalador** 2018-10-24 06:29 UTC
Labels: bug, components, duplicate
