### ISSUE TITLE
development mode: continuous spurious error messages on browser dev console

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#15574] opened 2022-12-25 20:47 UTC
### Description of the bug

When running in development mode, there are continuous connection refused messages on the console.
The application is running from an embedded Jetty and uses @Push
There are no observable errors on the application, which runs correctly. 
The problem does not happen in production mode.
The application is a Maven project and is structured the same way as the plain java skeleton.

![3LEM2UIEAg](https://user-images.githubusercontent.com/678663/209481368-785e447e-4a65-4521-95bd-de1e0c1b1ce0.png)

### Expected behavior

There should be a way to turn off these messages.
Could not figure out what the application is seeking behind "/VAADIN" since nothing breaks.

### Minimal reproducible example

https://github.com/jflamy/owlcms4/tree/develop/owlcms is the project.
Jetty configuration visible in https://github.com/jflamy/owlcms4/blob/develop/shared/src/main/java/app/owlcms/servlet/EmbeddedJetty.java

### Versions

Vaadin: 23.3.1
Flow: 23.3.1
Java: AdoptOpenJDK 11.0.10
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Live reload: Java active (HotswapAgent): Front end active

**Comment by Artur-** [comment] 2022-12-26 07:23
It is the Vite dev server that tries to connect to its websocket server to listen for frontend reload and other commands. The Vite server is started automatically and the port it listens to is listed in the startup log - that one should match what the browser is using. Is something preventing the connection?

**Comment by jflamy** [comment] 2022-12-26 15:39
I am firing an embedded Jetty (running my Java main from the Eclipse IDE with DCEVM HotSwap). 
I checked that the Windows Firewall is completely disabled.  
But I do not see a Vite process running -- though the error is a Connection Refused and not a hang.  
In this mode, what is supposed to start Vite? I have Node 16 installed on the machine.

**Comment by jflamy** [comment] 2022-12-26 15:41
I have not tried (yet) editing/updating my old Polymer stuff -- I am migrating an application from 14 to 23.  I suspect this would kill the JS hot reload, and would be very incapacitating.

**Comment by jflamy** [comment] 2022-12-26 15:46
There is a node running on the failing port.  I believed I had completely disabled my Windows firewalls, will dig deeper.

**Comment by jflamy** [comment] 2022-12-26 15:58
If I open my application with the local windows machine name (http://jflxps:8081) the connections to Vite fail.
But there are no error messages if I use http://localhost instead, or http://jflxps.local

**Comment by jflamy** [comment] 2022-12-26 16:00
Using a local Linux host name without a full FQDN will likely cause the same issue.

**Comment by Artur-** [comment] 2022-12-26 16:47
Ah, then it sounds like https://github.com/vaadin/flow/issues/14773

**Comment by jflamy** [comment] 2022-12-26 16:53
I start a browser for convenience when my program starts.  Current workaroun is that if I detect that the address reported for the current machine is one of the machine's own interfaces, I force the browser opening to use "localhost".  I will upvote the reverse proxy solution!

**Comment by MarcinVaadin** [comment] 2023-01-03 09:24
Closing as a duplicate of https://github.com/vaadin/flow/issues/14773

**Closed by MarcinVaadin** 2023-01-03 09:24 UTC
Labels: duplicate
