### ISSUE TITLE
Hot reload frontend files in a module

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#12232] opened 2021-11-02 07:37 UTC
In a Vaadin application when I update my frontend files I would like the application reloaded with the updated files.

Currently if I update a file in the frontend file of my main module in Maven, it's automatically refreshed and I don't need to restart the application.
For example this file: https://github.com/jcgueriaud1/multimodule-spring-vaadin-app/blob/main/ui-bootstrap/frontend/global.css

If I have a submodule (jar) that contains a css and I update it the file is not updated in my application and I need to restart the application. For example this file:
https://github.com/jcgueriaud1/multimodule-spring-vaadin-app/blob/main/ui-module/src/main/resources/META-INF/resources/frontend/module.css

I tried different ways and it's working fine Java files in a submodule but not with the Vaadin-specific frontend folder.

The solution I found is only working with Spring boot + Spring dev tools + IntelliJ

> if you run it as spring-boot:run + resolve workspace Artifacts (which is not checked by default)

But the DX is poor since it requires spring boot (in general not used for addons) or it doesn't keep the authentication (for most of the application).
Is there any way to refresh the frontend folder of submodule with JRebel?

**Comment by oliveryasuna** [comment] 2021-11-08 00:40
I think it's irrelevant whether JRebel solves this because most people don't want to spend $500+/yr for JRebel.

**Comment by jcgueriaud1** [comment] 2021-11-08 04:42
The documentation mentions 3 possible hot reload https://vaadin.com/docs/v14/guide/starters/bakeryflow/auto-restart#hotswapagent
 But it doesn't explain how the front-end can be reloaded. For spring boot devtools, I found a way with Intellij ultimate. It could be great to have a solution for the other possibilities.

**Comment by pleku** [comment] 2021-11-12 13:54
As a workaround, in a multimoduleproject it should be possible to setup things so that the updated resources are e.g. copied/unpacked to somewhere (like frontend/generated?) and then picked up from there .. though it might require some hacking to get the paths to work both when unpacked manually and when coming from jar.

After some digging for similar issues, I'd say this is a duplicate of #6347 and thus closing in favor of that one.

**Closed by pleku** 2021-11-12 13:54 UTC
Labels: enhancement, live reload
