### ISSUE TITLE
Restart loop with Jetty and automatic reload on Windows

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9809] opened 2021-01-14 10:14 UTC
### Description of the bug
On Windows, the business starter application enters a reload loop with Vaadin 19.0.0.alpha2. The reason seems to be that files generated in the `target` folder (`index.ts`, `sw.ts`, `index.html`) on server startup triggers Jetty reload (when `scanIntervalSeconds` is set to a small positive value).

### Minimal reproducible example
1. Download Business App Starter with V17 (https://vaadin.com/start/v17/business-app)
2. Update pom.xml to v19.0.0.alpha2
3. Run `mvn jetty:run`

### Expected behavior
Application starts up normally.

### Actual behavior
Application enters reload loop.

### Versions:
    - Vaadin / Flow version: 19.0.0.alpha2 / 6.0.0.alpha4
    - Java version: 8
    - OS version: Windows 10

**Comment by johannest** [comment] 2021-01-14 10:48
node v14.15.4
npm 6.14.10

**Comment by haijian-vaadin** [comment] 2021-01-19 12:51
A workaround for now could be to disable the `scanInterval` in the  pom.xml file.

**Comment by platosha** [comment] 2021-01-26 06:30
Debugging with the Jetty Maven Plugin source revealed, that the restart occurs because of `frontend` change in the project directory. It seems to be caused by this [Jetty scanner issue](https://github.com/eclipse/jetty.project/issues/2266), which is already fixed in recent Jetty versions.

Bumping the Jetty version to latest 9.4.x fixed the issue for me.

**Comment by haijian-vaadin** [comment] 2021-01-26 07:19
Amazing! thanks for the info, I think now we should update the jetty version in our starters.

**Closed** 2021-01-26 13:11 UTC
Labels: Impact: High, Severity: Major, bug, fusion

**Comment by javier-godoy** [comment] 2021-09-15 18:44
The same situation was found with Vaadin 14.7.0 and jetty-maven-plugin 9.4.15.v20190215. 
Updating jetty to 9.4.36.v20210114 seems to fix it.
