### ISSUE TITLE
Vaadin 23.3.0 does not work with multi-module projects

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow#15534] opened 2022-12-21 08:40 UTC
### Description of the bug

Just upgraded from 23.2.6 to 23.3.0. Executed vaadin:dance and mvn clean install.
Running the application results in several ts-errors preventing my application to run (see below)
Looks to me like some problem with multi-module projects.
I have vaadin components in several modules, which seems to cause recursive "generated"-Folders in frontend/generated.
The recursively added folders contain index.ts files for which the import does not point to a valid file, therefore the error is raised.

The last 2 errors also seem multi-module related, seems to occur because the js/ts resources occur multiple times below frontend/generated.

`Started Vite. Time: 10722ms
  ➜  Local:   http://127.0.0.1:65168/VAADIN/

 ERROR(TypeScript)  Cannot find module '../../target/frontend/generated-flow-imports' or its corresponding type declarations.
 FILE  C:/intellij_workspace/SQACE/Application/gui/main/frontend/**generated/jar-resources/generated/index.ts**:20:25

    18 |
    19 | const { serverSideRoutes } = new Flow({
  > 20 |   imports: () => import('../../target/frontend/generated-flow-imports')
       |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    21 | });
    22 |
    23 | const routes = [

 ERROR(TypeScript)  Cannot find module '../../target/frontend/generated-flow-imports' or its corresponding type declarations.
 FILE  C:/intellij_workspace/SQACE/Application/gui/main/frontend/**generated/jar-resources/generated/jar-resources/generated/index.ts**:20:25

    18 |
    19 | const { serverSideRoutes } = new Flow({
  > 20 |   imports: () => import('../../target/frontend/generated-flow-imports')
       |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    21 | });
    22 |
    23 | const routes = [

 ERROR(TypeScript)  Subsequent property declarations must have the same type.  Property 'sfmanager' must be of type 'SyncFusionVaadinManager', but here has type 'SyncFusionVaadinManager'.
 FILE  C:/intellij_workspace/SQACE/Application/gui/main/frontend/generated/jar-resources/generated/jar-resources/SyncFusionVaadinManager.ts:25:9

    23 | declare global {
    24 |     interface Window {
  > 25 |         sfmanager: SyncFusionVaadinManager;
       |         ^^^^^^^^^
    26 |     }
    27 | }
    28 |

 ERROR(TypeScript)  Type 'this' is not assignable to type 'SyncFusionVaadinManager'.
  Type 'import("C:/intellij_workspace/SQACE/Application/gui/main/frontend/**generated/jar-resources/generated/jar-resources/SyncFusionVaadinManager**").SyncFusionVaadinManager' is not assignable to type 'import("C:/intellij_workspace/SQACE/Application/gui/main/frontend/**generated/jar-resources/SyncFusionVaadinManager**").SyncFusionVaadinManager'.
    Types have separate declarations of a private property 'gridList'.
 FILE  C:/intellij_workspace/SQACE/Application/gui/main/frontend/generated/jar-resources/generated/jar-resources/SyncFusionVaadinManager.ts:36:9

    34 |
    35 |     constructor() {
  > 36 |         window.sfmanager = this
       |         ^^^^^^^^^^^^^^^^
    37 |         registerLicense('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    38 |         Grid.Inject(ContextMenu, Group, Filter, Sort, Page, VirtualScroll, ExcelExport
    39 |             , LazyLoadGroup, Resize, Selection, InfiniteScroll) //Preload all modules beforehand.

[TypeScript] Found 4 errors. Watching for file changes.`

### Expected behavior

Application should start as in 23.2.6

### Minimal reproducible example

any multi module project should reproduce this

### Versions

- Vaadin / Flow version: 23.3.0
- Java version: 15
- OS version: Win10
- IDE (if applicable): IntelliJ

**Comment by finaris-cs** [comment] 2022-12-21 09:37
In meantime found out that most of recursively added generated stuff is caused by vaadin-maven-plugin prepare-frontend calls in used modules. When removing these, i still have 1 recursive "generated" folder containing a problematic index.ts and a file named jsdom-exporter-bundle.js

`Started Vite. Time: 9580ms
  ➜  Local:   http://127.0.0.1:52690/VAADIN/

 ERROR(TypeScript)  Cannot find module '../../target/frontend/generated-flow-imports' or its corresponding type declarations.
 FILE  C:/intellij_workspace/SQACE/Application/gui/main/frontend/generated/jar-resources/generated/index.ts:20:25

    18 |
    19 | const { serverSideRoutes } = new Flow({
  > 20 |   imports: () => import('../../target/frontend/generated-flow-imports')
       |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    21 | });
    22 |`

**Comment by mcollovati** [comment] 2022-12-21 10:39
I tried to reproduce the issue with a simple multimodule project with component modules without `vaadin-maven-plugin` and resources in `src/main/resources/META-INF/frontend` and I cannot see any error.

The only way I could reproduce the problem was by manually copying `frontend/generated` (created by a wrong module setup with `vaadin-maven-plugin` enabled) folder under `src/main/resources/META-INF/frontend` in one of the submodules.

But I may have something missing on my test project. Do you mind sharing an example project that reproduces the issue?

**Comment by finaris-cs** [comment] 2022-12-21 11:08
can be closed, residual problem was cased by some old generated resources

**Comment by mcollovati** [comment] 2022-12-21 11:34
Good, I'll close it. Thanks for reporting and to help investigating the issue

**Closed by mcollovati** 2022-12-21 11:34 UTC
