### ISSUE TITLE
Fusion endpoints do not work with Spring Boot 2.3.2 (work with 2.2.0)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9199] opened 2020-10-19 14:54 UTC
Upgrading Spring Boot to 2.3.2 breaks Fusion endpoints in projects where they work without issues with Spring Boot 2.2.0. Vaadin 18.0.0.alpha1

Steps to reproduce:
* download the default starter from start.vaadin.com (select TypeScript + HTML and Vaadin 18)
* see that the project uses Spring Boot 2.3.2 by default
* update `AboutEndpoint.java`: add a `getVersion` method:
    ```java
    @Endpoint
    @AnonymousAllowed
    public class AboutEndpoint {
        public String getVersion() {
            return "1234";
        }
    }
    ```
* update `about-view.ts`: show the version from the endpoint:
    ```ts
    import * as endpoint from '../../generated/AboutEndpoint';
    ...
    private version = "";
    async connectedCallback() {
      super.connectedCallback();
    
      this.version = await endpoint.getVersion();
      this.requestUpdate();
    }
    
    render() {
      return html`
        <br />
        Content placeholder
        <br />
        version: ${this.version}
      `;
    }
    ```
* see that the endpoint call fails with HTTP status 404 (and nothing in the server logs)
* downgrade Spring Boot to 2.2.0 in `pom.xml` and restart the app with `mvn clean spring-boot:run`
* see that the endpoint call to `AboutEndpoint.getVersion()` succeeds and the server-side value is displayed as expected

**Comment by knoobie** [comment] 2020-10-19 15:36
Just an idea: Spring Boot removed `spring-boot-starter-validation` from the `spring-boot-starter-web` - this could possible explain your problem, because Fusion uses `javax.validation` under the hood to create the endpoints. 


See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters

**Comment by vlukashov** [comment] 2020-10-20 06:44
This is a weird one. I re-build _the same exact project_ today and the issue does not reoccur anymore.

**Comment by haijian-vaadin** [comment] 2020-10-23 11:31
Prefer to close it for now as it cannot be reproduced. We can reopen this issue once we ran into it again.

**Closed by haijian-vaadin** 2020-10-23 11:31 UTC
Labels: Impact: Low, Severity: Minor, bug, fusion
