### ISSUE TITLE
npm resolution fails in multi-module project (14beta2)

### ISSUE THREAD

**Issue by eiswind** [vaadin/flow#5787] opened 2019-05-28 06:57 UTC
I tried to convert my multi-module maven app from bower mode to npm. I get a lot of errors like

```
 ERROR in ../target/frontend/generated-flow-imports.js
2019-05-28 08:50:24.218 ERROR 22066 --- [        webpack]                                          : Module not found: Error: Can't resolve '@vaadin/vaadin-button/src/vaadin-button.js' in '/home/thomas/projects/eiswind/hello-vaadin14/hello-vaadin14-module/target/frontend'
2019-05-28 08:50:24.218 ERROR 22066 --- [        webpack]                                          :  @ ../target/frontend/generated-flow-imports.js 6:0-52
2019-05-28 08:50:24.218 ERROR 22066 --- [        webpack]                                          : 
```
Just created a little example for you to reproduce it with an hello-world app that was generated with vaadin-cli.

https://github.com/eiswind/hello-vaadin14

**Comment by pleku** [comment] 2019-05-29 07:55
Could be related to https://github.com/vaadin/flow/issues/5655

**Comment by denis-anisimov** [comment] 2019-05-29 11:35
Yeah, it looks like this is the same as #5655.

>I tried to convert my multi-module maven app from bower mode to npm. I get a lot of errors like

Thanks a lot for the project but I don't see steps to reproduce.
What should I do to see the mistakes ?
If I run 
- `mvn install` in the main project
- `mvn -pl hello-vaadin14-module spring-boot:run`

then everything works fine: app works as it's expected and not any error.

So I guess this is just duplicate of #5655.
I'm closing this ticket. If you think this is not a duplicate then please just reopen and provide exact steps to reproduce.

**Closed by denis-anisimov** 2019-05-29 11:35 UTC
Labels: bug, npm

**Comment by eiswind** [comment] 2019-05-29 12:55
I see. running mvn package before launching the app from the IDE helps.
But it's unbearably slow. I'll file another one for that.
