### ISSUE TITLE
how to validate a form in TypeScript

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#7427] opened 2020-01-26 21:45 UTC
When adding form validation to a form in TypeScript with Vaadin, I want to find relevant copy/paste-able examples in Vaadin docs, so that I know:
 - how to validate a form (per field / as a whole / cross-field)
   I want the most common validators to be available OOtB: min , max , required , notBlank , pattern , minLength , maxLength , numeric, etc
 - how to show that the form does not pass validation
 - how to convert data formats between DOM / backend
 - how to run validations asynchronously on the backend

**Comment by haijian-vaadin** [comment] 2020-05-19 07:51
A duplicate of smaller tickets: #7934(show validation errors), #8377(cross-field validation), #7933(Validation API), #7931(Converter), #7932(general vaildators)

**Closed by haijian-vaadin** 2020-05-19 07:51 UTC
Labels: ccdm
