### ISSUE TITLE
Unable to remove attribute not set on the server

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2193] opened 2017-08-17 13:28 UTC
Given a template with e.g.
`<button foo=bar>`

I can map the button to an element on the server and change the value of `foo` to `baz` using `element.setAttribute("foo","baz");`. It is, however, not possible to remove the attribute using `element.removeAttribute("foo");`.  

Except, if I first set the attribute to some value, e.g. the initial value using
`element.setAttribute("foo","bar");`
then I can remove it using
`element.removeAttribute("foo");`. But these calls have to be in separate requests so it does not even function as a workaround.

**Comment by pleku** [comment] 2020-02-26 12:56
This is working as designed, and any changes to this should be considered as an enhancement (#3735). Closing this issue as "it is not a bug".

There might be a way to workaround this by using the server side API to synchronize the property (not tested).

**Closed by pleku** 2020-02-26 12:56 UTC
Labels: bug, element API
