### ISSUE TITLE
ComponentTemplateRenderer too slow

### ISSUE THREAD

**Issue by tomasell** [vaadin/flow#3165] opened 2017-12-15 10:34 UTC
When I add a component as grid cell using ComponentTemplateRenderer, rendering is too slow.
I post a gif as attachment as you can see.

```java
grid.addColumn(new ComponentTemplateRenderer<>(device -> { return new Span(device.getClock());}));
// no more data are retrieved
```

Maybe new implementazione of ComponentTemplateRenderer::getTemplate is involved.
![componenttemplaterenderer](https://user-images.githubusercontent.com/3263675/34038164-aed71d6a-e18b-11e7-8492-c9c698857668.gif)
 Thanks!

**Comment by pleku** [comment] 2017-12-15 10:52
Hello. Thanks for the feedback, marking this a (very likely) duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/3

**Closed by pleku** 2017-12-15 10:52 UTC

**Comment by gilberto-torrezan** [comment] 2017-12-15 10:55
I don't think they are the same issue. Actually, the current "blink" on the Grid is a consequence of the asynchronous rendering introduced to avoid Grid from blocking the UI.

The problem is that this asynchronous rendering is taking too much time to happen. It is probably related to https://github.com/vaadin/vaadin-grid-flow/issues/46
