### ISSUE TITLE
Displaying DatePickers is very slow

### ISSUE THREAD

**Issue by Wnt** [vaadin/flow#5257] opened 2019-03-13 13:12 UTC
Displaying a 16 DatePickers takes more than half a second.

Steps to reproduce:

1. open the Vaadin UI defined in the code below.
2. switch to 'Datepickers in a layout' tab and back to 'Empty tab' to make browser load all needed dependencies
3. switch again to the 'Datepickers in a layout' tab and measure the time it takes the DatePickers to be visible.

Actual result: it takes about 500ms - 1000ms for the DatePickers to be visible.

Expected result: DatePickers are visible in less than 100ms

Looks like most of the time (~1 second) is spent on the server side as highlighted in the screenshot.

Minimal code to reproduce the issue:
```java
@Route("")
@Theme(Lumo.class)
@HtmlImport("frontend://bower_components/vaadin-lumo-styles/presets/compact.html")
public class MainView extends VerticalLayout {

	private static final int COUNT = 16;

	public MainView() {
		Tabs mainTabs = new Tabs();
		add(mainTabs);
		mainTabs.setWidthFull();

		VerticalLayout firstTabContent = new VerticalLayout();
		firstTabContent.setSizeFull();
		VerticalLayout secondTabContent = new VerticalLayout();
		secondTabContent.setSizeFull();
		VerticalLayout thirdTabContent = new VerticalLayout();
		thirdTabContent.setSizeFull();
		VerticalLayout fourthTabContent = new VerticalLayout();
		fourthTabContent.setSizeFull();
		Tab firstTab = new Tab("Empty tab");
		Tab secondTab = new Tab("Grid");
		Tab thirdTab = new Tab("Datepickers in a layout");
		Tab fourthTab = new Tab("Datepickers in a Grid");
		mainTabs.add(firstTab, secondTab, thirdTab, fourthTab);

		mainTabs.addSelectedChangeListener(change -> {
			remove(firstTabContent);
			remove(secondTabContent);
			remove(thirdTabContent);
			remove(fourthTabContent);
			if (mainTabs.getSelectedTab() == firstTab) {
				add(firstTabContent);
				expand(firstTabContent);
			} else if (mainTabs.getSelectedTab() == secondTab) {
				add(secondTabContent);
				expand(secondTabContent);
			} else if (mainTabs.getSelectedTab() == thirdTab) {
				add(thirdTabContent);
				expand(thirdTabContent);
			} else {
				add(fourthTabContent);
				expand(fourthTabContent);
			}
		});

		Grid<Dto> grid = new Grid<>(Dto.class);
		List<Dto> data = new ArrayList<>();
		for (int i = 0; i < COUNT; i++) {
			data.add(getNewMockDto());
		}
		grid.setItems(data);
		grid.setSelectionMode(SelectionMode.MULTI);
		secondTabContent.add(grid);
		secondTabContent.expand(grid);

		for (int i = 0; i < COUNT; i++) {
			thirdTabContent.add(new DatePicker(LocalDate.now()));
		}
		thirdTabContent.setSpacing(false);

		Grid<Dto> datepickerGrid = new Grid<>(Dto.class);
		datepickerGrid.setItems(data);
		datepickerGrid.setSelectionMode(SelectionMode.MULTI);
		datepickerGrid.setColumns("property1");
		datepickerGrid.addComponentColumn(item -> {
			return new DatePicker(item.getDate().atZone(ZoneId.systemDefault()).toLocalDate());
		}).setHeader("Date");
		fourthTabContent.add(datepickerGrid);
		fourthTabContent.expand(datepickerGrid);

		setSizeFull();
	}

	private Dto getNewMockDto() {
		return new Dto(UUID.randomUUID().toString(), LocalDate.now().atStartOfDay().toInstant(ZoneOffset.UTC));
	}

	public static class Dto {

		private String property1;
		private Instant date;

		public Dto(String property1, Instant date) {
			super();
			this.property1 = property1;
			this.date = date;
		}

		public String getProperty1() {
			return property1;
		}

		public void setProperty1(String property1) {
			this.property1 = property1;
		}

		public Instant getDate() {
			return date;
		}

		public void setDate(Instant date) {
			this.date = date;
		}

	}
}
```
and here's the whole test project: https://github.com/Wnt/vaadin-slowness-test
![image](https://user-images.githubusercontent.com/886091/54281283-0d336000-45a2-11e9-8b5f-c873e14fe083.png)

![image](https://user-images.githubusercontent.com/886091/54281158-c8a7c480-45a1-11e9-9ab1-d9cdd7a28d18.png)
![image](https://user-images.githubusercontent.com/886091/54281232-effe9180-45a1-11e9-90a4-c2d389072923.png)
Using Windows 10, Chrome 72, Oracle JDK 11.0.1, Vaadin 13.0.1.

related to
https://github.com/vaadin/vaadin-grid-flow/issues/584

**Comment by Legioth** [comment] 2019-03-13 13:14
Closing as a duplicate of #5256 since these share the same root cause.

**Closed by Legioth** 2019-03-13 13:14 UTC
