### ISSUE TITLE
Redirection after login does not work

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#9787] opened 2021-01-11 13:49 UTC
Checkout bakery and set vaadin version to `19.0.0.alpha2` 
Visit `/dashboard` it will ask for login, after that it redirects to `/` instead of the original requested location

**Comment by joheriks** [comment] 2021-01-12 07:41
I can't reproduce this by doing the following:
- checked out `master` branch of https://github.com/vaadin/bakery-app-starter-flow-spring
- updated `pom.xml`:  `<vaadin.version>19.0.0.alpha2</vaadin.version>`
- added `"/sw-runtime-resources-precache.js" to `SecurityConfiguration.java` to work around #9786
- run `mvn spring-boot:run`
- go to http://localhost:8080/dashboard, is redirected to login.
- after logging in (as `admin@vaadin.com`, pw `admin`), the login succeeded and I am redirected to the dashboard view (

Anything missing from the steps?

**Comment by manolo** [comment] 2021-01-17 07:28
* checkout `update-vaadin-19.0.0.alpha2-1610135647` of bakery (it is already using v19 y the `sw` added)
* run `mvn verify -Pit,production  -Dit.test=LoginIT`

There are two method failing 
```
[ERROR]   LoginIT.loginToNotDefaultUrl:32 » Timeout Expected condition failed: waiting f...
[ERROR]   LoginIT.openLoginAfterLoggedIn:38->loginToNotDefaultUrl:32 » Timeout Expected ...
```

**Comment by haijian-vaadin** [comment] 2021-01-21 07:19
The security config in the Bakery app needs to be updated. It's fixed in [this commit ](https://github.com/vaadin/bakery-app-starter-flow-spring/pull/1141/commits/14f774c7cbaf28564981e1fee148e26de1f7180b)

**Closed by haijian-vaadin** 2021-01-21 07:19 UTC
Labels: fusion

**Comment by chkpnt** [comment] 2021-07-28 10:07
Mh, got an 404 and can find only a docs-repository (https://github.com/vaadin/bakery-app-starter-flow-docs). Is it gone?
