### ISSUE TITLE
Broken link in dev tools window

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/flow#17700] opened 2023-09-22 12:14 UTC
### Description of the bug

After clicking the }> logo and "Theme Editor" in an application without a custom theme, the message shows a link to the documentation. This link is broken. It goes to https://vaadin.com/docs/latest/styling/custom-theme/creating-custom-theme (404).

### Expected behavior

The link is not broken.

### Minimal reproducible example

Any Vaadin app with no custom themes.

### Versions

- Vaadin / Flow version: Vaadin 24.1.10
- Java version: 17

**Comment by MarcinVaadin** [comment] 2023-09-22 14:24
Duplicate of https://github.com/vaadin/flow/pull/17482 @mshabarov please decide if should be merged into 24.1. I didn't check when documentation URL has been updated.

**Comment by jouni** [comment] 2023-09-22 19:49
We could add a redirect from that URL to https://vaadin.com/docs/styling/application-theme

**Comment by mshabarov** [comment] 2023-09-26 11:08
@MarcinVaadin I see no obstacles to fix the link in 24.1. I've placed a target/24.1 label on the PR, so hope it will be picked and merged soon.

**Comment by mshabarov** [comment] 2023-09-26 11:09
Let me close this ticket.

**Closed by mshabarov** 2023-09-26 11:09 UTC
Labels: Theme Editor
