### ISSUE TITLE
resultHandler for UI.getPage().executeJs() is not invoked when a modal dialog is shown

### ISSUE THREAD

**Issue by willemv** [vaadin/flow#13398] opened 2022-03-30 11:37 UTC
### Description of the bug

When calling `UI.getCurrent().getPage().executeJs(js).then(resultHandler, errorHandler)` in reaction to a button click on a modal dialog, the resultHandler nor errorHandler are triggered.

The javascript itself _is_ executed, however.

### Expected behavior

The resultHandler and errorHandler should be run, after all, the javascript _was_ executed.

### Minimal reproducible example

```
@PageTitle("Modal Dialogs")
@Route(value = "")
public class ModalDialogs extends VerticalLayout
{
    public ModalDialogs()
    {
        UI ui = UI.getCurrent();
        add(new Button("Modal Dialog", clicked -> {
            Dialog modalDialog = new Dialog(new Div(new Span("Modal dialog")));
            modalDialog.setCloseOnEsc(false);
            modalDialog.setCloseOnOutsideClick(false);
            modalDialog.setModal(true);

            modalDialog.add(new Button("Execute JS", clickEvent -> {
                ui.getPage().executeJs("console.log($0);", Instant.now().toString())
                  .then(success -> System.out.println("should be printed, but isn't"), System.out::println);
            }));
            modalDialog.add(new Button("Close", clickEvent -> modalDialog.close()));
            modalDialog.setWidth("40ch");

            modalDialog.open();
        }));
    }
}
```
### Versions

- Vaadin / Flow version: 23.0.0
- Java version: 11.0.13
- OS version: Ubuntu Linux 18.04

**Comment by caalador** [comment] 2022-03-31 05:55
Closing the issue as a duplicate of #13208 which was fixed in release 23.0.2
Tested the reported case with 23.0.3 and it works as expected.

**Closed by caalador** 2022-03-31 05:55 UTC
