### ISSUE TITLE
@PreserveOnRefresh does not work with MPR

### ISSUE THREAD

**Issue by mletenay** [vaadin/flow#11279] opened 2021-06-17 15:08 UTC
### Description of the bug / feature
The @PreserveOnRefresh functionality stops working as soon as any legacy Vaadin 8 component is displayed.
If the V8 label is commented out in the example below, @PreserveOnRefresh works again.
### Minimal reproducible example
```
package com.example.application.views.helloworld;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;

@Route("myview")
@PreserveOnRefresh
public class PreservedView extends VerticalLayout {

  public PreservedView() {
    add(new TextField("Content will be preserved"));
    add(new com.vaadin.mpr.LegacyWrapper(new com.vaadin.ui.Label("V8 Label")));
  }
}
```
### Expected behavior
@PreserveOnRefresh should work with Vaadin Framework components via Multi-platform runtime.
### Actual behavior
Brief debugging shows the issue is caused by broken windowName ("v-wn") behavior.
When MPR is used, every single request receives new window name (its value looks like UUID).
And since @PreserveOnRefresh relies on stable v-wn, it no longer works.
### Versions:
    - Vaadin / Flow version: 20.0.3 + MPR 5.0.3 + Framework 8.11.3

**Comment by pleku** [comment] 2021-06-18 07:09
Closing as a duplicate of https://github.com/vaadin/multiplatform-runtime/issues/85

**Closed by pleku** 2021-06-18 07:09 UTC
