### ISSUE TITLE
Static files from /VAADIN/ not compliant anymore with reverse proxy

### ISSUE THREAD

**Issue by 2portusbswitch** [vaadin/flow#15399] opened 2022-12-08 00:49 UTC
# Description of the issue

I have a cloud infastructure with multiple vaadin ui, each beeing in his own service (eg different docker containers)
all vaadin ui use vaadin.urlMapping=/

These vaadin ui are behind a reverse proxy.
so app ui1 with vaadin.urlMapping=/ is servered to the web browser as https://server/ui1/
so app ui2 with vaadin.urlMapping=/ is servered to the web browser as https://server/ui2/
etc

With vaadin 22.0.15, the static files in the html file are requested like src="VAADIN/....". As the page of ui1 was served at the end to the web browser as https://server/ui1/, the static file requested by the web browser was https://server/ui1/VAADIN/... and the reverse proxy was correctly routing this request to the ui1 service as  https://ui1-internal-server/VAADIN/..  

I moved to vaadin 23.2.7. I now see static files requested as /VAADIN/ and not anymore as /ui1/VAADIN/. So the served url is ignored and static files are always requested from the root.
As a consequence, the reverse proxy don't know where to route the request back to the original service.

**Comment by mcollovati** [comment] 2022-12-20 11:38
A workaround for Spring Boot base application would be to serve the application setting the `server.servlet.context-path` property to match the reverse-proxy configuration.
For example, `server.servlet.context-path=/ui1`

**Comment by 2portusbswitch** [comment] 2022-12-24 11:07
Thanks for the suggestion. 
I have made a try and it seems to work from the pure Vaadin point of view. 
However this workaround trigger a number of issues as it changes the root for the servlet including spring boot actuator entry point etc so the different monitoring/isalive mecanism I use stopped working. 
I tried to change vaadin.urlMapping and it seems to also move the VAADIN static file which is a bit surprising as it was the initial reason a few vaadin release ago for me stay on / + reverse proxy as the  VAADIN static path was not changed initialy. 
I will continue to investigate but I will very likely postpone vaadin 23 upgrade.

**Comment by mvysny** [comment] 2023-02-05 15:08
I have exactly the same problem. I have a microk8s with ingress reverse proxy, mapping from `/app1` to `/`; I'm running a Vaadin 23.3.5-based non-Spring app in the root context. http://localhost/app1/ works properly, while http://localhost/app1 only shows blank screen.

The problem is that `index.html` loads `indexhtml.2ae6b87b.js` from `./VAADIN/build/indexhtml.2ae6b87b.js`, which resolves to `http://localhost/VAADIN/build/indexhtml.2ae6b87b.js` when resolving against `http://localhost/app1`, which is a 404, and thus Vaadin doesn't initialize.

**Comment by mcollovati** [comment] 2023-02-10 16:29
@2portusbswitch a question to clarify your setup
since `/*` is the default URL mapping for Vaadin, if you configure the reverse proxy to forward `https://server/ui1/(.*)` to `https://ui1-internal-server/$1` it should work without any problem, since also `https://server/ui1/VAADIN/xxx` should be forwarded to `https://ui1-internal-server/VAADIN/xxx`

Perhaps I did not understand correctly your configuration.
Could you share the reverse proxy configuration?

**Comment by mcollovati** [comment] 2023-02-10 16:33
@mvysny I post here the conclusions of our discussion, in case it may be of any help for someone else

The problem with `/app1` seems more an issue with the reverse proxy configuration, that should perhaps issue a redirect from `/app1` to `/app1/` instead of serving `/app1` as the `index.html` file.

**Comment by 2portusbswitch** [comment] 2023-02-12 17:19
@mcollovati : thanks for looking at the issue

I have build a demonstrator of the issue with a vaadin 22 and a vaadin 23 app

https://www.dropbox.com/s/0538cavbyvgs6bb/Vaadin23proxyIssue.zip?dl=0

There are 3 directories in this example 

- app22 ... a vaadin 22 helloworld app
- app23 ... a vaadin 23 helloworld app
- nginx-1.17.10 ... nginx setup as a reverse proxy
 
The two files build.cmd and run.cmd build the apps and run the apps + nginx.

Vaadin apps are available directly 
- https://localhost:8081 for app22 
- https://localhost:8082 for app23
 
Nginx is on port 8080

I have setup 2 reverse proxy entries in nginx (cf  nginx-1.17.10\conf\nginx.conf)
These two entries are setup in the same way for the vaadin 22 and 23 app

So through the proxy, the vaadin app are available on

 - https://localhost:8080/app22/ for app22 
 - https://localhost:8080/app23/ for app23
 
At this stage, the vaadin 22 app works fine, the vaadin 23 app doesn't work

Looking in the details of vaadin 23 exchange we get

- 1st request to http://localhost:8080/app23/  is fine and return the main html page
- but next request http://localhost:8080/VAADIN/@vite/client is not as /VAADIN should be /app23/VAADIN but is asked form the root instead

Let me know if it helps or if I can help ...

**Comment by mcollovati** [comment] 2023-04-14 13:30
Hi @2portusbswitch, sorry for so long delay in the answer.
Based on your information, I tried the following configuration that seems to work well.
Please let me know if it may work for you, or if you can see other issues with this setup

```
upstream app22 {
    server vaadin1:8080 max_fails=3 fail_timeout=20s;
    keepalive 5;
}

upstream app23 {
    server vaadin2:8080 max_fails=3 fail_timeout=20s;
    keepalive 5;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {

    listen       80;
    server_name  localhost;

    location ~* "^/app22(/|$)(.*)" {
        proxy_http_version 1.1;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-Host $host;
        proxy_set_header        X-Forwarded-Server $host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection $connection_upgrade;
        proxy_cookie_path       ~*^/(.*) /app22/$1;
        proxy_redirect off;
        proxy_buffering off;
        proxy_ignore_client_abort off;
        proxy_connect_timeout 3s;
        proxy_read_timeout 20s;
        proxy_send_timeout 20s;

        rewrite ^(/app22)$ $scheme://$http_host$1/ permanent;
        rewrite "(?i)/app22/(.*)" /$1 break;
        proxy_pass http://app22;
    }

    location ~* "^/app23(/|$)(.*)" {
        proxy_http_version 1.1;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-Host $host;
        proxy_set_header        X-Forwarded-Server $host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection $connection_upgrade;
        proxy_cookie_path       ~*^/(.*) /app23/$1;
        proxy_redirect off;
        proxy_buffering off;
        proxy_ignore_client_abort off;
        proxy_connect_timeout 3s;
        proxy_read_timeout 20s;
        proxy_send_timeout 20s;

        rewrite ^(/app23)$ $scheme://$http_host$1/ permanent;
        rewrite "(?i)/app23/(.*)" /$1 break;
        proxy_pass http://app23;
    }

}
```

**Comment by mcollovati** [comment] 2023-05-02 10:57
@2portusbswitch do you managed to try the above configuration?

**Comment by 2portusbswitch** [comment] 2023-05-02 12:06
Hi, sorry for the long response time and many thanks for your answer.
I was just running the test this morning
It doesn't seems to work on my side
Fine with vaadin 22 but the vaadin 23 app doesn't load

Passed the first response with the html page, the 2nd request is "http://127.0.0.1:8080/VAADIN/@vite/client" so no indication for the proxy to route the request correctly to the right app, VAADIN folder is still requested from root instead of being relative to one app or another

The matching script node from the first html page is looking like
<script type="module" src="/VAADIN/@vite/client"></script>

Sorry, not a routing expert at all but I feel this line may be wrong, as it starts with "/" the proxy will not consider this path as relative no ?

**Comment by mcollovati** [comment] 2023-05-02 12:32
So, it seems like you are not deploying a production build

**Comment by 2portusbswitch** [comment] 2023-05-02 15:45
Ouch, painful. this has been working since vaadin 13 at least
I have no many other choice than completely stopping using vaadin in dev mode for the moment
Do you if it is something that will be fixed ?

**Comment by mcollovati** [comment] 2023-05-03 05:46
I'm uncertain if this will be changed.
The current implementation works in production mode and in development mode with common scenarios, where the reverse proxy path prefix matches the context path of the backend application.

As a workaround for development mode with Vaadin 23.3 you can switch back to [webpack ](https://vaadin.com/docs/v23/configuration/live-reload/#webpack-feature-flag). I tested it with 23.3.11 and the suggested configuration also worked in development mode.
However, webpack is not supported on Vaadin 24.

Otherwise, you should have to try configuring context-path or servlet mapping on backed application and handle the load set up accordingly.

**Comment by mcollovati** [comment] 2023-05-03 07:23
A workaround for Vite could be to add some content rewrite on nginx. Not good for performance, but it may be acceptable for a development environment.
For example, the following rule seems to work, but they may not be enough

```
sub_filter_types application/javascript;
sub_filter '"/VAADIN/' '"/app23/VAADIN/';       # html script tags and javascript imports
sub_filter "'/VAADIN/" "'/app23//VAADIN/";     # html script tags and javascript imports
sub_filter "(/VAADIN/" "(/app23//VAADIN/";    # inlined CSS
sub_filter_once off;
```

**Comment by 2portusbswitch** [comment] 2023-05-03 10:59
Thank you @mcollovati for your help and your proposals. 
I'm working on a microservice complex cloud app so I need in dev to stick as close as possible to the live environment to avoid issues and bugs but also to be able to debug. I have multiple applications and each application can be present at the same time in different version in a blue green deployment case ... a lot a routing case to handle dynamically :-)
I will have a try to your sub_filter suggestion,may be it can save me from running in production mode in dev ... This could take a bit of time as I have to change to vaadin 24 plus spring upgrade at the same time so a lot of things to test and fix ....

**Closed** 2023-06-13 09:42 UTC
Labels: waiting for author, workaround
