### ISSUE TITLE
Favicon not shown in production mode, when placed under resources

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#6842] opened 2019-11-06 06:08 UTC
Following problem:
Based on the bakery starter app I put the customer's favicon under `src/main/resources/...`. When in dev mode the icon is shown, but in production mode it shows the default icon (blue square/white circle) instead. The main layout class is annotated with `@PWA(name = "..." , shortName = "...", enableInstallPrompt = false)`.

When putting the icon into `src/main/webapp/icons` it also works for production mode. That's the way as it is mentioned in the docs.

I'm not sure, if this is now a Flow bug and Flow should also recognize the icon when placed in `resources` or if it is a bakery app `bug`, so that the bakery simply put resources in the wrong location.

**Comment by DiegoCardoso** [comment] 2019-11-11 13:05
There's has been some reports about what I believe is related to this same issue here
https://vaadin.com/forum/thread/17784234/17937345

**Comment by edler-san** [comment] 2020-06-09 05:12
It seems the PWA annotation overrides the default and you have to use its _iconPath_ attribute for that.

(Thanks to Joel for letting us know!)

**Comment by denis-anisimov** [comment] 2020-07-28 06:14
I cannot reproduce the issue.
`Based on the bakery starter app I put the customer's favicon under src/main/resources/...` : I don't see the exact path which makes this ticket extremely unclear but based on my investigation this path is
`src/main/resources/META-INF/resources/icons/icon.png`.
The reason why I think this is the path is : `icon.png` is shown as an icon in the browser tab.
Also `@PWA` annotation doesn't have a specific `iconPath`  value which means that default `"icons/icon.png"` is used which is exactly `src/main/resources/META-INF/resources/icons/icon.png` for Spring.

This icon is shown in dev mode: `true`.
This icon is shown for me in production mode.
If I change the icon then it's shown in dev mode but it's cached by the browser.
That's why you see the old icon.
Clearing the cache allows to see the updated icon in production mode as well.

I'm using the latest bakery based on `17.0.0.alpha7` (since the version is not specified)  but I'm pretty  sure it doesn't relate to Vaadin platform version since there were no changes in PWA for ages.

I'm closing this ticket. Please reopen or let me know if there is something I've missed and I reopen the ticket.

**Closed by denis-anisimov** 2020-07-28 06:14 UTC
Labels: Impact: High, Severity: Major, bug, investigation

**Comment by TorstenKruse** [comment] 2020-07-28 06:25
Which browser did you use for testing? It looks like the error occurs on chrome but not on firefox.
Did you read the thread referenced above by Diego? There are more details.

Personally I have the same problem in my project based on current bakery app with vaadin 14.

So it would be quite nice, if you could re-test the issue with bakery vaadin 14 and chrome. Thanks.

**Comment by denis-anisimov** [comment] 2020-07-28 06:35
Thanks.
Retested in Chrome.
In my case there is no even need to clear the browser cache (it was needed in Safari).

Works as expected.

Did you clear the browser cache ?

**Comment by denis-anisimov** [comment] 2020-07-28 06:41
Tested with latest `17.0.0.alpha7` _AND_ v14 and Chrome.
Everything works fine.

Please clear your browser cache. There can't be magic: if it works in other browsers then it should work in Chrome as well since the file is obviously generated correctly (it works in other browsers) and the only thing is the "client side setting" which point to the browser which file to use. Again: since it works in other browsers then this instruction presents.
I don't see any other reason except browser cache.

**Comment by TorstenKruse** [comment] 2020-07-28 14:50
Of course I cleared the browser cache...so many times. Did not help.
When I call <site-url>/icons/icon.png I get the right custom icon.
But <site-url>/icons/icon-144x144.png or icons/icon-16x16.png still deliver the default vaadin icon (blue with white circle).
Even using curl delivers the default icon. So perhaps I (and all the others in the referenced links) did miss anything in the build process?

So I tried again starting from https://vaadin.com/start/v14 with Vaadin Bakery.
Download and replace icon.png

mvn -Pproduction spring-boot:run
-> the custom icon is shown -> fine

mvn -Pproduction install
java -jar target\my-starter-project-1.0-SNAPSHOT.war
-> the default vaadin icon is shown -> fail

Any idea how to solve this?

**Comment by denis-anisimov** [comment] 2020-07-29 06:15
I would like to emphasize the fact that I cannot reproduce the issue.
Since I'm not familiar with this functionality I cannot fix the issue which I cannot reproduce: I can't imagine what can be wrong.

So without exact information it's impossible for me to do anything.

Now I see contradictions in the ticket description and comments which makes it very misty.
Here is your quote:
>It looks like the error occurs on chrome but not on firefox.

Then:
>But /icons/icon-144x144.png or icons/icon-16x16.png still deliver the default vaadin icon (blue with white circle).

Any idea how is that possible that the functionality works FOR YOU in firefox but not in chrome ?
The consequence of the first statement is : if you access `icons/icon-16x16.png` (in FF) it works which means that there is an image generated on the server side.
It means that there is a generate image on the server side.
And it means that only Chrome has issue on accessing to  `icons/icon-16x16.png`. I don't see how it can be possible (considering that this works in FF) except browser cache influence.

**Comment by denis-anisimov** [comment] 2020-07-29 06:26
Another _EXTREMELY IMPORTANT_  thing: we are discussing now totally different issue at least based on ticket description.

```
mvn -Pproduction spring-boot:run
-> the custom icon is shown -> fine
```

This is exactly what I'm testing and it works fine.
Thank you for confirmation.
And this is production mode definition without further clarification.

```
mvn -Pproduction install
java -jar target\my-starter-project-1.0-SNAPSHOT.war
```
This absent in the ticket description and this is the first time when I see this way of running in this ticket.
This is not just a `production` mode: this is specific execution of production mode.
Here is the ticket: https://github.com/vaadin/flow/issues/8705.
This is excellent example of the ticket which is created correctly: it contains all necessary information.

**Comment by TorstenKruse** [comment] 2020-07-29 08:09
Just to remind: I'm not the author of this issue. I just jumped in because I had the same problem, subscribed this issue and wanted to avoid it being closed without a solution. I think the original author just realized custom favicon was not working and did not know why. 

But you are totally right, the other issue describes exactly the same problem. I was even watching this too. ;-)

So I think this issue here could be closed and the other one should be solved.
