### ISSUE TITLE
Compatibility mode OSGi tests are broken in 2.5

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9973] opened 2021-02-05 06:39 UTC
https://bender.vaadin.com/viewLog.html?buildId=212394&buildTypeId=Flow_Flow25_Nightly_FlowFelixJettyIntegrationTests25&tab=buildLog

Artifacts show that application can't navigate to the route which is expected.
Dev mode page lists all available routes: there are only few routes.
There are plenty of IT views. It means that for some reason route registration is broken.
I'm pretty sure that this is not related to OSGi anyhow: everything worked yesterday.
Most likely this is related to compatibility mode and this is a regression introduced by some backport.

**Comment by mshabarov** [comment] 2021-02-09 13:10
This issue reproduces with `felix-jetty` configuration no matter whether the compatibility mode is enabled or not.
However, `test-root-context` ITs run successfully even if I enable the compatibility mode.

Another observation is that the test views with a route targets containing an URL parameter (`@OptionalParameter` or `WildcardParameter`) are resolved with a double parameter placeholder, like this:

`com.vaadin.flow.uitest.ui.BackButtonServerRoundTripView/:___url_parameter/:___url_parameter`,

which is wrong, should be:

`com.vaadin.flow.uitest.ui.BackButtonServerRoundTripView/:___url_parameter`.

If I hack the `HasUrlParameterFormat::getTemplate` to only generate a template, if no template has been generated previously, like this:

```java
if (hasUrlParameter(navigationTarget) && !urlBase.contains(PARAMETER)) {
// template generate code
}
```
then the tests are passed and routes registered as expected.

Apparently, the root cause is that the `AbstractRouteRegistry::setRoute` invoked twice for each route target.
Will check that and propose a fix.

**Closed** 2021-02-15 13:58 UTC
Labels: Impact: High, Severity: Blocker
