### ISSUE TITLE
Static files should be made available for the devloper to use in java code

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9654] opened 2020-12-15 08:33 UTC
At the moment webpack handles the copying of all static files referenced from css. This means that any file not referenced from css will not be available at runtime when the theme is under frontend folder

We should somehow be able to copy any files not made available by webpack so that they can be referenced.

**Comment by pleku** [comment] 2020-12-16 07:44
Duplicate of #9622

**Closed by pleku** 2020-12-16 07:44 UTC
Labels: theming
