### ISSUE TITLE
Element methods do not work in some cases inside vaadin-dialog

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#3513] opened 2018-02-08 13:08 UTC
When there are 2 templates in dialog, and one of them initially is displayed and another one is hidden, then it's impossible to change the first shown template. Only TemplateModel methods work.

Code example:
https://github.com/alexberazouski/skeleton-starter-flow/tree/bug/dialog-templates

1. Open dialog
2. See initial template1
3. Check checkbox
4. See template2 which is changed (by both templateModel method and button method)
5. Uncheck
6. template1 was changed by templateModel method, but not by button.setText

In browser console I see correct messages, but they are not executed in the end

**Comment by denis-anisimov** [comment] 2018-02-11 15:49
Cannot reproduce this without dialog.
May be it's specific to dialog....

**Comment by denis-anisimov** [comment] 2018-02-11 16:43
I'm not able to reproduce this for regular HTML element as well (element inside `Dialog`, e.g. `Div`).
May be something specific for Template elements.

**Comment by denis-anisimov** [comment] 2018-02-11 17:56
Weird.
I cannot reproduce it in the simplest case (no dialog, `Div` instead of button, `Div` as a container for the templates).
Need to investigate.

**Comment by denis-anisimov** [comment] 2018-02-12 06:19
The mentioned example doesn't reproduce the issue if I use `Div` instead of button.
It also doesn't reproduce the issue if there no dialog.

So it looks like this is specific to:
- `Dialog` as a container
- `Button` or may be any web component based on a template.

**Comment by denis-anisimov** [comment] 2018-02-12 06:32
Actually it seems this issue has no relation to `setVisible` feature at all.
It somehow relates to a web component injected into template via `@Id` and used inside a dialog.

No need to use `setVisible` call in this example: remove lines that modifies the visibility of the templates.
Now the button text should be modified each time when checkbox is clicked.
And it happens if I change `Button`  injected by `@Id` to `Div`.
But it doesn't happen with `Button` : the text of the button should be modified in both templates (since both of them are shown) but it's not modified at all.

**Comment by alexberazouski** [comment] 2018-02-12 08:14
It's not only the issue of `Button.setVisible`, but also with `Combobox.setValue` and even with calling `getElement().callFunction()`. 
Tried to debug this issue on client side in `ExecuteJavaScriptProcessor.handleInvocation()` and noticed that all such commands are not put into the `map`. They are added into `Reactive.addPostFlushListener(() -> handleInvocation(invocation));`.

**Comment by denis-anisimov** [comment] 2018-02-12 09:40
`setVisible`/`setValue`  shouldn't be affected by the `ExecuteJavaScriptProcessor` anyhow.

`getElement().callFunction()` is just another way of JS execution.
JS execution goes through `ExecuteJavaScriptProcessor`.
And the may be postponed in some cases via the `Reactive.addPostFlushListener`.
But that should be a totally different case.

Any property change shouldn't have any relation to (`ExecuteJavaScriptProcessor`).
If they have then I'm missing something fundamental. 
And this specific ticket is actually about property change (most likely for virtual children injected by `@Id`  which are the web components by themselves).

**Comment by denis-anisimov** [comment] 2018-02-13 09:57
Still investigating.
For some reasons splice listeners which handles children nodes for bound node are not called.
(When new text is set for `Button` it removes and creates a new text node with new text internally).

**Comment by denis-anisimov** [comment] 2018-02-13 13:46
Splice listeners are not called because they are removed.
I have no any idea why the are removed.

It looks like it happens because "checked" (or "indeterminate") property change which calls `syncToServer` method which updates the property value and for some reason this trigger dependencies computations which removes the splice listener.
But It's totally unclear for me how the property change for checkbox element may have dependencies to the totally different node.

**Comment by denis-anisimov** [comment] 2018-02-14 10:11
Most likely we will reimplement a bit `Dialog` and `Notification`.

It's still not clear how exactly it is broken.

It relates to the fact that virtual child is used internally for `Dialog` which is initially `Div` but then it becomes a template element via setting `innerHtml` property value.
This template is used to run the logic on the client side which attaches the content of the container to the dialog overlay.

If the container is not a virtual child then this bug doesn't appear.
So it might be that this somehow relates to virtual children functionality and may be also "innerHtml" property.

**Comment by gilberto-torrezan** [comment] 2018-02-15 06:49
A fix for `Dialog` and `Notification` components has been merged, but the root problem isn't solved yet.

In `Dialog`, if this line https://github.com/vaadin/vaadin-dialog-flow/blob/0bc2d15116d270966a9608cbebf5a87e1ce05340/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L46 is changed to `getElement().appendVirtualChild(container);`, the bug reappears.

Now there is a integration test just for this bug: https://github.com/vaadin/vaadin-dialog-flow/blob/0bc2d15116d270966a9608cbebf5a87e1ce05340/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithTemplateIT.java

The problem seems to be in the interaction between `@Id` mappings and `virtual children` mechanism.

**Comment by gilberto-torrezan** [comment] 2018-02-16 11:55
I'm closing this issue (since it was related just to Dialog - which is fixed now) and create a specific one for Flow.

**Closed by gilberto-torrezan** 2018-02-16 11:55 UTC
Labels: bug
