### ISSUE TITLE
DebugWindowConnection check causes problems on Liberty websockets

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13627] opened 2022-04-26 14:53 UTC
### Description of the bug

Open OpenLiberty 22 (and 19) you get
```
[err] [Atmosphere-Shared-2] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
[err] java.lang.IllegalStateException: Request object no longer valid. This object has been cancelled
[err]   at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:422)
[err]   at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:436)
[err]   at com.vaadin.flow.server.communication.PushHandler.isDebugWindowConnection(PushHandler.java:606)
[err]   at com.vaadin.flow.server.communication.PushHandler.handleConnectionLost(PushHandler.java:360)
[err]   at com.vaadin.flow.server.communication.PushHandler.connectionLost(PushHandler.java:333)
[err]   at com.vaadin.flow.server.communication.PushAtmosphereHandler$AtmosphereResourceListener.onDisconnect(PushAtmosphereHandler.java:113)
[err]   at org.atmosphere.cpr.AtmosphereResourceImpl.onDisconnect(AtmosphereResourceImpl.java:759)
[err]   at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:650)
[err]   at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:630)
[err]   at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:897)
[err]   at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
[err]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
```

Looks like it does not allow checking attributes from the request when it has been closed. 

### Expected behavior

No exception when a websocket connection is lost.

### Minimal reproducible example

https://github.com/vesanieminen/sample-mpr-v14/tree/v23

### Versions

- Vaadin / Flow version: 23.0.4

**Comment by caalador** [comment] 2022-05-04 06:10
The application doesn't work for me either, but the exception is different:
```
[INFO] [err] [Default Executor-thread-33] WARN com.vaadin.flow.server.communication.PushHandler - Error while ending request
[INFO] [err] java.lang.NullPointerException
[INFO] [err]    at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1498)
[INFO] [err]    at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:294)
[INFO] [err]    at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:562)
[INFO] [err]    at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
[INFO] [err]    at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
[INFO] [err]    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
[INFO] [err]    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
[INFO] [err]    at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
[INFO] [err]    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
[INFO] [err]    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
[INFO] [err]    at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
[INFO] [err]    at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
[INFO] [err]    at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:136)
[INFO] [err]    at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:177)
[INFO] [err]    at [internal classes]
[INFO] [err]    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[INFO] [err]    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[INFO] [err]    at java.base/java.lang.Thread.run(Thread.java:829)
[INFO] [WARNING ] AtmosphereResource was null
[INFO] [WARNING ] Problem opening websocket for ecacd648-f4f6-48b7-8e5b-729b6916b3f4
[INFO] [ERROR   ]
[INFO] java.lang.NullPointerException
```

This happens both using the downloaded wlp-webProfile8 and using the liberty-plugin with the same version.

Doc for using plugin, just add:
```
            <plugin>
                <groupId>io.openliberty.tools</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <serverName>guideServer</serverName>

					<runtimeArtifact>
						<groupId>com.ibm.websphere.appserver.runtime</groupId>
						<artifactId>wlp-webProfile8</artifactId>
						<version>22.0.0.4</version>
						<type>zip</type>
					</runtimeArtifact>
                </configuration>
            </plugin>
```
start server with `mvn liberty:run` or `mvn liberty:dev`

**Comment by caalador** [comment] 2022-05-04 07:29
In a project without MPR the application works, but I do see an exception:
```
[INFO] java.lang.NullPointerException: null
[INFO]  at org.atmosphere.websocket.WebSocket.shiftAttributes(WebSocket.java:137) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:na]
[INFO]  at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:261) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:na]
[INFO]  at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:258) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:na]
[INFO]  at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:136) ~[tomcat-embed-websocket-9.0.62.jar:9.0.62]
[INFO]  at com.ibm.ws.webcontainer31.osgi.srt.SRTConnectionContext31.finishConnection(SRTConnectionContext31.java:177) ~[na:na]
[INFO]  at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1166) ~[na:na]
[INFO]  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281) ~[na:na]
[INFO]  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1184) ~[na:na]
[INFO]  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:453) ~[na:na]
[INFO]  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:412) ~[na:na]
[INFO]  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566) ~[na:na]
[INFO]  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500) ~[na:na]
[INFO]  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360) ~[na:na]
[INFO]  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968) ~[na:na]
[INFO]  at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057) ~[na:na]
[INFO]  at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245) ~[na:na]
[INFO]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
[INFO]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
[INFO]  at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```
And in the client console there is:
```
VaadinDevmodeGizmo.js?10c7:26 

WebSocket connection to 'ws://localhost:35729/' failed: 
Connection @ VaadinDevmodeGizmo.js?10c7:26
openWebSocketConnection @ VaadinDevmodeGizmo.js?10c7:909
connectedCallback @ VaadinDevmodeGizmo.js?10c7:978
constructor.connectedCallback @ License.js?f621:48
customElements.define @ License.js?f621:51
eval @ VaadinDevmodeGizmo.js?10c7:1463
../target/flow-frontend/VaadinDevmodeGizmo.js @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:763
__webpack_require__ @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:64
eval @ vaadin.ts?0a64:1
./generated/vaadin.ts @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:834
__webpack_require__ @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:64
0 @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:857
__webpack_require__ @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:64
(anonymous) @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:199
(anonymous) @ vaadin-bundle-ff28be4a6a89e68a39dd.cache.js:202
``` 

So there is a problem with websockets, but MPR doesn't work at all with OpenLiberty.

**Comment by mshabarov** [comment] 2022-05-12 08:50
WebSocket connection error is raised for me on the client side, I'm able to see the error in the console.
But no errors are thrown on the server/java side.
What I did:
1. Download the example project
2. Add liberty plugin into the pom.xml as suggested https://github.com/vaadin/flow/issues/13627#issuecomment-1116960092
3. Add SB dev tools
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>
```
5. Run `mvn liberty:dev`
6. Seeing the error only on client side
<img width="1162" alt="Screenshot 2022-05-12 at 11 41 49" src="https://user-images.githubusercontent.com/61410877/168031198-28600925-99c5-4c77-b0b5-986eb0f9e721.png">

@Artur- @caalador did you do anything extra to these steps to get the exceptions?

**Comment by caalador** [comment] 2022-05-12 09:01
Nothing extra. Artur just created the ticket, but didn't test if I remember correctly.

Remember to use the correct branch `v23` with the test project

**Comment by vesanieminen** [comment] 2022-05-12 09:28
@mshabarov The steps to reproduce the issue are quite similar to this other ticket: https://github.com/vaadin/flow/issues/13608

What I did to get it to show up:

- Build the project
- Download [Open Liberty 22](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/22.0.0.4/openliberty-webProfile8-22.0.0.4.zip)
- Extract it and deploy the V23 project to the application server
- Observe the server logs

**Comment by mshabarov** [comment] 2022-05-12 10:50
Thanks for your suggestions, it helped.
My mistake was that I used `master` instead of `v23` branch. Besides that, I've upgraded to version `23.0.9`, otherwise I got an error about multiple `AppShellConfigurator`, which is fixed in #13608 .
But still I have not relevant error:

```
[INFO] [err] Caused by: java.lang.IllegalStateException: Failed to determine project directory for dev mode. Directory '/Users/mikhail/workspace/vaadin/reproduce/sample-mpr-v14/target/liberty/wlp/usr/servers/guideServer' does not look like a Maven or Gradle project. Ensure that you have run the prepare-frontend Maven goal, which generates 'flow-build-info.json', prior to deploying your application
[INFO] [err]    at com.vaadin.base.devserver.startup.DevModeInitializer.getBaseDirectoryFallback(DevModeInitializer.java:383)
[INFO] [err]    at com.vaadin.base.devserver.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:211)
[INFO] [err]    at com.vaadin.base.devserver.DevModeHandlerManagerImpl.initDevModeHandler(DevModeHandlerManagerImpl.java:80)
[INFO] [err]    at com.vaadin.base.devserver.startup.DevModeStartupListener.initialize(DevModeStartupListener.java:74)
[INFO] [err]    at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:42)
[INFO] [err]    ... 47 more

```
(running with the plugin).

Trying run it with Open Liberty bundle...

**Comment by mshabarov** [comment] 2022-05-12 12:00
Eventually caught the error with Open Liberty 22 bundle:

```
[err] [ForkJoinPool.commonPool-worker-5] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Started Webpack. Time: 5897ms
[err] [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - No issues found.
[WARNING ] Exception during suspend() operation java.lang.IllegalStateException: Request object no longer valid. This object has been cancelled
[err] [Atmosphere-Shared-1] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
[err] java.lang.IllegalStateException: Request object no longer valid. This object has been cancelled
[err] 	at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:422)
[err] 	at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:436)
[err] 	at com.vaadin.flow.server.communication.PushHandler.isDebugWindowConnection(PushHandler.java:606)
[err] 	at com.vaadin.flow.server.communication.PushHandler.handleConnectionLost(PushHandler.java:360)
[err] 	at com.vaadin.flow.server.communication.PushHandler.connectionLost(PushHandler.java:333)
[err] 	at com.vaadin.flow.server.communication.PushAtmosphereHandler$AtmosphereResourceListener.onDisconnect(PushAtmosphereHandler.java:113)
[err] 	at org.atmosphere.cpr.AtmosphereResourceImpl.onDisconnect(AtmosphereResourceImpl.java:759)
[err] 	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:650)
[err] 	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:630)
[err] 	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:897)
[err] 	at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
[err] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[err] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Artur-** [comment] 2022-05-12 12:13
I am not sure why we need to store the info that one push connection is the debug window connection as a request attribute. Can't it just be a field in `PushHandler` ...

**Comment by mshabarov** [comment] 2022-05-12 14:25
`AtmosphereResource::getResource` is used not only for checking the "debug window connection" parameter of the `AtmosphereRequest` on connection lost, but also for further session and UI retrieval in `PushHandler::handleConnectionLost` and clean up the information about closed push connection stored in the UI.

Probably ignoring `enforceScope` parameter of `AtmosphereResource` (calling `AtmosphereResource::getResponse(false)`) will be sufficient to properly handle connection lost.

**Comment by mshabarov** [comment] 2022-06-16 15:42
The application throws exceptions in so many different places.
I patched the `PushHandler` in the `flow-server` to catch the possible runtime exceptions during checking request whether is it a debug window request or not, just to see if the problem occurs in any other place:

```java
        try {
            if (isDebugWindowConnection(resource) && liveReload.isPresent()
                    && liveReload.get().isLiveReload(resource)) {
                liveReload.get().onDisconnect(resource);
                return null;
            }
        } catch (IllegalStateException | NullPointerException e) {
            return null;
        }
```

I also patched the place when `VaadinService` ends the request (usually there is no such an attribute):

```java
Object startTime = request.getAttribute(REQUEST_START_TIME_ATTRIBUTE);
if (startTime != null) {
    final long duration = (System.nanoTime() - (Long) startTime) / 1000000;
    session.setLastRequestDuration(duration);
}
```

Then the application does fail in `PushAtmosphereHandler::onStateChange` with 

```
[err] [Atmosphere-Shared-2] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
[err] java.lang.NullPointerException
[err]   at com.ibm.ws.webcontainer.srt.SRTServletRequest.getContentType(SRTServletRequest.java:701)
[err]   at javax.servlet.ServletRequestWrapper.getContentType(ServletRequestWrapper.java:184)
[err]   at org.atmosphere.cpr.AtmosphereRequestImpl.getContentType(AtmosphereRequestImpl.java:213)
[err]   at org.atmosphere.util.IOUtils.isBodyBinary(IOUtils.java:110)
[err]   at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:78)
[err]   at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:57)
[err]   at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
[err]   at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
[err]   at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
[err]   at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
[err]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[err]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[err]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err]   at java.base/java.lang.Thread.run(Thread.java:834)
```

This is not clear so far why `SRTServletRequest.getContentType` throws NPE.

**Comment by Artur-** [comment] 2022-06-20 07:27
You are including Tomcat in the WAR which will cause Atmosphere to use Tomcat classes instead of Liberty. If you add
```
    <exclusion>
            <artifactId>tomcat-embed-el</artifactId>
            <groupId>org.apache.tomcat.embed</groupId>
    </exclusion>
    <exclusion>
            <artifactId>tomcat-embed-core</artifactId>
            <groupId>org.apache.tomcat.embed</groupId>
    </exclusion>
    <exclusion>
            <artifactId>tomcat-embed-websocket</artifactId>
            <groupId>org.apache.tomcat.embed</groupId>
    </exclusion>
```
to the spring boot starter dependency, it works as expected

**Comment by mshabarov** [comment] 2022-06-20 10:29
Thanks @Artur- , this works perfectly and resolves the issue with websockets.
With MPR I have another issue, most likely because I'm missing the license server's certificate in my Open Liberty's secure directory.
Here is the error:
```
[INFO] [err] Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] [err]    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[INFO] [err]    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)
[INFO] [err]    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
[INFO] [err]    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
[INFO] [err]    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[INFO] [err]    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[INFO] [err]    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[INFO] [err]    at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[INFO] [err]    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[INFO] [err]    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[INFO] [err]    at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)
[INFO] [err]    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
[INFO] [err]    at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488)
[INFO] [err]    at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
[INFO] [err]    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
[INFO] [err]    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
[INFO] [err]    at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[INFO] [err]    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[INFO] [err]    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[INFO] [err]    at com.vaadin.pro.licensechecker.ProKeyValidator.queryServer(ProKeyValidator.java:107)
[INFO] [err]    at com.vaadin.pro.licensechecker.ProKeyValidator.validate(ProKeyValidator.java:42)
[INFO] [err]    ... 55 more
[INFO] [err] Caused by: java.security.cert.CertificateException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] [err]    at com.ibm.ws.ssl.core.WSX509TrustManager.processServerTrustError(WSX509TrustManager.java:955)
[INFO] [err]    at [internal classes]
[INFO] [err]    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[INFO] [err]    ... 71 more
```

**Comment by mshabarov** [comment] 2022-06-20 13:23
Close this ticket since it is a problem in a project setup.

**Closed by mshabarov** 2022-06-20 13:23 UTC
Labels: bug, BFP, Impact: Low, Severity: Major, MPR
