### ISSUE TITLE
Production build fails, if a projects dependencies contain the same maven artifact multiple times with a different classifier

### ISSUE THREAD

**Issue by FelixLanghof** [vaadin/flow#20609] opened 2024-12-04 07:12 UTC
### Description of the bug

For projects that contain multiple dependencies of the same maven artifact with different classifiers (or a dependency for which this applies), the production build fails with an IllegalStateException.
Example:
```stacktrace
java.lang.IllegalStateException: Duplicate key io.netty:netty-tcnative-boringssl-static (attempted merging values io.netty:netty-tcnative-boringssl-static:jar:2.0.69.Final:compil
e and io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.69.Final:compile)
[...]
at com.vaadin.flow.plugin.maven.Reflector.createIsolatedClassLoader (Reflector.java:245)
at com.vaadin.flow.plugin.maven.Reflector.of (Reflector.java:201)
at com.vaadin.flow.plugin.maven.FlowModeAbstractMojo.isHillaAvailable (FlowModeAbstractMojo.java:372)
at com.vaadin.hilla.maven.EngineConfigureMojo.execute (EngineConfigureMojo.java:56)
```

### Expected behavior

Production build runs successfully

### Minimal reproducible example

- Download the Hello World Project from https://start.vaadin.com/app (Flow/Java/Maven/Spring Boot)
- (Check that Vaadin Version is 24.5.6)
- Add a dependency that contains the same maven artifact multiple times, only with different classifiers
  - For example `io.netty:netty-tcnative-boringssl-static`
- Run `mvn -Pproduction install`

The error is 

### Versions

- Vaadin / Flow version: 24.5.6
- Java version: 17/21
- OS version: Win10
- Maven: 3.9.6

**Comment by mcollovati** [comment] 2024-12-04 07:18
Duplicate of #20555

**Closed as not planned by mcollovati** 2024-12-04 07:18 UTC
Labels: duplicate
