### ISSUE TITLE
Fails to open or reload browser tab on the second launch

### ISSUE THREAD

**Issue by jojule** [vaadin/flow#19969] opened 2024-09-18 01:27 UTC
### Description of the bug

When I launch my new project with `mvn` it opens up `http://localhost:8080/` as expected on Chrome. 

When I kill the server (mvn) and run it again, it does not launch the browser.

Way to fix the issue is to delete `target/tab.launch`. After that `mvn` agains opens the browser as expected. And recreated the file. Leading back to the original problem.

### Expected behavior

`mvn` command should always open my application in a browser.

### Minimal reproducible example

Minimal Hello World application from start.vaadin.com with two views: One for Hilla and for Flow

### Versions

Hilla: 24.5.0.alpha15
Flow: 24.5.0.alpha20
Vaadin: 24.5.0.alpha17
Copilot: 24.5.0.alpha20
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 15.0
Java: JetBrains s.r.o. 21.0.3
Browser: Chrome 128.0.6613.138 (Official Build) (arm64)
Java Hotswap: false
IDE Plugin: 1.3.1
IDE: IntelliJ 2024.2

**Comment by caalador** [comment] 2024-09-18 03:55
Yes this is by design #18393
The bigger issue was that developers restart their server, but leave the browser page open leading to an increasing amount of tabs. 
But as there is no way to know if there is a tab open in some browser there is instead a timeout (30 min) after latest open tab call.
To always open a tab just run `mvn` with the `clean` target and server start (e.g. `spring-boot:run`)

**Comment by mcollovati** [comment] 2024-09-18 04:58
Another way to always open the browser is to set vaadin.launch-browser-delay=0 in application.properties

**Comment by mshabarov** [comment] 2024-09-20 08:23
Deserves a better documentation maybe ?

**Comment by caalador** [comment] 2024-09-20 08:29
There is: https://vaadin.com/docs/latest/flow/integrations/spring/configuration#launch-browser-in-development-mode

**Comment by mshabarov** [comment] 2024-09-20 08:35
This can be documented: https://github.com/vaadin/flow/issues/19969#issuecomment-2357498924.

Also, was your problem in not having a second tab opened, or having your first tab not updates after a second run @jojule ?

I'd say if your first tab doesn't get a refresh after a second run, this sounds like a bug.

**Comment by Artur-** [comment] 2024-09-20 08:44
I think the first tab issue was #19973

**Comment by mcollovati** [comment] 2024-09-20 08:48
> This can be documented: [#19969 (comment)](https://github.com/vaadin/flow/issues/19969#issuecomment-2357498924).
> 
> Also, was your problem in not having a second tab opened, or having your first tab not updates after a second run @jojule ?
> 
> I'd say if your first tab doesn't get a refresh after a second run, this sounds like a bug.

https://github.com/vaadin/docs/pull/3682

**Comment by mshabarov** [comment] 2024-09-24 10:53
Closed as the mentioned bug has been fixed and online docs have been updated.

**Closed by mshabarov** 2024-09-24 10:53 UTC
Labels: documentation
