### ISSUE TITLE
Vaadin 14 randomly throws NullPointerException on detach

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#11088] opened 2021-05-27 06:17 UTC
### Versions:
    - Vaadin / Flow version: 14.6.1
    - Java version: 11
    - OS version: Linux
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat 9
    - IDE (if applicable): N/A

Vaadin 14 Flow. Sometime Vaadin throws exception that doesn't link to my application code. This issue happens when I start using new menu at https://start.vaadin.com/. 

_This is issue on auto generated code of https://start.vaadin.com or Vaadin flow ?_

**Note**: I submitted this issue at Vaadin stackoverflow:
https://stackoverflow.com/questions/67716676/vaadin-14-nullpointerexception-on-detach

```
 [http-nio-8080-exec-144] ERROR com.vaadin.flow.component.UI - null
 java.lang.NullPointerException
  at com.vaadin.flow.component.UI$1.handleError(UI.java:519)
  at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
  at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2068)
  at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:682)
  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1509)
  at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1584)
  at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:829)
 [http-nio-8080-exec-144] ERROR com.vaadin.flow.component.UI - null
 java.lang.NullPointerException
  at com.vaadin.flow.component.UI$1.handleError(UI.java:519)
  at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
  at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2068)
  at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:682)
  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1509)
  at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1584)
  at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

**or sometime throws this error when click on an item in menu:**

 ```
 | [http-nio-8080-exec-41] WARN com.vaadin.flow.server.communication.PushHandler - Error while ending request
  | java.lang.IllegalStateException: Unregistered node was not found based on its id. The tree is most likely corrupted.
  |  at com.vaadin.flow.internal.StateTree.unregister(StateTree.java:243)
  |  at com.vaadin.flow.internal.StateNode.handleOnDetach(StateNode.java:759)
  |  at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  |  at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:337)
  |  at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:280)
  |  at com.vaadin.flow.internal.StateTree$RootNode.setParent(StateTree.java:65)
  |  at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:400)
  |  at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:594)
  |  at com.vaadin.flow.server.VaadinService.lambda$removeClosedUIs$20ed7015$1(VaadinService.java:1342)
  |  at com.vaadin.flow.component.UI.accessSynchronously(UI.java:434)
  |  at com.vaadin.flow.component.UI.accessSynchronously(UI.java:395)
  |  at com.vaadin.flow.server.VaadinService.removeClosedUIs(VaadinService.java:1340)
  |  at com.vaadin.flow.server.VaadinService.cleanupSession(VaadinService.java:1304)
  |  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1504)
  |  at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
  |  at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:522)
  |  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
  |  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
  |  at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
  |  at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
  |  at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
  |  at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
  |  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
  |  at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
  |  at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
  |  at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:135)
  |  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  |  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  |  at java.base/java.lang.Thread.run(Thread.java:829)
  | [INFO: 2021-05-27 09:23:33 (StaffCompanyView.java:115)] StaffCompanyView auto init..........
  | [INFO: 2021-05-27 09:23:33 (StaffAssetView.java:700)] DetachEvent Session-ID: C11F6F0B3B6482D3FC1C86D156243AB9 UIID: 2
  | [INFO: 2021-05-27 09:23:33 (StaffCompanyView.java:257)] AttachEvent Session-ID: C11F6F0B3B6482D3FC1C86D156243AB9 UIID: 2
  | [http-nio-8080-exec-47] WARN com.vaadin.flow.server.communication.PushHandler - Error while ending request
  | java.lang.IllegalStateException: Unregistered node was not found based on its id. The tree is most likely corrupted.
  |  at com.vaadin.flow.internal.StateTree.unregister(StateTree.java:243)
  |  at com.vaadin.flow.internal.StateNode.handleOnDetach(StateNode.java:759)
```

**Comment by Legioth** [comment] 2021-05-27 06:28
Seems like the code in `handleError` fails because it assumes that the UI for which the error is reported is also detached at that point. It might be useful to understand what the underlying error is.

Could you try two things to help collect more information about what goes on behind the scenes:
1. Run your server with Java assertions enabled. This is done by passing `-ea` as a JVM parameter.
2. Run the JVM in debug mode and set a breakpoint on line 519 in `UI.java` so that you can investigate the exception that is being handled to understand its origin.

**Comment by letrthang** [comment] 2021-06-02 17:33
this is a random error when app runs for long enough time (24h+) so not easy to reproduce.

**Comment by letrthang** [comment] 2021-06-05 11:27
This is our snipe  code (**VerifyUserAccountPresenter.java**):

```
@Override
public void detach() {
	// do common tasks
	super.detach();
	baseView = null;
	userDAO = null;
	companyDAO = null;
	LOG.debug("UI detach at VerifyUserAccountPresenter. UIID: " + (ui == null ? "" : ui.getUIId()));
}
```

exception:

 ```
[DEBUG: 2021-06-05 09:45:38 (VerifyUserAccountPresenter.java:84)] UI detach at VerifyUserAccountPresenter. UIID:
 [http-nio-8080-exec-144] ERROR com.vaadin.flow.component.UI - null
 java.lang.NullPointerException
  at com.vaadin.flow.component.UI$1.handleError(UI.java:519)
  at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
  at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2068)
  at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:682)
  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1509)
  at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
  at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:522)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
  at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
  at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
  at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
  at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
  at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
  at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:135)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:829)
 [http-nio-8080-exec-144] ERROR com.vaadin.flow.component.UI - null
 java.lang.NullPointerException
  at com.vaadin.flow.component.UI$1.handleError(UI.java:519)
  at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
  at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2068)
  at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:682)
  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1509)
  at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
  at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:522)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
  at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
  at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
  at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
  at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
  at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
  at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:135)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:829)
 [http-nio-8080-exec-144] ERROR com.vaadin.flow.component.UI - null
 java.lang.NullPointerException
  at com.vaadin.flow.component.UI$1.handleError(UI.java:519)
  at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
  at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2068)
  at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:682)
  at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1509)
  at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
  at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:522)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
  at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
  at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
  at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
  at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
  at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
  at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
  at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
  at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:135)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pleku** [comment] 2021-06-15 13:19
> 	`LOG.debug("UI detach at VerifyUserAccountPresenter. UIID: " + (ui == null ? "" : ui.getUIId()));`

I'm not sure where is this `ui` here originating from and how, but this is not still enough to get started. I don't understand how the menu code from the start.vaadin.com itself could have any effect on this.

And I'm not sure whether the session or the error handler is `null` in this case - are you customizing the error handling somehow ? The session should not be `null` based on the check that is done in the `access` method that triggers the execution. 
Also I don't know if you could check in your pending task execution that when it is triggered, what is the state of the UI/session.

As there is just random details without proper steps and code to reproduce the issue, we're not able to do anything about this. So please try to create a simple project with example code that can be used to reproduce the issue.

**Comment by denis-anisimov** [comment] 2021-07-26 08:10
No any response for a month.
I'm closing the issue.
Please comment if you can provide requested details and I will reopen it.

**Closed by denis-anisimov** 2021-07-26 08:10 UTC
Labels: waiting for author
