### ISSUE TITLE
Mobile client idles after a short timeout.

### ISSUE THREAD

**Issue by hons82** [vaadin/flow#14803] opened 2022-10-11 14:54 UTC
### Description of the bug

We do have some clients that use iPads/iPhones or Android tablets/phones to interact with our Application. Typically for our system is that a user opens a UI and leaves it open for a while (usually by disabling the screen sleep mode, so that it remains always on). 
As long as they are actively used the devices remain responsive and quite fast, but when not used they seem to enter in some kind of idle mode, so that on the first click on an action it takes seconds (in our application 5-10sec) and while that happens the blue loading bar appears. After the first request is handled the UI remains responsive for subsequent requests, until it is left alone for something like 15-30 seconds. Then is starts over again.

Currently we have to use long polling as transport for the push because of some external requirements that do not allow us to use websockets so far. 

### Expected behavior

Ideally those mobile clients should not idle... At least until the screen shuts down. But we'd already be happy if we'd know what does trigger that behavior and ideally configure it to some higher value.

### Minimal reproducible example

https://github.com/hons82/vaadin_sampler

You'll need to start it, then go to http://localhost:8080/grid_columns on your mobile device. Click a couple of times on reset columns to get a bunch of columns. Then leave the mobile untouched for a minute and try to remove a column. 

### Versions

- Vaadin / Flow version: The minimal is on 14, but we use 23.2 currently
- Java version: 17
- OS version: Windows for the Server and iOS/Android on the clients
- Browser version (if applicable): Mobile Safari and Mobile Chrome
- Application Server (if applicable):
- IDE (if applicable): InteliJ

**Comment by caalador** [comment] 2022-10-27 08:13
I'm not seeing any extra slow requests using my iPad (iOS 15.6.1), but remove first column sets sorting on everything and on the server I see the exception:
```
Caused by: java.lang.IllegalArgumentException: Received a sorters changed call from the client for a non-existent column
        at com.vaadin.flow.component.grid.Grid.sortersChanged(Grid.java:3019) ~[vaadin-grid-flow-14.8.19.jar:na]
        at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[na:na]
```

I can get a loading bar by going to another app and then when coming back to the browser, but that is most likely due to an os optimization on memory usage.

Are there some other specifics in the setup that might generate the behaviour?

**Comment by mshabarov** [comment] 2022-11-29 12:02
Closed, because of no information provides for us to reproduce the issue. Please provide the information and re-open this ticket, if the issue is still valid for you.

**Comment by TatuLund** [comment] 2022-12-02 04:52
May be related: https://stackoverflow.com/questions/74604808/vaadin-23-ui-recreation-after-idle-time

**Comment by TatuLund** [comment] 2022-12-02 04:52
May be related: https://stackoverflow.com/questions/49233769/is-there-a-way-to-prevent-safari-on-ios-from-clearing-the-cookies-for-a-website

**Comment by alexanoid** [comment] 2022-12-02 21:21
I may confirm,  I see absolutely the same behavior in my Vaadin app on my iPhone. After some idle time when I try to access the app in the already existing browser tab and click something, I have to wait a few seconds ~5-10 in order to get the page updated. Right after that, UI becomes as fast as usual.

**Comment by mshabarov** [comment] 2022-12-20 09:23
Reopened for further investigation.

**Comment by mcollovati** [comment] 2023-01-18 13:01
I can reproduce the issue with the example project (Vaadin version 14.8.19), but the problem seems not to be present using Vaadin 14.9.4.
@hons82 @alexanoid, can you please try to upgrade to Vaadin 14.9.4, that contains a fix that prevents unnecessary push?

**Comment by mshabarov** [comment] 2023-01-31 11:15
@hons82 @alexanoid have you had a chance to try Vaadin 14.9.4 or later version?

**Comment by alexanoid** [comment] 2023-01-31 11:19
@mshabarov I'm on 23.3.5 version. Works good now, thanks! The only issue I have on my iPhone - is that sometimes after some idle time when I restore the browser window with my Vaadin app - I see the white screen. So I have to refresh the entire page in order to get it working again.

**Comment by alexanoid** [comment] 2023-02-24 09:59
@mshabarov I don't see the issue since my upgrade to 23.3.6. I'm still monitoring the app.

**Comment by mshabarov** [comment] 2023-03-21 11:24
@alexanoid do you have any negative results? Can I close this issue?

**Comment by alexanoid** [comment] 2023-03-21 23:18
Looks like the issue is gone! Thank you!

**Comment by hons82** [comment] 2023-03-22 05:36
Seems like that's not an issue currently, however we start hearing from clients the problem that @alexanoid describes above, that there is an issue with restoring the connection somehow... Might be related to this, but I do not have enough information right now to reproduce it

**Comment by alexanoid** [comment] 2023-03-22 22:32
Very likely this issue relates to this one https://github.com/vaadin/flow/issues/16046  Very often I see the following - let's say I have an open application, then I redeploy it on my server.. and from time to time the application unable to reload itself and I have to refresh the page manually. This is only related to pages where I use  `HasUrlParameter.setParameter()` Looke like the page is failing on the second redundant call of the `HasUrlParameter.setParameter() `method..

**Comment by mcollovati** [comment] 2023-05-02 11:02
@alexanoid @hons82 the mentioned issue #16046 has been released in Vaadin 24.1.0.alpha3. Can you please check if that version solves also this issue?

**Comment by alexanoid** [comment] 2023-05-02 11:27
@mcollovati I'm on Vaadin 24.1.0.alpha3 - https://github.com/vaadin/flow/issues/16046 works good! But this issue I mentioned previously "redeploy it on my server.. and from time to time the application unable to reload itself and I have to refresh the page manually" is unfortunately still present

**Comment by mshabarov** [comment] 2023-06-13 10:09
@alexanoid is this the one you are talking about https://github.com/vaadin/flow/issues/16664 ? (problems on redeployment). I propose to continue discussing in the other issue more relevant to a problem you have, and close this issue as it seems it was solved in a latest versions.

**Comment by alexanoid** [comment] 2023-06-13 19:35
@mshabarovSure! I'm currently on version 24.1.0, and the application is working much more stable now. Thank you! However, I did notice that occasionally (rarely) the PUSH functionality stops working after a resync. Yes, it was mentioned there https://github.com/vaadin/flow/issues/16664 I will continue monitoring the application on version 24.1.0. If I notice the issue occurring frequently, I will report it there.

**Comment by mshabarov** [comment] 2023-06-20 10:15
Thanks! Let's use #16664 for monitoring and further discussion.

**Closed by mshabarov** 2023-06-20 10:15 UTC
Labels: waiting for author
