### ISSUE TITLE
Resources leak

### ISSUE THREAD

**Issue by dkononenko** [vaadin/flow#7379] opened 2020-01-17 08:57 UTC
Hello!

I think that Vaadin has a serious problem: resource leak.
Vaadin checks expired sessions and ui in VaadinService after response handle. 
No response, no checks!
Case: Open tab in browser. Created session & ui. Close tab. Session & ui destryed after http session timeout.

application.properties
```
server.servlet.session.timeout=60m
vaadin.heartbeatInterval=20
```

```java
package com.example.vl;

import com.vaadin.flow.component.AttachEvent;
import com.vaadin.flow.component.DetachEvent;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.router.Route;

import java.time.LocalDateTime;

@Route
public class MainView extends Label {
    public MainView() {
        setText("Hello world");
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        System.out.println("attach " + LocalDateTime.now());
    }

    @Override
    protected void onDetach(DetachEvent detachEvent) {
        System.out.println("detach " + LocalDateTime.now());
    }
}
```

Correct result: destroy UI after heartbeatInterval * 3.1 expired

I use openjdk 13 & vaadin 14.1.5

**Comment by Legioth** [comment] 2020-01-17 09:18
This is a known architectural limitation. The last open UI in a session will remain open until the session expires. The purpose of the heartbeat interval is to eagerly clean up some specific cases earlier, but Vaadin is still ultimately at the mercy of the session expiration interval.

There is an [add-on for Vaadin 8](https://vaadin.com/directory/component/cleanupservlet-add-on) that starts a separate thread that looks for expired UIs. The add-on hasn't been ported to Vaadin 10+, but doing so would most likely not require too much effort. This kind of functionality hasn't been added to the core framework because of the general recommendations about starting custom threads in a servlet container.

One thing that Vaadin could do is to start using the new Beacon API to better detect closed UIs, even though it still cannot catch all the cases. There's some discussion about that topic in https://github.com/vaadin/flow/issues/6293.

**Comment by pleku** [comment] 2021-03-29 12:30
Like pointed out in the comment, this is a known limitation and thus not a bug by categorization. I would refer to this as a duplicate of #6293.

**Closed by pleku** 2021-03-29 12:30 UTC
Labels: enhancement
