### ISSUE TITLE
Client side grid columns are not bound to server side properties

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4221] opened 2018-06-04 07:35 UTC
We have a client side configured grid and want to attach the data with a data provider on the server side to provide lazy loading while the client side can be designed by an UX designer. When solely using `grid.setDataProvider` the Grid shows empty rows (where the number of rows is calculated correct). 

It seems that the properties of the beans are not automatically bound to the grid. 

When adding columns from the server side by using a template renderer and `withProperty`, the properties are bound to the grid and also used from the server side.

Example polymer template code
```
<vaadin-grid id="project-list" theme="compact no-row-borders">
    <vaadin-grid-column flex-grow="4">
          <template class="header">
                <div class="header-item">Project Name</div>
          </template>
          <template class="data-item customer-list">
                 <div class="customer-list">
                        [[item.name]]
                 </div>
          </template>
    ...
```

Binding the data provider 
```
projectGrid.setDataProvider(DataProvider.<ProjectDPO, Object>fromFilteringCallbacks(...));
```

This combination leads to the empty results. We have to add a new column on server side with the following code. After that, also the client side configured conten is shown correctly.

```
projectGridd.addColumn(TemplateRenderer.of(...).withProperty("name", ProjectDPO::getName));
```

This should not be needed, since the additional column is unnecessary. The property binding should work automatically out of the box.

**Comment by stefanuebe** [comment] 2018-06-04 09:01
How about to add a method that is called "initPropertiesByBean" or smth like that. This method could automatically bind the properties that are defined in the bean by using the same internal mechanisms that I trigger when using `TemplateRenderer.of().withProperty().withProperty(). ...`

**Comment by gilberto-torrezan** [comment] 2018-06-04 09:49
I was thinking on adding a method for adding DataGenerators without having to add columns. And on top of that something to introspect a Bean could also be developed.

Example:
```
grid.addDataGenerator("name", ProjectDPO::getName);
```

**Comment by stefanuebe** [comment] 2018-06-04 12:17
Yep, sounds good.

I helped myself with the following solution.

```
TemplateRenderer<ProjectDPO> renderer = TemplateRenderer.<ProjectDPO>of("");

renderer.withProperty("name", ProjectDPO::getName);
renderer.withProperty("budget", ProjectDelegate::getBudget);
// ...

Column<ProjectDPO> column = addColumn(renderer);
column.setId("___property_provider___");
column.setVisible(false);
```

**Comment by Legioth** [comment] 2018-06-13 06:41
Seems like this is a duplicate of vaadin/vaadin-grid-flow#62.

**Closed by Legioth** 2018-06-13 06:41 UTC
Labels: bug, components, data binding, data provider
