### ISSUE TITLE
Resynchronizing UI by client's request. 

### ISSUE THREAD

**Issue by amit-official** [vaadin/flow#8827] opened 2020-08-07 06:57 UTC
2020-08-07 12:16:06 - [http-nio-8081-exec-9] - WARN  - c.v.f.s.c.ServerRpcHandler - Resynchronizing UI by client's request. Under normal operations, this should not happen and may indicate a bug in the Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues

This happening every time when I have 2 window open in the same browser.

**Comment by denis-anisimov** [comment] 2020-08-07 07:06
The ticket requires steps to reproduce.
Please provide the exact steps to reproduce because otherwise we are not able identify the problem and it's not possible to say whether it's fixed or not.

**Comment by pleku** [comment] 2020-08-24 12:06
Hello. Since there is no way for us to reproduce this issue, I'm closing the ticket. If this is still an issue, please open a new ticket **with the exact steps to reproduce the problem** by providing code, thanks.

**Closed by pleku** 2020-08-24 12:06 UTC
Labels: waiting for author
