### ISSUE TITLE
Favicon not shown with JAR packaging

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/flow#8705] opened 2020-07-08 22:10 UTC
### Description of the bug
When packaging a project as a JAR, using a custom `icon.png` in `src/main/resources/META-INF/resources/icons`, and running with `java -jar ...`, the custom favicon is not shown (it is shown correctly when running the `main` method in IntelliJ IDEA, though). The problem is the same with both development and production builds.
### Minimal reproducible example
Go to https://vaadin.com/start/v14. Create a Spring Boot project. Replace the `icon.png` file with a custom one. Build with `mvn package`. Run with ´java -jar ...`.
### Expected behavior
Should show the custom icon.
### Actual behavior
Shows the default white circle with a blue background icon.
### Versions:
    - Vaadin / Flow version: 14.3.0
    - Java version: 8 and 11
    - OS version: macOS
    - Browser version (if applicable): Chrome

**Comment by denis-anisimov** [comment] 2020-08-03 06:12
In fact it's even worse: no need to replace the existing icon at all.
The provided icon in the skeleton `src/main/resources/META-INF/resources/icons/icon.png` is shown being run via `spring-boot:run` but a default icon ( totally different one) is shown being run via `java -jar`.

**Comment by denis-anisimov** [comment] 2020-08-04 07:24
This is a Spring issue.
The problem is that all classes being packaged in Jar goes into `BOOT-INF`  folder.
But resources goes to `META-INF`  directly  (not as a sub-package of `BOOT-INF`).

Then embedded servlet container is responsible for finding the resources (as static web resources).
By default Tomcat is used . `TomcatServletWebServerFactory` has code in its nested `StaticResourceConfigurer` which scans Jars for `"/META-INF/resources"` folders. But that works only for Jars _inside_ the Jar (library Jars) and the "/META-INF" inside the Jar itself is not handled.

So as a result: the code in Flow tries to search the static web resource using a Servlet context and it's not able to find it (see above).
The proper way to fix this would be fix the project itself specifically for this case since Spring is not able to handle this properly. So it should be fixed in skeleton-starter project itself.

I'm going to implement a workaround as well in Flow for this specific case: search the resource in classpath if it's not found via a servlet context. But this is more a hack (and it's not really correct to fix this Spring specific case in Flow repo).

**Comment by denis-anisimov** [comment] 2020-08-04 07:59
A workaround in Flow : https://github.com/vaadin/flow/pull/8808
A proper fix in skeleton: https://github.com/vaadin/skeleton-starter-flow-spring/pull/381

**Comment by Artur-** [comment] 2020-08-04 11:57
Another way to solve this would be to use the approach prototyped in https://github.com/vaadin/flow/tree/webpack-workbox to enable offline routing using the webpack workbox plugin

It moves all `@PWA`, manifest, sw.js and icon handling to the build phase instead of runtime.

**Closed** 2020-08-06 10:44 UTC
Labels: Impact: High, Severity: Major, bug

**Comment by nox10** [comment] 2022-02-20 21:27
In Vaadin 22 it's not working again

**Comment by nox10** [comment] 2022-02-21 01:04
This is because the default icon now is in resources as well, from exampledata-4.1.0.jar dependency, which eventually breaks the workaround #8808.

I used truezip-maven-plugin to remove the default icon from exampledata-4.1.0.jar archive during package step, as another temporary workaround for this situation.

**Comment by Artur-** [comment] 2022-02-21 14:58
Exampledata has been fixed in 4.1.1

**Comment by nox10** [comment] 2022-02-21 15:14
Thank you
