### ISSUE TITLE
Pre-release gradle plugin is broken

### ISSUE THREAD

**Issue by vlotarev** [vaadin/flow#15711] opened 2023-01-16 11:19 UTC
The gradle plugin in the version 24.0 24.0.0.alpha7 does not generate vaadin-dev-tools.js (and related) files. To reproduce:
- execute vaadinClean goal
- execute vaadinPrepareFrontend

No vaadin-dev-tools.js generated. Maven plugin of the same version generates everythign correctly. Here is the discussion: https://discord.com/channels/732335336448852018/1009201939092865084/threads/1063023660266434570

**Comment by caalador** [comment] 2023-01-18 07:39
Seeing as the link doesn't immediately redirect me to the expected conversation could someone summarize on the ticket what the issue is and what are the expectations for prepare-frontend.

**Comment by Artur-** [comment] 2023-01-18 07:49
> 12:32:17.389 INFO  [][dev-server-output] Failed to load url /generated/jar-resources/vaadin-dev-tools.js (resolved id: /generated/jar-resources/vaadin-dev-tools.js). Does
 the file exist? (com.vaadin.base.devserver.DevServerOutputTracker:118)
The file is imported from vaadin.ts, if I remove that import it appears again ...

**Comment by Artur-** [comment] 2023-01-18 07:50
> I've already checked that - everything seems to be OK. BTW I replaced frontend/generated folder with the one prepared by pre-release Maven plugin and that problem goes away ... Looks like pre-release Gradle plugin is a bit broken.

**Comment by caalador** [comment] 2023-01-18 08:01
So that would mean that gradle doesn't copy the jar resources or the vaadin-dev-server is not imported.
In development mode those should be copied when the server starts.

**Comment by Artur-** [comment] 2023-01-18 08:04
Anyway, this needs a test case. All gradle tests pass in the build

**Comment by mcollovati** [comment] 2023-01-26 15:18
I tried to reproduce the issue, creating projects based on `base-starter-spring-gradle` and `base-starter-gradle` and updating them to use the mentioned gradle plugin version and also the latest one, and I never got errors like the one in the comments above.

@vlotarev could you please provide a sample project that reproduces the issue?

**Comment by vlotarev** [comment] 2023-01-28 09:26
@mcollovati , please see [base-starter-spring-gradle.zip](https://github.com/vaadin/flow/files/10526862/base-starter-spring-gradle.zip) attached. Just execute "gradlew vaadinPrepareFrontend". There will be no vaadin-dev-tools.js in frontend\generated\jar-resources.

**Comment by Artur-** [comment] 2023-01-28 10:18
The file is named vaadin-dev-tools.ts nowadays. Is that there?

**Comment by vlotarev** [comment] 2023-01-28 17:54
Yes, vaadin-dev-tools.ts is here. Probably, wrong file is referenced from vaadin.ts?

**Comment by mcollovati** [comment] 2023-01-30 07:23
@vlotarev unfortunately the attached project did not help to reproduce the issue: it has a reference to spring boot 2.2.4 and java 1.8.
Anyway, once changed the configuration to use Spring Boot 3.0.1 and java 17 the project build and starts correctly, both in development and production mode.

`vaadin-dev-tools.js` is not present, but there is `vaadin-dev-tools.ts` as pointed out by Artur.
In `vaadin.ts` I can see `import 'Frontend/generated/jar-resources/vaadin-dev-tools.js';`, but `vaadin-dev-tools.ts` is loaded correctly

**Comment by vlotarev** [comment] 2023-01-30 07:51
@mcollovati , so having import of non-existing 'Frontend/generated/jar-resources/vaadin-dev-tools.js' file you don't have errors? Shouldn't this import be corrected to point to new .ts file?

**Comment by mcollovati** [comment] 2023-01-30 11:05
It is vite that tries to resolve`.js` files to `.ts`

```
vite:resolve 0.64ms /path/to/project/frontend/generated/jar-resources/vaadin-dev-tools.js -> /path/to/project/frontend/generated/jar-resources/vaadin-dev-tools.ts
vite:resolve 0.73ms Frontend/generated/jar-resources/vaadin-dev-tools.js -> /path/to/project/frontend/generated/jar-resources/vaadin-dev-tools.ts
vite:resolve 0.09ms /generated/jar-resources/vaadin-dev-tools.ts -> /path/to/project/frontend/generated/jar-resources/vaadin-dev-tools.ts
```

@Artur-, does it make sense to change the import in `vaadin.ts` to point to the typescript file instead of the js?

**Comment by mshabarov** [comment] 2023-01-31 11:29
Should be re-tested after https://github.com/vaadin/flow/pull/15785.

**Comment by Artur-** [comment] 2023-01-31 11:40
Is there anything broken or is this just an academic discussion?

**Comment by Artur-** [comment] 2023-01-31 11:40
As mentioned in #15785, you are supposed to import .js files even if the source is .ts if you want to be compatible with newer module resolutions in node

**Comment by mcollovati** [comment] 2023-02-07 14:37
I'm closing the issue as it was not possible to reproduce the error.
The absence of the `vaadin-dev-tools.js` is expected, as is importing `vaadin-dev-tools.js` that is then resolved as `vaadin-dev-tools.ts`.

@vlotarev if you still have the issue, please comment here and, if possible, provide an example project to reproduce it

**Closed by mcollovati** 2023-02-07 14:37 UTC
Labels: bug, Impact: High, Severity: Major
