### ISSUE TITLE
Verify that Flow Spring application serves webjars correctly

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#4685] opened 2018-10-10 11:29 UTC
When an application servlet is mapped to a custom url pattern (for instance, `/app1/*` instead of `/*`, see example in https://github.com/vaadin/flow/issues/3600) Flow was not able to serve webjar contents.

The https://github.com/vaadin/flow/pull/4674 PR fixed this by automatically registering the servlet for `/frontend/*` url pattern in `com.vaadin.flow.server.startup.ServletDeployer` class.

If a Spring-based Flow application has the same issue, the approach may be reused to fix it.

**Comment by pleku** [comment] 2018-10-17 07:51
This is a duplicate of vaadin/spring#348

**Closed by pleku** 2018-10-17 07:51 UTC
Labels: spring
