### ISSUE TITLE
PWA does not find files from the spring static resources directory

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#4687] opened 2018-10-10 13:00 UTC
Based on https://github.com/vaadin/bakery-app-starter-flow-spring/pull/664#pullrequestreview-162749992

Take https://github.com/vaadin/skeleton-starter-flow-spring
Note that the icon file is located in the `src/main/webapp/icons` directory.
Also note that if you launch the app, the icon is available as a static resource at http://localhost:8080/icons/icon.png

Move the icon to `src/main/resources/static/icons` directory, restart an app.

Expected: the icon is still shown and loaded
Actual: the default icon is loaded (and the icon is still available at http://localhost:8080/icons/icon.png)

It seems like PWA resources loader should support the resources placed in the standard Spring directories.

**Comment by pleku** [comment] 2018-10-31 08:08
After this one is fixed, we should change the location of these files in Bakery & Project Base for Spring too.

**Comment by denis-anisimov** [comment] 2018-11-02 12:30
I'm not sure whether I correctly understand the issue because it seems I can't reproduce it.
If I move `icon.png` into the `src/main/resources/static/icons` then URL `http://localhost:8080/icons/icon.png` still works for me as it should.

If this is the only issue then there is nothing to fix except the example projects.
If it's not the issue then I doin't understand what should I check to see that something is wrong.

The standard directory for Jar is `src/main/resources/META-INF/resources`. And this directory works for me as well.

So I will just move icon file (and any other resources) from webapp to this directory for all sample projects and that's it.

Please let me know if there is a real  issue in Flow which I don't see at the moment related to PWA and Spring (as I understand we don't have any code which reads the specific directories. The code relies on the static web resources availability. So it's just about whether one or another location works as a static resources location. And it doesn't relate to PWA anyhow. )

**Comment by denis-anisimov** [comment] 2018-11-02 12:48
`Bakery` already has the icon in the `static` folder as requested.
So nothing to do for it.

**Comment by pleku** [comment] 2018-11-05 09:31
You should verify that the icon works also - so that Flow is able to generate the resources based on the icon (there are different sized icons for different devices generated). https://github.com/vaadin/flow/blob/5b5a18c003cb0f8889209a8c8cb89c3a8c4917e5/flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java#L118

Also now realized, that the besided the icons, also the offline page should work from the static file location for Spring https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/pwa/tutorial-pwa-offline.asciidoc

**Comment by denis-anisimov** [comment] 2018-11-05 10:40
I've verified that icons are generated for the icon within path `META-INF/resources`.
Also `offline.html` file inside this location works.

So I close this.

**Comment by cedricaebi** [comment] 2019-04-16 13:48
Still doesn't work. I use Spring and packaging jar. My icon is in resources/META-INF/resources/icons/icon.png
offline.html is in resources/META-INF/resources/offline.html

Locally everything works. The icon gets fetched and converted into 144x144 etc. But when i deploy it to the server, vaadin overwrites it with the default icon without an error message. `offline.html` gets fetched correctly.

**Comment by ajgassner** [comment] 2019-08-30 11:04
@denis-anisimov I can confirm. It does work locally but not when running as jar.
@cedricaebi @pleku Please reopen the issue and assign it to the correct project, maybe vaadin-spring?

Regardless if this issue is related to flow, vaadin-spring or any other project it should be fixed. Most people I guess use Vaadin in conjunction with Spring Boot these days.

I've found a very dirty classpath hack to workaround the issue :roll_eyes: 
You can overwrite Vaadin's default logo with your icon, see screenshot.

![image](https://user-images.githubusercontent.com/2866145/64016216-a6413d80-cb26-11e9-9995-7aa17c3ba70e.png)

**Comment by denis-anisimov** [comment] 2020-08-07 06:42
The ticket is apparently about running the app via jar even though the original description doesn't say that:
> @cedricaebi I can confirm. It does work locally but not when running as jar.

We have another ticket for that with a proper description which is fixed.

**Closed by denis-anisimov** 2020-08-07 06:42 UTC
Labels: Impact: High, Severity: Major, bug, pwa
