### ISSUE TITLE
Grid cells ignore column class names / stylings.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4550] opened 2018-08-23 11:47 UTC
The developer sets a class name for a grid column via Java (e.g. "my-special-col") to apply some stylings like flex-grow, width, etc. The class name is applied to the element (`vaadin-grid-column`), but not used for the content representation elements (`vaadin-grid-cell-content`). Since these are siblings, the stylings of the column is neither applied via inheritation. 

This makes it impossible to style a certain column via css, when using Java (doing it in Java via `getStyles().set(...)` is not an option).

Following requests / proposals for that problem:
1. Class names of the column are copied to the cells-contents.

2. Columns and cells class names are also extended by the key name of the column, like "xyz grid-cell-xyz" or "xyz grid-column-xyz".

With 2. it would be possible to have a column "x" and use a styling like
```
vaadin-grid-cell-content.xyz { ...}
```
or
```
.grid-cell-xyz {...}
```

**Comment by pleku** [comment] 2018-08-23 12:55
I think this is a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/185

**Closed by pleku** 2018-08-23 12:55 UTC
