### ISSUE TITLE
Grid - content disappears when scrolled down few pages and switched to other view

### ISSUE THREAD

**Issue by aguzik** [vaadin/flow#5583] opened 2019-04-29 18:15 UTC
Vaadin 13.0.4 + Spring Boot 2.1.4

Example application: https://github.com/aguzik/VaadinGridBug
To reproduce the problem we need to do few steps:
1. Open application and scroll down the list a lot (to be sure few (4-5) pages of rows have been scrolled
2. Go to the second view
3. Go back to the first view again. 

Grid is empty and only page refresh is able to restore grid content.
All views are configured as Spring beans with UIScope.

What is expected by me in this scenario is first view should be rendered and grid should scrolled to place I left it - or at least should contain rows :)

Both Chrome and FF are affected.

**Comment by Legioth** [comment] 2019-04-30 07:17
Duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/539

As a workaround, you can change the Grid instance to not be in the UI scope so that it would be recreated when navigating back to the first view.

**Closed by Legioth** 2019-04-30 07:17 UTC
