### ISSUE TITLE
Missing js modules at start after building fat jar with profile production

### ISSUE THREAD

**Issue by mmirwaldt** [vaadin/flow#6596] opened 2019-10-01 20:07 UTC
I can run my vaadin application from IntelliJ IDE but not from console as fat jar.
What I use:

- IntelliJ 2019.2.2
- Vaadin 14.0.7
- Spring Boot 2.1.7.RELEASE
- java version "11.0.4" 2019-07-16 LTS
- npm version
{ npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.39.2',
  node: '10.16.3',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.54',
  zlib: '1.2.11' }

I get the following error:
```
2019-10-01 21:47:17.149  INFO 41556 --- [           main] dev-updater                              :

  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
  If the build fails, check that npm packages are installed.
```

My pom.xml (the *** in artifact id in the parent tag are a real name. I must hide it here ;-) :
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>net.mirwaldt.***</artifactId>
        <groupId>net.mirwaldt</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>webapp</artifactId>
    
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <vaadin.version>14.0.7</vaadin.version>

        <drivers.dir>${project.basedir}/drivers</drivers.dir>
        <drivers.downloader.phase>pre-integration-test</drivers.downloader.phase>
    </properties>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
            <snapshots><enabled>false</enabled></snapshots>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
            <snapshots><enabled>false</enabled></snapshots>
        </repository>
        <!-- Repository used by many Vaadin add-ons -->
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots><enabled>false</enabled></snapshots>
        </repository>
    </repositories>
    
    <!-- https://www.baeldung.com/spring-boot-dependency-management-custom-parent -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.1.7.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>
            <exclusions>
                <!-- Webjars are only needed when running in Vaadin 13 compatibility mode -->
                <exclusion>
                    <groupId>com.vaadin.webjar</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.insites</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymer</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymerelements</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.vaadin</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.webcomponents</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
            <exclusions>
                <!-- Excluding so that webjars are not included. -->
                <exclusion><groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core</artifactId></exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-testbench</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.1.7.RELEASE</version>

                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!--
                Take care of synchronizing java dependencies and imports in
                package.json and main.js files.
                It also creates webpack.config.js if not exists yet.
            -->
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <profiles>
        <profile>
            <!-- Production mode is activated using -Pproduction -->
            <id>production</id>
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-server-production-mode</artifactId>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <jvmArguments>-Dvaadin.productionMode</jvmArguments>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                                <phase>compile</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

I see that the folder npm_modules/@vaadin/flow-frontend is empty but
the missing js-files are in the fatjar under META-INF/resources/frontend:

      - contextMenuConnector-es6.js
      - gridConnector.js
      - contextMenuConnector.js
      - flow-component-renderer.js
      - gridConnector-es6.js
      - vaadin-grid-flow-selection-column.js

Removing 
 - npm_modules
- package.json
- package-lock.json
- package.json
- webpack.config.js
- webpack.generated.js

didn't help. It always runs in the same error and cannot build the frontend.
What''s going wrong? How can I fix it? Is there a workaround?

**Comment by mmirwaldt** [comment] 2019-10-01 20:25
I discovered that target/frontend/generated-flow-imports.js references those under npm_modules/flow-frontend/ :
```
...
import '@vaadin/flow-frontend/flow-component-renderer.js';
import '@vaadin/flow-frontend/gridConnector-es6.js';
import '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js';
import '@vaadin/flow-frontend/contextMenuConnector-es6.js';
...
import '@vaadin/flow-frontend/gridConnector.js';
import '@vaadin/flow-frontend/contextMenuConnector.js';
```

**Comment by mmirwaldt** [comment] 2019-10-01 20:42
I discovered that #5632 tried to introduce it but broke it.

**Comment by mmirwaldt** [comment] 2019-10-02 19:39
I found a workaround:
I copied all files from META-INF/resources/frontend to npm_modules/@vaadin/flow-frontend/.
That works.

Changing target/frontend/generated-flow-imports.js does not work because it is overwritten with every restart.

**Comment by mmirwaldt** [comment] 2019-10-02 20:00
I opened a discussion in the forum https://vaadin.com/forum/thread/17871763 .
I am not sure whether this issue is a ticket or a discussion in the forum.

**Comment by joheriks** [comment] 2019-10-08 11:46
@mmirwaldt Before packaging the fat jar, did you run `vaadin:prepare-frontend` (this goal is missing from the `pom.xml` but  I do not know what is in the parent)? Also, how do you run the far jar?

I was able to start the application without npm errors with the `pom.xml` above as follows: 
`mvn -Pproduction vaadin:prepare-frontend package`
`java -jar target/webapp-0.0.1-SNAPSHOT.jar`

**Comment by mmirwaldt** [comment] 2019-10-19 20:23
@joheriks 
The parent is just a pom listing the modules my project has. Nothing special.
My vaadin webapplication is a separate module in the profile webapp.

Here is it:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.mirwaldt</groupId>
    <packaging>pom</packaging>
    <version>0.0.1-SNAPSHOT</version>
    <artifactId>net.mirwaldt.***</artifactId>

    <name>***</name>
    <description>***</description>
    <url>***</url>

    <modules>
        <module>core</module>
        <module>core-demos</module>
        <module>object</module>
        <module>object-demos</module>
        <module>data</module>
    </modules>

    <profiles>
        <profile>
            <id>webapp-demo
            </id>
            <modules>
                <module>webapp</module>
            </modules>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>1.0.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.junit.jupiter</groupId>
                        <artifactId>junit-jupiter-engine</artifactId>
                        <version>5.0.1</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>1.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>3.0.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>`

I run the fat jar as a service on my centos 7 server without maven.

I changed the goal to "prepare-frontend" in the vaadin-maven-plugin and will try it out soon.

**Comment by polishcode** [comment] 2019-10-28 11:20
@mmirwaldt did it work for you?
I am facing the same problem. I already tried
`mvn -Pproduction vaadin:prepare-frontend package`
suggested by @joheriks , but running the app fails like before.

**Comment by joheriks** [comment] 2019-11-08 12:08
@mmirwaldt Could you run the fat jar or do you still experience the same issue efter running  
@polishcode Can you provide a minimal self-contained example that exposes the issue?

**Comment by mmirwaldt** [comment] 2019-11-15 00:04
I have tried out and it does not work.
I get "Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES6' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'."
Even setting original.frontend.resources=true in application.properties or in system properties does not work. :-(

**Comment by mmirwaldt** [comment] 2019-11-15 00:17
I could solve that problem by adding the system property vaadin.original.frontend.resources=true .

**Comment by denis-anisimov** [comment] 2019-11-15 06:33
`vaadin-flow-bundle-manifest.json` file  and `vaadin.original.frontend.resources` makes sense and do something only in compatibility mode.
So apparently you are running the app in compatibility mode.

The original reports was about NPM mode.

Also the original report is about dev mode since you should not have any `dev-updater` errors in production mode.

Just ti clarify: to be able to run you app in production mode you should:
- build the app for production (`production` profile which also can be activated via `vaadin.productionMode`property)
- run the app in production mode : either via `vaadin.productionMode` system property (or application property in Spring) or `productionMode` init parameter (for servlet).
- dev mode in fat jar should work nowadays with the latest release.

**Comment by denis-anisimov** [comment] 2019-11-15 06:38
Also please note that there is https://github.com/vaadin/flow/issues/6657.
Which is about running fat jar in dev mode without need to specify production mode property explicitly.

**Comment by mehdi-vaadin** [comment] 2019-11-22 11:54
@mmirwaldt #6657 and some other issues related to fat jar have been recently fixed. Would you please try Vaadin 14.0.13 and see if your problem is resolved?

**Comment by pleku** [comment] 2020-01-03 09:00
Closing the issue as it probably has been fixed, but there has not been a response from the author in a reasonable time. If the issue is still valid, please reopen with instructions on how to reproduce.

**Closed by pleku** 2020-01-03 09:00 UTC
Labels: question, waiting for author
