### ISSUE TITLE
Vaadin 14 embedded application scripts change host website styling

### ISSUE THREAD

**Issue by fschon** [vaadin/flow#7868] opened 2020-03-24 10:57 UTC
When embedding a Vaadin application into a host website, the scripts that load the Vaadin app also make unwanted changes to the website css styling:

"For the issues on the page; I see the Vaadin script adds multiple embedded style settings, script blocks and an indicator div to the DOM of the page. Some of the style settings would interfere with the Bootstrap styling, as it changes the min and max widths and heights, and creates styles for objects already controlled by Bootstrap. The added indicator seems to be what creates the horizontal scrollbar, as the animation goes all the way behind the scrollbar, so is obviously bigger than the document width. I see also that the system error block has an overflow:auto which would create the scrollbar as well."

These styling changes unfortunately make the embedded route nonviable. Is there some way to mitigate/remove these side effects. Or is the idea for embedded application only to be inserted into other Vaadin websites?

Current workaround is to use an iframe which defeats the whole purpose of embedded apps.

**Comment by Legioth** [comment] 2020-03-25 08:13
Duplicate of https://github.com/vaadin/flow/issues/5363 which was recently closed and will be fixed in Vaadin 14.2

**Comment by fschon** [comment] 2020-06-11 12:28
Hi, this has not yet been fixed in 14.2.1. The embedded application still has no Theme and the page css is broken.

**Comment by denis-anisimov** [comment] 2020-06-15 07:55
I've verified that #5363 is fixed in `14.2`.
This bug sounds as a duplicate of #5363 .

If it's still valid then this is not a duplicate and I'm not able to verify whether it's fixed or not 
because _there is no steps to reproduce_.

My steps to reproduce which I've used to verify #5363  shown that the ticket is fixed.

So please provide the steps to reproduce.

**Comment by denis-anisimov** [comment] 2020-07-31 10:09
No response for a long time.
Closing.

**Comment by pleku** [comment] 2021-01-27 12:25
>No response for a long time.
Closing.

**Closed** 2021-01-27 12:25 UTC
Labels: Impact: High, Severity: Major, bug, embedding flow
