### ISSUE TITLE
Webpack errors only shown in web page notification, not log

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#6016] opened 2019-07-02 20:14 UTC
- Description of the bug
![Screen Shot 2019-07-02 at 12 24 15 PM](https://user-images.githubusercontent.com/883698/60543356-fa68a680-9cca-11e9-9384-41584745892e.png)

- Minimal reproducible example
A project that loads a JSModule with an error

- Expected behavior
That I see the webpack error log in my console

- Actual behavior
I do not see the webpack error log in my console. Only in a popup in the web app.

- Versions:
    - Vaadin / Flow version: 14.0.0.rc3
    - Java version: 11
    - OS version: macOS 10.14
    - Browser version (if applicable): Chrome 75

**Comment by Legioth** [comment] 2019-07-31 06:46
I cannot reproduce this. I would assume it has been fixed by some other change.

This is the steps I've tested:
1. Get a vanilla Beverage Buddy
2. `mvn jetty:run`
3. Open in the browser and see that everything is OK
4. Modify `review-list.js` to introduce different kinds of errors, e.g. adding a typo to an import or adding a `{` to cause an obvious syntax error
5. Reload the page.

In the cases that I tested, I always got both a browser error similar to the one in the screenshot and also the same error message in the server console. In some cases, there was also a Flow stacktrace after the webpack error.

**Closed by Legioth** 2019-07-31 06:46 UTC
Labels: bug, investigation
