### ISSUE TITLE
Serialization issue with ShortcutRegistration

### ISSUE THREAD

**Issue by davidef** [vaadin/flow#17201] opened 2023-07-06 17:03 UTC
### Description of the bug

We are getting the error on a cluster node which is reading a serialized session which contains a UI with a ShortcutRegistration 

similar to this one:
`Shortcuts.addShortcutListener(this, event -> testField.focus(), Key.KEY_F, KeyModifier.META);`
	
`java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.vaadin.flow.component.ShortcutRegistration.beforeClientResponseConsumer of type com.vaadin.flow.function.SerializableConsumer in instance of com.vaadin.flow.component.ShortcutRegistration`

### Expected behavior

No serialization exception

### Minimal reproducible example

Unfortunatelly we are not able to reproduce the issue with a small sample

### Versions

- Vaadin / Flow version: 23.3.15
- Java version:  Temurin-17.0.7+7 (build 17.0.7+7)
- OS version: docker / tomcat:9-jdk17-temurin

**Comment by mcollovati** [comment] 2023-07-07 05:00
@davidef thank for the issues!
Would you be able to reproduce the issue in your environment with the `sun.io.serialization.extendedDebugInfo` system property enabled and post the logs?

**Comment by davidef** [comment] 2023-07-07 08:35
@mcollovati We enabled that flag on an additional cluster node so we can debug it but it doesn't change the log output.
Checking the jdk source code that flag dump some additional output only on exception while writing not serializable objects.
The reported exception is raised when the serialized session is read back to objects (the exception is thrown here by jdk https://github.com/openjdk/jdk17u/blob/0f531dacb878efe77912688216b0f39a769259a3/src/java.base/share/classes/java/io/ObjectStreamClass.java#L2090C1-L2090C34 ).
Let us know if we can try to do more debugging

**Comment by mcollovati** [comment] 2023-07-07 08:45
@davidef yes, you're right.I missed the issue was during deserialization, sorry

**Comment by mcollovati** [comment] 2023-07-13 08:37
@davidef, we are unable to reproduce the issue from our side. And, unfortunately, without a detailed log output or a minimal example that reproduces the problem, we cannot investigate the issue further. Please let us know if you manage to reproduce the problem.

Also, for your consideration, the [Kubernetes Kit](https://vaadin.com/docs/latest/tools/kubernetes) (which is a commercial product), has a [session replication debug tool](https://vaadin.com/docs/latest/tools/kubernetes/session-replication-debug-tool) that can help you identify the root cause of the problem.

**Comment by davidef** [comment] 2023-07-13 14:49
Hi @mcollovati We spend all day trying to reproduce the issue and we managed to do so. The sample app make almost no sense but in the real one there are more checks ad make more sense.

If you start from view1 and serialize it is fine, following the link to view2 and trying to serialize it will fail.
If you start from view2 it serialize fine, then go to view1 it still serialize fine, going back again to view2 it fails.

```
public class MyLayout extends AppLayout implements AfterNavigationObserver {
	private static final long serialVersionUID = 1L;
	
	HorizontalLayout layout = new HorizontalLayout();
	TextField textField = new SearchTextField<>();

	public MyLayout() {
		layout.add(new H3("Title"));
	}

	@Override
	public void afterNavigation(AfterNavigationEvent event) {
		addToNavbar(layout);
		if (event.getActiveChain().get(0) instanceof View1) {
			layout.add(textField);
		}else {
			layout.remove(textField);
		}
	}
	
	private static class SearchTextField<T extends Serializable> extends TextField{
		private static final long serialVersionUID = 1L;

		public SearchTextField() {
			Shortcuts.addShortcutListener(SearchTextField.this, 
					event -> SearchTextField.this.focus(), 
					Key.KEY_F, KeyModifier.META);
			
		}
	}
}

@Route(value = "view1", layout = MyLayout.class)
public class View1 extends VerticalLayout {
	private static final long serialVersionUID = 1L;

	public View1() {
		RouterLink link = new RouterLink("Go to View2", View2.class);
		add(link);
		
		Button test = new Button("Serialize", e -> {
			try {
				ByteArrayOutputStream bos = new ByteArrayOutputStream();
				try(ObjectOutputStream oos = new ObjectOutputStream(bos)){
					oos.writeObject(VaadinSession.getCurrent());
					oos.writeObject(UI.getCurrent());
					oos.flush();
				}
				try(ByteArrayInputStream bis = new ByteArrayInputStream(bos.toByteArray())){
					try(ObjectInputStream ois = new ObjectInputStream(bis)){
						VaadinSession readObject = (VaadinSession) ois.readObject();
						UI readObject2 = (UI) ois.readObject();
					}
				}
				Notification.show("OK " + bos.toByteArray().length);
			}catch (Exception ex) {
				ex.printStackTrace();
				Notification.show("FAILED: " + ex.getMessage());
			}
		});
		add(test);
	}
}

@Route(value = "view2", layout = MyLayout.class)
public class View2 extends VerticalLayout {
	private static final long serialVersionUID = 1L;

	public View2() {
		RouterLink link = new RouterLink("Go to View1", View1.class);
		add(link);
		
		Button test = new Button("Serialize", e -> {
			try {
				ByteArrayOutputStream bos = new ByteArrayOutputStream();
				try(ObjectOutputStream oos = new ObjectOutputStream(bos)){
					oos.writeObject(VaadinSession.getCurrent());
					oos.writeObject(UI.getCurrent());
					oos.flush();
				}
				try(ByteArrayInputStream bis = new ByteArrayInputStream(bos.toByteArray())){
					try(ObjectInputStream ois = new ObjectInputStream(bis)){
						VaadinSession readObject = (VaadinSession) ois.readObject();
						UI readObject2 = (UI) ois.readObject();
					}
				}
				Notification.show("OK " + bos.toByteArray().length);
			}catch (Exception ex) {
				ex.printStackTrace();
				Notification.show("FAILED: " + ex.getMessage());
			}
		});
		add(test);
	}
}
```

I think the issue is caused by calling multiple time addToNavbar (in our real code there are addToNavbar and remove based on multiple conditions) so I think we will fix it from our side by add some more tracking on which components are already added and not calling addToNavbar on those. It is anyway a bit strange that this will cause a serialization issue.

**Comment by mcollovati** [comment] 2023-07-13 14:53
@davidef thank you very much for the reproducible example. I'll take a look at it soon as possible

**Comment by mcollovati** [comment] 2023-07-14 11:04
@davidef you're right that the issue in the above code is because of calling `addToNavbar()` for the same element multiple times.
For some reason, the `beforeClientResponseConsumer` field is serialized as a reference handle instead of object, probably because adding the horizontal layout again causes it be removed and added, triggering detach and attach listeners for all its children and adding change events object to the StateTree that references the removed components.

The easy fix for the sample code is to add the layout once in the constructor, but I understand that there may be different use cases that can provoke the same issue.

The real fix is to change `beforeClientResponseConsumer` initialization from a lamba to a concrete class

**Comment by mcollovati** [comment] 2023-07-14 13:47
The root cause seems to be that when adding the horizontal layout with the attached text field, the latter gets detached and attached, thus registering `beforeClientResponseConsumer` as a `beforeClientResponse` listener. But then, when during the same request the text field is removed, the `beforeClientResponse` listener is not unregistered.
When serialization happens the lambda assigned to `beforeClientResponseConsumer` field is replaced by a `SerializedLambda` instance when serializing the `beforeClientResponse` entries.
When it's time to serialize the `ShortcutRegistration` instance, the `beforeClientResponseConsumer` field is serialized as a handle to the previously generated `SerializedLambda`.

However, on deserialization, the `ShortcutRegistration.beforeClientResponseConsumer` field is deserialized before of the `beforeClientResponse` entries, so it still has a reference to the `SerializedLamdba` instead of the correct functional interface implementation.


Probably, the proper fix may be to cleanup the `ShortcutRegistration.executionRegistration` when the shortcut owner is detached.
I'll take a deeper look into this.

**Closed** 2023-07-20 04:44 UTC
Labels: bug, Impact: Low, Severity: Major
