### ISSUE TITLE
As a developer I want to setup superdevmode more easily, to be more efficient

### ISSUE THREAD

**Issue by rogozinds** [vaadin/flow#1974] opened 2017-07-06 08:48 UTC
Currently debugging client-side code is not so easy. The only way now, is to checkout Vaadin Flow repository, start codesever there and then attach it to you flow app. 
As a developer I would like to do it in one project, also I would like to have documentation how to do that.

**Comment by pleku** [comment] 2018-04-18 12:34
Closing in favor (and duplicate of) #1086

**Closed by pleku** 2018-04-18 12:34 UTC
Labels: enhancement, feedback
