### ISSUE TITLE
Vaadin Flow does not build on Java 11!!!

### ISSUE THREAD

**Issue by cachorios** [vaadin/flow#8102] opened 2020-04-20 01:48 UTC
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.1.25:build-frontend (default) on project vaadin-crm: Execution default of goal com.vaadin:vaadin-maven-p
lugin:14.1.25:build-frontend failed: Unsupported class file major version 58 -> [Help 1]

**Comment by caalador** [comment] 2020-04-20 05:25
I guess this should be Java14 not Java11?
The exception for java 11 has been `major version 55` where as `58` is for Java 14.
Also tested with Java 11 that there are no regressions and it worked as it should.

Java14 will be fixed with #8103

**Comment by caalador** [comment] 2020-04-20 05:28
Closing issue as duplicate of #8046

**Closed by caalador** 2020-04-20 05:28 UTC
