### ISSUE TITLE
Strange sysout log in the middle of startup

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8604] opened 2020-06-23 07:40 UTC
When starting an app I see
```
2020-06-23 10:37:54.081  INFO 49417 --- [           main] c.v.f.s.VaadinServletContextInitializer  : Search for VaadinAppShell took 30 ms
2020-06-23 10:37:54.087  INFO 49417 --- [           main] c.v.f.s.s.VaadinAppShellInitializer      : Using com.vaadin.recipes.AppShell class for configuring `index.html` response
2020-06-23 10:37:55.985  INFO 49417 --- [           main] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 1848 ms
2020-06-23 10:37:55.986  INFO 49417 --- [           main] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in /Users/artur/workspace/recipes folder.
2020-06-23 10:37:56.016  INFO 49417 --- [           main] c.v.f.s.f.s.FullDependenciesScanner      : Visited 97 classes. Took 19 ms.
Vaadin application has been deployed and started to the context path "/".
2020-06-23 10:37:56.028  INFO 49417 --- [nPool-worker-19] c.v.f.s.f.TaskGeneratePackageJson        : writing file /Users/artur/workspace/recipes/target/flow-frontend/package.json.
2020-06-23 10:37:56.030  INFO 49417 --- [nPool-worker-19] c.v.f.s.f.TaskGeneratePackageJson        : writing file /Users/artur/workspace/recipes/target/flow-frontend/form/package.json.
2020-06-23 10:37:56.046  INFO 49417 --- [nPool-worker-19] c.v.f.s.c.g.OpenApiSpecGenerator         : Parsing java files from [/Users/artur/workspace/recipes/src/main/java]
2020-06-23 10:37:56.149  INFO 49417 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
```

The `Vaadin application has been deployed and started to the context path "/".` seems really out of place as it is logged to sysout and with blue color. 

Is this some kind of debug statement that has been forgotten?

**Comment by denis-anisimov** [comment] 2020-07-31 09:52
This is done intentionally: The `Vaadin application has been deployed and started to the context path "/"` string is printed to std out instead of logger .
As I understand this is done to indicate that Servlet is deployed and user may go to the browser and open the app.
Other logging still may be shown in the console but it's not important (it's internal logging info which is not relevant for the started app).
That's why it's in the specific color.

BUT. I'm just speculating based on my knowledge and memory.
This change is intentionally done by @pleku .
So I'm just assigning it this him.

Most likely this is not a bug but by design. Though may be some improvement could be done here.

**Comment by pleku** [comment] 2020-09-09 10:07
This is intentional statement added based on feedback in onboarding DX tests that newbie developers didn't realize that the app is ready to be opened in the browser. And it is visible even if there is no logging implementation on runtime. Sure it is annoying for super users but if it helps someone (not sure if so as don't think we've redone the tests) then not going to remove it for now.

**Closed by pleku** 2020-09-09 10:07 UTC
Labels: Impact: Low, Severity: Minor, bug

**Comment by guttormvik2** [comment] 2023-05-04 08:07
@pleku, I see this is closed and wontfix, so don't know if anyone will see this, but you didn't respond to the 2nd part of the problem: You change color, to blue, and after that *all* output is blue. Here's my Eclipse log running vaadin24:

![image](https://user-images.githubusercontent.com/108350446/236146231-6f35b0f9-40d5-4dbd-b216-495a7c38145b.png)
