### ISSUE TITLE
Navigating to the same route is inconsistent

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7665] opened 2020-02-25 07:53 UTC
Go to start.vaadin.com

1. Download the default project as "java-only"
2. Set the "Master detail" view type to "Typescript" and download that project

Start the projects, open http://localhost:9090/dashboard and click on "dashboard" in the menu multiple times.

Expectation:
Regardless of whether the "master detail" view is using Java or Typescript, clicking on "Dashboard" view produces the same result

Actual:
In the Java only application (V14), more and more series are added to the charts when clicking. This is because `afterNavigation` is called for each click

In the Java+TS application (V15), nothing happens when clicking

**Comment by haijian-vaadin** [comment] 2020-02-25 12:33
Let's have an open discussion on this. Haijian will send a calendar invite

**Comment by Artur-** [comment] 2020-02-26 08:15
HTML in general will navigate again to the same page

GitHub catches routing links but also refreshes issues when clicking on "issues" even if you already are on the "issues" page

There are cases where you want the user to be able to refresh by navigating again, such as the GitHub case. Are there cases where you want to avoid navigating even when the link is enabled?

**Comment by vlukashov** [comment] 2020-04-24 13:35
> There are cases where you want the user to be able to refresh by navigating again, such as the GitHub case. Are there cases where you want to avoid navigating even when the link is enabled?

I do want to avoid trashing and re-creating the DOM content to avoid unnecessary screen flickering. A quick look at several SPAs shows that none of them recreates the views when navigating to the currently active route. In fact, from all SPAs that I have open in my browser(s) at the moment, I cannot find any that does it:
 - https://twitter.com/notifications
 - https://www.linkedin.com/mynetwork
 - https://app.clickup.com/2248825/notifications
 - https://drive.google.com/drive/recent
 - https://mail.google.com/mail/u/0/#inbox

My conclusion here would be that for an SPA re-creating the DOM for the current route is not an expected behavior. I would not want the Router to remove the DOM nodes and re-add them again.

I do want to know that the user has requested the navigation though, because I want to re-fetch the view data and re-render the view if there are changes. As a developer I expect the Router to trigger some sort of event on each view in the view chain to inform that a navigation event has occurred so that I can trigger a refresh.

**Comment by haijian-vaadin** [comment] 2020-04-30 09:38
This should be fixed with vaadin-router 1.7.2.

**Closed by haijian-vaadin** 2020-04-30 09:38 UTC
Labels: ccdm
