### ISSUE TITLE
addSucceededListener() is triggered before I upload the file.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [vaadin/flow#9229] opened 2020-10-25 14:19 UTC
Hello, community. I am new to Java and Vaadin in particular. Please explain to me why addSucceededListener() is triggered earlier (when loading a page) than I download a file?

> **Olli Tietäväinen:**
> Looks like there's already an answer to the same question on StackOverflow: https://stackoverflow.com/questions/64475277/addsucceededlistener-is-triggered-before-i-upload-the-file

The problem is that many Listener listeners do not work in principle, all of them are executed before the file is loaded, even addFinishedListener(). I can see that I'm not alone in this problem, I found a workaround so far with upload.getElement().addEventListener("upload-success" ... 

I also noticed that everything worked fine initially, until I started adding new Maven dependencies (I'm afraid I can't say at what point I didn't use git immediately).

[Link about this problem](https://github.com/vaadin/vaadin-upload-flow/issues/134)

**UploadView.class**
```
@Route("")
public class UploadView extends VerticalLayout {
    @Autowired
    PictureRepository pictureRepository;

    @Autowired
    GoogleCloudAiAssistantRecognition googleCloudAiAssistantRecognition;

    public UploadView() {
        this.pictureRepository = pictureRepository;
        this.googleCloudAiAssistantRecognition = googleCloudAiAssistantRecognition;

        MenuBar menuBar = new MenuBar();
        menuBar.addThemeVariants(MenuBarVariant.LUMO_PRIMARY);

        MenuItem resultsItem = menuBar.addItem("Get Results");
        MenuItem tagItem = menuBar.addItem("Edit Tag");

        resultsItem.addClickListener(e -> UI.getCurrent().navigate("ai-result"));
        tagItem.addClickListener(e -> UI.getCurrent().navigate("edit-tag"));

        add(menuBar, new H1("Assistant recognition by Google Vision"));

        MemoryBuffer buffer = new MemoryBuffer();
        Upload upload = new Upload(buffer);
        upload.setAcceptedFileTypes("image/jpeg", "image/png", "image/gif");
        upload.setMaxFileSize(10485760);
        Div output = new Div();

        upload.addSucceededListener(event -> {
                InputStream inputStream = buffer.getInputStream();
                byte[] bytes = new byte[0];
                try {
                    bytes = IOUtils.toByteArray(inputStream);
                } catch (IOException e) {
                    e.printStackTrace();
                }

                add(new H1(event.getMIMEType()));
                Component component = createComponent(event.getMIMEType(), event.getFileName(), inputStream);
                showOutput(event.getFileName(), component, output);

                PictureModel pictureModel = new PictureModel(event.getFileName(), event.getMIMEType(), bytes);
                Long picId = pictureRepository.save(pictureModel).getId();

                List<TagModel> tags = null;
                try {
                    tags = googleCloudAiAssistantRecognition.detect(picId);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                pictureModel.setTagModel(tags);
        });

        /*upload.getElement().addEventListener("upload-success", e -> {
            System.out.println(e.getEventData());
        });*/

        add(upload, output);
    }

    private Component createComponent(String mimeType, String fileName,
                                      InputStream stream) {
        if (mimeType.startsWith("text")) {
            return createTextComponent(stream);
        } else if (mimeType.startsWith("image")) {
            Image image = new Image();
            try {

                byte[] bytes = IOUtils.toByteArray(stream);
                image.getElement().setAttribute("src", new StreamResource(
                        fileName, () -> new ByteArrayInputStream(bytes)));
                try (ImageInputStream in = ImageIO.createImageInputStream(
                        new ByteArrayInputStream(bytes))) {
                    final Iterator<ImageReader> readers = ImageIO
                            .getImageReaders(in);
                    if (readers.hasNext()) {
                        ImageReader reader = readers.next();
                        try {
                            reader.setInput(in);
                            image.setWidth(reader.getWidth(0) + "px");
                            image.setHeight(reader.getHeight(0) + "px");
                        } finally {
                            reader.dispose();
                        }
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }

            return image;
        }
        Div content = new Div();
        String text = String.format("Mime type: '%s'\nSHA-256 hash: '%s'",
                mimeType, MessageDigestUtil.sha256(stream.toString()));
        content.setText(text);
        return content;
    }

    private Component createTextComponent(InputStream stream) {
        String text;
        try {
            text = IOUtils.toString(stream, StandardCharsets.UTF_8);
        } catch (IOException e) {
            text = "exception reading stream";
        }
        return new Text(text);
    }

    private void showOutput(String text, Component content,
                            HasComponents outputContainer) {
        HtmlComponent p = new HtmlComponent(Tag.P);
        p.getElement().setText(text);
        outputContainer.add(p);
        outputContainer.add(content);
    }
}
```

**pom.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.prosvirnin</groupId>
    <artifactId>assistant-recognition</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>assistant-recognition</name>
    <description>Assistant recognition by Google Vision</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <repositories>
        <repository>
            <id>jcenter-snapshots</id>
            <name>jcenter</name>
            <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-vision</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>10.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>14.1.17</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <pluginRepositories>
        <pluginRepository>
            <id>pvsstudio-maven-repo</id>
            <url>http://files.viva64.com/java/pvsstudio-maven-repository/</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.pvsstudio</groupId>
                <artifactId>pvsstudio-maven-plugin</artifactId>
                <version>7.09.41421</version>
                <configuration>
                    <analyzer>
                        <outputType>text</outputType>
                        <outputFile>path/to/output.txt</outputFile>
                    </analyzer>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by sergey-prosvirnin** [comment] 2020-10-25 14:19
[YouTube](https://www.youtube.com/watch?v=zOUkQuhktiE&feature=youtu.be) This video will help you better understand the problem.

**Comment by caalador** [comment] 2020-10-26 12:54
It seems you are breakpointing on the addListener line and not inside the actual even call.
Also we can't say much as the sample has many things that we don't have like: PictureRepository etc.

We would require a minimal working sample that fails with the issue to proceed.
Also the version that I could make with the given code worked as expected with events firing only for the actual upload.

**Comment by sergey-prosvirnin** [comment] 2020-10-26 16:00
> It seems you are breakpointing on the addListener line and not inside the actual even call.
> Also we can't say much as the sample has many things that we don't have like: PictureRepository etc.
> 
> We would require a minimal working sample that fails with the issue to proceed.
> Also the version that I could make with the given code worked as expected with events firing only for the actual upload.

For the PictureRepository, I attach it to the constructor through this. I copied this code from the example on one site and didn't have time to get it working because I had a problem with Listener, this monkey code is a draft that I don't want to post. Now I'm starting to learn Java and was madly grateful for some advice on how to make this terrible code a bit better.

I made another class just with Upload and reloaded the video on [YouTube](https://youtu.be/Qmzqms_pvJo).

I plan to continue working with this repository, so I will give a link to the GitHub [commit](https://github.com/sergey-prosvirnin/assistant-recognition/commit/19d31b353799a9f0bf84ec165041378b0350c974?branch=19d31b353799a9f0bf84ec165041378b0350c974&diff=unified).

**Comment by caalador** [comment] 2020-10-27 06:27
This code doesn't either showcase the issue when executing on a simple starter.
So if you go to https://vaadin.com/start and download one of the `Hello World Examples` and add this code there the listener event is fired.

You stated that it started failing after adding some dependency, you could start adding the dependencies to the starter project and note after which the event seems to stop working.

**Comment by sergey-prosvirnin** [comment] 2020-11-03 08:38
> This code doesn't either showcase the issue when executing on a simple starter.
> So if you go to https://vaadin.com/start and download one of the `Hello World Examples` and add this code there the listener event is fired.
> 
> You stated that it started failing after adding some dependency, you could start adding the dependencies to the starter project and note after which the event seems to stop working.

Hi, it did not help.

https://github.com/sergey-prosvirnin/assistant-recognition/commit/f8e9cb5dc21c73f7e955983af8c7aef8ed86c402

**Comment by taefi** [comment] 2020-12-01 10:29
Hi @sergey-prosvirnin, I'm closing this issue as I could not find anything at https://github.com/sergey-prosvirnin/assistant-recognition/, and also there isn't enough information/instructions to reproduce the issue.

**Comment by sergey-prosvirnin** [comment] 2020-12-01 10:36
> Hi @sergey-prosvirnin, I'm closing this issue as I could not find anything at https://github.com/sergey-prosvirnin/assistant-recognition/ (maybe a private repo?), and also there isn't enough information/instructions to reproduce the issue.

Good afternoon, I thought that no one was interested in this thread. Look again, please, I think the repository should now be available.

**Comment by taefi** [comment] 2020-12-03 23:13
Hi @sergey-prosvirnin,

I was able to run your application and it seems to be confusion about the order of actions. After you log into the application, you are already at the upload page (which is being served at the root URL), so the codes in the constructor of `UploadView.java` will be called and `addSucceededListener` is one of them. There is no problem with that being called because it is only registering a listener for the upload success event (codes inside the lambda expression you passed to it as the listener is not getting called). Then, when the upload happens successfully, the listener you added by a lambda expression is being called. 

So please tell me if anything else wrong, or I misunderstood your problem.

**Comment by pleku** [comment] 2021-01-08 17:13
Closing the issue for inactivity.

**Closed by pleku** 2021-01-08 17:13 UTC
Labels: waiting for author
