### ISSUE TITLE
NullPointerException when ItemLabelGenerator returns null

### ISSUE THREAD

**Issue by tuliogarcia** [vaadin/flow#2996] opened 2017-11-21 12:56 UTC
I'm getting a NullPointerException in Bakery when the screen is loaded if I have a ComboBox with a item label generator that returns null and the value of the ComboBox is set.

Basically, this code:
```java
		ComboBox<String> comboBox = new ComboBox<>();
		comboBox.setItemLabelGenerator(i -> null);
		comboBox.setValue(null);
```
Causes the following exception when the view is loaded:
```
java.lang.NullPointerException
	at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208)
	at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96)
	at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72)
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281)
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267)
	at com.vaadin.server.BootstrapHandler.getBootstrapJS(BootstrapHandler.java:585)
	at com.vaadin.server.BootstrapHandler.getBootstrapScript(BootstrapHandler.java:564)
	at com.vaadin.server.BootstrapHandler.setupFrameworkLibraries(BootstrapHandler.java:364)
	at com.vaadin.server.BootstrapHandler.setupDocumentHead(BootstrapHandler.java:303)
	at com.vaadin.server.BootstrapHandler.getBootstrapPage(BootstrapHandler.java:269)
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:254)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1508)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:298)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Legioth** [comment] 2017-11-21 12:57
What's the expected behavior? What should the ComboBox look like?

**Comment by tuliogarcia** [comment] 2017-11-21 13:05
It should either show a empty label, or generate an exception that tells me clearly what is wrong with the code. It took quite some debugging to find the actual cause, because the exception happens latter, when the JSON is being generated, not immediately when the label generator returns .

I would prefer the first option, since I think it will be a common cause of problems.

If the second option is chosen, I think the javadoc in the setItemLabelGenerator should also mention that it is not ok to return null values.

**Comment by Legioth** [comment] 2017-11-21 17:32
I think it would be better to go the exception route since things might be quite weird for the end user if there are accidentally empty items in the ComboBox, and especially so if there would be multiple such items. It's clearer if the code instead explicitly returns `""` if an empty item is intended.

We should still add a check closer to the origin of the `null` value so that we can throw a more helpful exceptions.

**Comment by asashour** [comment] 2017-12-09 17:06
I believe this should be closed now.

**Comment by denis-anisimov** [comment] 2017-12-11 07:57
Not really.
The PR is not yet merged https://github.com/vaadin/vaadin-combo-box-flow/pull/26.

Related issues have been fixed in the Flow core but they are not related to the combo box.

**Closed** 2017-12-11 11:47 UTC
Labels: bug, Good First Issue, Help wanted
