### ISSUE TITLE
Required flag clears invalid status of field on blur

### ISSUE THREAD

**Issue by ilya-ershov** [vaadin/flow#4777] opened 2018-11-13 16:23 UTC
There is a strange behavior of TextField onBlur when using Binder with a field marked as Required. It can be reproduced for at least 2 components (TextField and ComboBox). For example with simple TextField it has following behavior:
![required-no-ok](https://user-images.githubusercontent.com/39500120/48426752-73d17a00-e778-11e8-96ac-7e68bfe726ad.gif)

I've found similar bugs raised as this one https://github.com/vaadin/flow/issues/4597
But nobody mentions that component looses its invalid state not only when it is wrapped by Binder by also it should be set as **required** and binded to Binder. So that could be another issue.

If delete text from the field, than invalid flag stays even if I click outside the component causing onBlur event. I assume that could be somehow connected to logic that handles required indicator.

I attach sample project that can be run by **mvn jetty:run** to see bug in action.
[required-bug.zip](https://github.com/vaadin/flow/files/2577078/required-bug.zip)

**Comment by denis-anisimov** [comment] 2019-02-01 11:10
This is the duplicate of https://github.com/vaadin/vaadin-text-field-flow/issues/104
And your ticket has a proper description of the bug.
I'm pretty sure that the ticket which you refer to is just lacking all the details.

**Comment by Klaudeta** [comment] 2019-02-19 14:54
This issue is still reproducible
[vaadin/vaadin-text-field-flow#104](https://github.com/vaadin/vaadin-text-field-flow/issues/104) does not fix the problem stated in here.
JS code to override the element's validate function that is added inside the Flow.textConnector's disableClientValidation function does not have any affect on the initial validate function on the element. I guess reason is that the blur event listener pointing to validate function is registered before validate is overridden from Flow.textConnector JS code.

**Comment by Klaudeta** [comment] 2019-02-20 09:21
The change introduced here [PR 116](https://github.com/vaadin/vaadin-text-field-flow/pull/116) to clients-side validate method for required field is ignored and even when the field is used in binder with the required flag, the client-side validate method still get called on blur. 
I suppose reason for this behavior could be of the validate method registered with the blur event before the textConnector JS code is executed.

A possible fix would be to introduce a new method in VaadinTextFieldMixin like for example doValidate and have validate method change to 
`validate() {
      return this.doValidate();
    }`

and inside textConnector override the client-side doValidate method instead of the validate method.

**Comment by Wnt** [comment] 2019-02-21 08:22
I think I'm experiencing the same issue in Vaadin 13 beta 2
![ezgif-2-0b02c3daab9b](https://user-images.githubusercontent.com/886091/53153899-12644700-35c2-11e9-8735-6ebc086acc53.gif)
The required indication of the field dissapears after leaving the textfield on the second time without a value.

Minimal code to reproduce the issue:
```
package org.vaadin.vaadinfiddle;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.router.Route;
@Route("")
public class MainView extends VerticalLayout {

	private void createAndBIndFields() {
		TextField price = new TextField();
		binder.forField(price).asRequired().bind(o -> "12 EUR", (o, v) -> {});
		form.addFormItem(price, "Tax free price");

		TextField ownPrice = new TextField();
		binder.forField(ownPrice).asRequired().bind(o -> "12 EUR", (o, v) -> {});
		form.addFormItem(ownPrice, "Buy-in price");
	}

	private Binder<Object> binder;
	private FormLayout form;

	public MainView() {
		form = new FormLayout();

		binder = new Binder<Object>();
		createAndBIndFields();

		binder.readBean(new Object());

		add(form);
	}
}
```

**Comment by Klaudeta** [comment] 2019-02-21 08:34
Fix already done on the webcomponent side [PR #322](https://github.com/vaadin/vaadin-text-field/pull/322) We just have to wait for its release. 

Duplicate of [vaadin/flow/issues/3230](https://github.com/vaadin/flow/issues/3230)

**Comment by Klaudeta** [comment] 2019-02-22 09:17
Fixed as result of fixing [vaadin-text-field/issues/321](https://github.com/vaadin/vaadin-text-field/issues/321)

**Closed by Klaudeta** 2019-02-22 09:17 UTC
Labels: binder, bug, components

**Comment by denis-anisimov** [comment] 2019-03-19 12:54
Issue moved to [vaadin/vaadin-text-field-flow #156](https://github.com/vaadin/vaadin-text-field-flow/issues/156) via [**ZenHub**](https://www.zenhub.com/)
