### ISSUE TITLE
Binding with Validator and asRequired does not make field invalid on first load

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6263] opened 2019-08-16 10:40 UTC
Vaadin 14.0.0; Java 8; Ubuntu; Firefox.

- If you create a field with a `Validator`, bind it with `asRequired` and set an initial value, the `Validator` is not checked before the value is changed in the `UI`.
- Minimal reproducible example:

```java
package uk.ev.matt;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.ValidationResult;
import com.vaadin.flow.router.Route;
import java.time.LocalDate;
import java.time.chrono.ChronoLocalDate;

@Route("")
public class MainView extends Div {

    public MainView() {
        Binder<TestBean> testBinder = new Binder<>();
        testBinder.setBean(new TestBean());
        DatePicker datePicker = new DatePicker();
        Binder.Binding<TestBean, LocalDate> datepickerBinding = testBinder.forField(datePicker)
                .withValidator((value, context) -> {
                    if (value.isAfter(ChronoLocalDate.from(LocalDate.now().minusYears(18)))) {
                        return ValidationResult.error("Must be over 18.");
                    } else {
                        return ValidationResult.ok();
                    }
                })
                // remove .asRequired() -> Validator will work as expected
                .asRequired()
                .bind(TestBean::getDob, TestBean::setDob);
        add(datePicker);
        // validator should fail immediately, text field should be invalid
        datepickerBinding.validate();

        Button revalidate = new Button("Validation");
        revalidate.addClickListener(clickEvent -> {
            datepickerBinding.validate();
        });
        add(revalidate);
        add(new Paragraph("Validator should make datepicker invalid immediately"));
        add(new Paragraph("Clicking 'Validation' should also make datepicker invalid because of Validator"));
        add(new Paragraph("Only after changing the value, Validator starts working"));
        add(new Paragraph("Remove 'asRequired' and Validator starts working without value change in the UI"));
    }

    private class TestBean {

        public LocalDate getDob() {
            return dob;
        }

        public void setDob(LocalDate dob) {
            this.dob = dob;
        }

        private LocalDate dob = LocalDate.now().minusYears(17);

    }
}
```

This issue resembles https://github.com/vaadin/flow/issues/5875 however this time it's a DatePicker field.

**Comment by mvysny** [comment] 2019-08-16 10:44
The bug is reproducible with a ComboBox as well:

```java
package com.vaadin.starter.skeleton;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.ValidationResult;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.PWA;

/**
 * The main view contains a button and a click listener.
 */
@Route("")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base")
public class MainView extends VerticalLayout {

    public MainView() {
        Binder<TestBean> testBinder = new Binder<>();
        testBinder.setBean(new TestBean());
        ComboBox<Boolean> datePicker = new ComboBox<>();
        datePicker.setItems(true, false);
        Binder.Binding<TestBean, Boolean> datepickerBinding = testBinder.forField(datePicker)
                .withValidator((value, context) -> {
                    if (value) {
                        return ValidationResult.error("Must be false");
                    } else {
                        return ValidationResult.ok();
                    }
                })
                // remove .asRequired() -> Validator will work as expected
                .asRequired()
                .bind(TestBean::getDob, TestBean::setDob);
        add(datePicker);
        // validator should fail immediately, text field should be invalid
        datepickerBinding.validate();

        Button revalidate = new Button("Validation");
        revalidate.addClickListener(clickEvent -> {
            datepickerBinding.validate();
        });
        add(revalidate);
        add(new Paragraph("Validator should make combobox invalid immediately"));
        add(new Paragraph("Clicking 'Validation' should also make combobox invalid because of Validator"));
        add(new Paragraph("Only after changing the value, Validator starts working"));
        add(new Paragraph("Remove 'asRequired' and Validator starts working without value change in the UI"));
    }

    private class TestBean {

        public Boolean getDob() {
            return dob;
        }

        public void setDob(Boolean dob) {
            this.dob = dob;
        }

        private Boolean dob = true;

    }
}
```

**Comment by knoobie** [comment] 2019-08-16 19:12
Could this be related to

* https://github.com/vaadin/vaadin-form-layout-flow/issues/66
* https://github.com/vaadin/vaadin-form-layout-flow/issues/59

as well?

**Comment by TatuLund** [comment] 2019-09-11 07:28
I just noticed that problem is not appearing in Vaadin 13.

**Comment by ujoni** [comment] 2019-09-19 12:33
Hmm. It seems that the problem is somewhere else than Flow. 

When I refresh the page (Chrome), I can see the validation error being displayed briefly. After this, the component has `invalid` attribute even though it is not displaying the validation error.

Stepping through the execution logic in Flow showed everything working as it should. 

Here is a gif displaying the what happens after refresh:
![refresh](https://user-images.githubusercontent.com/45562391/65244147-88964100-daf2-11e9-898a-67a3f5a9521d.gif)

Vaadin version: 14.0.4

**Comment by bogdanudrescu** [comment] 2019-10-01 09:06
@mvysny Could you please confirm that with Vaadin 14.0.7 the behaviour is the same with or without `asRequired`, which is exactly what @ujoni wrote previously?

**Comment by bogdanudrescu** [comment] 2019-10-10 10:53
@mvysny DatePicker has a fix in https://github.com/vaadin/vaadin-date-picker-flow/releases/tag/2.0.3, i.e. https://github.com/vaadin/vaadin-date-picker-flow/pull/197. So if you use Vaadin 14.0.7 it should work fine for your `Validator` implementation.

In the same time, the kind of validation you're trying to achieve has better UX in the calendar, by having the invalid dates disabled so the user won't be able to select them, if you use `datePicker.setMax(LocalDate.now().minusYears(18));` instead of using the `Validator` implementation, although the error message is missing, but the field itself is marked as invalid.
```
        DatePicker datePicker = new DatePicker();
        datePicker.setMax(LocalDate.now().minusYears(18));
        Binder.Binding<TestBean, LocalDate> datepickerBinding = testBinder.forField(datePicker)
                .asRequired()
                .bind(TestBean::getDob, TestBean::setDob);
        add(datePicker);
```

**Closed** 2019-10-30 08:03 UTC
Labels: BFP, bug
