### ISSUE TITLE
Theme doesn't load when using Tomcat 9

### ISSUE THREAD

**Issue by pontusbostrom** [vaadin/flow#3871] opened 2018-04-12 08:36 UTC
There has been problems with loading the theme when using Tomcat 9 (on Java 8).

Steps to reproduce:
-Create a small Flow application (tested with Vaadin 10.0.0.beta5)
-Add the annotation @Theme(Lumo.class)
-Deploy to Tomcat and open the application in Chrome, run the application in debug-mode.

It is unclear in exactly which situations the problem occurs. For some configurations it works.

**Comment by heruan** [comment] 2018-04-12 08:45
I'm experiencing similar issues, where Lumo is applied to some components and not to others. For example:

![screenshot-2018-4-12 user list](https://user-images.githubusercontent.com/851745/38665969-12a88aae-3e3e-11e8-8729-6e608f4e90a3.png)

Here `Tabs` and `Grid` are not styled, but `TextField` and `Button` are.

But on another route I have `Tabs` and `Grid` correctly styled, e.g.

![screenshot-2018-4-12 session list](https://user-images.githubusercontent.com/851745/38666033-40cb41f6-3e3e-11e8-9916-2680d50ee5ce.png)

I tried to replicate this in a small project, without success. In the browser network console, I see only the `src/vaadin-grid.html` file is requested, not the `themes/lumo/vaadin-grid.html`.

**Comment by Legioth** [comment] 2018-04-12 08:48
@heruan Your problem might be a different one since it still uses the theme in some situations. Is the Grid component added programmatically or from a template? If it's from a template, then you might try to add `@Uses(Grid.class)` to your template class and see if that has any effect.

**Comment by heruan** [comment] 2018-04-12 08:59
It's all added programmatically, no templates involved. E.g.

```java
@Route(value = "users", layout = UserSection.class)
public class UserList extends FilterableListView {

   private final Grid<User> grid = new Grid<>();

    public UserList() {
        // add columns
        this.add(this.grid);
    }

}
```

One difference between the working view and the not working one is that the not working one has a longer class hierarchy, e.g. `UserList < FilterableListView < ListView` vs `SessionList < ListView`; another one is they have differen parent layouts, but the theme is set on a common root layout.

If your feel this is not the same issue of @pontusbostrom, I'll open a new one!

**Comment by Artur-** [comment] 2018-04-12 09:58
@pontusbostrom could you create this small Flow application in a GitHub repo or attach it here?

**Comment by pontusbostrom** [comment] 2018-04-12 12:10
I haven't been able to reproduce the issue myself. Here is some more info: 
OS: Windows 8.1 Pro
Tomcat: 9.0.6
Java: 1.8.0_66 

Attached is log from Chrome. It seems like it is not only the theme that fails to load.
[localhost-1523533148686.log](https://github.com/vaadin/flow/files/1903004/localhost-1523533148686.log)

**Comment by Legioth** [comment] 2018-04-12 12:30
The last time I encountered something like `ERR_CONTENT_LENGTH_MISMATCH`, it was caused by doing gzip encoding twice for the same payload.

**Comment by heruan** [comment] 2018-04-12 12:32
I confirm my issue is different and I've found it's from the latest `vaadin-tabs`. I'll open an issue there!

**Comment by Artur-** [comment] 2018-04-12 18:30
https://stackoverflow.com/questions/26013015/err-content-length-mismatch-while-loading-js-files-on-tomcat-server suggests

"
In conf/server.xml config file in apache tomcat folder set the "usesendfile" attribute to "false" as shown below:-

```
<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" URIEncoding="UTF-8"  **useSendfile="false"**/>
```
Please refer to link: http://ci.apache.org/projects/tomcat/tomcat7/docs/config/http.html for more details."

which also seems related to gzipping resources

**Comment by caalador** [comment] 2023-11-07 11:21
Not noted lately with theming so Closing ticket.

**Closed by caalador** 2023-11-07 11:21 UTC
Labels: bug, investigation, Impact: Low, Severity: Major
