### ISSUE TITLE
NullPointerException in getCookies() of AtmosphereRequestImpl.java

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#6699] opened 2019-10-16 15:42 UTC
In Vaadin Flow 14.0.8.
Servlet 4.0
Tomcat 9.

method `public Cookie[] getCookies()`  in **AtmosphereRequestImpl.java** .

line 324:  `return b.cookies.toArray(new Cookie[]{});`

if cookies is NULL, causes NullPointerException .

![image](https://user-images.githubusercontent.com/13396193/66935273-5be03580-f06e-11e9-997d-0a1f79e0f827.png)

![image](https://user-images.githubusercontent.com/13396193/66935387-79ad9a80-f06e-11e9-8b02-371b7dbd0698.png)

**Comment by mehdi-vaadin** [comment] 2019-10-21 07:09
@letrthang Thanks for reporting this. Would you please provide the steps to reproduce this issue?

**Comment by letrthang** [comment] 2019-10-22 07:49
Hi,
I just try to read cookie from Vaadin session leading to this issue.

**Comment by mehdi-vaadin** [comment] 2019-10-22 08:33
@letrthang I don't know how cookies can be obtained from `VaadinSession`. But, you should be able to get them from `VaadinRequest` like this `VaadinService.getCurrentRequest().getCookies()` without any error. Please let me know if it solves your problem.

**Comment by letrthang** [comment] 2019-10-22 08:36
Hello Mehdi,
Yes, i did this and causing exception. 
We access VaadinService.getCurrentRequest().getCookies() from another thread, is this a problem?

**Comment by mehdi-vaadin** [comment] 2019-10-22 08:41
Yes, `getCurrentRequest` doesn't work well from the threads you create. You can call `getCurrentRequest` only from the main thread created for the HTTP request.

**Comment by mehdi-vaadin** [comment] 2019-10-22 08:47
Since the issue is not on the Flow side, I'm closing this. @letrthang you should find another way to access the cookies in the other thread. E.g. you can get the cookies in the main thread and pass it to the other thread like the following piece of code.

```Java
Cookie[] cookies = VaadinService.getCurrentRequest().getCookies();
new Thread(() -> {
    System.out.println(Arrays.toString(cookies));
}).start();
```

**Closed by mehdi-vaadin** 2019-10-22 08:47 UTC
Labels: waiting for author

**Comment by letrthang** [comment] 2019-10-22 08:54
Sure, thanks
