### ISSUE TITLE
Navigation state renderer should resolve dynamic routes

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4883] opened 2018-12-18 12:45 UTC
At the `getNavigationEvent` uses the static method `Router.resolve` which requires a navigation target class with an `@Route` annotation.

This should be changed so that the url is gotten from the registry using `getTargetUrl(Class<? extends Component>)`.

**Comment by denis-anisimov** [comment] 2019-02-01 11:04
Looks like this is a duplicate of already fixed ticket: there is no `getNavigationEvent` in the `NavigationStateRenderer` class and `Router::resolve`  is deprecated and not used anymore from anywhere.

**Closed by denis-anisimov** 2019-02-01 11:04 UTC
Labels: bug, routing
