### ISSUE TITLE
theme-name.generated.js should be created to /frontend/generated/ with Flow 2.6+

### ISSUE THREAD

**Issue by chetex** [vaadin/flow#11180] opened 2021-06-08 11:16 UTC
### Description of the bug / feature
 - My objective is create a custom theme in an separate maven project, and join by a dependency in the pom.
### Minimal reproducible example
 - For that purpose I followed these steps...
   (1) Go to https://start.vaadin.com/ and create new initializr project with and example
   (2) Create new maven project in my own environment and following vaadin doc specification to create a package...
https://vaadin.com/docs/v14/flow/styling/custom-theme-packaging . Theme project is attached here in the issue.
   (3) Maven clean-install in the theme project, and clean-install in the initializr app created.
   (4) Run everything with Spring boot
### Expected behavior
 - With the initializr app, everything was perfect and theme was loading and showing ok.
### Actual behavior
 - In my own project, I'm using as well this maven project theme, but I'm getting following error...
_TypeError: can't access property "appendChild", e.shadowRoot is null_

![image](https://user-images.githubusercontent.com/3778410/121176018-07e61e00-c85c-11eb-8f7d-1512064d8f2f.png)

could be is something related with Lumo javascript, or I'm not loading properly lumo javascript clases?

I have also described the issue here in stackoverflow...

https://stackoverflow.com/questions/67874325/why-my-own-theme-does-not-work-with-vaadin-14?noredirect=1#comment119988225_67874325

### Versions:
    - Vaadin / Flow version: 14.6.2 (boht, my project, and theme project)
    - Java version: 11
    - OS version: Windows 10 profesional
    - Browser version (if applicable): Chrome Version 91.0.4472.77 (Official Build) (64-bit)
    - Application Server (if applicable):
    - IDE (if applicable): Eclipse

I will atach projects here...

[eo-vaadin-alonetheme.zip](https://github.com/vaadin/flow/files/6615961/eo-vaadin-alonetheme.zip)

In my project (I can't upload here, is a company project)... I just add to pom.xml...

`<dependency>
 			<groupId>com.vaadin.themes</groupId>
  			<artifactId>eo-vaadin-alonethemes</artifactId>
    		<version>0.0.1-SNAPSHOT</version>
		</dependency>`

and in the class I changed ... 

_@Theme(Lumo.class)_

to

_@Theme(themeFolder = "eo-vaadin-orange")_

**Comment by pleku** [comment] 2021-06-08 13:16
> Also the [theme-name].generated.js should not be added to the package.

The issue is exactly this - after removing the generated files, I can install and reuse the themes in another project.

We should fix the `2.6+` version of Flow to generate the files under `frontend/generated` to avoid causing this issue for the users, like it is done for version `6.0+`.

**Comment by chetex** [comment] 2021-06-08 14:01
Thank you very mucho @pekka. I have just remove this file. Then clean-install the theme project. Clean-install my project. I also tested in my ".m2" directory in local, that the theme-generated file is not added. Run my project, but still got this error.... I tried deleting the theme-generated files also moving to "frontend/generated" folder. Any idea?

**Comment by chetex** [comment] 2021-06-08 15:34
Hello,
The bug is only happening in Firefox developer edition (also in firefox)...
- Browser version (if applicable): 90.0b4 (64-bit)
Chrome browser and Edge works fine.

**Comment by Haprog** [comment] 2021-06-08 18:09
@chetex That seems to be a beta version of Firefox which might have some issues that will be solved before stable. Can you try if it works in latest stable Firefox which seems to be Firefox 89 at the moment?

**Comment by chetex** [comment] 2021-06-09 11:23
Hi @Haprog 

With the latest version of Firefox occurs the same thing... Firefox : 89.0 (64-bit)

**Comment by pleku** [comment] 2021-06-09 13:14
To me using Firefox 89.0 (64-bit) on Windows 10, both themes work out fine.

![Screenshot 2021-06-09 161119](https://user-images.githubusercontent.com/1478381/121360837-6fc06580-c93d-11eb-912d-f4d083437001.png)

I wonder if it is something with the project that you're consuming the themes in ? 
Anyway, it might be better to create a new issue that is specific to Firefox failing for consuming the theme in a project. You could also test if it fails for Firefox when you just have the theme files inside the same project @chetex ?

For now, this issue would be about addressing the problem with the generated theme file location for Vaadin 14-series.

**Comment by chetex** [comment] 2021-06-10 15:09
Hi Pleku,

I have just tested in initializr example downloaded from https://start.vaadin.com/app/ and you are right, everything works fine in firefox latest version. Perhaps it is something related with my project. Then I'm going to ckeck it and send feedback if I find something.

Thank your

**Comment by caalador** [comment] 2021-09-13 06:36
Generated theme is moved in 2.7 so I'm closing this ticket as resolved.
If there was anything specific failing in the custom theme for FireFox please open a new ticket with steps. (and a minimal project if possible)

**Closed by caalador** 2021-09-13 06:36 UTC
Labels: bug, theming, workaround, Impact: High, Severity: Major, Severity: Minor, target/2.6, target/2.7, Released with Platform 14.7.0.alpha3, prerelease version for platform 14.7.0
