### ISSUE TITLE
readbean only on filled in values

### ISSUE THREAD

**Issue by Braus** [vaadin/flow#7628] opened 2020-02-19 10:03 UTC
- Description of the bug
Binder cannot handle null values
- Minimal reproducible example
call `readBean` on  binder which has a null value
- Expected behavior
That `readBean` will just skip the null values in the form
- Actual behavior
the binder throws an error which states you should input a dummy value instead of null.

I have an application with quite alot of forms. Because the binder cannot read 'invalid' beans I'm forced to manually map the bean to the fields. This costs quite alot of time because my forms are quite big and complex. It would save large amounts of time if this could get fixed.

- Versions:
    - Vaadin / Flow version
14.0.13

**Comment by mehdi-vaadin** [comment] 2020-02-24 15:48
@Braus thank you for reporting this issue. However, you should provide a minimal piece of code that helps us reproduce the incorrect behavior you mentioned. Without that, we can't proceed further. Could you add the code and explain what exactly you expect?

**Comment by Braus** [comment] 2020-02-26 08:12
I expect that the following will write an invalid bean regardless whether it is invalid or not:
Unfortunately it throws an error when writing an invalid bean

`binder.writeBean(bean);`

I expect that the following throws an error if invalid, this happens:

`writeBeanIfValid(result);`


Example:

Where VM stands for a random ViewModel

`Binder<VM> binder;`

Where there are some values in the ViewModel:

```
    @NotEmpty
    private String someValue;
```
Then binding the bean like:

`binder.bindInstanceFields(this);`

And then doing this:

`binder.writeBean(bean); `


An invalid bean in my view is a bean which has a value which is not correct according to it's binding/annotation, like empty or null.

**Comment by pleku** [comment] 2020-03-10 09:54
The javadocs for `readBean` don't say anything about `null` values in the given bean.

```
     * Reads the bound property values from the given bean to the corresponding
     * fields.
     * <p>
     * The bean is not otherwise associated with this binder; in particular its
     * property values are not bound to the field value changes. To achieve
     * that, use {@link #setBean(Object)}.
     *
     * @see #setBean(Object)
     * @see #writeBeanIfValid(Object)
     * @see #writeBean(Object)
     *
     * @param bean
     *            the bean whose property values to read or {@code null} to
     *            clear bound fields
```
Thus I would now initially claim this is a bug. If later there is discovered a good reason why it should keep on working like it does now, then we should probably add a feature for this.

**Comment by denis-anisimov** [comment] 2020-03-12 13:14
I'm sorry.
I don't understand anything here....

It seems there is a mess with various issues and no any exact description.
So I don't have an understanding what the bug is and what is wrong.........

Description says: `readbean only on filled in values`.

Minimal reproducible example says : `call readBean on binder which has a null value`.

Unfortunately this is not a minimal reproducible example.
Because this is not an example. 

The example is a piece of code or a ready project which can be created on top of https://github.com/vaadin/skeleton-starter-flow.

Expected behavior says: `That readBean will just skip the null values in the form`.
I can't  understand the behavior without the example.

Actual behavior says: `the binder throws an error which states you should input a dummy value instead of null.`.

Can't understand the  behavior without the example. Which error ?
Is an exception thrown ? Which exception ? At which point ?

>I expect that the following will write an invalid bean regardless whether it is invalid or not:
Unfortunately it throws an error when writing an invalid bean

`binder.writeBean(bean);`

The original ticket is about `readBean` , but here  it's about `writeBean` ?

>I expect that the following throws an error if invalid, this happens:

`writeBeanIfValid(result);` 

or it's about `writeBeanIfValid` ?

The exact example would give the answers to all questions.

I still don't understand the problem but if the problem is with `write` methods then javadocs for _both_ methods say:

```
Writes changes from the bound fields to the given bean if all validators
    (binding and bean level) pass.
```

So unfortunately you can't write invalid bean ever.
There is no any functionality which allows you to write an invalid bean.
That may be an issue but this is not a bug. This is done by design.

The only difference between `writeBean`  and `writeBeanIfValid`  : one throws a  checked exception , another one doesn't throw anything but returns a boolean.

Neither of them gives a way to write an invalid bean.

If this ticket is about impossibility to write an invalid bean then please clarify it.
That can be considered as an enhancement.

If this ticket is about totally different issue then please clarify what it's about.

**Comment by Braus** [comment] 2020-03-12 13:42
The readbean function seems to work now. I just tested it again. Guess the bug has been removed somewhere down the road. Only thing that needs to be resolved on my end is setting some .setitems() before reading the bean. Nothing special.

The write problems persists though. But I understand you see it as a seperate issue/feature.

**Comment by denis-anisimov** [comment] 2020-03-12 13:49
Yes, if `write`  is an issue for you then please make a separate ticket please.
`write`  behavior is not a bug even though I agree that sometimes it's inconvenient that there is no any way to write invalid bean.
But it has been designed like this initially. And there are serious obstacles to make it work in fact:
if some fields uses converters then sometimes it's not possible to convert a value using a converter.
Such situation is considered as a validation failure and it's technically not possible to write an invalid bean.

So term "invalid" required clarification.

**Comment by denis-anisimov** [comment] 2020-03-12 13:49
I'm closing this issue as resolved.

**Closed by denis-anisimov** 2020-03-12 13:49 UTC
Labels: Impact: High, Severity: Major, binder, bug, waiting for author

**Comment by Braus** [comment] 2020-03-12 13:57
I forgot to deploy my build so I didn't see the result.
When I call readbean i get:
There was an exception while trying to navigate to 'x/x/x' with the exception message 'A field of type com.vaadin.flow.component.textfield.TextField didn't accept a null value. If null values are expected, then configure a null representation for the binding.'

**Comment by Braus** [comment] 2020-03-12 13:57
I get different ones if I use different components.

**Comment by denis-anisimov** [comment] 2020-03-12 14:06
>here was an exception while trying to navigate to 'x/x/x' with the exception message 'A field of type com.vaadin.flow.component.textfield.TextField didn't accept a null value. If null values are expected, then configure a null representation for the binding.'

And this is true: 
`TextField` doesn't accept `null` value.

You should use `Binder::forField::withNullRepresentation("")`

**Comment by Braus** [comment] 2020-03-12 14:08
Yes I see this alternative. But setting this for every textfield in the form is almost as much work as setting them manually. I have forms with alot of fields so that wouldn't be much of an improvement.

But thanks for thinking along.

**Comment by denis-anisimov** [comment] 2020-03-12 14:31
`forField` has javadocs:

```
 <p>
     * <strong>Note:</strong> Not all {@link HasValue} implementations support
     * passing {@code null} as the value. For these the Binder will
     * automatically change {@code null} to a null representation provided by
     * {@link HasValue#getEmptyValue()}. This conversion is one-way only, if you
     * want to have a two-way mapping back to {@code null}, use
     * {@link BindingBuilder#withNullRepresentation(Object)}.
```

I expect that any binding method also preserve this behavior.
So there should not be an exception in case of null value.

This example works for me without any exception:

```
public class MainView extends VerticalLayout {

    public static class Bean {
        private String name;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

    }

    private TextField name = new TextField();

    public MainView() {
        Binder<Bean> binder = new Binder<>(Bean.class);
        binder.bindInstanceFields(this);
        binder.readBean(new Bean());
        add(name);
    }
}
```
