### ISSUE TITLE
Change text of a span during attach cycle leads to exception

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4620] opened 2018-09-19 06:47 UTC
Vaadin version 10.0.5:

I have a component, that contains a `Span` as text container. The span is added to the component at construction time with an initial text (`new Span("my text")`).

During the attachment process (in method `onAttach()`) this text is changed via `span.setText("new text")`.

This leads to the following exceptions:
```
java.lang.IllegalArgumentException: Not in the list
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:113)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:329)
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:565)
	at com.vaadin.flow.dom.Node.insertChild(Node.java:246)
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
	at com.vaadin.flow.dom.Element.setTextContent(Element.java:989)
	at com.vaadin.flow.dom.Element.setText(Element.java:974)
	at com.vaadin.flow.component.HasText.setText(HasText.java:42)
...

java.lang.IllegalStateException: Unregistered node was not found based on its id. The tree is most likely corrupted.
	at com.vaadin.flow.internal.StateTree.unregister(StateTree.java:205)
	at com.vaadin.flow.internal.StateNode.handleOnDetach(StateNode.java:508)
	at com.vaadin.flow.internal.StateNode.visitNodeTreeBottomUp(StateNode.java:459)
	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:251)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:206)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.detatchPotentialChild(NodeFeature.java:95)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.remove(StateNodeNodeList.java:65)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.remove(ElementChildrenList.java:52)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:100)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:349)
	at com.vaadin.flow.component.internal.UIInternals.removeServerSideChildrenFromUI(UIInternals.java:684)
	at com.vaadin.flow.component.internal.UIInternals.showRouteTarget(UIInternals.java:671)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:204)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:49)
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:240)
	at com.vaadin.flow.router.Router.navigate(Router.java:175)
	at com.vaadin.flow.component.UI.navigate(UI.java:772)
	at com.vaadin.flow.component.UI.navigate(UI.java:735)
...
```

**Comment by Legioth** [comment] 2018-09-19 06:54
Duplicate of #4209

**Comment by mvysny** [comment] 2018-12-07 17:03
This bug also manifests a lot when you replace Pekka's Checkbox Group with Vaadin 12 one in the Bookstore Example app.

**Comment by Legioth** [comment] 2018-12-14 12:13
@mvysny Is this also the case when using a version including the fix for #4209, i.e. starting from version 1.2.1?

**Comment by mvysny** [comment] 2018-12-21 07:20
Yes, unfortunately. I'm using flow 1.2.3 and I get the following stacktrace:
```
java.lang.IllegalArgumentException: Not in the list
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:123)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:332)
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:568)
	at com.vaadin.flow.dom.Node.insertChild(Node.java:249)
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
	at com.vaadin.flow.dom.Element.setTextContent(Element.java:992)
	at com.vaadin.flow.dom.Element.setText(Element.java:977)
	at com.vaadin.flow.component.checkbox.Checkbox.setLabel(Checkbox.java:120)
	at com.vaadin.flow.component.checkbox.CheckboxGroup.updateCheckbox(CheckboxGroup.java:324)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.vaadin.flow.component.checkbox.CheckboxGroup.refreshCheckboxes(CheckboxGroup.java:307)
	at com.vaadin.flow.component.checkbox.CheckboxGroup.onEnabledStateChanged(CheckboxGroup.java:146)
	at com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:277)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:107)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:343)
	at com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:769)
	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:333)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:272)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.detatchPotentialChild(NodeFeature.java:95)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.remove(StateNodeNodeList.java:65)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.remove(ElementChildrenList.java:52)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:332)
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:568)
	at com.vaadin.flow.component.internal.UIInternals.removeFromParent(UIInternals.java:712)
	at com.vaadin.flow.component.internal.UIInternals.showRouteTarget(UIInternals.java:660)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:204)
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:221)
	at com.vaadin.flow.router.Router.navigate(Router.java:192)
	at com.vaadin.flow.component.UI.navigate(UI.java:776)
	at com.vaadin.flow.component.UI.navigate(UI.java:739)
	at eu.vok.bookstore.authentication.LoginScreen.login(LoginScreen.kt:77)
	at eu.vok.bookstore.authentication.LoginScreen.access$login(LoginScreen.kt:23)
	at eu.vok.bookstore.authentication.LoginScreen$2$1$3$1$1.invoke(LoginScreen.kt:62)
	at eu.vok.bookstore.authentication.LoginScreen$2$1$3$1$1.invoke(LoginScreen.kt:23)
	at com.github.mvysny.karibudsl.v10.VaadinComponentsKt$sam$com_vaadin_flow_component_ComponentEventListener$0.onComponentEvent(VaadinComponents.kt)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:396)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:396)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:379)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:368)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:368)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:310)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1533)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:227)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```
You can see the stacktrace here: https://bookstore-vok.herokuapp.com/
What's weird the stacktrace only flashes briefly, but then the app seems to be working :confused: 
The sources of the app are here: https://github.com/mvysny/bookstore-vok the bug is reproducible in master dcf5c97038eee0b5c29441d48a8a14483d785cf1

**Comment by denis-anisimov** [comment] 2019-10-15 05:42
Duplicate of #4209 and it's fixed. Can't reproduce anymore.

**Closed by denis-anisimov** 2019-10-15 05:42 UTC
