### ISSUE TITLE
VaadinRequest and VaadinServletRequest do not produce correct current path

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow#17602] opened 2023-09-12 08:49 UTC
### Description of the bug

With starter projects calling `VaadinRequest.getCurrent().getPathInfo()` or `VaadinServletRequest.getCurrent().getPathInfo()` produces incorrect result.
This also affects what cookies are available, for example, if I were to create a cookie with path "/about" and add it to response, after navigating to `/about` the cookie is not available through `VaadinRequest` or `VaadinServletRequest` `request.getCurrent().getCookies()` APIs. 
This was working as expected in V14.

Example, entering `/about` view, in `afterNavigation` method I called these pathInfo APIs on different versions:
on V24 and V23 results in:
> Path should be /about, but is: /

on V14:
> Path should be /about, and it is: /about

### Expected behavior

Like in V14: 
* `getPathInfo()` returns the path that we're on
* cookies for that path are available through `VaadinRequest.getCurrent().getCookies()` 

### Minimal reproducible example

```
@PageTitle("About")
@Route(value = "about")
@PermitAll
public class AboutView extends VerticalLayout implements AfterNavigationObserver {

    public AboutView() {
        add(new H2("This place intentionally left empty"));
        add(new Paragraph("It’s a place where you can grow your own UI 🤗"));
    }

    @Override
    public void afterNavigation(AfterNavigationEvent event) {
        System.out.println("Path should be /about, but is: " + VaadinRequest.getCurrent().getPathInfo());
        System.out.println("VaadinServletRequest Path should be /about, but is: " + VaadinServletRequest.getCurrent().getPathInfo());
    }
}
```

### Versions

- Vaadin / Flow version: V23.3, V24
- Java version: 17
- OS version: Windows 11
- Browser version (if applicable): Chrome 116.0.5845.187, Firefox 117.0

**Comment by mshabarov** [comment] 2023-09-12 10:17
The difference in `getPathInfo` result can be related to how navigation is done in V14 and V15+.
We have to check, but Vaadin Router sends the path in a payload of post request, so that the path is not visible for servlet on the server.
Need to debug and compare the logic in V14 vs V15+. Until then, not sure 100% this is a bug, however different behaviour looks incorrect, or at least have to be documented as a breaking change with a recommended workaround.

**Comment by TatuLund** [comment] 2023-09-13 05:58
@mshabarov could the root cause be the same as with the other issue here https://github.com/vaadin/flow/issues/17528

**Comment by tepi** [comment] 2023-09-26 11:47
Tested this using both RouterLink and Anchor (pointed to the About page) with 14.10.7 and 24.1.10.

Behavior with the **RouterLink** navigation seems to be identical.

**14.10.7:**
```
Path should be /about, but is: /
VaadinServletRequest Path should be /about, but is: /
```
**24.1.10:**
```
Path should be /about, but is: /
VaadinServletRequest Path should be /about, but is: /
```

However, behavior with **Anchor** navigation (or direct load of About page URL) is not identical.
**14.10.7:**
```
Path should be /about, but is: /about
VaadinServletRequest Path should be /about, but is: /about
```
**24.1.10:**
```
Path should be /about, but is: /
VaadinServletRequest Path should be /about, but is: /
```

The change in the latter behavior is most likely due to the fact that v24 does an extra xhr request when loading the page, and that request is always pointing to the root context path with no route added. In v14, the initial uidl is delivered as response to the original request and so the route part of the request path will be available.

Related ticket: https://github.com/vaadin/flow/issues/17428

**Comment by tepi** [comment] 2023-09-28 06:01
Tested the cookie setting too. There seems to be no differences in that functionality between v14 and v24.

I added the following to AboutView's `afterNavigation` method:
```
Cookie cookie = new Cookie("testcookie", "testvalue");
cookie.setPath("/about");
VaadinResponse.getCurrent().addCookie(cookie);
```
After this, if I navigate to AboutView via RouterLink, the cookie is not set in either v14 or v24.

If I navigate to AboutView via Anchor (or directly load the about view url), the cookie is set in both v14 and v24.

@HerbertsVaadin Could you provide more info on how the use case with cookies should work?

**Comment by HerbertsVaadin** [comment] 2023-09-29 06:55
@tepi in our case we navigate with `UI.getCurrent().getPage().setLocation("/secondary");` 
Tested with this code for both V14 (without `@PermitAll`) and V24

```
@PageTitle("About")
@Route(value = "about", layout = MainLayout.class)
@PermitAll
public class AboutView extends VerticalLayout {

    public AboutView() {
        add(new Paragraph("View to setup a cookie and redirect to secondary page"));

        var button = new Button("Secondary view");
        button.addClickListener(event -> moveToSecondaryView());
        add(button);
    }

    private void moveToSecondaryView() {
        addCookie((HttpServletResponse) VaadinResponse.getCurrent(), "SecondaryView",
                DateTimeFormatter.ofPattern("yyyy-MM-dd'x'HH:mm:ss").format(LocalDateTime.now()), "/secondary");
        addCookie((HttpServletResponse) VaadinResponse.getCurrent(), "SecondaryViewNoPath",
                DateTimeFormatter.ofPattern("yyyy-MM-dd'x'HH:mm:ss").format(LocalDateTime.now()), null);
        UI.getCurrent().getPage().setLocation("/secondary");
    }

    public static void addCookie(HttpServletResponse response, String key, String value, String path) {
        Cookie cookie = new Cookie(key, value);
        cookie.setMaxAge(-1); // deleted on browser exit
        cookie.setPath(path);
        cookie.setSecure(true);
        response.addCookie(cookie);
    }
}
```

```
@PageTitle("Secondary View")
@Route(value = "secondary", layout = MainLayout.class)
@PermitAll
public class SecondaryView extends VerticalLayout implements AfterNavigationObserver {

    Div cookieContainer = new Div();
    Div noPathCookieContainer = new Div();

    public SecondaryView() {
        setSpacing(false);

        var text = new Span("Current cookie value:");
        var noPathText = new Span("Current no path cookie value:");
        add(text, cookieContainer, noPathText, noPathCookieContainer);
    }

    @Override
    public void afterNavigation(AfterNavigationEvent event) {
        var cookie = getCookieValue("SecondaryView");
        var noPathCookie = getCookieValue("SecondaryViewNoPath");
        System.out.println("SecondaryView cookie: " + cookie + ", SecondaryViewNoPath:"+ noPathCookie);
        cookieContainer.setText(cookie);
        noPathCookieContainer.setText(noPathCookie);
    }

    public static String getCookieValue(String key) {
        var request = (HttpServletRequest) VaadinRequest.getCurrent();

        return Optional.ofNullable(request.getCookies()).stream().flatMap(Stream::of)
                .filter(cookie -> key.equals(cookie.getName()))
                .findFirst().map(Cookie::getValue).orElse(null);
    }
}
```
V14 Result:
![image](https://github.com/vaadin/flow/assets/80950643/d3179d5b-20ea-40d6-ab95-70baffbcbe27)


V24 Result:
![image](https://github.com/vaadin/flow/assets/80950643/1ac93311-66b6-4e16-bda7-5e47ce4df5e0)

**Comment by mshabarov** [comment] 2023-10-12 14:29
The workaround described [here](https://github.com/vaadin/flow/issues/17602#issuecomment-1740933903) doesn't work, because service init listener is invoked AFTER the UI is initialised and `afterNavigation` callback is called for the secondary view.

However, if you just switch to the eager mode for [your example](https://github.com/vaadin/flow/issues/17602#issuecomment-1740395471), you should see a proper value for both cookies and also path info returns "/secondary":

```
<configuration>
     <eagerServerLoad>true</eagerServerLoad>
</configuration>
```

My output:
```
Current cookie value:
2023-10-12x17:25:13
Current no path cookie value:
2023-10-12x17:25:13
Path Info:
/secondary
```

Please check the starter project with your example and eager mode workaround https://github.com/vaadin/skeleton-starter-flow-spring/tree/workaround-17602 .

**Comment by mshabarov** [comment] 2023-10-25 07:29
Documentation update is ready, I propose to close this issue. Please comment if you have further issue.

**Comment by TatuLund** [comment] 2023-12-08 07:43
I tried this (eagerServerLoad = true) with Vaadin 24.3.0.rc1 out with request handler printing out path info and request headers

```
@Component
public class ApplicationServiceInitListener
        implements VaadinServiceInitListener {
    @Override
    public void serviceInit(final ServiceInitEvent serviceInitEvent) {
        serviceInitEvent.addRequestHandler((session, request, response) -> {
            HttpServletRequest req = ((HttpServletRequest) request);
            final String fullUrl = req.getPathInfo();
            System.out.println("PathInfo: " + fullUrl);
            Iterator<String> headers = req.getHeaderNames().asIterator();
            while (headers.hasNext()) {
                String header = headers.next();
                System.out.println("  " + header + ":" + req.getHeader(header));
            }
            return false;
        });
    }
}
```

The output is, which shows that in same cases the referer has the url with route, but not the path info. 

```
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:0
  sec-ch-ua:"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
  sec-ch-ua-platform:"Windows"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
  content-type:text/plain; charset=utf-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/badge
  accept-encoding:gzip, deflate, br
  accept-language:fi-FI,fi;q=0.9,en-US;q=0.8,en;q=0.7
```

**Comment by tepi** [comment] 2023-12-14 09:36
@TatuLund The original use case was about pathinfo being correct in the current vaadin request, after navigating to the view using `setLocation`. I confirmed this to be the case on 24.3.0 when `eagerServerLoad` is enabled.

I tried your use case and there (in dev mode) I get 14 requests when navigating from `hello` to `about` using `setLocation`:

```
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:337
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:337
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /about
  host:localhost:8080
  connection:keep-alive
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  sec-ch-ua-mobile:?0
  upgrade-insecure-requests:1
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  sec-ch-ua-platform:"macOS"
  sec-fetch-site:same-origin
  sec-fetch-mode:navigate
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:SecondaryView=2023-12-14x11:28:45; JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /about
  host:localhost:8080
  connection:keep-alive
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  sec-ch-ua-mobile:?0
  upgrade-insecure-requests:1
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  sec-ch-ua-platform:"macOS"
  sec-fetch-site:same-origin
  sec-fetch-mode:navigate
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:SecondaryView=2023-12-14x11:28:45; JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
Path should be /about, but is: /about
VaadinServletRequest Path should be /about, but is: /about
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:99
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:text/plain;charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:no-cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:99
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:text/plain;charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:no-cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /VAADIN/push
  host:localhost:8080
  connection:keep-alive
  content-length:0
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:text/plain;charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:no-cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /VAADIN/push
  host:localhost:8080
  connection:keep-alive
  content-length:0
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:text/plain;charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:no-cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/hello
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:439
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:439
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:503
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:503
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:230
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
PathInfo: /
  host:localhost:8080
  connection:keep-alive
  content-length:230
  sec-ch-ua:"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
  sec-ch-ua-platform:"macOS"
  sec-ch-ua-mobile:?0
  user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  content-type:application/json; charset=UTF-8
  accept:*/*
  origin:http://localhost:8080
  sec-fetch-site:same-origin
  sec-fetch-mode:cors
  sec-fetch-dest:empty
  referer:http://localhost:8080/about
  accept-encoding:gzip, deflate, br
  accept-language:en-GB,en-US;q=0.9,en;q=0.8,fi;q=0.7
  cookie:JSESSIONID=31D91FB52E9B29384A0DBE5737D0EEAB; SecondaryViewNoPath=2023-12-14x11:28:45
```

In this case, 2 of the 14 requests have the route in their pathinfo. Could you be more specific about which request(s) are you referring to that should have the route in the pathinfo? Or alternatively please provide a more concrete use case where the cookies / pathinfo is not working since the original use case in this issue seems to be working.

**Comment by tepi** [comment] 2024-01-03 15:24
Closing this issue since the original use case was about `VaadinRequest.getCurrent().getPathInfo()` returning the full URL including the route part, after navigating to the said route using `setLocation`. I confirmed this to be the case on 24.3.0 when `eagerServerLoad` is enabled.

There is an [issue remaining](https://github.com/vaadin/flow/issues/18395) about getting the route included into `pathInfo` on further navigation xhr requests, e.g. when using a `RouterLink` or programmatic navigation. Currently the `pathInfo` will point to the context root and does not include the route part. [This issue](https://github.com/vaadin/flow/issues/10045) is also somewhat related, but would not solve all the issues.

Another issue that also touches this one a bit is that currently it's impossible or at least difficult to use URL hashes for navigation (or much else). See e.g. https://github.com/vaadin/flow/issues/2742, https://github.com/vaadin/flow/issues/1215, https://github.com/vaadin/flow/issues/6646 and https://github.com/vaadin/flow/issues/13404 for details. In practice this makes it impossible to have Vaadin 8 -style navigation URLs on Flow, and thus also breaks backwards compatibility of bookmarked URLs in version upgrades.

**Closed by tepi** 2024-01-03 15:24 UTC
Labels: investigation, blocked, BFP
