### ISSUE TITLE
lit-html/is-server.js cannot be found caused by missing version for lit

### ISSUE THREAD

**Issue by joergdev** [vaadin/flow#15007] opened 2022-11-04 21:32 UTC
### Describe the bug

Getting this error:

Webpack build failed with errors:
ERROR in ../node_modules/.pnpm/lit@2.4.0/node_modules/lit/index.js
Module not found: Error: Can't resolve 'lit-html/is-server.js' in '....\node_modules\.pnpm\lit@2.4.0\node_modules\lit'
 @ ../node_modules/.pnpm/lit@2.4.0/node_modules/lit/index.js 1:87-122 1:87-122
 @ ../node_modules/@vaadin/flow-frontend/@f0rce/lit-ace/lit-ace.js
 @ ../target/frontend/generated-flow-imports.js

Caused by:

There is no version provided (in package.json) for "lit" so the newest version (lit 2.4.0) is used.
In lit 2.4.0 index.js the file lit-html/is-server.js should be loaded but doesnt exists because lit-html is provided with version 1.4.1 (in package.json) but is-server.js exists only from version 2.4.0.

### Expected-behavior

Versions should work together, lit should be explicit provided with version 2.3.0 (as it is in newest vaadin version).

### Reproduction

Allways

### System Info

Windows 10, Vaadin 14.8.20 (also with 14.9.1), Google Chrome 107.0.5304.88

**Comment by joergdev** [comment] 2022-11-06 21:46
Workaround: Replacing all files in lit folder with files from version < 2.4.0 worked for me.

**Comment by TatuLund** [comment] 2022-11-07 05:56
>  ../node_modules/@vaadin/flow-frontend/@f0rce/lit-ace/lit-ace.js

Based on this you are using https://vaadin.com/directory/component/ace

Are you using version 2.3.1 (for Vaadin 14) or 3.4.2 (for Vaadin 23)?

**Comment by joergdev** [comment] 2022-11-07 08:30
> > ../node_modules/@vaadin/flow-frontend/@f0rce/lit-ace/lit-ace.js
> 
> Based on this you are using https://vaadin.com/directory/component/ace
> 
> Are you using version 2.3.1 (for Vaadin 14) or 3.4.2 (for Vaadin 23)?

=> 2.3.1

**Comment by INPUTsys-Chris** [comment] 2022-11-28 15:56
Happened to me as well.
An update to 14.9.2 did not work due to problems with License.ts, so I did a Vaadin Dance.

After that, this error appeared.
Could work around by overriding settings in package.json.

**Comment by mcollovati** [comment] 2023-01-18 10:45
I tried to reproduce the issue with Vaadin 14.8.20 and 14.9.1 in a local project (with the ace add-on as a dependency) but I never get errors. Lit version in node_modules is 2.6.1, and in package.json I can see  `lit-element: 2.5.1` and `lit-html: 1.4.1`.

Could you please provide an example project that reproduces the problem?

**Comment by INPUTsys-Chris** [comment] 2023-01-30 10:37
Seems to happen for me only in pnpm environments:

- Download plain Java Vaadin 14 starter: https://github.com/vaadin/skeleton-starter-flow/archive/v14.zip
- Add: 
                <configuration>
                    <pnpmEnable>true</pnpmEnable>
                </configuration>
  to both <vaadin-maven-plugin> plugin sections.
- Add Ace editor dependency:
        <dependency>
            <groupId>de.f0rce</groupId>
            <artifactId>ace</artifactId>
            <version>2.3.1</version>
        </dependency>

- Reimport maven
- mvn jetty:run

I also cleaned .pnpm-store directory and it also happens.

**Comment by mcollovati** [comment] 2023-01-30 14:13
Thanks @INPUTsys-Chris, I confirm I can reproduce the issue but only using PNPM

**Comment by mcollovati** [comment] 2023-04-14 11:24
Related issue on Ace Editor for Vaadin add-on: https://github.com/F0rce/ace/issues/39

**Comment by fschoning** [comment] 2023-10-05 09:30
I am getting this same error with a project using Vaadin 23.2.25. I do not know what changed in my build to cause this error to materialise, but I recently downgraded from Vaadin Pro subscription to no subscription.

The following node versions are pulled in:
    "lit": "2.6.1",
    "lit-element": "^2.2.1",
    "lit-html": "^1.1.2",

As the original poster commented, is-server.js is not in lit-html v1.1.2.

As this Vite build is all a bit of a black box for me, how can I trace where the lit-html v1.1.2 is being pulled in?

Is there some kind of workaround for this error?

> [ERROR] [vite]: Rollup failed to resolve import "lit-html/is-server.js" from "node_modules/lit/index.js".
[ERROR] This is most likely unintended because it can break your application at runtime.
[ERROR] If you do want to externalize this module explicitly add it to
[ERROR] `build.rollupOptions.external`
[ERROR] error during build:
[ERROR] Error: [vite]: Rollup failed to resolve import "lit-html/is-server.js" from "node_modules/lit/index.js".
[ERROR] This is most likely unintended because it can break your application at runtime.
[ERROR] If you do want to externalize this module explicitly add it to
[ERROR] `build.rollupOptions.external`
[ERROR]     at onRollupWarning (file:///G:/proj/example/app/node_modules/.pnpm/vite@3.2.7/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45909:19)
[ERROR]     at onwarn (file:///G:/proj/example/app/node_modules/.pnpm/vite@3.2.7/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45680:13)
[ERROR]     at Object.onwarn (file:///G:/proj/example/app/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
[ERROR]     at ModuleLoader.handleResolveId (file:///G:/proj/example/app/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
[ERROR]     at file:///G:/proj/example/app/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26

**Comment by mcollovati** [comment] 2023-10-05 09:58
Did you already try a `mvn vaadin:clean-frontend`?

**Comment by fschoning** [comment] 2023-10-05 10:52
Yes. No success.

**Comment by mcollovati** [comment] 2023-10-05 11:00
@fschoning do you use add-ons in your projects? If so, can you provide a list?

**Comment by mcollovati** [comment] 2023-10-05 11:03
@fschoning just to confirm, the Vaadin version you are using 23.**3**.25, not 23.**2**.25 as in your comment?

**Comment by fschoning** [comment] 2023-10-05 11:28
Yes, apologies it is 23.3.25.

Yes I use a lot of add ons - see below. However none of these have changed
versions since before the problem occurred with the exception of the Quill
Editor. I will try and remove it and rebuild.

Switching back to vaadin versions as far back as 23.3.19 does not fix the
problem.

Is there some way to trace where the node module dependency is pulled in?

        <dependency>
            <groupId>com.coachautomator</groupId>
            <artifactId>vaadincomponents</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>in.virit</groupId>
            <artifactId>viritin</artifactId>
            <version>${viritin.version}</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.olli</groupId>
            <artifactId>file-download-wrapper</artifactId>
            <version>6.0.0</version> 
            
        </dependency>

        <dependency>
            <groupId>org.vaadin.stefan</groupId>
            <artifactId>lazy-download-button</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>pl.unforgiven</groupId>
            <artifactId>superfields</artifactId>
            <version>0.17.0</version>
        </dependency>

This is a modified version of the add on to support quill delta format
files that I created.
        <dependency>
            <groupId>com.schoning</groupId>
            <artifactId>quill-editor</artifactId>
            <version>1.0.2</version>
            
        </dependency>

       <dependency>
            <groupId>org.parttio</groupId>
            <artifactId>line-awesome</artifactId>
            <version>1.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaddon</groupId>
            <artifactId>mediaquery</artifactId>
            <version>5.0.3</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.olli</groupId>
            <artifactId>clipboardhelper</artifactId>
            <version>1.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.stefan</groupId>
            <artifactId>fullcalendar2</artifactId>
            
            
            <version>4.1.6</version>
        </dependency>

        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>vaadin-css-grid</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>ch.carnet.kasparscherrer</groupId>
            <artifactId>scrolllayout</artifactId>
            <version>2.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.flowingcode.addons</groupId>
            <artifactId>font-awesome-iron-iconset</artifactId>
            <version>2.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin.componentfactory</groupId>
            <artifactId>togglebutton</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.addons.componentfactory</groupId>
            <artifactId>vcf-gridlayout</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>dev.mett.vaadin</groupId>
            <artifactId>tooltip</artifactId>
            <version>2.3.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>vaadin-css-grid</artifactId>
            <version>2.0.0</version>
        </dependency>

Kind regards,
Franz Schöning

**Comment by mcollovati** [comment] 2023-10-05 11:56
I think at least `dev.mett.vaadin:tooltip` should be upgraded to `3.1.0`

**Comment by mcollovati** [comment] 2023-10-05 12:07
Also, `com.github.appreciated:vaadin-css-grid` seems to target to Vaadin 14, so it could be one of the causes

**Comment by fschoning** [comment] 2023-10-05 13:35
Hi Marco,

Thanks for checking. I isolated the error to the quill editor component
that I forked from the add on directory. If I mock the editor then the
build succeeds.

The code for the editor is at https://github.com/fschoning/quill-editor

Is there something I am doing wrong in this fork?

Kind regards,
Franz Schöning

**Comment by mcollovati** [comment] 2023-10-05 14:03
You should probably update the `@NpmPackage` annotations for `lit-element` and `lit-html`  in `QuillEditorComponent`,
as it has been done in this fork https://github.com/Klaudeta/quill-editor/compare/master...ulrich-grossmann:quill-editor:master

**Comment by fschoning** [comment] 2023-10-05 14:27
Brilliant :-) You nailed it Marco. Build is fine now.

Thank you!

**Comment by mcollovati** [comment] 2023-10-05 15:15
I wonder if we can close this ticket, since the issue is on the add-on.
@mshabarov what do you think? Do you see any action we can take on the Flow side?

**Comment by INPUTsys-Chris** [comment] 2023-10-06 11:50
we moved on from pnpm to npm, so it's definitely not a problem for us anymore

**Comment by mshabarov** [comment] 2023-10-25 13:36
Closed, as nothing to fix on the Flow side.

**Closed by mshabarov** 2023-10-25 13:36 UTC
Labels: bug, investigation, workaround
