### ISSUE TITLE
Resources in frontend folder is not resolved if no servlet is mapped to context root

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#3301] opened 2018-01-11 14:33 UTC
Given: Two servlets are defined in the application, and none of them maps to the context root.
```
@WebServlet(urlPatterns = { "/app1/*"}, name = "MyServlet1", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false)
public class MyServlet1 extends VaadinServlet {
}
```
```
@WebServlet(urlPatterns = { "/app2/*"}, name = "MyServlet2", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false)
public class MyServlet2 extends VaadinServlet {
}
```
Expected: page can be load without problem

Result: Got 404 errors that resources from frontend folder cannot be found. But resources from VAADIN and webjars folder are loaded correctly.

Workaround: add /frontend/* to either urlPatterns in either MyServlet1 or MyServlet2. But since resources from VAADIN and webjars folders can be loaded, this makes it a bit inconsistent.

**Comment by haiwan** [comment] 2018-01-11 14:38
<img width="765" alt="screen shot 2018-01-11 at 16 37 56" src="https://user-images.githubusercontent.com/3388675/34830850-d8fee6d2-f6ed-11e7-8f67-d4336e6eeafe.png">

**Comment by pleku** [comment] 2018-02-16 11:10
Please add tests to our subcontext test module for this.

**Comment by denis-anisimov** [comment] 2018-02-21 10:28
Correction: 
- custom resources are correctly resolved from the frontend folder. So if I have my own template whose HTML file inside frontend folder inside web resources folder ( e.g. `src/main/webapp/frontend`) then this file is loaded correctly without issues. But its import `/frontend/bower_components/polymer/polymer-element.html` is loaded from the URL root ignoring servlet context and mapping.
- apparently the same happens with URL from web-jars: they are loaded ignoring servlet context and mapping.

**Comment by denis-anisimov** [comment] 2018-02-21 13:55
There are many aspects that are not clear and requires clarifications (may be should be available somewhere in tutorials).
- `/VAADIN/static/client` is the folder which is a part of `flow-client.jar` and it's available as a web resource. It means that this URL is handled by the Web server itself and doesn't require any handling form vaadin servlet. As a result regardless of mapping paths used in the custom servlets it always served from the servlet context path. And Flow doesn't handle this path anyhow.
- `src/main/webapp/` is also a part of static web resources paths. And everything there is also served by the Web server itself, not by the vaadin servlet. So when you have a servlet with a non-root mapping then it's your responsibility to care about correct URI used in the HTML import. See examples below. That's kind of not obvious and may be very confusing. I would say this should be clarified in the tutorials. The additional issue with that is the URI format which becomes more complicated since we started to use `frontend` schema by default for relative URLs.
- web jars introduce another issue: web jar URLs are never served as static web resources. They are always served by Flow vaadin servlet. That's why there is a difference between static web resource like `/VAADIN/static/client` or  resources in `src/main/webapp/` and web jar resources. As a result web jar resources should be relative to the servlet mapping path (only in this way it's possible to handle them by the vaadin servlet). There is a bug in web jars handling when not root mapping is used. I will fix it but developer should also care about the correct URI in HTML import.
- We are using URIs like this: `"frontend://bower_components/vaadin-text-field/src/vaadin-text-field.html"` which cannot technically work at all with servlets mapped to non-root paths. The latter URI is the same as `"context://frontend/bower_components/vaadin-text-field/src/vaadin-text-field.html"` and if servlet is mapped to `"foo"` then it's not able to handle ``"context://frontend"` .

So the examples are below.

The servlet class is:
```
@WebServlet(urlPatterns = {
        "/non-root/*" }, name = "NonRootMappingServlet", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false)
public class NonRootMappingServlet extends VaadinServlet {

}
```

The custom template:
```
@Route("")
@HtmlImport("context://non-root/frontend/frontend-template.html")
@Tag("frontend-template")
public class TemplateComponent extends PolymerTemplate<TemplateModel> {

}
```
And you have to put `frontend-template.html`  file into `src/main/webapp/non-root/frontend`.
In this case `frontend-template.html` may have import to `polymer-element` file in this way:
`<link rel="import" href="bower_components/polymer/polymer-element.html">`

Alternatively the file can be inside `src/main/webapp/frontend` (also works since Vaadin servlet is not involved here).
In this case the HTML import will be `@HtmlImport("frontend-template.html")` (much better than previous one which knows about: `context`, `non-root` mapping, `frontend` ) but import will be very ugly:
`<link rel="import" href="../non-root/frontend/bower_components/polymer/polymer-element.html">`

Now the string inside HTML file knows about URL mapping and `frontend`.
Normally we cannot control HTML file content (e.g. for web jar web components) so it's better to use URI inside `@HtmlImport`  attached in Java source files.

Now if I use custom web component than I have to care about `HtmlImport` correctness:
```
@Tag("paper-slider")
@HtmlImport("context://non-root/frontend/bower_components/paper-slider/paper-slider.html")
@Route("slider")
public class PaperSlider extends Component {
```
And then there is no need to modify HTML file (which will be in web jar and cannot be modified).

But that doesn't work at all with our components like TextField. As I mentioned it's declared as :
```
@Tag("vaadin-text-field")
@HtmlImport("frontend://bower_components/vaadin-text-field/src/vaadin-text-field.html")
public abstract class GeneratedVaadinTextField<R extends GeneratedVaadinTextField<R>>
```
So the URI resolves to the `context://bower_components` and will never be served by the vaadin servlet with non root mapping.

The solutions could be:
- Use dedicated vaadin servlet which cares about web jars (this is the way how it worked in old FW: you had to care about static resources by yourself if you have non root mapping(s)). This way it works e.g. in our root-context tests.
- We may modify meaning of the `HtmlImport` `frontend`  URIs. Now `frontend` schema is `context://frontend`. But to be able to handle this issue we should use `context://servlet_mapping/frontend`. Here `context` means context path. Or may be we should resolve frontend relatively to _servlet path_ not the _context path_.

**Comment by denis-anisimov** [comment] 2018-02-23 13:05
The PR for one aspect of this issue is here: #3590. It doesn't fix the issue but allows to make a fix for it.

I've extracted the main problem of this issue here: #3600.
And I close this ticket as a duplicate of #3600.

**Closed by denis-anisimov** 2018-02-23 13:05 UTC
Labels: bug
