### ISSUE TITLE
two-way binding does not work for array elements

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2413] opened 2017-09-17 06:02 UTC
When creating a template-based Flow component I want to have the server-side and the client-side models in sync. This is not the case for model properties that are lists of beans if Polymer's two-way data-binding is used in the template. In such cases updates to properties of the array elements do not get synced with the server-side. Consider the example below:

```html
<template is="dom-repeat" items="[[items]]">
    <div>
        <label>
            Title:
            <input type="text" value="{{item.title::input}}">
        </label>
        <label>
            <input type="checkbox" checked="{{item.completed::change}}">
            completed
        </label>
    </div>
</template>
```

The server-side model does not get updated when the client-side model changes.

A complete project that shows this issue is attached: 
[two-way-binding-inside-lists.zip](https://github.com/vaadin/flow/files/1308864/two-way-binding-inside-lists.zip)

**Comment by heruan** [comment] 2018-01-31 14:54
Also adding/removing items to the array properties do not get synced with the server-side (not just changes on the item properties).

**Comment by heruan** [comment] 2018-02-07 11:07
Seems like also one-way binding isn't working, e.g.

```java
@Route("people")
@Theme(Lumo.class)
public class People extends VerticalLayout {

    public People() {
        PeopleComponent people = new PeopleComponent();
        this.add(people);
        this.add(new Button("Add", event -> {
            people.getPeople().add(new Person("Foo"));
        }));
        this.add(new Button("Change", event -> {
            people.getPeople().forEach(p -> p.setName("Bar"));
        }));
    }

    public static class Person {

        String name;

        public Person() {
        }

        public Person(String name) {
            this.name = name;
        }

        public String getName() {
            return this.name;
        }

        public void setName(String name) {
            this.name = name;
        }

    }

    public static interface PeopleModel extends TemplateModel {

        List<Person> getPeople();

        void setPeople(List<Person> people);

    }

    @Tag("people-list")
    @HtmlImport("people-list.html")
    public static class PeopleComponent extends PolymerTemplate<PeopleModel> {

        public List<Person> getPeople() {
            return this.getModel().getPeople();
        }

    }

}
```

```html
<link rel="import" href="bower_components/polymer/polymer-element.html">

<dom-module id="people-list">
  <template>
    <ul>
      <template is="dom-repeat" items="{{people}}">
        <li><input value="{{item.name::change}}"></li>
      </template>
    </ul>
  </template>
  <script>
    class PeopleList extends Polymer.Element {

      static get is() {
        return 'people-list';
      }

      static get properties() {
        return {
          people: {
            type: Array,
            value: []
          }
        };
      }

    }
    customElements.define(PeopleList.is, PeopleList);
  </script>
</dom-module>
```

Clicking on "Add" and then "Change" I would expect the name on the field to change, but it doesn't. On the Network console I see the update coming from the server for the item, but it seems it doesn't get applied.

**Comment by Legioth** [comment] 2018-02-09 08:27
The only case that is expected to not work is structural changes to arrays from the client. For anything else, please create separate tickets.

**Comment by denis-anisimov** [comment] 2018-05-24 06:39
The original issue is a duplicate of #4091  actually.
Please see the IT test for PR which fixes it. It's almost the same as the example in the description.
I didn't read all other comments in the conversation.
If there are other issues with this please more tickets.

**Comment by denis-anisimov** [comment] 2018-05-24 07:07
I'm closing the ticket.
Please reopen if you think there are something uncovered in #4091 (hopefully the fix will be merged soon and you will be able to check the resulting functionality as well).

**Closed by denis-anisimov** 2018-05-24 07:07 UTC
Labels: feedback, template
