### ISSUE TITLE
2.4.4 release

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9712] opened 2020-12-22 08:21 UTC
There are some picks in already
- https://github.com/vaadin/flow/compare/2.4.3...2.4

And at least based on the labels, there are NO further picks needed but to be checked before release: https://github.com/vaadin/flow/pulls?q=is%3Apr+is%3Aclosed+label%3Atarget%2F2.4+label%3A%22to+be+cherry+picked%22

**Comment by caalador** [comment] 2020-12-22 08:35
Duplicate of #9701, but closing that in favor of this as this has more information

**Closed** 2020-12-24 15:07 UTC
Labels: release
