### ISSUE TITLE
JS Elements outside of frontend/src no longer found since Vaadin 14.10.4

### ISSUE THREAD

**Issue by bananer** [vaadin/flow#18237] opened 2023-12-06 20:03 UTC
### Describe the bug

I have a custom element definition, which is in `frontend/component`. After upgrading from 14.10.3 to 14.10.4 this only works if I move it to `frontend/src`. I could not find that requirement anywhere in the documentation.

### Reproduction

SetPasswordComponent.java
```java
package de.partnerpsychiatrie.server.therapist.ui;

import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.spring.annotation.SpringComponent;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;

@Tag("set-password")
@JsModule("./component/set-password.js")
@SpringComponent
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class SetPasswordComponent extends PolymerTemplate<SetPasswordComponent.SetPasswordModel> {
    // ...
}

```

frontend/component/set-password.js
```js
import {html, PolymerElement} from '@polymer/polymer/polymer-element.js';

class SetPassword extends PolymerElement {
    static get template() {
        return html`...`;
    }

    static get is() {
        return 'set-password';
    }
}

customElements.define(SetPassword.is, SetPassword);

```

### System Info

Throws `Couldn't find the definiton of the element with tag "set-password" in any template file declared using '@JSModule' annotations` on Vaadin 14.10.4

Works fine on Vaadin 14.10.3

**Comment by Artur-** [comment] 2023-12-07 07:15
The JsModule annotation says ./src/, is that a typo?

**Comment by bananer** [comment] 2023-12-07 08:52
> The JsModule annotation says ./src/, is that a typo?

Yes, seems I accidentally copied the fixed version. It was pointing to tbe actual path of the js file.

**Comment by mcollovati** [comment] 2023-12-11 07:21
I tried the given sample code on the [skeleton-starter-flow-spring](https://github.com/vaadin/skeleton-starter-flow-spring/tree/v14) project with Vaadin 14.10.11 and 14.10.4 but cannot reproduce.
The resource in `frontend/component/` is found and the component works both in development and production mode.

@bananer could you provide an example project that reproduces the issue?

**Comment by mshabarov** [comment] 2024-01-09 12:15
Closed as no answer provided within more than 2 weeks. If this issue is still valid for you, please comment.

**Closed by mshabarov** 2024-01-09 12:15 UTC
Labels: waiting for author
