### ISSUE TITLE
flow should ignore value-changed event when changing value from server side

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3350] opened 2018-01-19 07:28 UTC
In BFF we need workarounds in date-picker and combo-box to avoid binder marking beans as dirty when it sets the value the first time.

Note that Binder adds a value-changed listener to each field so as it can update its changed status, but the binder also sets the field value when initialising, hence binder receives an event after setting the value and it is always dirty.

We workaround this by extending the component and preventing execution of ValueChangeListener in certain circumstances, but this should be controlled in binder implementation.

For your reference, here is the workaround for the combo-box

```
/**
 * Workaround for combo-box to avoid receiving a value-changed event when the
 * value has been changed from server side. This prevents binder marking the
 * bean dirty.
 */
public class ComboBoxForBinder<T> extends ComboBox<T> {

  private T lastSetValue;

  @Override
  public void setValue(T value) {
    super.setValue(value);
    this.lastSetValue = value;
  }

  @Override
  public Registration addValueChangeListener(ValueChangeListener<ComboBox<T>, T> listener) {
    return super.addValueChangeListener(e -> {
      if (e.getValue() != null && !e.getValue().equals(lastSetValue) ||
          e.getValue() == null && lastSetValue != null) {
        listener.onComponentEvent(e);
      }
    });
  }
}
```

**Comment by pleku** [comment] 2018-02-05 09:23
Looks like `Binder` should be verifying is the event coming from client side or not.

BTW @manolo I think the workaround could just check for the `event.isFromClient()` instead of storing the previous value.

**Comment by manolo** [comment] 2018-02-07 07:30
The event is always from client (already tried that), so server updates client-side, and then client send the same event back.

**Comment by pleku** [comment] 2018-02-07 11:20
Ok, then it is probably the bug that causes default values to get updated unnecessarily  
https://github.com/vaadin/flow/issues/3496

**Comment by manolo** [comment] 2018-02-07 12:30
not sure that this is the same case. Here, values are not booleans but string, and default value in client side is different to the client side, e.g. client side might be empty and server side 'foo'. Binder sets correctly foo and client-side changes empty to 'foo' hence triggers the event that it's captured from server with the isFromClient true

**Comment by denis-anisimov** [comment] 2018-02-16 07:08
My initial impression on this issue: 
date-picker and combo-box has no logic which prevents firing events (and any action at all) if the current value is already the same as the new one.

Though I'm not sure why it happens on the server side: the value from the client side should not be sent to the server side if it's the same.

But normally we have logic for web components on the server side as well: if the current value is the same as a new value then don't do anything (e.g. text field has this logic).

Same thing should technically work on the client side (so there should not be client side update at all) but apparently it doesn't work.
Will see.

**Comment by manolo** [comment] 2018-02-16 09:05
They don't send the value change if the value is the same, I think the problem is an async issue. Server side sets the value in a request, then the client side notifies the server that the value changed in a different request, and eventually binder sets the field as dirty

**Comment by manolo** [comment] 2018-02-16 09:11
We had to change the algorithm to skip certain notifications because when client side set the value to null, if value is set again to the previous value it was ignored, so the new code for the workaround is 

```
/**
 * Workaround for date-picker to avoid receiving a value-changed event when the
 * value has been changed from server side. This prevents binder marking the
 * bean dirty. https://github.com/vaadin/flow/issues/3350
 */
public class ComboBoxForBinder<T> extends ComboBox<T> implements Focusable<ComboBox<T>> {

	private T lastNotifiedValue;
	private boolean setFromServer;

	@Override
	public void setValue(T value) {
		super.setValue(value);
		setFromServer = true;
	}

	@Override
	public Registration addValueChangeListener(ValueChangeListener<ComboBox<T>, T> listener) {
		return super.addValueChangeListener((ValueChangeListener<ComboBox<T>, T>) e -> {
			if (!setFromServer && (getValue() != null && !getValue().equals(lastNotifiedValue)
					|| e.getValue() == null && lastNotifiedValue != null)) {
				listener.onComponentEvent(e);
			}
			lastNotifiedValue = e.getValue();
			setFromServer = false;
		});
	}
}
```

**Comment by denis-anisimov** [comment] 2018-02-16 09:38
I guess it's closed accidentally

**Comment by denis-anisimov** [comment] 2018-02-19 10:53
This is not Flow bug.

This is bug in the components.
The `Combobox` issue is caused by the https://github.com/vaadin/vaadin-combo-box-flow/issues/48.
This issue is very specific for `Combobox` and the way how it sets the value in the component.

I will check what's going on with `DatePicker`.
This ticket will be closed most likely (may be another ticket for  `DatePicker` will be created).

It would be nice though to have the issues localized: the ticket is technically is invalid. It's not the issue in Flow. Instead there are two issues in two unrelated components. And the tickets for those components should have been created from the very beginning.

Please always keep in mind that issue creation requires some efforts from the submitter to localize the issue and create it properly.

**Comment by denis-anisimov** [comment] 2018-02-19 11:25
I'm pretty sure that the issue with `DatePicker` is caused by the https://github.com/vaadin/vaadin-date-picker-flow/issues/36.

And that's one more problem with this issue: it doesn't mention when `DatePicker` is work unexpectedly (always or only in some special cases). So there is no any localization of the issue and just some report like "something doesn't work". As a result I'm not even able to verify that the issue https://github.com/vaadin/vaadin-date-picker-flow/issues/36 is the real problem here.

I'm closing the issue.
Please verify that mentioned issues replace this one in reality.
If not: 
- Please create a ticket(s) with exact steps to reproduce (at the moment I'm not even sure that I understand what "dirty bean" means).
- Please localize the issues. So that it's possible to verify that the issue is fixed when we think that it's fixed.

**Closed by denis-anisimov** 2018-02-19 11:25 UTC
Labels: app starter, binder, bug

**Comment by manolo** [comment] 2018-02-19 16:43
It might be related with https://github.com/vaadin/vaadin-combo-box-flow/issues/53 .
Problem with`DatePicker` has gone, but I can still suffer the problem in `ComboBox` by using latest platform version.

I'll try to isolate the problem in a simpler project before re-opening this.
