### ISSUE TITLE
Make grid to be bundled without any warnings.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3320] opened 2018-01-16 10:51 UTC
@SomeoneToIgnore commented on [Mon Dec 04 2017](https://github.com/vaadin/flow-maven-plugin/issues/32)

When bundling a grid, a warning message pops up

```
[INFO]     class GridFlowSelectionColumnElement extends Vaadin.GridColumnElement {
[INFO]                                                  ~~~~~~~~~~~~~~~~~~~~~~~~
[INFO] 
[INFO] frontend/vaadin-grid-flow-selection-column.html(22,49) warning [unknown-superclass] - Unable to resolve superclass Vaadin.GridColumnElement
```

should be investigated if there is any impact on the grid functionality and find a way to fix/mute (if there's no impact) this.

---

@SomeoneToIgnore commented on [Tue Jan 02 2018](https://github.com/vaadin/flow-maven-plugin/issues/32#issuecomment-354715150)

Most probably fixed by https://github.com/vaadin/flow-maven-plugin/pull/34

**Comment by pleku** [comment] 2018-01-17 07:32
Duplicate of https://github.com/vaadin/flow/issues/3315

**Closed by pleku** 2018-01-17 07:32 UTC
Labels: maven-plugin
