### ISSUE TITLE
Vite doesn't respect `vaadin.urlMapping`

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#13750] opened 2022-05-12 08:39 UTC
### Description of the bug

When I configure `vaadin.urlMapping = /ui/*` in my Spring Boot based Vaadin application (which I consider critical due to this issue: vaadin/spring#602), Vite no longer works. There are no errors, but the browser simply shows a blank page and there are several 404s in the console. The issue is that the generated URLs do not consider the mapping. For example, it's attempted to load `http://localhost:8080/VAADIN/generated/vite-devmode.ts` instead of `http://localhost:8080/ui/VAADIN/generated/vite-devmode.ts.`

### Expected behavior

Vite should work with `vaadin.urlMapping`.

### Minimal reproducible example

Use a Vite-enabled starter from https://start.vaadin.com/ and add `vaadin.urlMapping = /ui/*` to the `application.properties`.

### Versions

- Vaadin / Flow version: 23.0.9
- Java version: 11
- OS version: Windows 10
- IDE (if applicable): Eclipse

**Comment by Artur-** [comment] 2022-05-12 08:55
Sounds like the same issue as #13190

**Comment by mcollovati** [comment] 2022-05-13 09:38
Closing as duplicate of #13190

**Closed by mcollovati** 2022-05-13 09:38 UTC
Labels: duplicate
