### ISSUE TITLE
Grid pagination broken when using count

### ISSUE THREAD

**Issue by fleahy** [vaadin/flow#17750] opened 2023-09-30 01:16 UTC
### Description of the bug

If a count is used in the grid.setItems call, such as the following code:
`        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream(), query -> samplePersonService.count());`

Then the pagination that Vaadin creates gets confused for the last page if the number of items to be fetched is not a multiple of the page size (50 by default). 

What ends up happening is that the last few items (depending on the item count and page size) are duplicates of the preceding items. 

The following example is based on what gets produced by start.vaadin.com with the helloworld page changed to a Master-Detail view. Additional lines are added to data.sql to make the record count not be a multiple of 50.

Example original code (count is commented out):
`        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream()/*, query -> samplePersonService.count()*/);`

Result:
![image](https://github.com/vaadin/flow/assets/14794583/e23b7ba3-2455-4026-b79e-6a95285259db)

Note that the lines at the bottom contain the additional people added to data.sql.

With the following code (count is enabled):
`        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream(), query -> samplePersonService.count());`

Result:
![image](https://github.com/vaadin/flow/assets/14794583/00faffde-d0e4-4ad3-8a45-c9c7c67d8a8d)

Note that the last few lines are duplicated instead of showing the correct data.

Please note that this seems to be dependent on the user scrolling using the mouse rather than going to the bottom of the grid at once using the scroll bars. 

### Expected behavior

The resulting grid data should not depend on the whether the code makes use of the record count or if the user scrolls with the mouse, or the scroll bars or goes directly to the end of the grid. The results should be the same.

### Minimal reproducible example

Steps to duplicate:

- Go to start.vaadin.com and change the hello world page to use a Master-Detail view.
- Download the resulting zip file, open in the IDE, get it to run, etc.
- Add 13 additional lines to the data.sql file so the record count doesn't match a multiple of the page size.
- Change the code for grid.setItems in HelloWorldView.java to:
`        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream(), query -> samplePersonService.count());`
- Run the application and scroll with the mouse wheel towards the end of the grid to see the duplicated items.

Attached is a zip file with the steps above in case I have missed anything.
[my-app.zip](https://github.com/vaadin/flow/files/12773087/my-app.zip)

### Versions

- Vaadin / Flow version: 23 and 24
- Java version: 11 and 17
- OS version: Linux
- Browser version (if applicable): N/A
- Application Server (if applicable): N/A
- IDE (if applicable): N/A

**Comment by fleahy** [comment] 2023-09-30 01:22
With the application in debug mode and a breakpoint set on repository.findAll(pageable) (line 33), looking at the value of the pageable variable, this is the sequence of events:

1. Page request [number: 0, size 50, sort: UNSORTED]
2. Page request [number: 1, size 50, sort: UNSORTED]
3. Page request [number: 7, size 13, sort: UNSORTED]

It seems that Vaadin code gets confused with the remaining items as the last request will get rows 91 through 104, thus getting about 9 or so duplicate rows (91 through 100) and missing on 9 fresh rows (100 through 113). 

Maybe it should request page 2 with a size of 50 and internally handle only looking through 13 of the 50 rows that are returned.

**Comment by rsercano** [comment] 2023-10-14 11:30
Exact same issue.

**Comment by rsercano** [comment] 2023-10-18 09:50
> > Exact same issue, have you find any solution?
> 
> What I did was to use the version of the API without the count component. It is probably not as efficient since it doesn't know how many items there are in total but it works. This also seems to be an issue in other cases, such as when using a data provider (not in front of the code right now to verify and provide an example).

I'm actually setting a data provider without even using set Items, so I wonder if there's a workaround for that particularly.

**Comment by rsercano** [comment] 2023-10-18 09:51
This must be labeled as criticial IMHO. It's pretty annoying.

**Comment by fleahy** [comment] 2023-10-18 12:08
I agree that this is very critical indeed! 

Just checked and the fix for me was to change from
`grid.setDataProvider(dataProvider);`
to
``grid.setItems(q -> dataProvider.fetchFromBackEnd((Query)q));`

This works but the setDataProvider call should be fixed quickly since it is providing very incorrect data and this could be a major problem for some applications. In our case it was showing duplicated items in the grid which was really confusing for our users but thankfully it was not a mission critical bug in a hard-to-fix system. But I can see this being a big deal in many cases.

**Comment by rsercano** [comment] 2023-10-18 12:19
Tbh. This must be resolved asap, because filtering is pretty annoying without setDataProvider, I was using configurable data provider, but with setItems handling filter and sorting is not really intuitive.

**Comment by simasch** [comment] 2023-10-25 07:37
I have the same issue when using 

```
var configurableFilterDataProvider = DataProvider.fromFilteringCallbacks(
        fetchCallback, countCallback).withConfigurableFilter();
```

IMO this is a sever error as it produces wrong results and should be fixed ASAP

**Comment by caalador** [comment] 2023-10-25 09:45
Just as a question now that I'm starting to look deeper on the issue, does everyone else also see this issue only if the grid is scrolled slowly, but if you scroll down fast the content is as it should?

**Comment by fleahy** [comment] 2023-10-25 13:04
Agree that this seems to be an issue only if the grid is scrolled slowly. If you go straight to the end of the grid (if I remember correctly) it works ok.

**Comment by simasch** [comment] 2023-10-25 13:47
Not in my case.

**Closed** 2023-10-26 08:28 UTC
Labels: bug, data provider, BFP, Impact: High, Severity: Major

**Comment by rsercano** [comment] 2023-10-26 08:37
Will there be a maven release fixing this that we can start using asap please?

**Comment by mshabarov** [comment] 2023-10-26 09:07
@rsercano which Vaadin version you use? We are going to release Vaadin Flow versions with this patch today. But Vaadin platform overall version needs more efforts.

**Comment by rsercano** [comment] 2023-10-27 07:19
@mshabarov I can wait for overall version change, I was using 24.1.12

**Comment by mshabarov** [comment] 2023-10-27 07:28
@rsercano we are planning to release next Vaadin 24.1 release today, so hopefully it will be available in maven tomorrow.

**Comment by rsercano** [comment] 2023-10-27 07:31
Thx for your efforts.

**Comment by simasch** [comment] 2023-10-27 10:28
In which 24.2.x version will the fix be included?

**Comment by caalador** [comment] 2023-10-27 10:37
24.2.1 released yesterday evening contains the fix.
This PR actually has labels `Released with Vaadin` that should state which versions it has come out in so 24.1.14 and 24.2.1

**Comment by simasch** [comment] 2023-10-27 10:43
@caalador Updated to 24.2.1 and everything works as expected. Thanks for the fix!

**Comment by rsercano** [comment] 2023-10-31 06:20
Still  not working properly with 24.1.14, will try 24.2.1 now.

**Comment by rsercano** [comment] 2023-10-31 06:26
Pinging for visibility @caalador try scrolling all the way to bottom and top, can't see real values. When I change sort back I see different data, this's really an annoying bug.

**Comment by caalador** [comment] 2023-10-31 06:40
@rsercano can you open a new issue with sample and steps to reproduce.
Or if possible make another test case like `DataCommunicatorTest::fetchFromProvider_itemCountLessThanTwoPages_correctItemsReturned` that shows the issue.

**Comment by rsercano** [comment] 2023-11-01 09:32
I'm sorry I dont have time but this issue still occurs for all new versions.

**Comment by caalador** [comment] 2023-11-01 10:55
With the current steps and information I can not see any exceptions in the data with or without sorting.
Verify from the classes executed that the Query:getPageSize() is not only a call to getLimit()
If it is not for some reason using old class code add steps to reproduce and write out expectations on the data.
