### ISSUE TITLE
WebBrowser.getTimezoneOffset() always returns 0

### ISSUE THREAD

**Issue by jennybou** [vaadin/flow#4941] opened 2019-01-09 10:47 UTC
Version 12.0.0

WebBrowser.getTimezoneOffset() always returns 0.  The timezoneId is null also.

I checked using JavaScript that the browser (Chrome) is providing the offset so it seems to be a Vaadin bug.

**Comment by bogdanudrescu** [comment] 2019-01-11 12:42
I could reproduce that request parameters `v-sw`, `v-tzo`, `v-tzid` which are required to set the timezone on server are missing from the HttpServletRequest.

**Comment by Legioth** [comment] 2019-01-11 14:45
Duplicate of #3657

**Closed by Legioth** 2019-01-11 14:45 UTC
Labels: app starter, bug
