### ISSUE TITLE
Use latest TB for integration tests

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#3055] opened 2017-11-27 09:18 UTC
New TB will includes new selenium version and includes some extra helpers that were common in users projects, details in [release notes](https://github.com/vaadin/testbench/releases/tag/6.0.0.alpha1)
This will also help validate TB 6.
There was a previous attempt in #2832, but I didn't have time to check the last test failures

**Comment by pleku** [comment] 2017-12-23 14:09
Duplicate of #3149

**Closed by pleku** 2017-12-23 14:09 UTC
