### ISSUE TITLE
Add public interface HasLabel ... to support polymorphism

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#6826] opened 2019-11-02 10:31 UTC
A lot of Vaadin components implement: property **getLabel** / **setLabel** 
https://vaadin.com/api/platform/14.0.11/com/vaadin/flow/component/textfield/TextField.html
...
https://vaadin.com/api/platform/14.0.11/com/vaadin/flow/component/datepicker/DatePicker.html

Please add public interface **HasLabel** ... like 
https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasText.java
to support polymorphism.

**Comment by Legioth** [comment] 2019-11-03 09:09
This is a duplicate of https://github.com/vaadin/flow/issues/3241.

**Closed by Legioth** 2019-11-03 09:09 UTC
