### ISSUE TITLE
Wrong Lookup instance used when trying to run on embedded OSGi

### ISSUE THREAD

**Issue by mg-dev-fis** [vaadin/flow#9695] opened 2020-12-18 13:40 UTC
My case: embedded OSGi framework within ear/war.

During application startup LookupInitializer is setting servlet context lookup property using standard LookupImpl.
Why? Because osgiAccess.getOsgiServletContext() is null as Initializer is run by container service (jboss undertow in my case).

When my Vaadin based servlet inits it contains that LookupImpl already set.
On VaadinServlet.init() method proper OSGiLookupImpl could be set but there is a condition checking for empty servlet attributes list - but it's not empty.

On the finale - DeploymentConfigurationFactory is using wrong lookup and fails loading token.

Using flow-osgi-2.5.osgi-20201201.091831-34 together with Vaadin 14.4.4

**Comment by pleku** [comment] 2020-12-18 13:50
Hi again. Just to be sure - is the `flow-server` version too `2.5.osgi-20201201.091831-34` instead of `2.4` (that Vaadin 14.4.4 brings in) ?

**Comment by mg-dev-fis** [comment] 2020-12-18 13:53
from bundleInfo.txt
[...]
commons-lang3-3.4.jar;
commons-logging-1.2.jar;
error_prone_annotations-2.3.2.jar;
failureaccess-1.0.1.jar;
flow-client-2.5.osgi-SNAPSHOT.jar;
flow-data-2.5.osgi-SNAPSHOT.jar;
flow-dnd-2.5.osgi-SNAPSHOT.jar;
flow-html-components-2.5.osgi-SNAPSHOT.jar;
flow-osgi-2.5.osgi-SNAPSHOT.jar;
flow-push-2.5.osgi-SNAPSHOT.jar;
flow-server-2.5.osgi-SNAPSHOT.jar;
fluent-hc-4.5.13.jar;
gentyref-1.2.0.vaadin1.jar;
guava-28.1-jre.jar;
gwt-elemental-2.8.2.vaadin2.jar;
hk2-api-2.5.0-b32.jar;
hk2-locator-2.5.0-b32.jar;
hk2-utils-2.5.0-b32.jar;
httpclient-4.5.13.jar;
[...]

**Comment by denis-anisimov** [comment] 2020-12-21 08:47
The report is quite weird since it's about functionality which doesn't exist.

The `osgi`  feature branch is just a feature branch and the PR which contains changes from the branch is not yet merged and there is a question whether it will be merged at all.

Then, I believe you are aiming to run Vaadin in NPM mode in OSGi. Otherwise there is no reason to use feature branch.

The code for basic OSGi support in the feature branch is the same as before: nothing has changed.
So if you use compatibility mode in `2.4` /`2.5`  then there should be exactly the same issue ( so no need to refer to the feature branch).

The error which you refer to comes from the fact that OSGi is not detected inside the applicaiton.
Here is the code which is used to detected whether it's executed in OSGi or not.
https://github.com/vaadin/flow/blob/2.4/flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java#L289
So it means that in your case  `Class.forName("org.osgi.framework.FrameworkUtil")` throws an exception.

That's quite weird: in OSGi `FrameworkUtil` should be available.

I don't know the exact details of your setup but are you sure that the app is running in OSGi as a WAB and not a WAR ?

Anyway : I don't know another way how to detect OSGi container in the code. If you may suggest another way then I will be happy to use more correct way.

Finally: if you want NPM mode in OSGi then `2.5`  is not ready for it (yet at least and not sure whether it will be ready at all).
There is already work done to support OSGi with NPM mode properly (without such check). But it's done for the `master`  branch.
And if we decide to support NPM mode in OSGi for `2.5` then the support will be done in sync with the `master` .

So : 
- I don't know what to do with the issue since there is no code (official) where it can be reproduced with the provided description
- there is an issue which I don't know how to solve. I expect that `org.osgi.framework.FrameworkUtil`  can be loaded via `Class.forName` in OSGi.

So I would say this is more an action point for you if you want to use the feature branch: understand how to detect that a bundle is executed inside OSGi container (without using OSGi API directly).

**Comment by mg-dev-fis** [comment] 2020-12-22 08:50
We are using embedded OSGi container so the bundles are put within single WAR.

I've started migration from V8.12.0 to V14.4.4 but due to https://github.com/vaadin/flow/issues/9146 Pekka on Discord suggested to check the 2.5.0-osgi snapshot branch. Given issue has been fixed but another one is present.

I can work on snapshots while waiting for next official 14 release which contains proper OSGi support.

Master branch is related to V19.

Will and when OSGi support be merged into 2.4.x / 2.5.x branch?

**Comment by denis-anisimov** [comment] 2020-12-23 10:35
WAR: I don't see how WAR. can be executed in pure OSGi container.
Doesn't look that you are using OSGi at all and may be this is the source of the issues.

In pure OSGi container there is anything except bundles. And the bundle is just a jar file with a proper manifest.
WAR can't be a bundle.

Some OSGi containers allow to run WARs (not bundles). But such WARs don't use any OSGi : they are just plain WARs.
Karaf e.g. allows to run WAR inside it. But this has nothing to do with OSGi in fact.

And as I mentioned: `FrameworkUtil`  class has to be available in OSGi. This class is a part of OSGi core.
If it's not available then the app is not running in OSGi.

>Will and when OSGi support be merged into 2.4.x / 2.5.x branch?

I cannot answer to this question unfortunately.
It's not my decision. The problem is licensing.
`V19`  OSGi is not Apache licensed.
And it's not clear how to make licensing for `2.5`  which already contains OSGi support for compatibility mode.
That's the main question.

**Comment by denis-anisimov** [comment] 2020-12-23 10:36
But anyway: may I close the ticket since it doesn't look like an issue at all ?

**Closed** 2021-01-07 09:14 UTC
Labels: OSGi
