### ISSUE TITLE
[Vaadin 14] Leverage Browser "Save Password"-Feature without enable Polyfill

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#11985] opened 2021-10-05 15:46 UTC
### Versions:
    - Vaadin / Flow version: 14.7
    - Java version: 11
    - OS version: Windows
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat

Details of the issue is here:
[Vaadin 14 - Error: Detected container element removed from DOM](https://stackoverflow.com/questions/69447470/vaadin-14-error-detected-container-element-removed-from-dom)

And my solution is to remove config: `window.ShadyDOM={force:true}`

But it causes other issue:
[Leverage Browser "Save Password"-Feature](https://vaadin.com/forum/thread/17399734/leverage-browser-save-password-feature)

So how can we allow Browser "Save Password" feature without enable Polyfill ?
Seem that Vaadin-starter demo project not enable Polyfill and password cannot auto save in Browser.

**Comment by denis-anisimov** [comment] 2021-10-06 06:02
Hello, thanks for the report. Can you please provide an example project based on https://github.com/vaadin/skeleton-starter-flow-spring or your own that reproduces the issue ? Otherwise there is not much what we can do with this.

The error report looks like it's a PayPal error. So I don't see how Vaadin is involved here and what's exactly broken in Vaadin.
Looks like only frontend HTML is involved here and not really Vaadin functionality.
It's more a question how can this be done rather than a bug report.

**Comment by INPUTsys-Chris** [comment] 2021-10-06 06:12
@denis-anisimov 

For our product https://www.spareparts365.de we had to introduce native components (@Tag "input") for username and password since the browsers did not recognize the TextField/PasswordField as username/password fields.

I think I read somewhere that you did similar for your login component.

Vaadin could benefit from an off-the-shelf solution for that problem.

**Comment by letrthang** [comment] 2021-10-06 06:48
Hi

This is our repo.

we added below part (`window.ShadyDOM={force:true}`) to fix [browser auto save password issue](https://vaadin.com/forum/thread/17399734/leverage-browser-save-password-feature).


```
public class MainView extends Div implements RouterLayout, PageConfigurator {
 @Override
    public void configurePage(InitialPageSettings settings) {
	// TODO Auto-generated method stub
	settings.addMetaTag("mobile-web-app-capable", "yes");
	settings.addMetaTag("apple-mobile-web-app-capable", "yes");
	settings.addMetaTag("apple-mobile-web-app-status-bar-style", "black");
	// to fix auto complete email on browser
	settings.addInlineWithContents(
		InitialPageSettings.Position.PREPEND, "window.customElements=window.customElements||{};"
			+ "window.customElements.forcePolyfill=true;" + "window.ShadyDOM={force:true};",
		InitialPageSettings.WrapMode.JAVASCRIPT);
    }

}
```

After we remove the part:

```
settings.addInlineWithContents(
		InitialPageSettings.Position.PREPEND, "window.customElements=window.customElements||{};"
			+ "window.customElements.forcePolyfill=true;" + "window.ShadyDOM={force:true};",
		InitialPageSettings.WrapMode.JAVASCRIPT); 
```

then Paypal issue was fixed.


I also checked on Vaadin starter demo project. There is no use of "`window.ShadyDOM={force:true}`" so it does not allow browser to auto save password.

**Comment by denis-anisimov** [comment] 2021-10-06 06:58
So based on this comment https://github.com/vaadin/flow/issues/11985#issuecomment-935546807 and the details from the last comment I don't see how Vaadin is involved here: it's about the HTML page configuration. All the methods which you called just sets the meta-tags and some scripts to the initial page.
It's an issue with Shadow DOM overall. Same should happen without Flow.

This is not a bug (at least in Flow) but rather a question: how to achieve something. But this is an issue tracker not a forum.

The questions may be asked here: https://vaadin.com/forum.

It looks like this is an issue with information how to make "save password" browser feature to work with custom component.
I've added @mstahv who will redirect this question to someone who is able to answer.
But this ticket will be closed since it's not a bug.

**Comment by letrthang** [comment] 2021-10-06 07:06
@denis-anisimov:


I expect 
```
@vaadin/vaadin-text-field/vaadin-password-field.js
@vaadin/vaadin-form-layout/vaadin-form-layout.js
```
will handle for this issue. 


Because when we use "vaadin-email-field" and "vaadin-password-field", if it cannot allow browser to auto save password, then it's involved to Vaadin-flow because both "vaadin-email-field" and "vaadin-password-field" are Vaadin official components.

**Comment by denis-anisimov** [comment] 2021-10-06 07:17
That should have been the statement in the description of the ticket:

**`vaadin-password-field` and `vaadin-email-field` should handle browser "save password" feature.**

May be this is an issue. I don't know. Since this is a Flow issue tracker. And Flow doesn't provide neither if these components.

https://github.com/vaadin/flow-components is the repository for Java server side components.
https://github.com/vaadin/vaadin-text-field is the repository for JS client side components.

Since I don't see how Java is involved here I transfer the issue to the https://github.com/vaadin/vaadin-text-field repo.

>Anyway, https://vaadin.com/forum seems that was closed and all questions will move to stackoverflow ?

Ops. You are right. I missed that.

**Comment by denis-anisimov** [comment] 2021-10-06 07:19
I cannot transfer the issue for some reason to the `vaadin-text-field`  repo so I will close it here and recreate there with a reference.

It makes sense to use proper repositories to avoid such misunderstanding.

**Comment by letrthang** [comment] 2021-10-06 07:20
okay, please bring this issue to:

https://github.com/vaadin/web-components/issues

**Closed by denis-anisimov** 2021-10-06 07:20 UTC
Labels: waiting for author
