### ISSUE TITLE
[VAADIIN 19] Embedded jetty and ServeStaticOrWebJarRequest in VaadinServlet crashes

### ISSUE THREAD

**Issue by pk1057** [vaadin/flow#10238] opened 2021-03-09 12:13 UTC
When i tried Vaadin 19rc1 with Jetty my pages are not served anymore.
Till the last Vaadin 18 release i had no problem.
I digged a little bit around and found the the staticFileHandler in VaadinServlet is not initialized and this leads to an exception because serveStaticOrWebJarRequest assumes that the staticFileHandler is initialized.

The VaadinSeevlet.init whas changed from flow 5.0.3 to 6.0.0 heavily.

The VaadinServlet.init does not reach the initialization because of the following code block:

           if (servletService != null || vaadinServletContext
                    .getAttribute(Lookup.class) == null) {
                return;
            }

servletService is null at this time and the Lookup.class is not set (for what is this ?) so it seems that the init suspects to be already initialized.

**Comment by pk1057** [comment] 2021-03-11 12:55
Attached a rough demo, not complete working because the routing is quite more complex.
But when you are using Vaadin 19, NPE occur. With Vaadin 18 only complains about missing index.html

[emb.tar.gz](https://github.com/vaadin/flow/files/6123058/emb.tar.gz)

**Comment by denis-anisimov** [comment] 2021-03-12 06:56
Several notes here:
- I don't see how may I run the project
- I see there a main class in the resulting just but when I execute `java -jar target/embedded-jetty-demo-1.0-SNAPSHOT.jar`I get 
```
Error: Unable to initialize main class com.example.Application
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
```

I would like to avoid any guess but for some reasons it's impossible to get the exact steps to reproduce from the reporters and I have to.
`complete working because the routing is quite more complex.` : I guess this is the cause of everything.
Routes should work out of the box if `Servlet 3.0 specification` is used.
I guess that this example is not `Servlet 3.0 specification` compliant and that the reason why the `Lookup`  is not set.
It's not set by the same reason why there is no routes: `RouteRegistryInitializer` is not executed.
The `RouteRegistryInitializer` is a `ServletContainerInitializer` and `ServletContainerInitializer` are invoked in the  `Servlet 3.0`  containers.
`Lookup` is initialized in the `LookupServletContainerInitializer`  which is also a `ServletContainerInitializer`.
Since `LookupServletContainerInitializer`   is not executed the servlet doesn't work because it relies on its execution and `Lookup` presence in the `ServletContext`  attributes.

I recall I have already similar conversation about embedded jetty and `ServletContainerInitializer`s. Have you reported already similar ticket ?

**Comment by pk1057** [comment] 2021-03-12 08:36
Well i just run it straight out of the IDE, in my case netbeans.
What i found out, it's necessary to set at least webAppContext.setConfigurations(new Configuration[]{new AnnotationConfiguration()}));
Without initialization of vaadin 19 fails, in contrast to Vaadin 18

**Comment by denis-anisimov** [comment] 2021-03-12 08:42
Didn't find any mention of IDE in your original description.

So looks like my guess was correct: the `ServletContainerInitializer`s are not executed in this config which means that the config is not `Servlet 3.0` spec compliant but this specification is required for Vaadin.

So I'm closing this but you still can add comments here.

**Closed by denis-anisimov** 2021-03-12 08:42 UTC
Labels: waiting for author
