### ISSUE TITLE
HasValidation fields are generally not validated server-side

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5934] opened 2019-06-18 09:18 UTC
Most implementations of `HasValidation` are only validated on the client, and can as such be circumvented by the user.

In addition, if server-side validations are manually added, e.g. through a `Binder`, if the validations do not exactly match that of the client-side component, error messages may be incorrectly displayed or hidden.

For a consistent server-side developing experience, the validations should also be implemented on the server. 

The following code shows a few examples of missing server-side validation. For all fields, notifications can easily be shown with seemingly invalid values.

    @Route
    public class ComponentValidationTest extends VerticalLayout {
    
        public ComponentValidationTest() {
    
            add(new Label("Only positive numbers"));
            NumberField numberField = new NumberField();
            numberField.setMin(0);
            numberField.addValueChangeListener(e -> {
                if (!numberField.isInvalid()) {
                    Notification.show("Number field set to valid value " + e.getValue());
                }
            });
            add(numberField);
    
            add(new Label("Only dates in 2019"));
            DatePicker datePicker = new DatePicker();
            datePicker.setMin(LocalDate.of(2019, 1, 1));
            datePicker.setMax(LocalDate.of(2019, 12, 31));
            datePicker.addValueChangeListener(e -> {
                if (!datePicker.isInvalid()) {
                    Notification.show("Date picker set to valid value " + e.getValue());
                }
            });
            add(datePicker);
    
            add(new Label("Only valid email-addresses"));
            EmailField emailField = new EmailField();
            emailField.addValueChangeListener(e -> {
                if (!emailField.isInvalid()) {
                    Notification.show("Email field set to valid value " + e.getValue());
                }
            });
            add(emailField);
    
            add(new Label("Password min 6 characters"));
            PasswordField passwordField = new PasswordField();
            passwordField.setMinLength(6);
            passwordField.addValueChangeListener(e -> {
                if (!passwordField.isInvalid()) {
                    Notification.show("Password field set to valid value " + e.getValue());
                }
            });
            add(passwordField);
    
            add(new Label("One or more lowercase letters a-z"));
            TextField textField = new TextField();
            textField.setPattern("[a-z]+");
            textField.addValueChangeListener(e -> {
                if (!textField.isInvalid()) {
                    Notification.show("Text field set to valid value " + e.getValue());
                }
            });
            add(textField);
        }
    }

*Vaadin version 14.0.0.beta2*

**Comment by peholmst** [comment] 2019-06-20 14:33
I've been looking at how this could be fixed. It is indeed really easy to go in using e.g. Chrome Devtools and just change the validation criteria and then the application will act as if that is the correct one. This could be fixed by adding an additional server-side validation mechanism to each individual component that also has client side validation and make sure these are in sync. Exactly when this validation should be triggered remains to be seen.

I did a test on `TextField` where I added the server-side validation to the `isInvalid()` method, but this does not change the client-side value of the invalid flag if the server-side validation fails. With this implementation, if I tamper with the client side constraints the server-side validation will still fail, but the client side validation will succeed and no error indication will be visible to the user. Then again you're not supposed to tamper with apps like this and so it might be acceptable.

As for the `Binder`, I think it should be up to the developer to make sure that if you are using server-side validators in a `Binder` then you should not be using client side validation at all on those fields. I don't see any easy way of combining client-side validation (with the server-side corresponding validation built in), server-side validations and value converters in a seamless way where no part causes weird side effects for the other.

**Comment by peholmst** [comment] 2019-06-24 12:02
I'm going to let the components team take care of this, but I started something for the text fields here: https://github.com/vaadin/vaadin-text-field-flow/tree/flow5934-server-side-validation

**Comment by denis-anisimov** [comment] 2020-03-03 08:42
The problem is that we can't know which methods on the server side leads to the clients side validation.
E.g. `numberField.setMin(0);`  enables the client side validation but the server side doesn't know anything about the semantic of `min` generally (on the Flow side) .
I'm not sure whether it's feasible to fix this at all and how but this can't be done on the Flow side.
It can be done only in every specific component (like `NumberField`) because only the component knows the semantic of its methods.

So please make tickets for every component which you mentioned here in their own repositories.
I don't see how this can be solved generally on Flow side.

Please write a comment so that I can reopen the ticket if you see a general way.

**Closed by denis-anisimov** 2020-03-03 08:42 UTC
Labels: bug
