### ISSUE TITLE
Using "PageConfigurator" in combination with "@PreserveOnRefresh" doesn't work

### ISSUE THREAD

**Issue by mgae0047** [vaadin/flow#11518] opened 2021-08-04 12:26 UTC
### Description of the bug / feature
When using the interface "PageConfigurator" in combination with the annotation "@PreserveOnRefresh" the code in configurePage(...) will only be executed when the screen is loaded by entering an URL. When refreshing the page by "F5" that code will not be executed again (caused by the "@PreserveOnRefresh").

Solution for us is to use the BootstrapListener as mentioned in https://vaadin.com/docs/v14/flow/advanced/tutorial-bootstrap#bootstraplistener.

### Minimal reproducible example
```Java
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.InitialPageSettings;
import com.vaadin.flow.server.PageConfigurator;

@PreserveOnRefresh
@Route(value = "main")
public class MainLayout extends VerticalLayout implements PageConfigurator {

	public MainLayout() {
	}

	@Override
	public void configurePage(InitialPageSettings settings) {
		String theIcon = "icons/shortcut.ico";

		settings.addLink("shortcut icon", theIcon);
		settings.addFavIcon("icon", theIcon, "192x192");

		System.out.println("Setting favIcon to " + theIcon);
	}
}
```

### Expected behavior
The code in configurePage(...) should be executed also when pressing F5 in the browser.

### Actual behavior
Message comes only on once when loading the page for the first time. When pressing "F5" the message didn't appear.

### Versions:
    - Vaadin / Flow version: 14.6.3
    - Java version: 1.8.0
    - OS version: Windows 10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Eclipse

**Comment by denis-anisimov** [comment] 2021-08-05 07:16
Honestly speaking I would like to close this ticket because the whole idea of `PageConfigurator` is illogical.

I see immediate logical problem with `PageConfigurator` : if it's implemented by another Component which is not used in the initial page rendering then its code won't be called ever.

So two immediate issues:
- logic clash : if several `PageConfigurator` is implemented by several components then which one is executed ? (in fact all of them which participate in the initial rendering)
- If Route is not loaded initially (with the very first browser request) then it's `PageConfigurator` logic will never be executed.

The second issue causes non deterministic behavior : depending on the very first request the initial page behaves differently.

The original issue is caused by one more issue: the way how `PageConfigurator` is found to apply its code.
Everything happens during the initial page bootstrapping. 
The `UI` instance has to have all its children  components when initial page is handled. This is how the code is implemented.
So if `UI` initialization is somehow deferred then this code won't be executed ever.

One of such case is `PreserveOnRefresh`: the `UI` instance in this case is not yet ready on the very first request when initial page is made during bootstrap.
Window name is required to be able to transfer the state from the old StateTree to the new one.
The window name is requested from the client side asynchronously. As a result the initial page is already rendered when window name is received by the server side and it responds with the `UI` content.

Deferred `UI` initialization may happen also with using `Push`.

So this functionality is broken from the very beginning in many various cases.

There is no way to fix this at all without complete rewriting the functionality. But it has no sense since there is already a proper way to do this : using `BootstrapListener` or `AppShellConfigurator`.
The `AppShellConfigurator` interface is a proper replacement for  `PageConfigurator` in the `master` branch where the  `PageConfigurator` is deprecated.

So I don't know what to do with this ticket: the bug is there. It's true. But I don't see any reason to fix it since the functionality is initially broken and there is already the proper way (`BootstrapListener` ).

As mentioned `PageConfigurator`  is already deprecated in the `master` (and any modern version).
I can deprecate `PageConfigurator`  in 2.x series but I'm not sure whether it's correct.

**Comment by mgae0047** [comment] 2021-08-05 07:41
In my point of view you can close this issue when there is another recommended way of doing the thing (here `BootstrapListener`). But keep in mind to update the other documentations in the forum etc. because that was the way we found this bug (and the solution later on).

We had used the `PageConfigurator` for some more things and wondered why the icons disappear on "F5" (and other things) ;)

**Comment by denis-anisimov** [comment] 2021-08-05 12:26
Docs issue :https://github.com/vaadin/docs/issues/678

So I'm closing this as WONTFIX.
This is indeed a bug but `PageConfigurator` has initially broken design.
It should not be used at all.
`AppShellConfigurator` is a proper replacement for modern Flow series and for 2.x `BootstrapListener` should be used instead.

**Closed by denis-anisimov** 2021-08-05 12:26 UTC
Labels: Impact: Low, Severity: Major, bug, workaround

**Comment by Legioth** [comment] 2021-08-05 12:30
Should `PageConfigurator` be marked as deprecated then?

**Comment by denis-anisimov** [comment] 2021-08-05 12:33
It's in the `master`.

Should I make it in the 2.x series ?
I would like to do it but is it "compatible" ?

**Comment by Legioth** [comment] 2021-08-05 13:04
Deprecation is compatible. The earlier a deprecation can be introduced, the fewer users will end up using approaches that will lead them into trouble.

**Comment by pleku** [comment] 2021-08-09 07:52
> I see immediate logical problem with PageConfigurator : if it's implemented by another Component which is not used in the initial page rendering then its code won't be called ever.

As the documentation states
> To be able to modify default bootstrap page and add your custom meta tags on the page you can implement the `PageConfigurator` on the navigation target with `@Route` or the top most `RouterLayout` that builds the navigation target chain. The `PageConfigurator` gives you easy access to customize the `LoadingIndicatorConfiguration`, `ReconnectDialogConfiguration` and `PushConfiguration` for the initial response.

And even a _note_:
> If the PageConfigurator implementation is not on a `@Route` Component or a RouterLayout used from a route it will not be used.

Which is bad design indeed as it is easy for users to do this mistake and the framework doesn't help them in catching this.

**However I think deprecating the `PageConfigurator` doesn't really work for Flow 2.x series as:**
1) there is no proper replacement - with `BootstrapListener` the users cannot access the same details through `BootstrapPageResponse` as with `InitialPageSettings` - they would need to know to access the `UI` and `Page` for certain settings and  `Router` for some..
2) `BootstrapListener` is also deprecated since Flow 3.0+ so we're deprecating in favor of another thing that is also deprecated ...

So I think the deprecation is problematic and should be reverted. Your thoughts @Legioth ?

Instead I would look at
a) backporting `AppShellSettings` to Flow 2.x series to make it easy for users to switch to it immediately instead of only when updating to a newer major version. It would also help people who are working with both versions LTS + Latest, as there is only one recommended way to do things. 
b) fix `@PageConfigurator` settings to be reapplied when used together with `@PreserveOnRefresh`. 
c) try to make it more visible that using a `@PageConfigurator` in a _non-root-navigation-component_ or multiple times is a probably a mistake. I can't see how we could throw an error though but instead just maybe log an warning during start-up time (when scanning for the annotations)

**Comment by Legioth** [comment] 2021-08-09 08:14
It might make sense to revert the deprecation in case there are use cases that aren't covered with anything else. I wasn't certain of all the implications which is why I presented the thought as a question rather than as a direct suggestion. I was expecting any challenges to become apparent at the latest when trying to write a good description of the alternatives in the deprecation message.

The more users are using `PageConfigurator`, the more problems will they get when updating to newer versions. How can we help users avoid `PageConfigurator` while still ensuring that all use cases are covered? I don't see it as a big problem to reference `BootstrapListener` even though it is also deprecated since that API has a really straightforward replacement.

Could it be an option to deprecate only those specific parts of the `PageConfigurator` API for which replacements exist without going to `AppShellConfigurator`?

**Comment by pleku** [comment] 2021-08-17 14:07
I still think it is not that good practice to reasons mentioned above, but I'm fairly sure all similar usage should be possible via `BootstrapListener` instead. I've improved the deprecation messages with providing the details on _why_ and _what to do_ instead of just previous "Use BootstrapListener" instead which doesn't help that much when the API is not the same.
