### ISSUE TITLE
Opening a Notification or Dialog in the constructor for a @Route does not show the popup at all

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3279] opened 2018-01-08 20:26 UTC
```
@Route("")
public class ComponentsView extends VerticalLayout {
	public ComponentsView() {
		Dialog dialog = new Dialog();
		dialog.add(new Label("This is the contents"));
		dialog.open();
	}
}
```

Expected outcome:
A dialog is shown with the contents "This is the contents"

Actual outcome:
Nothing is shown

`Dialog.open()` adds the dialog to the `UI` element, which is then overwritten in `UIInternals.showRouteTarget`:
```
uiElement.removeAllChildren();
rootElement.removeFromParent();
uiElement.appendChild(rootElement);
```

**Comment by ZheSun88** [comment] 2018-01-09 07:07
i think there is one line missing to make the `dialog` or `notification` work. 
As the constructor for these two components will not add the components to the UI directly, so you should add `add(dialog);` to the `verticalLayout` too. 

Besides,  for `notification`, there is a convenience method, (Notification.show("this is the contents", duration, position)) that you can use.

**Comment by Artur-** [comment] 2018-01-09 07:18
The show method is broken, see https://github.com/vaadin/vaadin-notification-flow/issues/13
Even if that is fixed to work the same way as Dialog, this issue still persists as long as the component is added to the UI and the UI children are cleared on navigation

**Comment by pleku** [comment] 2018-02-16 11:13
Duplicate of https://github.com/vaadin/vaadin-dialog-flow/issues/32

**Closed by pleku** 2018-02-16 11:13 UTC
Labels: bug
