### ISSUE TITLE
ComboBox filtering doesn't work at least with the latest FlowBaseProject

### ISSUE THREAD

**Issue by johannest** [vaadin/flow#4967] opened 2019-01-17 14:34 UTC
*Description of the bug*
When trying to filter, nothing happens except the empty overlay quickly flashes under the combobox

*Minimal reproducible example*
Add following snippet to the latest Flow Spring base project's MainView

    ComboBox<String> comboBox = new ComboBox<>("Browsers");
    comboBox.setItems("Google Chrome", "Mozilla Firefox", "Opera", "Apple Safari", "Microsoft Edge");
    add(comboBox);

*Expected behavior*
Filtering would work when typing e.g. G

*Versions:*
<vaadin.version>12.0.3</vaadin.version>
Window 10
At least Chrome

Works normally with older 12.0.2 version

**Comment by bogdanudrescu** [comment] 2019-01-24 10:18
Duplicate of https://github.com/vaadin/vaadin-combo-box-flow/issues/182

Fixed by https://github.com/vaadin/vaadin-combo-box-flow/pull/192

**Closed by bogdanudrescu** 2019-01-24 10:18 UTC
Labels: bug, components
