### ISSUE TITLE
URL incorrect after BeforeLeaveEvent.ContinueNavigationAction.proceed()

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#17450] opened 2023-08-15 12:08 UTC
### Description of the bug

1. Start my example
2. Click on the link "Two"
3. Then click on the Browser back button and confirm the dialog
4. Now check the URL and you will see that it's incorrect.

### Expected behavior

The URL should be correct

### Minimal reproducible example

https://github.com/simasch/vaadin-postpone-navigation

### Versions

- Vaadin / Flow version: 24.1.5
- Java version: 17

**Comment by knoobie** [comment] 2023-08-15 12:31
Sounds similar to https://github.com/vaadin/flow/issues/9551

**Comment by simasch** [comment] 2023-08-15 12:36
@knoobie Indeed! Wow, this issue is three years old and seems to be inactive.

**Comment by knoobie** [comment] 2023-08-15 12:42
Unfortunately, both Denis + Pekka in the ticket are no longer part of the flow team, therefore it probably slipped through over the years.

**Comment by simasch** [comment] 2023-08-15 12:44
Let's see what happens here ;-)

**Comment by simasch** [comment] 2023-08-15 13:34
This was working with Vaadin 23.3! So it looks like a regression.

**Comment by mcollovati** [comment] 2024-02-06 15:51
This appears to be similar to https://github.com/vaadin/flow/issues/17528, that has been fixed and released in 24.1.11

I think this issue can be closed, since I cannot reproduce the issue with the latest 24.3 nor with 24.1.11

**Comment by knoobie** [comment] 2024-08-14 09:37
@mcollovati I think I can reproduce this with 24.4 ;) https://github.com/vaadin/flow/issues/19786

**Comment by tepi** [comment] 2024-08-22 07:07
Tested using Vaadin 24.4.10 (and 24.5-SNAPSHOT as well) and latest available Chrome browser on macOS. Could not reproduce the issue with either react router or vaadin router. URL is correctly updated when clicking the confirm button in the dialog.

**Comment by tepi** [comment] 2024-08-22 07:11
I'll close this issue for now since it can't be reproduced with latest Vaadin version. Please open a new issue if the problem still persists in some circumstances.

**Closed by tepi** 2024-08-22 07:11 UTC
Labels: bug, routing, Impact: High, Severity: Major
