### ISSUE TITLE
webpack bundle is sent non gzipped to the browser

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#6412] opened 2019-09-06 11:08 UTC
The Business App example on V13:

<img width="821" alt="Screenshot 2019-09-06 at 14 06 54" src="https://user-images.githubusercontent.com/260340/64423609-9f2ea800-d0af-11e9-96e0-2e3f18c0abdd.png">

The Business App example on V14:
<img width="819" alt="Screenshot 2019-09-06 at 14 07 42" src="https://user-images.githubusercontent.com/260340/64423660-b66d9580-d0af-11e9-93c2-beae5d8f0007.png">

**Comment by denis-anisimov** [comment] 2019-09-06 11:25
Would be good to have a ticket description which can be reproduced by anyone and without external unknown projects mention.
`The Business App example`  : I don't know what is this.


Steps to reproduce :
- use https://github.com/vaadin/skeleton-starter-flow project
- use V13 branch
- run the project via `mvn clean jetty:run-exploded -Dvaadin.productionMode=true`
- check the network tab. `vaadin-bundle` file size :  226KB transferred over network, resource size: 847KB
- use the `master` branch
- run the project via `mvn clean install jetty:run`
- check the network tab. `vaadin-bundle` file size :  1.8MB transferred over network, resource size: 1.8MB

**Comment by Legioth** [comment] 2019-09-06 11:35
You're comparing apples to oranges with `skeleton-starter-flow` since the NPM numbers are not from a production build. The actual issue of not having the bundle precompressed does still apply.

**Comment by denis-anisimov** [comment] 2019-09-06 11:58
>You're comparing apples to oranges

True since the original ticket doesn't have a description at all but rather says that some file is not gzipped without any explanation why it should be gzipped.

**Comment by Peppe** [comment] 2019-09-06 14:50
“The Business App example“ is the Business App Starter found on our start page: https://vaadin.com/start/latest/business-app

The live deployment demo of the app was recently redeployed with the V14 version. 
The official demo for the app is deployed here: https://labs.vaadin.com/business/
An alternative version of the demo, which is still running on V13, can be found here: https://labs.vaadin.com/business-tabs/

Both are built for production. Results can be reproduced with the Starter mentioned above.

**Comment by pleku** [comment] 2019-09-09 09:24
This definitely is not an enhancement since it has worked differently previously and there is no reason for anyone to presume that is should change for npm mode in 14.

The production bundle should be sent gzipped by default, like with Vaadin 13.

**Closed** 2019-09-17 10:30 UTC
Labels: bug
