### ISSUE TITLE
Moving a child between two tree nodes can remove the child's key from `KeyMapper`

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow#17307] opened 2023-07-28 09:29 UTC
### Description of the bug

Using `HierarchicalDataCommunicator`, moving a child node from one parent node to another one can result in the child's key being removed from the `KeyMapper` used by the data communicator. That in turn causes operations in `TreeGrid` to fail where the component needs to access the item by its key (select item, start dragging item). This only seems to happen when refreshing the parent nodes individually after moving the child via `dataProvider.refreshItem(node, true)`, but not with `dataProvider.refreshAll`.

This is related to this BFP: https://github.com/vaadin/flow-components/issues/5249

### Expected behavior

The child's key should still be in the key mapper as long as it is in the tree.

### Minimal reproducible example

<details>
<summary>Reproduction using TreeGrid</summary>

```java
@Route("repro")
public class Repro extends Div {
    private TreeGrid<String> treeGrid;
    private TreeData<String> treeData;
    private TreeDataProvider<String> treeDataProvider;
    private List<String> draggedNodes = new ArrayList<>();

    public Repro() {
        treeGrid = new TreeGrid<>();
        treeGrid.addHierarchyColumn(item -> item);
        treeGrid.setRowsDraggable(true);
        treeGrid.setDropMode(GridDropMode.ON_TOP);

        treeGrid.addDragStartListener(event -> {
            draggedNodes.clear();
            draggedNodes.addAll(event.getDraggedItems());
        });

        treeGrid.addDragEndListener(event -> draggedNodes.clear());

        treeGrid.addDropListener(this::drop);

        treeData = getTreeData();
        treeDataProvider = new TreeDataProvider<>(treeData);
        treeGrid.setDataProvider(treeDataProvider);
        treeGrid.expandRecursively(List.of("root"), 2);

        add(treeGrid);
    }

    private Optional<String> getDragged() {
        return draggedNodes.stream().findFirst();
    }

    private void drop(GridDropEvent<String> event) {
        Optional<String> dragged = getDragged();
        Optional<String> dropped = event.getDropTargetItem();

        if (dragged.isPresent() && dropped.isPresent()) {
            String draggedNode = dragged.get();
            String droppedNode = dropped.get();

            String previousParent = treeData.getParent(draggedNode);

            treeData.removeItem(draggedNode);
            treeData.addItem(droppedNode, draggedNode);

            treeDataProvider.refreshItem(previousParent, true);
            treeDataProvider.refreshItem(droppedNode, true);
        }
    }

    private TreeData<String> getTreeData() {
        TreeData<String> treeData = new TreeData<>();

        treeData.addRootItems("root");
        treeData.addItem("root", "root child 0");
        treeData.addItem("root", "root child 1");
        treeData.addItem("root child 0", "root child 0 grandchild 0");
        treeData.addItem("root child 1", "root child 1 grandchild 0");

        return treeData;
    }
}
```
</details>

- Drag `root child 1 grandchild 0` to `root child 0`
- Drag `root child 1 grandchild 0` back to `root child 1`
- Observe exception in server log caused by the dragged item being `null` in `GridDragStartEvent`

<details>
<summary>Reproduction as unit test in HierarchicalCommunicatorDataTest</summary>

```java
    @Test
    public void moveItem_refreshParentNodes_itemKeyPresent() {
        // Setup communicator with tree data
        TreeData<String> treeData = new TreeData<>();
        treeData.addItem(null, "root");
        treeData.addItem("root", "first-1");
        treeData.addItem("root", "first-2");
        treeData.addItem("first-1", "second-1-1");
        treeData.addItem("first-2", "second-2-1");

        HierarchicalDataCommunicator<String> communicator = new HierarchicalDataCommunicator<>(
                Mockito.mock(CompositeDataGenerator.class), arrayUpdater,
                json -> {
                }, element.getNode(),
                () -> (ValueProvider<String, String>) item -> item);
        TreeDataProvider<String> treeDataProvider = new TreeDataProvider<>(treeData);
        communicator.setDataProvider(treeDataProvider, null);
        fakeClientCommunication();

        // Expand items and load data
        communicator.expand("root");
        communicator.expand("first-1");
        communicator.expand("first-2");
        communicator.setParentRequestedRange(0, 50, "root");
        communicator.setParentRequestedRange(0, 50, "first-1");
        communicator.setParentRequestedRange(0, 50, "first-2");
        fakeClientCommunication();

        // Move grandchild from second child to first child, refresh items
        treeData.removeItem("second-2-1");
        treeData.addItem("first-1", "second-2-1");
        treeDataProvider.refreshItem("first-1", true);
        treeDataProvider.refreshItem("first-2", true);
        fakeClientCommunication();

        // Confirm updates
        communicator.confirmUpdate(1, communicator.getKeyMapper().key("first-1"));
        communicator.confirmUpdate(1, communicator.getKeyMapper().key("first-2"));
        fakeClientCommunication();

        // Key for first grandchild is still there
        Assert.assertTrue(communicator.getKeyMapper().has("second-1-1"));
        // Fails, key for second grandchild is gone even though it's still in the tree
        Assert.assertTrue(communicator.getKeyMapper().has("second-2-1"));
    }
```

</details>

### Versions

- Vaadin / Flow version: Tested with 24.1 and 24.2, but this likely also affects previous versions

**Comment by tepi** [comment] 2023-10-27 06:24
Closing this since it is a duplicate of https://github.com/vaadin/flow/issues/14351 which has been fixed.

**Closed by tepi** 2023-10-27 06:24 UTC
Labels: bug, data provider, Impact: Low, Severity: Major
