### ISSUE TITLE
Vaadin 19: InvalidRouteLayoutConfigurationException: Only one target for an exception should be defined

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#10117] opened 2021-02-23 23:23 UTC
I have the same problem from https://github.com/vaadin/flow/issues/8948 in Vaadin 19.0.0.beta4.

When starting my simple app on Tomcat:
 com.vaadin.flow.server.InvalidRouteLayoutConfigurationException: Only one target for an exception should be defined. Found 'pl.portal.webbase.app.ui.view.error.ErrorNotFoundView' and 'com.vaadin.flow.spring.router.SpringRouteNotFoundError' for exception 'com.vaadin.flow.router.NotFoundException'

I know it was fixed but is the fix added to Vaadin 19 code?

**Comment by taefi** [comment] 2021-03-01 13:11
Hi @darmro, 
Vaadin 19.0.x uses the vaadin-spring 16.0.x series, and as you mentioned, that regression was fixed in vaadin-spring 14.0.2. So if you are experiencing this issue with Vaadin 19.0.x, would you please add more details about the environment along with a minimal example that can reproduce the issue?

**Comment by darmro** [comment] 2021-03-01 16:17
Hi, test is rather simple.
I entered Vaadin page, choose "Start building -> Vaadin 18", run app builder, changed Vaadin version to 19. Then imported app as a war into my eclipse, added only one class `ErrorNotFoundView extends RouteNotFoundError`, run app war on Tomcat 9 and ... 
```
2021-03-01 16:51:38.331 ERROR 42516 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vaadinApplicationContextInitializer' defined in class path resource [com/vaadin/flow/spring/VaadinApplicationConfiguration.class]: Initialization of bean failed; nested exception is com.vaadin.flow.server.InvalidRouteLayoutConfigurationException: Only one target for an exception should be defined. Found 'com.example.application.views.ErrorNotFoundView' and 'com.vaadin.flow.spring.router.SpringRouteNotFoundError' for exception 'com.vaadin.flow.router.NotFoundException'
``` 

Source code: 
[my-app.zip](https://github.com/vaadin/flow/files/6062921/my-app.zip)

**Comment by caalador** [comment] 2021-03-02 12:57
The workaround for this is to extend `SpringRouteNotFoundError` instead of `RouteNotFoundError`
I would guess that the issue is that it's run as a war on tomcat which means that the route initialization is done by the `ServletContextInitializer` instead of the `VaadinServletContextInitializer` which doesn't know about the special spring class andthus fails on duplicate error handlers.

**Comment by pleku** [comment] 2021-03-02 13:05
As there is a simple workaround and this is not on the critical path of trying things, I don't see this as a blocker. Related to https://github.com/vaadin/spring/pull/657

**Comment by denis-anisimov** [comment] 2021-06-22 07:59
Duplicate of vaadin/spring#661

**Closed by denis-anisimov** 2021-06-22 07:59 UTC
Labels: Impact: High, Severity: Major, bug, spring, workaround
