### ISSUE TITLE
Allow Custom types for HasUrlParameter/ParameterDeserializer

### ISSUE THREAD

**Issue by robert-lee-hisl** [vaadin/flow#7598] opened 2020-02-14 15:19 UTC
It would be advantageous to rework ParameterDeserializer to allow the use of custom data types.

**Use case:**

Supported URL parameters include Long, Integer, String or Boolean. Of these, String is the most common as it can include any text that can be included in a URL.

There are several views, each implementing HasUrlParameter<String>, with the string represents a key in a specific database table.

Each view must parse the String, validate the value and either convert it to an internal identifier or handle the validation error.

There may be other views also implementing HasUrlParameter<String>, where the string has a different representation.

* Each of these methods must implement setParameter(BeforeEvent, String).
* This violates type safety; the String in one class may have the same semantic meaning in the second class but a different semantic meaning in a third.
* Each class with the same meaning for String must reimplement the same parsing logic.
* Vaadin already handles validation for Booleans, Integers and Longs within the routing framework, but not for String types, even where only a subset of strings (eg database table keys) is valid.

If custom types were available, you could have:

`HasUrlParameter<Key> {}`

where Key is defined as (for example):

    public class Key {
    int tableId;
    String valueId;
    public Key(String urlForm) throws IllegalArgumentException {
        final String[] parts = urlForm.split(":", 2);
        if (parts.length != 2) throw new IllegalArgumentException("Bad key");
        tableId = Integer.parseInt(parts[0]);
        // ... validate tableId is a lawful table ID here ...
        valueId = parts[1];
    }
    public String toString() {
        return tableId + ":" + valueId;
    }
    }

**Comment by haijian-vaadin** [comment] 2020-02-14 16:18
Thank you for the suggestion, sounds very reasonable. 
It looks like an enhancement for the Flow routing in general, so I transferred the issue here.

**Comment by knoobie** [comment] 2020-02-14 16:25
Sounds like a duplicate of #4689.

**Comment by haijian-vaadin** [comment] 2020-02-14 16:29
Indeed, let's close this one in favor of https://github.com/vaadin/flow/issues/4689.

**Closed by haijian-vaadin** 2020-02-14 16:29 UTC
Labels: enhancement
