### ISSUE TITLE
Frontend compilation fails during debug with 16.0.0.rc1

### ISSUE THREAD

**Issue by andersforsell** [vaadin/flow#8456] opened 2020-05-29 07:11 UTC
I have been testing Vaadin 16 and get problems when running in dev mode in Eclipse (using Maven):
`------------------ Starting Frontend compilation. ------------------`
`Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1478`
...
`java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.DevModeHandler.doStartDevModeServer(DevModeHandler.java:568)`

I can compile with mvn clean package -Pproduction without errors, and then as a workaround debugging works fine until the next time it want to compile the frontend.

**Comment by joheriks** [comment] 2020-05-29 08:25
OS type and Node version? Can this be related to https://github.com/libuv/libuv/issues/2587?

**Comment by pleku** [comment] 2020-05-29 09:00
I just tested with vaadin/skeleton-starter-flow with 16.0.0.rc1, Windows 10 and Node.js versions:
- 12.11.0
- 12.14.1
- 12.17.0
Using either Maven from command line or via IDEA. Not reproducing.

Please @andersforsell provide more details on the versions used and how to reproduce this. If there is a problem, we want to fix it ASAP but without proper steps to take, you will cause us to waste our time and you can probably understand that it makes us upset.

**Comment by andersforsell** [comment] 2020-05-29 11:11
Windows 10 and node v12.16.3.

I'll try to get you more details, starting with cleaning my .m2 to wipe previous releases.
Of course I don't want to "waste your time", but it has been a mess with frontend compilation so I do believe you want to make it more stable.

**Comment by andersforsell** [comment] 2020-05-29 11:53
I debugged DevModeHandler.java to see which command was failing.
I turned out it fails when running the webpack-dev-server, but I did not get that output in Eclipse Console.
Running the same command in Windows CMD I got the attached log.
[webpack-dev-server.log](https://github.com/vaadin/flow/files/4701610/webpack-dev-server.log)

**Comment by andersforsell** [comment] 2020-05-29 12:52
After removing all generated frontend files I got the `Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1478` again.

I can reproduce the problem using the attached java program., which is where the frontend tools 
checks for the pnpm version.
[Test.java.txt](https://github.com/vaadin/flow/files/4701844/Test.java.txt)

**Comment by pleku** [comment] 2020-05-29 14:28
Thanks for the further details, really appreciate it. It is indeed very messy with so many version permutations that we're now considering to limiting all frontend versions to pinned ones. But now as it is the exact version that Vaadin it is installing it by default it looks like we have picked a bad version ...

I've deleted my Node.js & npm & pnpm installations and caches and let Vaadin install `12.16.0` (not 12.16.3 ?), but it still does not fail. I tried running the `Test.java` but it just reports the version correctly. If I use `nvm` (https://github.com/coreybutler/nvm-windows) to switch to Node 12.16.3 everything still works.

Is it possible that you have "too long" PATH variable in your system ? If you try with `$Env:PATH` on terminal, what do you get ?
> An environment variable has a maximum size limit of 32,767 characters, including the null-terminating character.

Maybe you can try by just deleting the `.vaadin` folder and see if it helps after the reinstall ? If not then maybe try installing a global Node.js version in your system like 12.17 which is the latest LTS. I know it is not nice to have to do it yourself, but this problem seems like its quite system dependent.

**Comment by pleku** [comment] 2020-05-29 15:24
The same error (except via Gradle) that was fixed by changing the path https://vaadin.com/forum/thread/18277566/18277835

**Comment by andersforsell** [comment] 2020-05-29 15:26
I deleted the .vaadin folder and got the v12.16.0 node version.
Now it fails in FrontendUtils.java:879 when trying to run: <HOMEDIR>\.vaadin\node\node.exe --no-update-notifier --no-audit --version

But running from a CMD window clearly states that there are bad options:
C:\Users\aforsell\.vaadin\node\node.exe: bad option: --no-update-notifier
C:\Users\aforsell\.vaadin\node\node.exe: bad option: --no-audit

BTW I don't have a long path in my env setting.

**Comment by andersforsell** [comment] 2020-06-03 15:11
I found that the problem is the JRE I was using: OpenJDK8U-jdk_x64_windows_hotspot_8u252b09
It works fine when using Amazon Corretto JDK11: amazon-corretto-11.0.7.10.1-windows-x64

**Comment by pleku** [comment] 2020-06-04 08:39
Ok, thanks for the update! I'm going to close this as duplicate to #7527

**Closed by pleku** 2020-06-04 08:39 UTC
Labels: waiting for author
