### ISSUE TITLE
Validation status reported on UI is not in sync with the binder

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#4077] opened 2018-05-07 10:17 UTC
With following code snippet:

 1. write a letter to input
 1. delete the letter from input
 1. click the button
 1. binder reports valid bean, UI shows invalid value in the TextField

Test code:
```package org.vaadin.matti.spring;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.BeanValidationBinder;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.router.Route;
import javax.validation.constraints.NotNull;
import java.util.Set;

@Route("")
public class MainView extends VerticalLayout {

    public static class Entity {

        @NotNull
        private String name;

        public void setName(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        @Override
        public String toString() {
            return "Entity, name: " + name;
        }

    }

    final TextField name = new TextField();

    public MainView() {

        final VerticalLayout layout = new VerticalLayout();
        name.setLabel("Type your name here:");

        Entity entity = new Entity();
        Binder<Entity> b = new BeanValidationBinder<>(Entity.class);
        b.bindInstanceFields(this);

        b.setBean(entity);

        Button button = new Button("Check validity");
        button.addClickListener(e -> {
            String msg = String.format("Binder.isValid: %s", b.isValid());
            Notification.show(msg);
        });

        add(name, button);

    }

}
```

Note, the code snippet is related to https://github.com/vaadin/framework/issues/9000 (which is valid for Flow as well), but the issue here is different.

**Comment by denis-anisimov** [comment] 2018-05-17 12:31
Looks like this bug is invalid and should be closed.

There are a lot of confusions everywhere.

- First of all: binder reports a (kind of) correct status. There are no errors in validation result. Please note that you are using `@NotNull` annotation which says that the field must not be `null`.  The text field after cleaning is not `null`  it's an empty string. That's why validation has no errors. In reality we are using default conversation `""`-> `null`  and that's why the `validator` instance in the code returns `false`. But this is the issue which you already referenced:  vaadin/framework#9000 
- Now the UI doesn't report the validation status in this case. It reports the required status which is not the same as validation status. Required status is forced by the web component itself ( and the error message comes from the client side). It automatically triggered if the required indicator is set.
- The required indicator is really automatically set in this case because of `@NotNull` annotation. The default required configurator chacks the presence of `@NotNull` or `@NonEmpty` annotations and if they are there then it set required indicator visible. All other machinery is done on the client side. That's exactly the case.

So you may fix your example by setting `setRequiredConfigurator(null);`.

That's the reason of the behavior. And it's caused desync between required validation on the client side and server side validation .
Technically once vaadin/framework#9000  is fixed there will be no this issue as well.

The confusion really exists and I may set required configurator to `null`  by default to avoid this confusion.

Don't know what's better.
Your opinion ?

**Comment by mstahv** [comment] 2018-05-18 06:30
I don't know how you consider issues invalid, but I think this issue reports just one issue, pretty well: from UI developer would expect that form is not considered valid and still Binder says everything is fine. This may easily cause invalid data to be submitted to backend.

I don't want to think about the technical limitations, but as an end user I wouldn't expect that I need to configure another validator to check the field if framework automatically marks my field required. Even if it technically isn't a validator currently, the end user will think so.

The fact that it marks it automatically as required is very handy, please don't remove that. Just make it work logically.

**Comment by Legioth** [comment] 2018-05-18 07:18
So the question then is why is the text field shown as required even though Binder doesn't validate it as required?

**Comment by Legioth** [comment] 2018-05-18 08:34
So is this situation in any way different than https://github.com/vaadin/framework/issues/9000? If it isn't then this is just as much a blocker for Flow 1.x as https://github.com/vaadin/framework/issues/9000 is for FW 8.x.

**Comment by denis-anisimov** [comment] 2018-05-18 08:45
The possible solution is (as I suggested) use `setRequiredConfigurator(null);`  by default.
Would it be OK ?

Another option is to remove required Configurator from binder at all since it's not validator on the server side but it causes validation in reality on the client side.

One more option is to consider this as a duplicate of  vaadin/framework#9000 (or better to say reformulate this ticket for Flow) since the main reason : desync between client side validation and server side validation.

In Fw8 it has not been an issue since required indicator just mark the field as required and didn't do any validation by itself on the client side.
Here it's not true anymore. The client side makes its own validation which is not in sync with server side.

The `setRequiredConfigurator` method is the main problem here actually.
There may be another aspect of the issue.
Since required configurator is not validator then this is possible:
Required indicator may be based on some custom annotation which is not known for the JSR-303 validator. Let's say I'm using my custom annotation which says that a string should start from prefix `"-"`: `@Prefix("-")`. And I've implemented my custom `RequiredConfigurator` which says that field is required (in sense that it should start from `"-"`).
As already mentioned the validator ignores the annotation and binder think the field value is fine.
But required indicator is set for the field and now client side starts to "validate" the field .
Empty field is fine from the point of view of `Binder`  but it's invalid from the point of view of the client side and marked as invalid.

**Comment by denis-anisimov** [comment] 2018-05-18 08:46
One more option: disable somehow  "required" validation on the client side.
Not sure whether it's possible.

**Comment by Legioth** [comment] 2018-05-18 09:45
This all stars from an application developer mistake / ambiguity: Using `@NotNull` instead of e.g. `@Size(min=1)` or the non-standard `@NotEmpty` when binding to a field field that never has a `null` value.

Our options are basically to either help the developer understand why there is a problem, or try to deal with the situation in a way that doesn't cause too much problems for the end user.

I don't think `setRequiredConfigurator(null)` is a good idea since it would instead "break" situations where there aren't any mistakes by not showing a required indicator even if one would be expected.

One option could be to make `Binder` do an explicit `field.isEmpty()` validation for any binding for which `RequiredConfigurator` is triggered. If this is done, it should be done in a way that first tries to run the JSR 303 validator to get the error message configured in that way, and only fall back to the explicit check. This has a risk of instead causing unintended validation in other situations where there's a mismatch between how the field works and how JSR 303 works. The question is just whether that is more or less severe than the problem described here.

It can also be noted that things would again be ok-ish if there would be an explicitly configured `withNullRepresentation("")` for the binding since that would cause `""` from the field to write `null` to the bean and subsequently cause the server-side validation to fail.

**Comment by denis-anisimov** [comment] 2018-05-18 09:57
My example with custom `@Prefix("-")`  generally cannot be solved with any suggested option.

The main root of the problem is : the client-side does its own validation if the field is required.
This validation is not known for the server side.
We are just lucky that logically required configuration has some relation to the bean validation in all meaningful cases and especially in this specific case.
In reality `required configuration` functionality has no any relation to the JSR-303.
There are just a number of predefined configurations which are based on JSR-303 annotations.

`required configuration` has been added for FW8 where required indiction is just required indication and nothing else.
In Flow it causes validation on the client side which is out of the original usage.
So we may just do some workarounds which works for many usecases but it doesn't solve the problem.

I personally think that the client-side validation should be switched off (for the required field).
Then it's just a question of a proper server side validation.

**Comment by denis-anisimov** [comment] 2018-05-18 10:07
>I don't think setRequiredConfigurator(null) is a good idea since it would instead "break" situations where there aren't any mistakes by not showing a required indicator even if one would be expected.

By the way:  `expected` here is not really clear.
It's just a default behavior.
By default 3 annotations `NotNull`, `NotEmpty` and `Size` are considered.
Everything else may be configured manually.
So by `setRequiredConfigurator(null)` I suggest to force the developer to explicitly specify what he expects actually instead of guessing .......
I worked somehow good with FW8 without the client-side validation but now the situation has changed. And I would say that guessing is dangerous.
I don't insist on this. I'm just trying to consider the situation from various points of view.

**Comment by Legioth** [comment] 2018-05-18 10:18
I would claim that it didn't work well with FW8 either, as discussed in https://github.com/vaadin/framework/issues/9000. But it's indeed one step worse here when there's also automatic client side validation.

Don't see what the problem would be with `@Prefix("-")`. The field would be marked as required on the client which would cause it to be eagerly marked as invalid, then `""` would be passed to the JSR-303 validator which would say that the value is invalid and then the field would be explicitly marked as invalid also from the server.

We can override the default client-side validation by overwriting the `checkValidity()` function on the element instance to always return a static value instead of the default logic which among other things also checks whether `required` has been set.

**Comment by mstahv** [comment] 2018-05-18 10:38
Leif, this is different from the framework issue 9000, although slightly related. In FW8 the field doesn't become red without explanation, indicating that there is something wrong with that field. I just tested that it always reports it valid there too, which is not how things worked before FW8. I think that is a critical bug too, but the UI errors are not contradicting what Binder reports, which makes things even more confusing in Flow.

You also seem to think that a certain issue can be a blocker for some release like V10. It doesn't work that way. If an overall quality don't feel good enough, it shouldn't be claimed ready for GA. I have never really enjoyed using the V8 Binder (maybe because I like to use JSR 303 validators that don't really work well), now it don't seem be any better at least. We should think of making this tool handy for developers, not how to get it out as soon as possible.

I really like your idea that Binder should do isEmpty check as a special validation if it configures a field to be "required". That is what at least I'd expect it to do and I think it is not just because "that's how it used to work until version 7".

**Comment by denis-anisimov** [comment] 2018-05-18 10:51
This became tl;dr;
So I would summarize the main ways to fix this:
- use `isEmpty` as an additional validator
- disable the client-side validation

I'm OK with any. Let's just agree which one we choose.

Technically assuming `vaadin/framework#9000` is fixed this issue become also fixed, right ?
So consider this as a duplicate for `vaadin/framework#9000` is also an option. It's just another aspect of it.

**Comment by denis-anisimov** [comment] 2018-05-18 10:59
>Don't see what the problem would be with @Prefix("-"). The field would be marked as required on the client which would cause it to be eagerly marked as invalid, then "" would be passed to the JSR-303 validator which would say that the value is invalid and then the field would be explicitly marked as invalid also from the server.

I meant:
- no any JSR-303 annotation. Nothing related to JSR 303 is used.
- only custom required configurator is used which marks the field as required if there is `@Prefix`  annotation.

In this case `Binder` says that everything is OK, but the client-side validation says that it's not OK.

`isEmpty` check will work in this case of course but my main point is: the validation on the server side should be `startsWith("-")`  not `isEmpty`.

**Comment by denis-anisimov** [comment] 2018-05-18 11:03
And `isEmpty`  is strongly based on the knowledge how the client side validation works.
(the client side validation for the text field).
If for some reason the client side validation for requires is "value.trim().isEmpty()" then again everything explodes.
We are trying to inject logic which is strongly relates on the client side logic for one specific component. Which is not good from my point of view.

That's why I don't really like almost any suggested workaround.
It's the issue about client-side component specific and required configuration feature. Not binder at all.
But we are trying to solve it somehow on the binder level.

Sorry for more tl;dr;

**Comment by Legioth** [comment] 2018-05-18 11:06
Sounds like this issue should be fixed by overwriting `checkValidity()` to bring it to the same level of functionality as FW8, and then we could consider fixing vaadin/framework#9000 by adding a server-side `isEmtpy()` validator?

**Comment by Legioth** [comment] 2018-05-18 11:41
I think it would be fine to make `setRequiredIndicatorVisible(true)` overwrite `checkValidity()` to something that only looks at the `invalid` property, and then `setRequiredIndicatorVisible(false)` removes that overwrite.

If you're using e.g. `<vaadin-text-field>` without Binder and want to make it required, then you should use the `TextField::setRequired` method instead of `setRequiredIndicatorVisible`.

**Comment by denis-anisimov** [comment] 2018-05-18 11:48
Sure.
OK.
👍 

Matti, are you OK with this ?

**Comment by mstahv** [comment] 2018-05-18 12:15
I don't have that could understanding of all small details currently, but if I got it right, I think this is a good start.

I hope we can then continue fixing vaadin/framework#9000 😉 It would be nice to have that fixed for LTS version.

**Closed** 2018-05-21 17:54 UTC
Labels: binder, bug
