### ISSUE TITLE
Navigation target requires a parameter and can not be resolved

### ISSUE THREAD

**Issue by tco42** [vaadin/flow#5411] opened 2019-04-03 16:12 UTC
Vaadin-Version: 13.0.2

I created a class extending `Div` and implementing `HasUrlParameter<String>` like:
`@Route("user")`
`public class UserView extends Div implements HasUrlParameter<String>`
and implement the `setParameter` Method

`@Override`
`public void setParameter(BeforeEvent beforeEvent, String userUUID) {
    // do stuff
}`

then try to navigate to it:
`this.getUI().ifPresent(ui -> {
    ui.navigate(UserView.class, user.getId().toString());
});`

I get an error:
`There was an exception while trying to navigate to 'user/(uuid-string)' with the exception message 'Navigation target '(package).UserView' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead'`

Same error occurs if i swap `uuid.toString()` with any other string like 'abc'.

It's basically the same as in the example shown at [the navigation tutorial.](https://vaadin.com/docs/flow/routing/tutorial-routing-navigation.html)

However if i change the method implementation to
`@Override`
`public void setParameter(BeforeEvent beforeEvent, @OptionalParameter String userUUID) {
    // do stuff
}`
everything seems to work and i can even access the parameter.

**Comment by dfcortes** [comment] 2019-06-14 22:07
I'm facing the same problem, this is the exception message:

`Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:479)
	... 51 more
Caused by: java.lang.IllegalArgumentException: Navigation target 'org.example.window.views.LotteryView' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead
	at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:407)
	at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:160)
	at com.vaadin.flow.router.RouterLink.<init>(RouterLink.java:80)
	at org.example.window.MainWindow.<init>(MainWindow.java:45)`

Using Vaadin **13.0.1.**

**Comment by mehdi-vaadin** [comment] 2020-02-28 10:41
It should be verified that it can be reproduced in Vaadin 14.

**Comment by denis-anisimov** [comment] 2020-03-17 11:11
This bug is not reproducible for `14.x`.
Please use the latest versions.
I've added a unit test for this.
Closing this ticket.

**Closed by denis-anisimov** 2020-03-17 11:11 UTC
Labels: Impact: High, Severity: Major, bug, routing, tutorial

**Comment by LeoVerto** [comment] 2020-09-08 14:24
I'm running into this exact issue on Vaadin 14.3.3.

I'm creating a RouterLink like this:
```java
new RouterLink(account.getName(), UserBankAccountTransactionsView.class, "28")
```

The stracktrace I'm getting when trying to render the View using the RouterLinks is the following:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gravitasbankingsim.bankingsim.views.user.UserView]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Navigation target 'com.gravitasbankingsim.bankingsim.views.user.UserBankAccountTransactionsView' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        ... 112 common frames omitted
Caused by: java.lang.IllegalArgumentException: Navigation target 'com.gravitasbankingsim.bankingsim.views.user.UserBankAccountTransactionsView' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead
        at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:406) ~[flow-server-2.3.3.jar:2.3.3]
        at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:161) ~[flow-server-2.3.3.jar:2.3.3]
        at com.vaadin.flow.router.RouterLink.<init>(RouterLink.java:81) ~[flow-server-2.3.3.jar:2.3.3]
        at com.gravitasbankingsim.bankingsim.views.user.UserView.createMenuItems(UserView.java:26) ~[main/:na]
        at com.gravitasbankingsim.bankingsim.views.main.MainView.createMenu(MainView.java:101) ~[main/:na]
        at com.gravitasbankingsim.bankingsim.views.main.MainView.<init>(MainView.java:54) ~[main/:na]
        at com.gravitasbankingsim.bankingsim.views.user.UserView.<init>(UserView.java:19) ~[main/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        ... 114 common frames omitted
```

If I add the `@OptionalParameter` annotation the RouterLink is generated properly but the View it links to is unable to get the parameter.

**Comment by Avec112** [comment] 2021-02-12 15:34
I am on v14.4.6 and got this Exeption just now.

**Comment by vyatich** [comment] 2022-02-02 21:01
On Vaadin 14.8.3 too
