### ISSUE TITLE
Notification corrupt when not creating a dummy instance in [..]View.java

### ISSUE THREAD

**Issue by wfischlein** [vaadin/flow#5993] opened 2019-06-27 11:41 UTC
In TaskMob I have a view `TasksView.java`. In there you can delete tasks which invokes a `DeleteTaskAction`. That one shows a Notification like
```
        UI.getCurrent().access(() -> {
            Button undoButton = new Button("Undo");
            undoButton.addThemeVariants(ButtonVariant.LUMO_TERTIARY);

            Paragraph undoText = new Paragraph(item.getBuzzword());
            notification = new Notification(undoText,
                    undoButton);

            notification.getElement().getThemeList().add("undo");
            notification.getElement().getThemeList().add("dark");
            notification.setPosition(Notification.Position.BOTTOM_CENTER);
            notification.setDuration(10000);
            notification.open();
            registration = undoButton.addClickListener(event -> {
                […]
            });
        }

```

Expected:
<img width="466" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/16917619/60263229-6a98b600-98e0-11e9-85da-2a0a7cbffde2.png">

Found:
<img width="466" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/16917619/60263249-75534b00-98e0-11e9-974d-7fdd9ee6003b.png">

I can fix it by adding a dummy
    `private final Notification n = new Notification();`
to the `TasksView.java` - guess it is not supposed to work that way.

Vaadin versions: 14.0.0.beta2, 14.0.0.rc2

**Comment by wfischlein** [comment] 2019-06-27 11:48
This one might be related to/same as [this](https://github.com/vaadin/flow/issues/5986)

**Comment by Legioth** [comment] 2019-07-15 10:36
I'm quite sure this is a duplicate of https://github.com/vaadin/flow/issues/5658.

**Closed by Legioth** 2019-07-15 10:36 UTC
Labels: bug
