### ISSUE TITLE
Vaadin 14 package-for-production execution fails

### ISSUE THREAD

**Issue by go4st** [vaadin/flow#6677] opened 2019-10-14 07:38 UTC
When trying to build my Spring-Boot Vaadin application for production it always fails with following error: 

`Failed to execute goal com.vaadin:vaadin-maven-plugin:14.0.4:package-for-production (default-cli) on project vaadin-demo-bakery-app: Execution default-cli of goal com.vaadin:vaadin-maven-plugin:14.0.4:package-for-production failed: An import that ends with 'bower_components/vaadin-cookie-consent/src/vaadin-cookie-consent.html' cannot be resolved: the corresponding file 'D:\Git\vaadin-demo-bakery-app\target\frontend\bower_components\vaadin-cookie-consent\src\vaadin-cookie-consent.html' was not found.
Double check the corresponding import and verify the following:
* the import string is correct
* the file imported is either present in 'frontend://' directory of the project or in one of the project WebJar dependencies or in one of the regular jar dependencies
* if the file is present in one of the regular jar dependencies, it should be located in `META-INF/resources/frontend` directory in the jar`

Vaadin Version 14.0.5, Java 8, Spring Boot 2.1.3.RELEASE

Also tried to build the current vaadin bakery app (https://github.com/igor-baiborodine/vaadin-demo-bakery-app) which also fails with the same error.

Vaadin Version 14.0.4 , Java 8, Spring Boot 2.1.7.RELEASE

**Comment by denis-anisimov** [comment] 2019-10-14 09:54
Looks like the issue is in the `vaadin-cookie-consent-flow` .
But I see there are IT tests for bower mode. So I assume it's tested.

Anyway, I just want to double check that the ticket is about compatibility (bower) mode.
The modern mode for V14 is NPM mode and it's preferably to use this mode instead of legacy compatibility mode.
`package-for-production` is a  compatibility goal .
`build-frontend` goal should be used to build an app for production mode in NPM mode.

**Comment by go4st** [comment] 2019-10-14 10:59
Oh ok i see, i didnt noticed that the goal is a compatibility goal. I tried to build as modern mode with NPM and now found the documentation (https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html). With `mvn clean package -Pproduction` i can successfully build my application. Thank you.

**Comment by denis-anisimov** [comment] 2019-10-14 11:01
So I guess it's not an issue anymore ?
I'm closing it then.

**Comment by go4st** [comment] 2019-10-14 11:02
Yes no issue anymore!

**Closed by denis-anisimov** 2019-10-14 11:01 UTC
Labels: bug

**Comment by christian-ehmke** [comment] 2019-10-23 12:14
Since Vaadin **14.0.9** and **14.0.10** the problem **occurs again**, please reopen the issue. I am using Spring Boo: 2.2.0, Java JDK 13.0.1 and NPM 12.X.

You can reproduce the problem by using my artefact. The source code and build is documented on GitHub. Please see my links:

- [Sourcecode on GitHub](https://github.com/christian-ehmke/vaadin-starter-project)
- [Build on GitHub](https://github.com/christian-ehmke/vaadin-starter-project/commit/24b6c4948197c6c253f49bdf7cbf53c3cc9d39c0/checks?check_suite_id=277367460)
- [Download JAR fromGitHub](https://github.com/christian-ehmke/vaadin-starter-project/suites/277367460/artifacts/163164)

The problem occurs on my local Windows machine, Google Cloud Compute Engine (Ubuntu 19.04) and inside a Docker Container (Ubuntu 19.04) running on Google Cloud Run.

**Comment by earandap** [comment] 2019-11-01 19:47
I am able to reproduce in Vaadin 14.0.11

`/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/earandap/Downloads/vaadin-spring-boot-docker "-Dmaven.home=/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" "-Dmaven.ext.class.path=/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/plugins/maven/lib/maven-event-listener.jar" "-javaagent:/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/lib/idea_rt.jar=59876:/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/earandap/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/193.4778.7/IntelliJ IDEA 2019.3 EAP.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar" org.codehaus.classworlds.Launcher -Didea.version2019.3 com.vaadin:vaadin-maven-plugin:14.0.11:package-for-production -P production
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.gmail.eduardo:vaadin-spring-boot-docker >-------------
[INFO] Building vaadin-spring-boot-docker 2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:14.0.11:package-for-production (default-cli) @ vaadin-spring-boot-docker ---
[WARNING] The translated URL 'frontend://bower_components/vaadin-cookie-consent/theme/lumo/vaadin-cookie-consent.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-cookie-consent/theme/lumo/vaadin-cookie-consent.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-material-styles/typography.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-material-styles/typography.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-custom-field/theme/lumo/vaadin-custom-field.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-custom-field/theme/lumo/vaadin-custom-field.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-form-layout/theme/lumo/vaadin-form-item.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-form-layout/theme/lumo/vaadin-form-item.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-app-layout/theme/lumo/vaadin-drawer-toggle.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-app-layout/theme/lumo/vaadin-drawer-toggle.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-upload/theme/lumo/vaadin-upload.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-text-field/theme/lumo/vaadin-text-area.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-text-field/theme/lumo/vaadin-text-area.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-rich-text-editor/theme/lumo/vaadin-rich-text-editor.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-rich-text-editor/theme/lumo/vaadin-rich-text-editor.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid/theme/lumo/vaadin-grid-column.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid/theme/lumo/vaadin-grid-column.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-radio-button/theme/lumo/vaadin-radio-group.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-radio-button/theme/lumo/vaadin-radio-group.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-radio-button/theme/lumo/vaadin-radio-button.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-radio-button/theme/lumo/vaadin-radio-button.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-crud/theme/lumo/vaadin-crud-edit-column.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-crud/theme/lumo/vaadin-crud-edit-column.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-icons/vaadin-icons.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-icons/vaadin-icons.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-ordered-layout/theme/lumo/vaadin-horizontal-layout.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-ordered-layout/theme/lumo/vaadin-horizontal-layout.html'
[WARNING] The translated URL 'frontend://bower_components/iron-icon/iron-icon.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/iron-icon/iron-icon.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-text-field/theme/lumo/vaadin-number-field.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-text-field/theme/lumo/vaadin-number-field.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-list-box/theme/lumo/vaadin-list-box.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-list-box/theme/lumo/vaadin-list-box.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-login/theme/lumo/vaadin-login-overlay.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-login/theme/lumo/vaadin-login-overlay.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/icons.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/icons.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid/theme/lumo/vaadin-grid.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid/theme/lumo/vaadin-grid.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-crud/theme/lumo/vaadin-crud.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-crud/theme/lumo/vaadin-crud.html'
[WARNING] The translated URL 'frontend://bower_components/iron-list/iron-list.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/iron-list/iron-list.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-dialog/theme/lumo/vaadin-dialog.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-dialog/theme/lumo/vaadin-dialog.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-details/theme/lumo/vaadin-details.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-details/theme/lumo/vaadin-details.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-button/theme/lumo/vaadin-button.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-button/theme/lumo/vaadin-button.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-form-layout/theme/lumo/vaadin-form-layout.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-form-layout/theme/lumo/vaadin-form-layout.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-board/vaadin-board-row.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-board/vaadin-board-row.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-notification/theme/lumo/vaadin-notification.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-notification/theme/lumo/vaadin-notification.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-ordered-layout/theme/lumo/vaadin-vertical-layout.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-ordered-layout/theme/lumo/vaadin-vertical-layout.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-app-layout/theme/lumo/vaadin-app-layout.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-app-layout/theme/lumo/vaadin-app-layout.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-context-menu/theme/lumo/vaadin-context-menu.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-context-menu/theme/lumo/vaadin-context-menu.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-accordion/theme/lumo/vaadin-accordion.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-accordion/theme/lumo/vaadin-accordion.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-material-styles/color.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-material-styles/color.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/spacing.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/spacing.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-tabs/theme/lumo/vaadin-tabs.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-tabs/theme/lumo/vaadin-tabs.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid-pro/theme/lumo/vaadin-grid-pro-edit-column.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid-pro/theme/lumo/vaadin-grid-pro-edit-column.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid-pro/theme/lumo/vaadin-grid-pro.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid-pro/theme/lumo/vaadin-grid-pro.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-menu-bar/theme/lumo/vaadin-menu-bar.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-menu-bar/theme/lumo/vaadin-menu-bar.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-text-field/theme/lumo/vaadin-password-field.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-text-field/theme/lumo/vaadin-password-field.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-select/theme/lumo/vaadin-select.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-select/theme/lumo/vaadin-select.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox-group.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-checkbox/theme/lumo/vaadin-checkbox-group.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-login/theme/lumo/vaadin-login-form.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-login/theme/lumo/vaadin-login-form.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid/theme/lumo/vaadin-grid-column-group.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid/theme/lumo/vaadin-grid-column-group.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-combo-box/theme/lumo/vaadin-combo-box.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-combo-box/theme/lumo/vaadin-combo-box.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-time-picker/theme/lumo/vaadin-time-picker.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-time-picker/theme/lumo/vaadin-time-picker.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid/theme/lumo/vaadin-grid-tree-toggle.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid/theme/lumo/vaadin-grid-tree-toggle.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-text-field/theme/lumo/vaadin-text-field.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-text-field/theme/lumo/vaadin-text-field.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-charts/vaadin-chart.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-charts/vaadin-chart.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-tabs/theme/lumo/vaadin-tab.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-tabs/theme/lumo/vaadin-tab.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/style.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/style.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-split-layout/theme/lumo/vaadin-split-layout.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-split-layout/theme/lumo/vaadin-split-layout.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/typography.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/typography.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-board/vaadin-board.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-board/vaadin-board.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/sizing.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/sizing.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-date-picker/theme/lumo/vaadin-date-picker.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-date-picker/theme/lumo/vaadin-date-picker.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-item/vaadin-item.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-item/vaadin-item.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-confirm-dialog/theme/lumo/vaadin-confirm-dialog.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-confirm-dialog/theme/lumo/vaadin-confirm-dialog.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-progress-bar/theme/lumo/vaadin-progress-bar.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-progress-bar/theme/lumo/vaadin-progress-bar.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-text-field/theme/lumo/vaadin-email-field.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-text-field/theme/lumo/vaadin-email-field.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-grid/theme/lumo/vaadin-grid-sorter.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-grid/theme/lumo/vaadin-grid-sorter.html'
[WARNING] The translated URL 'frontend://bower_components/vaadin-lumo-styles/color.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-lumo-styles/color.html'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.041 s
[INFO] Finished at: 2019-11-01T16:42:31-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.0.11:package-for-production (default-cli) on project vaadin-spring-boot-docker: Execution default-cli of goal com.vaadin:vaadin-maven-plugin:14.0.11:package-for-production failed: An import that ends with 'bower_components/vaadin-cookie-consent/src/vaadin-cookie-consent.html' cannot be resolved: the corresponding file '/Users/earandap/Downloads/vaadin-spring-boot-docker/target/frontend/bower_components/vaadin-cookie-consent/src/vaadin-cookie-consent.html' was not found.
[ERROR] Double check the corresponding import and verify the following:
[ERROR] * the import string is correct
[ERROR] * the file imported is either present in 'frontend://' directory of the project or in one of the project WebJar dependencies or in one of the regular jar dependencies
[ERROR] * if the file is present in one of the regular jar dependencies, it should be located in `META-INF/resources/frontend` directory in the jar
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`
