### ISSUE TITLE
Upgrading to V22 causes mobx to be downgraded to 6.1.5

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11799] opened 2021-09-08 17:15 UTC
Given a project using V21 and mobx 6.3.3. If you upgrade from V21 to V22 alpha 3, then package.json is updated
```
-    "mobx": "^6.3.3",
+    "mobx": "^6.1.5",
```

This should not happen. 

```
vaadin init hello-v21 --preset fusion
cd hello-v21
# Change version from 21 to 22.0.0.alpha3
mvn
# Mobx is still the correct version
mvn
# Mobx is now changed to 6.1.5
```

**Comment by haijian-vaadin** [comment] 2021-09-09 19:18
I just downloaded a new Vaadin 21 Fusion app from the starter, then updated it to Vaadin 22.0.0.alpha3 and Flow 9.0.0.alpha4. Not able to reproduce the problem. `mobx` stays as `^6.3.3` and the app works fine.

I suspect that you are not using a fresh v21 app, but an app with a previous v21 version without [this fix](https://github.com/vaadin/flow/pull/11651), which the `mobx` is also added to vaadin dependencies, so that when upgrading the dependency got removed by [TaskUpdatePackages](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java#L257-L267).

**Comment by Artur-** [comment] 2021-09-10 06:57
I think (did not verify) the issue is the following:
1. Vaadin 21 alpha 3 bundles mobx 6.1.5. It downgrades the project to mobx 6.1.5 from 6.3.3. This is the bug that should be fixed with this issue. Maybe the generic issue is "If the project already has a dependency X and Vaadin adds this dependency, then Vaadin forces the version of X to be the one defined by Vaadin"
2. Vaadin 21 alpha 4 no longer bundles mobx so package.json is cleaned up. As mobx is removed from the "vaadin" section and the version matches in the `dependency` section, it is removed from both places.

So the complete removal only happens if you upgrade first to alpha3 and then to alpha4

**Comment by haijian-vaadin** [comment] 2021-09-14 11:45
For 1. Need to check if it's still a problem for user dependencies, or was it just caused the Fusion task that was introduced up to Vaadin 22 alpha3.
For 2. It only happens when upgrading from alpha3 to alpha4, I think we won't fix this particular issue.

**Comment by haijian-vaadin** [comment] 2021-09-15 08:36
I just verified the version downgrade problem, it's introduced by the already removed fusion task. Now the versions don't downgrade anymore. 

I think we can now close this issue.

**Closed by haijian-vaadin** 2021-09-15 08:36 UTC
Labels: fusion
