### ISSUE TITLE
Material Theme - Flow - Dialog set width does not work from java

### ISSUE THREAD

**Issue by anandguardx** [vaadin/flow#4926] opened 2019-01-04 22:38 UTC
- Description of the bug
I am creating a dialog from java which is set the width and height to be 1200px each. Works fine in Lumo Theme, does not work fine when the page is in Material Theme.

- Minimal reproducible example
```
Dialog d = new Dialog();
Label l = new Label("FOOBAR");
d.add(l);
d.setCloseOnEsc(true);
d.setCloseOnOutsideClick(false);
			
d.setHeight("1200px");
d.setWidth("1200px");
			
d.open();
```
- Expected behavior
Dialog width setting should work in both Lumo and Material Theme

- Actual behavior
Dialog width setting works in Lumo theme but does not work in Material Theme. It is being set to 497px

- Versions:
    - Vaadin / Flow version: 12.0.3
    - Java version: Java 9
    - OS version: Mac OS X - latest version
    - Browser version (if applicable) - Chrome latest version

**Comment by bogdanudrescu** [comment] 2019-01-11 13:44
It is reproducible with java 8 as well as other platform version (eg. 12.0.1), and Safari as well.

**Comment by web-padawan** [comment] 2019-01-11 14:06
Most likely duplicate of vaadin/vaadin-dialog#127

**Comment by bogdanudrescu** [comment] 2019-01-14 12:57
@anandguardx, this is indeed a duplicate of https://github.com/vaadin/vaadin-dialog/issues/127, please look for the solution there.

**Closed** 2019-01-14 12:58 UTC
