### ISSUE TITLE
client-side expection when using callFunction from beforeClientResponse

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#2873] opened 2017-11-08 12:39 UTC
This happens when using `callFunction` in `beforeClientResponse` from a `Component` injected with `@Id`.

To reproduce this issue you need a simple Component with some client-side API:
```
@Tag("example-component")
@HtmlImport("ExampleComponent.html")
public class ExampleComponent extends Component {
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        attachEvent.getUI().beforeClientResponse(this, () -> greet());
    }
    public void greet() {
        getElement().callFunction("greet");
    }
}
```
```
<dom-module id="example-component">
    <template>
    </template>
    <script>
        class ExampleComponent extends Polymer.Element {
            static get is() {
                return 'example-component'
            }
            greet(){
              window.alert('👋');
            }
        }
        customElements.define(ExampleComponent.is, ExampleComponent);
    </script>
</dom-module>
```

And a simple `PolymerTemplate` view including that component and injecting it by `@Id`
```
@Tag("example-template")
@HtmlImport("template/ExampleTemplate.html")
@Route("template")
public class TemplateView extends PolymerTemplate<TemplateModel> {
    @Id("component-id")
    private ExampleComponent component;
}
```

```
<dom-module id="example-template">
    <template>
      <example-component id="component-id"></example-component>
    </template>
    <script>
        class ExampleTemplate extends Polymer.Element {
            static get is() {
                return 'example-template'
            }
        }
        customElements.define(ExampleTemplate.is, ExampleTemplate);
    </script>
</dom-module>
```

Expected result when navigating to the `template` route is to only see the result of `alert('👋')`.
Actual result is the greeting and the following exception:
>(TypeError) : Cannot read property 'greet' of undefined

**Comment by Legioth** [comment] 2017-11-08 17:04
Seems like the same issue as https://github.com/vaadin/flow/issues/2817.

**Comment by denis-anisimov** [comment] 2017-11-09 06:01
Most likely yes.

**Comment by denis-anisimov** [comment] 2017-11-09 06:03
Well, not most likely.
It's exactly the same issue.

I'm closing this as a duplicate of #2817.

**Closed by denis-anisimov** 2017-11-09 06:03 UTC
