### ISSUE TITLE
@vaadin/form Binder constructor fails when entity has a @Nullable List property

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9049] opened 2020-09-22 08:51 UTC
When trying to open the contact list view of [Vaadin CRM](https://github.com/vaadin-learning-center/crm-tutorial-typescript) I see only a blank screen and the browser console has run time errors claiming that the `private binder = new Binder(this, ContactModel);` line throws when trying to set the initial empty value to the binder:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/22416150/93861421-26ee5100-fcc9-11ea-914b-2946e271e915.png">

Works fine with Vaadin 17.0.2 / Flow 4.1-SNAPSHOT but fails with Vaadin 17.0.2 / Flow 5.0-SNAPSHOT.

```java
@Entity
public class Contact extends AbstractEntity implements Cloneable {
    @ManyToOne
    @JoinColumn(name = "company_id")
    @JsonIgnoreProperties("employees")
    @NotNull
    private Company company;
}
```

```java
@Entity
public class Company extends AbstractEntity {
  @OneToMany(mappedBy = "company", fetch = FetchType.EAGER)
  @Nullable
  private List<Contact> employees = new LinkedList<>();
}
```

It looks like with 5.0-SNAPSHOT the empty `Contact` value includes `company.employees: undefined`, which Binder does not expect.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/22416150/93861756-b562d280-fcc9-11ea-8ded-dec5b08c9bb3.png">

**Comment by haijian-vaadin** [comment] 2020-10-02 12:37
The crm tutorial is now working after https://github.com/vaadin-learning-center/crm-tutorial-typescript/pull/19 is merged. The root cause of this problem is #8849.

Let's close this one and implement #8849 either with a custom annotation (@TypeScriptOptional or similar) or change the default to nullable in the generated TS code.

**Closed by haijian-vaadin** 2020-10-02 12:37 UTC
Labels: Impact: High, Severity: Major, bug, ccdm
