### ISSUE TITLE
Unable to detect version of pnpm. Using command ...\bin\npx.cmd --yes --quiet pnpm@5 --version

### ISSUE THREAD

**Issue by Dudeplayz** [vaadin/flow#11081] opened 2021-05-26 16:10 UTC
### Description of the bug
FrontendTools can't find the pnpm package. If I run `npx --yes --quiet pnpm@5 --version` in console nothing is returned. Using `npx --yes --quiet pnpm --version` it returns the proper version. Tried with PowerShell and cmd on Windows 10.

I think the detection should be performed without the `@5` version specifier.

```log
2021-05-26 17:40:39 [vert.x-worker-thread-0] WARN  FrontendTools - version check 'C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm@5' failed
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm@5 --version
	at com.vaadin.flow.server.frontend.FrontendUtils.getVersion(FrontendUtils.java:809) ~[flow-server-2.5.4.jar:2.5.4]
	at com.vaadin.flow.server.frontend.FrontendTools.validatePnpmVersion(FrontendTools.java:712) ~[flow-server-2.5.4.jar:2.5.4]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
```

### Minimal reproducible example
Install pnpm[@5] with graalvm npm and run the above-mentioned commands.

### Expected behavior
Detection of correct pnpm version.

### Actual behavior
No version is detected.

### Versions:
    - Vaadin / Flow version:
    - Java version: `dcevm-11.0.10.+2`
    - OS version: `Windows 10 20H2`
    - IDE (if applicable): `IntelliJ IDEA 2021.1.1`
    - GraalVM node.js: `21.1.0` (used for `npm install -g pnpm`)

**Comment by pleku** [comment] 2021-06-23 09:15
On Windows 10, for me everything works out fine with any hotspot Java version using Vaadin 14.6.3. This is from Powershell 7:
```
PS C:\Users\Pekka\workspaces\flow\skeleton-starter-flow> java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
PS C:\Users\Pekka\workspaces\flow\skeleton-starter-flow> npx --yes --quiet pnpm@5 --version
5.18.9
PS C:\Users\Pekka\workspaces\flow\skeleton-starter-flow> npx --yes --quiet pnpm --version
6.9.0
```
The reason why it is using `pnpm@5` is that version 6 require at least Node.js v12.17.
To use pnpm 6, you could specify `vaadin.ignoreVersionChecks=true` but IIRC the version pinning frontend dependencies will not work as the pnpmfile.js is changed to pnpmfile.cjs.

I'll test this still with GraalVM.

**Comment by pleku** [comment] 2021-06-23 11:10
After uninstalling `pnpm` from global + `.vaadin` and removed `node_modules` and using GraalVM, everything still works
```
[ForkJoinPool.commonPool-worker-19] INFO com.vaadin.flow.server.frontend.FrontendTools - using 'C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5' for frontend package installation
```

So @Dudeplayz please update your Vaadin version to latest 14.6 release and try again. If the issue still reproduces, you'll have to provide all the steps to reproduce it and what node.js version you're using.

**Comment by Dudeplayz** [comment] 2021-06-29 21:27
Hi, I will test it soon. Didn't have the time until now.

**Comment by Dudeplayz** [comment] 2021-07-01 09:49
@pleku the command you mentioned is using nodejs. I am using the node implementation of GraalVM. I've tested it again and have deinstalled any pnpm package and reinstalled it with `npm install -g pnpm@5`. The maven build still shows:

```
[WARNING] version check 'C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm@5' failed
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm@5 --version
    at com.vaadin.flow.server.frontend.FrontendUtils.getVersion (FrontendUtils.java:824)
    at com.vaadin.flow.server.frontend.FrontendTools.validatePnpmVersion (FrontendTools.java:712)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:176)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
```

When I run the command `C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm@5 --version` in any shell it returns nothing. When running `C:\DEV\RUNTIME\graalvm-ce-java11-21.1.0\bin\npx.cmd --yes --quiet pnpm --version` (without @5) it correctly returns `5.18.9`.

**Comment by Dudeplayz** [comment] 2021-07-01 10:35
I tried it now by installing `nodejs 14.17.1`. Still the same problem:
```
[WARNING] version check 'C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5' failed
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of pnpm. Using command C:\Program Files\nodejs\npx.cmd --yes --quiet pnpm@5 --version
    at com.vaadin.flow.server.frontend.FrontendUtils.getVersion (FrontendUtils.java:824)
    at com.vaadin.flow.server.frontend.FrontendTools.validatePnpmVersion (FrontendTools.java:712)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:176)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
```

Here also, if running without the `@5` it works in the shell.

**Comment by Artur-** [comment] 2021-07-01 10:53
Isn’t `@` a special character in windows? Does it work if you out quotes around pnpm, i.e `”pnpm@5”`

**Comment by Dudeplayz** [comment] 2021-07-01 11:06
@Artur- I tested it. Doesn't solve the problem. I've tried:
```powershell
& "C:\Program Files\nodejs\npx.cmd" --yes --quiet "pnpm@5" --version
& "C:\Program Files\nodejs\npx.cmd" --yes --quiet 'pnpm@5' --version
```

Again...
```powershell
& "C:\Program Files\nodejs\npx.cmd" --yes --quiet "pnpm" --version
& "C:\Program Files\nodejs\npx.cmd" --yes --quiet 'pnpm' --version
```
are working.

I can't exclude that is a specific problem with my Windows-Environment or my network mapped user path (domain).
But I think running pnpm without the `@5` and then validating the returned version should do the same job? Even if another pnpm version is installed e.g. `6`, then is the version string 6.x.x and this could be also validated to not be version 5.x.x.

**Comment by Dudeplayz** [comment] 2021-07-05 14:13
I now understand, that the `@5` is used in case of multiple pnpm versions installed. Is this correct @pleku?

I also tried to run pnpm on my laptop and there works everything like wanted. So the problem is maybe caused by my setup. I will try to find the reason and come back.

**Comment by denis-anisimov** [comment] 2021-07-26 08:11
No any updates within 3 weeks. 
I'm closing the issue. 
Please provide details if it's still valid.

**Closed by denis-anisimov** 2021-07-26 08:11 UTC
Labels: waiting for author
