### ISSUE TITLE
webpack is left running when killing the server in Eclipse

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#6291] opened 2019-08-20 13:04 UTC
Take any V14 project, e.g. empty starter for plain java.

Start it as `mvn jetty:run` in Eclipse
Wait until it starts, then kill it using the red stop button.

`webpack-dev-server` keeps running even though the server is killed.

When I reached 68 instances running at the same time, I ran out of file descriptors or something and hot deployed stopped working with the error message
```
[webpack] ERROR dev-webpack - 2019-08-20 15:56 node[40312] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by denis-anisimov** [comment] 2019-08-29 09:54
I'm not able to reproduce it.
I'm using https://github.com/vaadin/skeleton-starter-flow.
The project has been started using project's context menu item "Run As" , `maven jetty:run`.
I used the "Terminate" button in the "Console" tab.
After that I don't see any running `webpack-dev-server`  process.
The only issue which I see is an Eclipse dialog about the process termination failure.
But in fact everything is terminated. So this is not a serious issue.

Do you still have this issue ?
I guess you are using Mac OS, right ?
I don't like how the web pack process is stopped: it's done via JVM shutdown hook which is not the booletproof solution here (or just a bad solution at all).
But I can't figure out anything better.

**Comment by pleku** [comment] 2019-09-05 07:20
Related https://github.com/vaadin/flow/issues/6281

**Comment by ujoni** [comment] 2019-09-05 07:42
### Acceptance criteria:
- [ ] Determine what is the most efficient way to implement "process watchdog" for the webpack
  - Are we able to tie the webpack process' lifecycle to that of the initiating Java process on all platforms ** (signal)?
    - [ ] Yes
    - [ ] No
  - Can we add a watchdog onto the webpack which follows the state of the initiating Java process on all platforms **
    - [ ] Yes
    - [ ] No
- [ ] Implement the selected fail-safe to make sure that Webpack process is terminated alongside the Java process

**) Windows, Mac, Ubuntu (others?)

**Comment by Legioth** [comment] 2019-09-18 06:20
Looks like this also affects Spring Boot: https://github.com/vaadin/spring/issues/491

**Comment by Legioth** [comment] 2019-09-18 06:39
At least for the case of killing from Eclipse on OS X, reading on a TCP socket input stream is a reliable way of detecting when another process is killed.

The benefit of this approach is that we don't have to do any explicit polling with a polling interval that is either too long (i.e. causing latency) or too short (i.e. causing overhead).

Instead, the operating system will take care of closing the TCP socket when the owning process is terminated, even if the process is terminated in a way that doesn't trigger the JVM shutdown hooks.

For a real solution, we would have to ensure this works on other operating systems as well. We might also have to look into whether we need to occasionally send something over the socket to prevent it from timing out. This can be done with a relatively long interval so it shouldn't cause the same kind of overhead as with polling.

```
public class Server {
    public static void main(String[] args) throws IOException, InterruptedException {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Shutdown hook triggered");
        }));

        ServerSocket server = new ServerSocket(54398);
        System.out.println("Waiting on port " + server.getLocalPort());

        Socket socket = server.accept();
        System.out.println("Got a connection");

        Thread.sleep(Long.MAX_VALUE);
    }
}
```
```
public class Client {
    public static void main(String[] args) throws UnknownHostException, IOException {
        Socket socket = new Socket("localhost", 54398);
        System.out.println("Opened socket to " + socket.getPort());

        InputStream inputStream = socket.getInputStream();
        System.out.println("Opened input stream, starting to read");

        int read = inputStream.read();
        System.out.println("read " + read);
    }
}
```

**Comment by ujoni** [comment] 2019-09-18 07:42
The TCP socket solution seems to work just fine on Windows 10 machine. Also, `socket.setSoTimeout(0);` claims to set an infinite timeout, so in ideal world, we got of easy.

**Comment by denis-anisimov** [comment] 2019-09-18 08:10
>Also, socket.setSoTimeout(0); claims to set an infinite timeout

**Comment by ujoni** [comment] 2019-09-18 08:27
> It's the default value, isn't it ?

For the default implementation, yes. 
If the user is using JBoss, do they automatically get JBoss's socket implementations? Or do they need to explicitly use those? JBoss has some non-zero defaults (60000ms for server and 1800000ms for a client socket).

**Comment by denis-anisimov** [comment] 2019-09-18 08:33
JBoss ?

I'm not sure how this relates to JBoss or any web server impl.

The server code will be implemented by us internally via a separate Thread inside `DevModeInitializer`: it doesn't relate to any web server.

The code in the `Client`  class won't be Java code at all, it should be somewhere inside dev server and it's not related to Java and as a result any web server as well.

**Comment by denis-anisimov** [comment] 2019-09-19 05:58
Just for the reference: reliable steps to reproduce the issue on Mac OS.

- Use skeleton-starter.
- Run `mvn jetty:run`.
- Find (maven)Java process pid.
- Make sure that webpack dev server is running (`ps ax| grep webpack-dev-server.js`).
- kill Java process ( `kill -9 java_porcess_pid`).
- Check that webpack process is still alive.

This way I may reliably reproduce the behavior described in the ticket. Look like (at least `9` signal) kills JVM to that it's not able to run shutdown hook and the webpack dev server process remain alive after JVM exit.

With the upcoming PR these steps don't leave the webpack process anymore.

**Closed** 2019-09-19 11:12 UTC
Labels: bug, investigation
