### ISSUE TITLE
Switching between theme folders causes endless reload loop

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#10451] opened 2021-03-29 08:17 UTC
### Description of the bug / feature

Adding two (or more) Theme folders and switching the `@Theme` annotation from one `themeFolder` value to another after starting the app once causes the browser to end up in an endless reload loop.

### Minimal reproducible example
https://github.com/OlliTietavainenVaadin/v14-6-pit
* Started from a Vaadin 14.5 project from Vaadin Start, updated to `14.6.0.alpha1` to test the new theme system. 
* Created two theme folder, `custom` and `custom2`
* Added a `styles.css` with different values to each theme
* Added a `@Theme(themeFolder="custom")` annotation to the `MainView`, started the app, and opened it in the browser
* Switched the theme annotation to `@Theme(themeFolder="custom2")`, restarted the app, and opened it in the browser

### Expected behavior
App should switch to the theme `custom2`
### Actual behavior
App ends up in a reload loop
### Versions:
    - Vaadin / Flow version: 14.6.0.alpha1
    - Java version: 11
    - OS version: Windows 10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): spring-boot
    - IDE (if applicable): IntellJ Idea

**Comment by pleku** [comment] 2021-03-29 11:05
Switching the theme from one to another requires restarting the server, if it is running already. This is at least how I've understood it. And that is also the workaround for now so I'm not marking this as a blocker as it is trivial to apply the workaround.

**Comment by OlliTietavainenVaadin** [comment] 2021-03-29 12:58
Yes, I can confirm, you need to stop the server completely and restart it (the autoreload's restart isn't enough). So it's annoying but not a blocker.

**Comment by mshabarov** [comment] 2021-03-30 12:48
I've not yet tried the app example to reproduce it, but I got this step:
`Switched the theme annotation to @Theme(themeFolder="custom2"), restarted the app, and opened it in the browser`
as a manual restart of the server, so put a blocker in there.

If the manual restart does the trick, then ofc it's not a blocker.

BTW, the custom theme documentation states that you cannot switch the theme on the fly https://vaadin.com/docs/v14/flow/styling/custom-theme/#limitations

**Comment by pleku** [comment] 2021-03-31 07:11
First we should check that what is the reload loop about (probably by webpack?) and try to avoid it and fail more graciously and make it clear that a restart is needed. We can then spend time on investigating how we could just make the theme (annotation) scanning work during development so that we could enable swapping the theme on the fly. There are some options for this. We should spend a few days timebox to investigate our options for improving this.

**Comment by mshabarov** [comment] 2021-04-06 15:40
Reload loop happens due to webpack recompilation infinite loop, which, in turn, happens because `theme-live-reload-plugin` enables webpack recompilation upon adding `custom2.generated.js`, which is being generated once one manually changes the theme name from `custom` to `custom2` in `@Theme` annotation.

`theme-live-reload-plugin` blocks only those auto-generated files whose names are equal to current theme name file:
```javascript
if (file.indexOf(this.themeName + '.generated.js') > -1)
```
but it passes other files.
As a result, adding the `custom2.generated.js` triggers live-reload and an infinite loop.
Replacing it with
```javascript
if (file.endsWith('.generated.js')) {
```
should fix the issue and make the changing theme name on the fly smoothly.

Last Flow versions (7.0) have generated theme file is being places into the `generated` folder and `theme-live-reload-plugin` does not need to check the file name at all.

**Closed** 2021-04-23 09:11 UTC
Labels: Impact: High, Released with Platform 14.6.0.beta2, Severity: Major, bug, prerelease version for platform 14.6.0, theming
