### ISSUE TITLE
Bean Validation Messages are not shown

### ISSUE THREAD

**Issue by eiswind** [vaadin/flow#6898] opened 2019-11-10 09:43 UTC
The information below is extra.

Use this comment to reproduce: 
https://github.com/vaadin/flow/issues/6898#issuecomment-553410077

Taken the following class:

```
class TitleElementComponent : HorizontalLayout() {

    val titleText = TextField()
    val subtitle = TextField()
    val titleElementLevel = ComboBox<List149>()

    val binder = BeanValidationBinder(OTitleElement::class.java)

    init {
        titleText.element.classList.add("full-width")
        subtitle.element.classList.add("full-width")

        add(titleText, subtitle, titleElementLevel)
        titleElementLevel.setItems(*List149.values())
        titleElementLevel.setItemLabelGenerator { c -> c.text }
        binder.bindInstanceFields(this)
        binder.validate()
    }
}
```

with OTitleElement Validation defined in xml:

```
<bean class="de.eiswind.onixbinding.onix3.dto.OTitleElement">
        <getter name="titleText">
            <constraint annotation="javax.validation.constraints.NotBlank"></constraint>
        </getter>
        <getter name="titleElementLevel">
            <constraint annotation="javax.validation.constraints.NotNull"></constraint>
        </getter>
    </bean>
```
with 14.0.12 binder validate reports some errors, but some of them only contain null values. None of the errors gets shown in the ui.

![Bildschirmfoto von 2019-11-10 10-46-26](https://user-images.githubusercontent.com/1238044/68542020-8e4c2c80-03a7-11ea-9b4b-a9206761e239.png)

I also noticed that the requiredIndicator is not showing up. The docs state that ```@NotBlank``` should trigger this by default.

**Comment by thigg** [comment] 2019-11-12 13:52
Can confirm, it works only for @NotEmpty in vaadin 14.
I created  a minimal not working example in this [repo](https://github.com/thigg/vaadin-validationbinder-minimal-nonworking-example)  I have one tag with vaadin13, which works and shows everything correctly, and one with vaadin 14, which doesn't.

**Comment by denis-anisimov** [comment] 2019-11-13 10:44
Hi, could you please provide an example which I can use to copy-paste ?
Or may be a project which I can use to reproduce this.

I cannot reproduce this issue with my project.
I'm using https://github.com/vaadin/skeleton-starter-flow.

Here are changes :
```
```

**Comment by eiswind** [comment] 2019-11-13 12:15
I cannot exaclty reproduce it. But if you look at
https://github.com/eiswind/skeleton-starter-flow

1) message is shown on blank field
2) enter text message dissapears as expected
3) delete text: message should reappear but does not

**Comment by thigg** [comment] 2019-11-13 13:13
Were you able to reproduce the issue with vaadin 14 now, or should I explain what I did in https://github.com/thigg/vaadin-validationbinder-minimal-nonworking-example ?

**Comment by denis-anisimov** [comment] 2019-11-13 13:44
There is a huge amount of extra information.

In the initial example `binder.validate()` is called.
In the https://github.com/eiswind/skeleton-starter-flow example it's not called.
In the latter example everything is added dynamically but in fact this is extra.

`BeanValidationBinder` with annotations is also extra here.

In fact the simplest example with trivial validator doesn't work:
```
public class MainView extends VerticalLayout {

    private TextField titleText = new TextField();

    private Binder<Bean> binder = new Binder<>(Bean.class);

    public MainView() {
        add(titleText);

        binder.forField(titleText)
                .withValidator(value -> !value.isEmpty(), "a")
                .bind("titleText");

        Bean bean = new Bean();
        binder.setBean(bean);
    }

}
```

Steps to reproduce:
- run
- enter something to the text field, commit ( press ENTER)
- remove , commit

No any error on the client side.

In fact the error message is sent.
But `invalid` flag is not sent for some reason.
As a result on the client side the element has `invalid`  `false` and nothing is shown.
I'm not sure where the bug is .
May be it's in the `vaadin-text-field-flow`.

**Comment by denis-anisimov** [comment] 2019-11-13 13:46
It might be that this is the same as https://github.com/vaadin/vaadin-date-picker-flow/issues/203

**Comment by denis-anisimov** [comment] 2019-11-14 08:16
So the original ticket is in `vaadin-text-field-flow` : https://github.com/vaadin/vaadin-text-field-flow/issues/257.

I'm closing this ticket in favor of the component's ticket.

**Closed by denis-anisimov** 2019-11-14 08:16 UTC
