### ISSUE TITLE
Can't select row of grid on IE11( works fine in Google Chrome, Firefox, Safari)

### ISSUE THREAD

**Issue by YeTingGe** [vaadin/flow#4611] opened 2018-09-17 03:18 UTC
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues concerning certain component should go to the corresponding components repository.

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Description of the bug
On Windows 7, with IE11,  set Grid as Grid.SelectionMode.MULTI mode and add it to a SplitLayout. The issue is you can't select any column within a single click in IE11 only. 
It works fine in Google Chrome, Firefox, Safari. 
Edge is not tested.

- Minimal reproducible example
    private class HeadInfo {
        int index;
        String name;

        public HeadInfo(int index, String name) {
            this.index = index;
            this.name = name;
        }

        public int getIndex() {
            return index;
        }

        public String getName() {
            return name;
        }
    }
    private final Grid<HeadInfo> grid = new Grid<>();
    private final GridSelectionModel<HeadInfo> selectionMode = grid.setSelectionMode(Grid.SelectionMode.MULTI);
    private final Grid.Column<HeadInfo> idColumn = grid.addColumn(HeadInfo::getIndex).setHeader("ID")
            .setFlexGrow(0).setWidth("75px");
    private final Grid.Column<HeadInfo> nameColumn = grid.addColumn(HeadInfo::getName)
            .setHeader("Name").setFlexGrow(1);

- Expected behavior
You can select any row display in Grid with a single click.

- Actual behavior
Sometimes, you can select a row by click on the checkbox multiple times 
Select all button always works fine.

**Comment by ZheSun88** [comment] 2018-09-17 05:38
This is a duplicated issue, as you have already created https://github.com/vaadin/vaadin-grid-flow/issues/331. 

If the issue is about the flow components, you only need to create a ticket the component repo. Thanks. We are going to close this issue.

**Closed by ZheSun88** 2018-09-17 05:38 UTC
