### ISSUE TITLE
Vaadin 24.5.0 Layout issue

### ISSUE THREAD

**Issue by alexanoid** [vaadin/flow#20271] opened 2024-10-16 19:46 UTC
### Description of the bug

I have a page that is divided into two sections: the central part and the right sidebar, which contains a Form Layout:

After the initial visit to the page, everything is displayed correctly:

![normal](https://github.com/user-attachments/assets/e93cd522-a208-4641-ac53-9a1d51f0c9f1)

But if I press F5 in the browser (for example, in Google Chrome) to refresh the page, all the components in the Form Layout get clustered together:

![not_normal](https://github.com/user-attachments/assets/69290019-05e9-487a-a4b9-a27d42061574)

In Vaadin Flow versions 24.4.x, such issues do not occur

### Expected behavior

After the page reloads, its appearance should not break

### Minimal reproducible example

n/a

### Versions

- Vaadin / Flow version: 24.5.0
- Java version: 17
- OS version: Windows 10
- Browser version (if applicable): Google Chrome

**Comment by mcollovati** [comment] 2024-10-17 06:27
Unfortunately, I cannot reproduce.
Please provide a reproducible example, or at least detailed information about how your view is built.

**Comment by alexanoid** [comment] 2024-10-17 07:38
The view content is created in the `com.vaadin.flow.router.HasUrlParameter#setParameter` method.

There is a `VerticalLayout `with a central part and a right sidebar. The `FormLayout `is in the right sidebar. 

The content of the central part and the sidebar is delivered asynchronously via `@Push(transport = Transport.WEBSOCKET_XHR, value = PushMode.MANUAL)` after the initial page creation. This might be the reason...

**Comment by knoobie** [comment] 2024-10-18 07:44
@web-padawan Could this be related to the fix you did yesterday? https://github.com/vaadin/web-components/pull/7988

**Comment by web-padawan** [comment] 2024-10-18 19:36
Yes, I suppose it's related to the same regression and should be fixed in the next patch release.

**Comment by alexanoid** [comment] 2024-10-22 07:42
@web-padawan I previously mentioned that this issue was absent in Vaadin 24.4.x, but now I also see it in Vaadin 24.4.14

**Comment by web-padawan** [comment] 2024-10-22 08:00
Yes, the latest version of v24.4 unfortunately includes the same PR for `vaadin-form-layout` that caused a regression.
We'll make new patch releases of 24.5 and 24.4 this week to include https://github.com/vaadin/web-components/pull/7988 which fixes it.

**Comment by mshabarov** [comment] 2024-10-22 10:41
Upcoming Vaadin 24.4.15 and Vaadin 24.5.1 should contain the mentioned fix.
Closing this issue.
Let us know if you experience this issue again in these future releases.

**Closed by mshabarov** 2024-10-22 10:41 UTC
Labels: waiting for author
