### ISSUE TITLE
TextField value not available in KeyUp listener

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4048] opened 2018-05-02 09:50 UTC
```
textField.addKeyUpListener("Enter", e -> {
    System.out.println("Committed "+textField.getValue());
});
```

Expected result after typing `123` and pressing enter:
"Committed 123"

Actual result:
"Committed "

**Comment by Legioth** [comment] 2018-05-02 10:46
That's kind-of the way HMTL works. The browser doesn't update the `value` property until after all key events have been delivered, since any of those might still do `preventDefault()` which would prevent the `value` property from being updated.

What we could do is to slightly delay the outgoing HTTP request until the next microtask or macrotask so that the property change event could also make it in the same round trip.

**Comment by Artur-** [comment] 2018-05-02 12:00
Still would not work as expected as `TextField` by default sends value only on `change` and adding a key listener does not change that

**Comment by Legioth** [comment] 2018-05-03 09:52
I think that for that to work, there should be possible to separately define "eager" and "lazy" synchronization triggers for a property.

A lazy trigger doesn't trigger a round trip, but still marks the property as changed in a way that the update will be sent out the next time anything causes a request to be sent, i.e. similar to `@Delayed(lastOnly = true)` in FW8.

Eager triggers would also cause a request to be sent immediately.

**Comment by pleku** [comment] 2018-05-03 11:47
You should not need a key up listener for `ENTER` key, as pressing enter will fire the basic value change event by default on the server side. So adding a key-up listener seems to me like an anti-pattern. Why would you want to do that ?

**Comment by Artur-** [comment] 2018-05-03 11:55
To get an event when the user presses enter so the value can be saved. Would be quite strange UX in some cases to handle blur the same way as enter

**Comment by heruan** [comment] 2018-05-06 08:30
Note that pressing <kbd>ENTER</kbd> enter will fire a `change` event, but the input won't blur.

**Comment by AlainaFaisal** [comment] 2024-06-11 07:23
Closing this issue as the expected behaviour in the initial description is working correctly when tested with Vaadin 24.3.12 version.

**Closed by AlainaFaisal** 2024-06-11 07:23 UTC
Labels: invalid
