### ISSUE TITLE
Browser error when adding @PWA to an app in express mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#15888] opened 2023-02-10 10:47 UTC
### Description of the bug

When you add `@PWA` to a newly created app, you see an error on startup
<img width="46" alt="image" src="https://user-images.githubusercontent.com/260340/218073135-2b35a120-f6be-4a36-a22e-edee5e174c58.png">

```
TypeError: Failed to register a ServiceWorker for scope ('http://localhost:32462/') with script ('http://localhost:32462/sw.js'): A bad HTTP response code (404) was received when fetching the script.
```

### Expected behavior

There is no error, PWA works and adds icons etc

### Minimal reproducible example

```
vaadin init --next v24snap
cd v24snap
npx upgrade-vaadin 24.0-SNAPSHOT
#Add `@PWA(name = "foo", shortName = "foo")` to Application.java
mvn
```

### Versions

- Vaadin / Flow version:24.0 snapshot

**Comment by mshabarov** [comment] 2023-02-17 13:20
I tried with both `<vaadin.version>24.0-SNAPSHOT</vaadin.version>` and `24.0.0.beta2` but couldn't reproduce this error.

**Comment by Artur-** [comment] 2023-02-17 15:03
I cannot anymore either

**Comment by Artur-** [comment] 2023-02-17 15:04
No seems a new snapshot application builds a bundle...

```
2023-02-17T17:04:00.431+02:00  INFO 82226 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Checking if an express mode bundle build is needed
2023-02-17T17:04:00.535+02:00  INFO 82226 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Detected changed content for jar-resource:
 - datepickerConnector.js
```

**Comment by Artur-** [comment] 2023-02-17 16:55
So by using
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-date-picker-flow</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

you can see the problem. Nobody serves /sw.js in express mode it cannot really work. You might need to delete an existing service worker also to see it. Or just try to load http://localhost:8080/sw.js

**Comment by mshabarov** [comment] 2023-06-14 06:41
Closed as two pull request related to this issue have been merged.

**Closed by mshabarov** 2023-06-14 06:41 UTC
Labels: bug, Impact: High, Severity: Major

**Comment by esin-gleb** [comment] 2025-05-19 18:13
I occasionally encounter a “Failed to register a ServiceWorker for scope” error.
I noticed that sw.js is served with Content-Type: text/html;charset=utf-8 when the error occurs.
username@server:~$ docker exec -it Helloround curl -I http://localhost:8080/sw.js  
HTTP/1.1 200  
Set-Cookie: JSESSIONID=...  
Content-Type: text/html;charset=utf-8  
...
But when there’s no error, it’s served correctly as Content-Type: text/javascript;charset=utf-8:
username@server:~$ docker exec -it Helloround curl -I http://localhost:8080/sw.js  
HTTP/1.1 200  
Content-Type: text/javascript;charset=utf-8  
...
