### ISSUE TITLE
missing URL parameters when using event.forwardTo("xxx");

### ISSUE THREAD

**Issue by kai83** [vaadin/flow#9526] opened 2020-11-29 19:18 UTC
HI,

I found a bug when using 

event.forwardTo in combination with the BeforeEnterObserver.
event.forwardTo forwards to another view and is changing the URL. But the URL parameters are lost and not transfered.

When using event.rerouteTo, then the new UI is shown including the URL paramaters, but the URL is not changed (as expected as guess.

So the bug seems to be in forwardTo only, which is lossing the URL paramaters.

    - Vaadin / Flow version: 14.4.3
    - Java version: Java 11
    - OS version: Windows 10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Eclipse

To reproduce:

URL to open: http://127.0.0.1:8080/Login?id=value1

Login Class:
```
public class LoginView extends VerticalLayout implements BeforeEnterObserver{

    public LoginView () {
        // Use TextField for standard text input
        TextField textField = new TextField("LoginView");
        textField.addThemeName("bordered");

        add(textField);
    }

	@Override
	public void beforeEnter(BeforeEnterEvent event) {
	    event.forwardTo("TestUI");
	}
}
```
`public class TestUI extends VerticalLayout implements HasUrlParameter<String> {

	Map<String, List<String>> parametersMap;

	public TestUI() {

		Button btn = new Button("FORWARDED");
		add(btn);
	}
	@Override
	public void setParameter(BeforeEvent event, @OptionalParameter String parameter) {
		Location location = event.getLocation();
	    QueryParameters queryParameters = location
	            .getQueryParameters();

	   parametersMap =
	            queryParameters.getParameters();
	    
	   System.out.println(" 1 " + parametersMap);
	    System.out.println(" 2 " + parametersMap.containsKey("id"));
	    System.out.println(" 3 " + parametersMap.get("id"));
	}
}`

RESULT of the URL:
http://127.0.0.1:8080/TestUI

**Comment by pleku** [comment] 2020-11-30 07:04
Hello. This is a duplicate of https://github.com/vaadin/flow/issues/7680 which is considered an enhancement. I'm closing this as a duplicate, please comment there instead.

**Closed by pleku** 2020-11-30 07:04 UTC

**Comment by kai83** [comment] 2020-11-30 07:47
Hi @pleku ,
I would not say it is the same, as Olli is saying:
"Currently, when you use rerouteTo or forwardTo, **original query parameters should be retained.**"

In my case, the parameters are not retained when using forwardTo, but are retained when using reRoute.

This is in my view not an enhancement, but a bug.
Please let me know your opinion.

**Comment by pleku** [comment] 2020-11-30 09:15
@kai83 you're right that the comment says so, but the way I read the javadocs is that for `forwardTo` it is working as intended and changing it now would not be backwards compatible. [Here is another related comment](https://github.com/vaadin/flow/issues/4606#issuecomment-530224579) requesting for giving url parameters to `forwardTo`. The javadocs could be explicit about this, but it is implicitly implied by
```java
* This function changes the browser URL as opposed to <code>rerouteTo()</code>.
```
But I do agree that it should be possible to retain or set the url parameters when forwarding. But since the current behavior has been around for a long time, it would require new API to be used for allowing different behavior.
Improving these based on feedback should be a low hanging fruit for us to pick https://github.com/vaadin/flow/issues?q=is%3Aissue+is%3Aopen+forwardto
