### ISSUE TITLE
Unable to navigate with RouterLink after navigating with UI::navigate

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/flow#8071] opened 2020-04-16 00:01 UTC
- Description of the bug
A `RouterLink` doesn't work if you navigated to the view containing it using `UI::navigate(Class)`.

- Minimal reproducible example
```
@Route
public class View1 extends VerticalLayout {

    public View1() {
        add(
                new H1("View 1"),
                new Button("View 2", event -> UI.getCurrent().navigate(View2.class))
        );
    }

}
```
```
@Route
public class View2 extends VerticalLayout {

    public View2() {
        add(
                new H1("View 2"),
                new RouterLink("View 1", View1.class)
        );
    }

}
```

- Expected behavior
Clicking the router link navigates to the corresponding view.

- Actual behavior
When you click the button in `View1` it correctly navigates to `View2`. But after doing this, if you click the router link in `View2`, it doesn't navigate to `View1`. It changes the URL in the browser but the content of the page doesn't change. If you request `View2` in the browser (without using the button in `View1`), then the router link works.

- Versions:
    - Vaadin 15.0.4

**Comment by vlukashov** [comment] 2020-04-16 12:08
Originally reported at https://stackoverflow.com/questions/61240148/vaadin-router-doesnt-update-the-view. The SO question also has a link to a minimal project

**Comment by gronono** [comment] 2020-04-16 22:41
The problem is from client. The browser does'nt send any request to the server when the UI doesn't update itself.

**Comment by haijian-vaadin** [comment] 2020-04-30 09:52
This problem should now be fixed with @vaadin/router 1.7.2

**Closed by haijian-vaadin** 2020-04-30 09:52 UTC
Labels: Impact: High, Severity: Major, ccdm

**Comment by ajgassner** [comment] 2020-04-30 09:58
Hi @haijian-vaadin,

I just wanted to try to new router version, but I'm unable to use it with Vaadin Flow, see https://github.com/vaadin/flow/blob/6c9a9557cc3f3752b620e69e84f99fa39d15901a/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java#L259

Maven overrides the vaadin-router package entry with "^1.6.0" although the version I added is newer. Seems to be impossible to fix this without releasing flow with an updated router version.

**Comment by haijian-vaadin** [comment] 2020-04-30 11:04
@ajgassner good to hear, thanks for the update.

**Comment by alejandro-du** [comment] 2020-04-30 16:14
@haijian-vaadin, what `vaadin` version will include the fix?

**Comment by haijian-vaadin** [comment] 2020-04-30 17:57
@alejandro-du, vaadin only pins @vaadin/router version as `^1.6.0`, which means that the fix is already available for any Vaadin 15+ versions, as long as you make sure you use @vaadin/router 1.7.2. To do this, you can choose one of the following ways:
- manually update the version in package-lock.json file.
- run `npm update` in the project root
- delete the `node_modules` folder and the `package-lock.json` file and then start the application. Let Vaadin regenerates for you.
