### ISSUE TITLE
Swapping the Data Provider of a detached Grid can lead to an unhandled exception

### ISSUE THREAD

**Issue by petrixh** [vaadin/flow#10002] opened 2020-12-17 12:48 UTC
While debugging a weird issue in a customer project we came across an issue where: 

- If the same Grid instance is reused
- but the Data Provider is replaced
- The Grid is removed from its parent layout between the DP swaps
- a Data Provider that was used earlier is used again
- The Grid will throw an exception like: 

```
java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:123) ~[flow-server-2.3.7.jar:2.3.7]
	at com.vaadin.flow.dom.Node.removeChild(Node.java:376) ~[flow-server-2.3.7.jar:2.3.7]
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:577) ~[flow-server-2.3.7.jar:2.3.7]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:293) ~[flow-server-2.3.7.jar:2.3.7]
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-2.3.7.jar:2.3.7]
	at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:128) ~[flow-data-2.3.7.jar:2.3.7]
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:84) ~[flow-data-2.3.7.jar:2.3.7]
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47) ~[flow-data-2.3.7.jar:2.3.7]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_191]
....

```

Since the exception comes from "registerRenderedComponent" it is probably related to the ComponentRenderer somehow. 

Vaadin versions affected (at least): 14.3.9, 14.4.2, 14.4.4
Browser: Server-side so probably browser independent (Happens with FF, Chrome and Chromium Edge at least)

Workaround (also in code): 
Instead of removing the Grid instance from the layout, hide it with setVisible()

Minimal reproducible example code: 

```
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.provider.ListDataProvider;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;

/**
 * This is a scaled down example with the bare minimum to reproduce the issue.
 * It is simplified, yes and normally in a hello world one would not remove
 * the Grid between Data Provider swaps. However, in more complex forms
 * options or filters that the user picks might dictate whether or not the
 * Grid is shown or not and what data is shown in it.
 *
 * Steps to reproduce:
 * - run the app
 * - make sure "Remove Grid from Layout before DB swap" is selected
 * - Click on "Set DP2"
 * - Observe that the data has changed ad the "Name" column now starts with DP2
 * - Click on "Set DP1"
 * - Observe the stacktrace on the server and the internal error in the UI
 */
@Route("gridbug2")
public class GridBug2 extends VerticalLayout {


    public GridBug2() {

        Grid<MyPojo> grid = new Grid<>();

        ListDataProvider<MyPojo> dataProvider = new ListDataProvider<>(createData("DP1"));
        ListDataProvider<MyPojo> dataProvider2 = new ListDataProvider<>(createData("DP2"));

        grid.setDataProvider(dataProvider);

        grid.addColumn(MyPojo::getName).setHeader("Name");
        grid.addComponentColumn(MyPojo::getCheckbox).setHeader("Checkbox");
        grid.addComponentColumn(MyPojo::getComboBox).setHeader("Combo");

        add(grid);

         /*
         * If the grid is removed from the layout and then the data provider is replaced and the Grid
         * is added back into a layout it will throw an exception once a DP that has been used before 
         * is reused (some kind of old state not being cleaned out?).
         */
        Checkbox removeFromLayoutBeforeSwap = new Checkbox("Remove Grid from layout before DP swap", true);

        /*
         * In some cases or complex UI's, a grid might be shown based on other options. A complex grid instance
         * might be reused but with a different data provider. A workaround is to not actually remove the
         * Grid from the UI context, rather just hide it (also uncheck the remove combo).
         */
        Checkbox workaround = new Checkbox("Hide Grid before swap (workaround)");
        add(removeFromLayoutBeforeSwap, workaround);

        add(new Button("Set DP1", e -> {
            preDataProviderSwap(grid, removeFromLayoutBeforeSwap, workaround);
            grid.setDataProvider(dataProvider);
            postDataProviderSwap(grid, workaround);
        }));
        add(new Button("Set DP2", e -> {
            preDataProviderSwap(grid, removeFromLayoutBeforeSwap, workaround);
            grid.setDataProvider(dataProvider2);
            postDataProviderSwap(grid, workaround);
        }));

    }

    private void postDataProviderSwap(Grid<MyPojo> grid, Checkbox workaround) {

        if(!grid.getParent().isPresent()){
            addComponentAsFirst(grid);
        }

        if(workaround.getValue()){
            grid.setVisible(true);
        }
    }

    private void preDataProviderSwap(Grid<MyPojo> grid, Checkbox removeFromLayoutBeforeSwap, Checkbox workaround) {

        // We tracked it down to this, so basically if the grid was rendered with
        // one set of data, then removed from the layout, a new data provider set
        // to it and then reattached it will throw a:
        // java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.
        // once a data provider that was used before is shown again
        // (it seems to accept the "new" data provider that has never been rendered previously just fine)
        if(removeFromLayoutBeforeSwap.getValue()){
            remove(grid);
        }

        if(workaround.getValue()){
            grid.setVisible(false);
        }

    }

    public ArrayList<MyPojo> createData(String prefix) {
        ArrayList<MyPojo> data = new ArrayList<>();

        for (int i = 0; i < 100; i++) {
            data.add(new MyPojo(prefix + " Data" + i));
        }

        return data;
    }

    public static class MyPojo {

        private String name;
        private Checkbox checkbox = new Checkbox();
        private ComboBox<String> comboBox = new ComboBox<>();

        public MyPojo(String name) {
            this.name = name;
            comboBox.setItems("Item 1", "Item 2", "Item 3");
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Checkbox getCheckbox() {
            return checkbox;
        }

        public void setCheckbox(Checkbox checkbox) {
            this.checkbox = checkbox;
        }

        public ComboBox<String> getComboBox() {
            return comboBox;
        }

        public void setComboBox(ComboBox<String> comboBox) {
            this.comboBox = comboBox;
        }
    }

}
```

**Comment by taefi** [comment] 2021-02-16 13:53
Based on @tulioag's Minimal Reproducible example, I could reproduce it for the Combobox even without setting the dataProvider, just removing and adding the Combobox results in the same behavior. 
But for the grid, setting the dataProvider is necessary.

**Comment by taefi** [comment] 2021-02-19 13:20
The source of this issue is about the way of providing `ComponentRenderer` for both the Grid and the ComboBox. ComponentRenderers should be configured in a way that everytime they take a model item and output a component instance, not to return the same instance always. 

The current provided code to reproduce the issue, obviously should not be the way of coding for creating the ComponentRenderers, since:
1. The POJO as the data holder should not hold instances of the UI elements, since even before the ComboBox or the Grid is attached, those UI elements are created in the memory. 
2. Passing the same instances everytime a call to the `componentFunction` happens, results in an uncertain state of the element tree including basic elements and shadow roots. 

Basically, the following change resolves the issue: 
```Java
public static class MyPojo {
    // private final Div div;
    private final String name;

    public MyPojo(String name) {
        // this.div = new Div(new Text(name));
        this.name = name;
    }

    public Div getDiv() {
        // return div;
        return new Div(new Text(name));
    }
}
```
However, as discussed, this is the wrong way of coding to have the logic of creating renderer components or the actual component instances inside the data holder POJO.
 
 I'm closing this issue as this is mentioned in the documentation of `ComponentRenderer` constructor:
 ```Java
/**
* Creates a new ComponentRenderer that uses the componentFunction to
* generate new {@link Component} instances. The function takes a model item
* and outputs a component instance.
* <p>
* Some components may support several rendered components at once, so
* different component instances should be created for each different item
* for those components.
*
* @param componentFunction
*            a function that can generate new component instances
* @see #ComponentRenderer(SerializableFunction, SerializableBiFunction)
*/
public ComponentRenderer(
        SerializableFunction<SOURCE, COMPONENT> componentFunction) {
    this(componentFunction, null);
}
 ```

**Closed by taefi** 2021-02-19 13:20 UTC
Labels: BFP, Impact: High, Severity: Major, bug
