### ISSUE TITLE
DataChangeEvent can't unregister its listener

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6947] opened 2019-11-14 14:43 UTC
`ComponentEvent`s have a useful `unregisterListener` method to be able to unregister themselves once invoked, but `DataChangeEvent` does not; it would be useful to set a "once" listener (not sure if there's another way to do it).

**Comment by denis-anisimov** [comment] 2019-11-15 06:25
When you register a listener you get `Registration` instance to unregister it in both cases.
So there is already to unregister the listener , right ?

I personally find any listener related method in event class as a confusing design.
So `ComponentEvent::unregisterListener` is quite weird method for me.

But let's have it as an enhancement.

**Comment by Legioth** [comment] 2019-11-15 08:23
The problem is usually that the listener callback cannot access the returned `Registration` without ugly workarounds such as assigning it to an instance field or wrapping it in an `AtomicReference<Registration>` or `new Registration[1]`.

**Comment by heruan** [comment] 2019-11-15 08:41
@denis-anisimov the reason of having `ComponentEvent::unregisterListener` is what @Legioth has explained, e.g.

```java
button.addClickListener(event -> {
  // something to do only once
  event.unregisterListener();
});
```

but I can't do this in `DataProvider::addDataProviderListener`.

**Comment by pleku** [comment] 2019-11-15 10:06
This issue is up for grabs, please make sure to read contribution guidelines before contributing https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md

**Comment by torok-peter** [comment] 2019-12-19 13:31
This is much more complex than a Good First Issue :-(

**Closed** 2021-09-17 05:45 UTC
Labels: enhancement, Help wanted
