### ISSUE TITLE
I don't know if it's a mistake or a minor problem

### ISSUE THREAD

**Issue by Tz1Git** [vaadin/flow#8562] opened 2020-06-14 16:35 UTC
Hello,

It's messages are appearing in the system, but since nothing else is reported, just that, I have no way of determining when the source code is carrying out this process. But it is very likely that at a moment I am leaving a comboBox and TextField with enabled = false:
```
> 13:29:28,957 WARN  [com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler] (default task-1) Property update request for disabled element is received from the client side. The property is 'opened'. Request is ignored.
> 13:29:28,957 WARN  [com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler] (default task-1) Property update request for disabled element is received from the client side. The property is 'filter'. Request is ignored.
> 13:29:28,970 WARN  [com.vaadin.flow.server.communication.ReturnChannelHandler] (default task-1) Ignoring update for disabled return channel: {"type":"channel","node":46,"channel":0,"args":[null]}
> 13:29:28,970 WARN  [com.vaadin.flow.server.communication.ReturnChannelHandler] (default task-1) Ignoring update for disabled return channel: {"type":"channel","node":46,"channel":2,"args":[null]}
```

**Comment by denis-anisimov** [comment] 2020-06-16 10:03
Could you please provide steps to reproduce ?

**Comment by Tz1Git** [comment] 2020-06-16 18:17
There is no step that I can report, just run the program to report it.
But it is probably on these lines, after which this information appeared:
```
((Tz1ComboEnum<?>) findModelObjects("taxNcmRulesTaxNcmRulesModel").getComponent()).addValueChangeListener(event -> {
	 TaxNcmRulesType valueRules = (TaxNcmRulesType) event.getValue();
	((Tz1TextField) findModelObjects("contentNCMTaxNcmRulesModel").getComponent()).getParent().orElse(null).setVisible(valueRules != null && !valueRules.equals(TaxNcmRulesType.NCM));
	((Tz1ComboBox<?>) findModelObjects("commonGovernmentNcmTaxNcmRulesModel").getComponent()).getParent().orElse(null).setVisible(valueRules != null && !valueRules.equals(TaxNcmRulesType.CONTAINING));
});
```
If you have anything that I can activate to give more information let me know, for the time being this information only appears during the execution of the system.

**Comment by denis-anisimov** [comment] 2020-06-17 05:59
Sorry, these line give me no any information about the essence of the issue.
`'opened'`  and `'filter'` are combo-box properties so I may assume that this is caused by combo-box.
Disabled element should not send any properties update to the server side.
This is what the message is about.
Why does it send ? I don't know.
May be something on the pure client side is trying to send the properties to the server side.
This is prevented on the server side ( via ignoring those updates).

It might be that there is some issue in the combo-box component related to enable/disable functionality.
Then it should be fixed in the component repository.
The problem is : without exact steps to reproduce no-one may approve this assumption and it's not possible to verify that issue is fixed or not.
So unfortunately we may not proceed with this with such description.

I'm closing the issue. If you will be able to provide exact steps to reproduce please add them here and I will reopen the ticket.
Also you may create a ticket in combo-box repo . It looks like this is a component issue.

**Closed by denis-anisimov** 2020-06-17 05:59 UTC
Labels: waiting for author
