### ISSUE TITLE
Make template information available through the server-side Element API

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3735] opened 2018-03-20 09:43 UTC
There are many cases when it would be practical if attributes, properties and child elements from the HTML template of a `PolymerTemplate` would also be accessible through the regular server-side Element API. This includes e.g. accessing preconfigured tabs in `Tabs` or clearing attributes set in the template (#2193 / #1649).

There are a couple of challenges associated with this kind of functionaltiy.
1) Eagerly creating `Element` instances for the entire template will inflate the memory use of every `PolymerTemplate` component instance. We would thus have to create such instances only on demand, and potentially allow the instance to be garbage collected if it's only used to read settings but not modified in any way.
2) This would still not support cases when the DOM hierarchy is modified by Polymer or other JS on the client. This is to some degree mitigated by https://github.com/vaadin/flow/issues/3713, but it's still a leaking abstraction.
3) Observing children injected by e.g.  `<dom-repeat>` wouldn't be available unless we hardcode support for specific special element types.
4) Knowing the property value of anything defined as a computed property through Polymer would require running Polymer on the server (or only provide the value asynchronously), which has turned out to not be feasible in previous prototypes.
5) There's an increased risk of conflicts if a property or attribute with a binding is also manipulated through the `Element` API since there's no guarantee that Polymer wouldn't overwrite that value based on e.g. changes to the model.

**Comment by pleku** [comment] 2020-08-31 10:22
We'll now target reading attribute values from lit templates which are ES6 modules instead of TS.
If reading attribute values from Polymer templates (also `.js`) is trivial to include on top of that, we can do it immediately afterwards.
Reading attribute values from lit based templates in TS can be done separately once (?) designer supports it, but it seems unlikely to be needed for server driven Java views.

**Comment by denis-anisimov** [comment] 2020-09-04 05:15
I will try to collect here all serious various obstacles for this feature.

First of all : the template element has no its template "child" elements as children.
It has a shadow root and the children are children of shadow root.

We may not mix children of shadow root and direct children of the element otherwise it will be a mess: it's possible to modify anyhow the children of the template and it's impossible to track such changes if we consider shadow root children as children of the template itself. Also it's just logically incorrect.

So the template hierarchy should be shadow root hierarchy.

Most likely we should disallow modification of shadow root hierarchy for the template (?).

As a result : we should parse template to read its hierarchy and store it somehow in shadow root `Node`.
Now the funny thing: we may not create shadow root in advance because Polymer 3 has a bug which breaks the template if shadow root has been created before Polymer element is initialized (it's not reused as in Polymer 2).
So we may not create shadow root to store there the parsed info.
We will need to create workaround for that.

Another annoying topic is: `Id`  mapping. If polymer template has `Id` then the `Element`  (and its `StateNode`) is created along with the template creation and it already exists. This element also can be viewed as a descendant of the template element.
And this should be very carefully handled.
By the way : what happens with the hierarchy of `Id` injected element ? Is it modifiable ?

There is a high possibility to introduce a regression for `Id`  mapped functionality in the existing code.
I may forecast that we will introduce bugs with this functionality just because we are breaking the API : Element API says that you may do many things which won't be supported in one or another way if the element is a descendant of the Polymer template.
Users don't read documentation and that's OK: there is API. They expect that it will work according to the contract. And it won't work. So there will be enormous number of bugs.

I foresee a lot of problems with this on every step of implementation.
This feature is absolutely not supported by the current architecture design and the code will be just an ugly buggy workaround.

**Comment by pleku** [comment] 2020-09-04 07:33
As discussed in daily, the idea is not to do what the original description says, but to focus on static attribute values read from the template for components that are `@Id` mapped as that is what is needed for users working with Vaadin Designer templates.

**Comment by denis-anisimov** [comment] 2020-09-07 07:37
> It should be possible to solve #7622 or create further steps to make it so

I don't see how reading attribute value may help to fix this issue anyhow.

To be able to fix #7622 we need the ticket in its original description: read elements hierarchy inside the template.
And then everything I wrote here https://github.com/vaadin/flow/issues/3735#issuecomment-686912294 needs to be taken into account.
The reason why  #7622 doesn't work is: the `tab` element is not a child of `tabs` element. As a result the "child index" is `-1`  and nothing works.
To be able make it working the `tab` element should be a child of `tabs` element and this is about elements hierarchy and not about attribute values at all.

So the acceptance criteria is either contradictory or contains two totally unrelated cases : read attribute values and hierarchy.

It might be that we may support very limited support of the initial ticket regarding hierarchy: only when one `@Id`  mapped element has another `@Id` mapped element as a child. In this case the hierarchy may be populated.
On the other hand it's totally unclear how to treat this "child" : is it a real child ? Which index should it has ? What about other children (not `@Id`  mapped)?

**Comment by pleku** [comment] 2020-09-07 09:29
Very good points. The attribute values would be needed for the ID-mapped components too. But the hierarchy is another question. I was able to find the plan that was thought out for proper Lit-support:

> For Java UI we implement the existing @Id mapping logic with the addition:
> - We fix all @Id mapped components to read their initial "simple" state from the template to avoid the unexpectedness that textField.getLabel() is null for <vaadin-text-field label="Hello">  and that textField.setLabel(null) does not clear the label
> - We do not add complex logic for e.g. defining grid columns declaratively as part of this

> We encourage the users to put all UI logic in either Java or in TS but do not enforce it.
> We add limited support for LitElement to Designer. Limited implies that only static HTML is supported. We thus target only the use case that server side Java developers can define their layouts visually.

The template is static and the ordering does not change - there is no client side JS code that changes this on the fly. The template should be just defining the (static) layout of the app and for that it will be setting some attribute values for the id-mapped elements. 

> It might be that we may support very limited support of the initial ticket regarding hierarchy: only when one @Id mapped element has another @Id mapped element as a child. In this case the hierarchy may be populated.

This limited support would be then needed and probably enough.

> On the other hand it's totally unclear how to treat this "child" : is it a real child ? Which index should it has ? What about other children (not @Id mapped)?

Not sure, but I would, again, suggest looking at the tabs issue as an example - what would be needed to be able to make the component support that. My own assumption is that it should be possible to use the component API for those `@Id` mapped components like:
- adding listeners
- reading & writing state, like disabled, visible, classnames etc.

Changing the hierarchy is might be desider, but I don't think it is mandatory - one could at least add all the components via Designer into the template, and then just use the state (enabled/visibility) to make those visible. @Artur- can comment on better/more examples on what should be expected from server side Java usage. I think at least this one https://github.com/vaadin/flow/issues/5428 should be covered by just reading the attribute value.

**Comment by denis-anisimov** [comment] 2020-09-07 09:53
As a result :
should `@Id` mapped hierarchy issue be part of this ticket or it's another ticket ?

**Comment by pleku** [comment] 2020-09-08 08:34
This issue originally encompassed many parts from the times when we thought it would be good to mix & match UI logic both on client & server. Part of this is now done (reading initial attribute values #8957) and another _maybe_ part, parsing the element hierarchy, is split into a new issue (#8958). The other remaining parts are considered for now as "won't fix" since the idea is that you should not mix UI logic both in server & client side, but just either of those.

For client side UI logic, there is the TS based views since v15.
For server side UI logic, it is to be seen if there is any additional requirements necessary. Closing this issue for now as _partly fixed and partly won't fix and because it is outdated, too wide and without concrete examples.

**Closed by pleku** 2020-09-08 08:34 UTC
Labels: enhancement, template
