### ISSUE TITLE
[Vaadin20 + Windows + Addon] Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#11306] opened 2021-06-22 09:28 UTC
**Describe the bug**
The bug appears for the new **Vaadin 20 and app deployed on Windows** for Vaadin + spring + addon. 
I generate and deploy the war app and deploy it on Win10 on Tomcat 9. The bug appears both in debug and production mode.
- The bug doesn't appear with Vaadin19 (no matter if on Windows or *UX)
- The bug doesn't appear with *UX (even with Vaadin20)
- But appears with Vaadin20 on Windows (always, on 3 different windows environment).
So it could be something with paths ('.' in front of paths?)

After successful deployment on Tomcat going to the View with addon component ends with:
`There was an exception while trying to navigate to '' with the exception message 'Error creating bean with name 'com.example.application.views.helloworld.HelloWorldView': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.application.views.helloworld.HelloWorldView]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file'`

```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:155) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:217) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:95) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:93) ~[flow-server-7.0.2.jar:7.0.2]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_181]
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:110) ~[flow-server-7.0.2.jar:7.0.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:96) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:94) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:109) ~[flow-polymer-template-7.0.2.jar:7.0.2]
	at com.github.appreciated.apexcharts.ApexCharts.<init>(ApexCharts.java:28) ~[apexcharts-2.0.0-beta12.jar:2.0.0-beta12]
	at com.github.appreciated.apexcharts.ApexChartsBuilder.build(ApexChartsBuilder.java:197) ~[apexcharts-2.0.0-beta12.jar:2.0.0-beta12]
	at com.example.application.views.helloworld.HelloWorldView$AreaChartExample.<init>(HelloWorldView.java:79) ~[classes/:1.0-SNAPSHOT]
```

**My simple test app:**
[my-app.zip](https://github.com/appreciated/apexcharts-flow/files/6679504/my-app.zip)
Just generate war and deploy it on Windows.

**Environment:**
 - OS: Windows10
 - Vaadin 20
 - Spring 5
 - ApexChart addon

**Comment by knoobie** [comment] 2021-06-22 09:41
Looks really similar to https://github.com/vaadin/flow/issues/11220 - could this help you?

**Comment by darmro** [comment] 2021-06-22 09:52
> Looks really similar to #11220 - could this help you?

Thanks @knoobie !  It's exactly the same problem :) I turned for help to Vaadin support 2 weeks ago (8 of Jun) and they couldn't give me any idea (strange ;). Im appreciated for your help. 
But what is the workaround for this?

**Comment by knoobie** [comment] 2021-06-22 10:01
Sorry answered in the wrong ticket - see https://github.com/appreciated/apexcharts-flow/issues/114#issuecomment-865841521

**Comment by pleku** [comment] 2021-06-22 11:22
Closing as duplicate of #11220

**Closed by pleku** 2021-06-22 11:22 UTC
