### ISSUE TITLE
Flow app might redirect to /login page when code is compiling in the background.

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#19512] opened 2024-06-04 16:10 UTC
### Description of the bug

When I do some operations using Copilot, the login page might appear from time to time. It is annoying and confusing for users especially after such an operation 

https://github.com/vaadin/flow/assets/100126447/8f778e97-0da5-4077-aa93-dfa768442341

This also happens when there is a code compilation error (the example above is not one of them).

Comment from @Legioth in internal Slack conversation: https://vaadin.slack.com/archives/C6X43FE8M/p1717057898635429

It has been noticed but we have had problems reproducing. That compilation error hint might be useful there since it's probably technically the same conditions as while a compilation is happening in the background with the main difference being that it never completed due to the error. 

### Expected behavior

Login page should not appear. 

### Minimal reproducible example

You can create a flow application and enable flow modifications for the copilot. Then, drag some templates from palette into view and you will encounter it about after 5-10 tries. 

It happens 1 in 5 times when I drop an element from the palette(which causes server restart) if the server startup time is longer than 3~4 seconds when there is no hot-swap agent or JRebel

### Versions

- Vaadin / Flow version: 24.5.0.alpha1
- Java version: Oracle OpenJDK 22.0.1 - aarch64
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by tltv** [comment] 2024-06-06 12:02
I'm not able to reproduce this exact same effect with 24.5.0.alpha1 or 24.5-SNAPSHOT. Actually i don't see server restart to happen at all after source file is updated because there's no compilation triggered. 
@Artur-, just a quick question, is Copilot supposed to also compile Java file after it modifies Java file, or should compilation happen manually by developer or automatically by IDE?

**Comment by abdullahtellioglu** [comment] 2024-06-06 12:06
Do you have the vaadin plugin installed? Idea plugin compiles the java file. https://plugins.jetbrains.com/plugin/23758-vaadin

**Comment by Artur-** [comment] 2024-06-06 12:20
Copilot never compiles Java files but your IDE will. IntelliJ if you have the plugin, VS code will always do it automatically I think

**Comment by tltv** [comment] 2024-06-07 13:47
With https://github.com/vaadin/intellij-plugin/issues/44 being fixed now, I tested this case with the plugin and I see that it has the same double restart issue.
As restart is caused by ItelliJ triggering one file deletion and another file addition instead of single file modification, and as Spring dev-tools's FileWatcher is listening and handling these, there's little for Flow to do for this other than adjusting those two properties mention earlier. It's also already [documented here](https://vaadin.com/docs/next/flow/integrations/spring/configuration#configure-spring-boot-development-tools).

**Comment by Legioth** [comment] 2024-06-07 14:14
Could Flow (or Spring Boot) have a relatively long delay with handling deletions based on the assumption that a corresponding addition may happen soon? And then in the few cases where a file is actually deleted, the user would just be slightly annoyed by that longer delay.

**Comment by Legioth** [comment] 2024-06-07 14:14
Also, can we do something to better recover in cases when there's a double redeploy?

**Comment by tltv** [comment] 2024-06-07 14:24
Flow does not have control over it. For Spring I can't recall anything like that other than those properties already mentioned plus a thing called "trigger file" which has also a ticket [Spring's trigger file feature](https://github.com/vaadin/flow/issues/17698), which could be implemented in Vaadin IntelliJ plugin to trigger reload based on a single trigger file somewhere.

**Comment by tltv** [comment] 2024-06-12 14:31
@abdullahtellioglu would you please upload a zipped app that reproduced the login page redirect issue? I can then verify that https://github.com/vaadin/flow/pull/19564 actually fixes the original issue too or see if it's caused by another bug.

**Closed** 2024-06-19 07:11 UTC
Labels: investigation
