### ISSUE TITLE
Paper Drop Down Error 14.1.20

### ISSUE THREAD

**Issue by byacobucci** [vaadin/flow#7854] opened 2020-03-20 17:03 UTC
Running 14.0.13 is fine, tried to go to 14.1.20 and when our software starts up, all is fine at the Login Screen, but when we go to the next screen (menu, etc.) this error is caught by Chrome and our applooks like the styles are not applied.

per instructions...tired removing
target folder
node_modules folder
package-lock.json
package.json and building the project again.

Uncaught Error: A custom element with name 'dom-module' has already been defined. at Zd (webcomponents-sd-ce.js:145) at Q.n.define (webcomponents-sd-ce.js:145) at Q.Rf.define (webcomponents-sd-ce.js:197) at eval (webpack-internal:///../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/elements/dom-module.js?babel-target=es6:181) at Module.../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/elements/dom-module.js?babel-target=es6 (VAADIN/build/vaadin-bundle-fef654298c2d6431b2e1.cache.js:625) at webpack_require (VAADIN/build/vaadin-bundle-fef654298c2d6431b2e1.cache.js:20) at eval (webpack-internal:///../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/utils/style-gather.js?babel-target=es6:10) at Module.../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/utils/style-gather.js?babel-target=es6 (VAADIN/build/vaadin-bundle-fef654298c2d6431b2e1.cache.js:1021) at webpack_require (VAADIN/build/vaadin-bundle-fef654298c2d6431b2e1.cache.js:20) at eval (webpack-internal:///../node_modules/@polymer/paper-dropdown-menu/node_modules/@polymer/polymer/lib/mixins/element-mixin.js?babel-target=es6:8)

Wildfly, using Intellij

Problem can be reproduced.

Package.json:
{
  "name": "no-name",
  "license": "UNLICENSED",
  "dependencies": {
    "@polymer/polymer": "3.2.0",
    "@webcomponents/webcomponentsjs": "^2.2.10",
    "@vaadin/flow-deps": "./target/frontend"
  },
  "devDependencies": {
    "webpack": "4.30.0",
    "webpack-cli": "3.3.10",
    "webpack-dev-server": "3.9.0",
    "webpack-babel-multi-target-plugin": "2.3.3",
    "copy-webpack-plugin": "5.1.0",
    "compression-webpack-plugin": "3.0.1",
    "webpack-merge": "4.2.2",
    "raw-loader": "3.0.0"
  },
  "vaadinAppPackageHash": "39d33b7795d6777266cf4dffe7bc71cdde0581b4e3cc66e936e8df0293a2f781"
}

/target/frontend/package.json
{
  "name": "@vaadin/flow-deps",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "dependencies": {
    "@vaadin/vaadin-grid": "5.5.2",
    "@vaadin/vaadin-icons": "4.3.1",
    "@vaadin/vaadin-split-layout": "4.1.1",
    "@vaadin/vaadin-combo-box": "5.0.11",
    "@vaadin/vaadin-core-shrinkwrap": "14.1.20",
    "@vaadin/vaadin-upload": "4.2.2",
    "@vaadin/vaadin-dialog": "2.2.1",
    "@vaadin/vaadin-select": "2.1.7",
    "@vaadin/vaadin-app-layout": "2.0.5",
    "@vaadin/vaadin-item": "2.1.1",
    "wysiwyg-e-fork": "3.0.8",
    "@vaadin/vaadin-notification": "1.4.0",
    "@vaadin/vaadin-progress-bar": "1.1.2",
    "@vaadin/vaadin-ordered-layout": "1.1.0",
    "@vaadin/vaadin-login": "1.0.1",
    "@vaadin/vaadin-button": "2.2.2",
    "@vaadin/vaadin-date-picker": "4.0.8",
    "@vaadin/vaadin-text-field": "2.5.3",
    "@vaadin/vaadin-menu-bar": "1.0.3",
    "@vaadin/vaadin-custom-field": "1.0.11",
    "@vaadin/vaadin-form-layout": "2.1.7",
    "@polymer/iron-list": "3.0.2",
    "@vaadin/vaadin-accordion": "1.0.1",
    "@vaadin/vaadin-list-box": "1.2.0",
    "@vaadin/vaadin-checkbox": "2.2.12",
    "@vaadin/vaadin-details": "1.0.1",
    "@polymer/iron-icon": "3.0.1",
    "@vaadin/vaadin-time-picker": "2.0.6",
    "@vaadin/vaadin-context-menu": "4.3.15",
    "@vaadin/vaadin-tabs": "3.0.5",
    "@vaadin/vaadin-radio-button": "1.2.6",
    "@vaadin/vaadin-lumo-styles": "1.5.0",
    "@vaadin/vaadin-material-styles": "1.2.3"
  }
}

**Comment by caalador** [comment] 2020-03-26 06:20
I could only reproduce the problem once, but after trying to figure out the cause I couldn't get it to reproduce anymore. 
The issue is that for some reason polymer gets two versions into the bundle 3.2.0 and 3.3.1 and these clash.
I would suggest trying to clean the project once more as this should work the same in 14.1.20 as it did with 14.1.13.

**Comment by byacobucci** [comment] 2020-03-26 13:09
You said "14.1.13". We are using "14.0.13" and wondering if you tried with 14.0.13.

**Comment by caalador** [comment] 2020-03-26 13:16
My typo, I didn't test 14.0.13 nor 14.1.13 as with the given information I couldn't replicate this issue in 14.1.20.

The one time I got it to get 2 polymer versions and fail as described, but that was with 14.2 prerelease where there might have been something extra that was broken.

**Comment by byacobucci** [comment] 2020-03-27 01:43
Well, I did as you suggested, still no go..but..I noticed I was seeing a "npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3." message. Researched that and found:
==========
It's a npm cache problem. Go to the path

C:\Users\johndoe\AppData\Roaming\npm-cache

and delete its content. Then open your console in administrator mode and execute the npm install command again
========

I did that and it worked!! I am now up to Vaadin 14.1.20. thanks for the extra "encouragement" for me to look a little closer.

**Comment by caalador** [comment] 2020-03-27 04:38
We would love to get a way to have this issue replicate as it seems to happen now and then with different setups.

**Comment by caalador** [comment] 2020-04-09 06:04
As you came to the conclusion that this was a npm cache issue I'll note it here that in some cases the npm cache might need to be cleaned e.g. `npm cache clean --force`
For more details see: https://docs.npmjs.com/cli-commands/cache.html

I'm closing this ticket, but feel free to comment here if there is any new information, or open a new ticket with more details if more appropriate.

**Closed by caalador** 2020-04-09 06:04 UTC
Labels: waiting for author
