### ISSUE TITLE
Resynchronize does not resynchronize

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7590] opened 2020-02-14 11:07 UTC
Using the plain java starter with the following MainView.java:

```
package com.example.app;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {

    public static class Person {
        private String firstName, lastName;

        public Person(String firstName, String lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

    }

    public MainView() {
        Button button = new Button("Add grid", e -> {
            Grid<Person> grid = new Grid<Person>(Person.class);
            grid.setItems(new Person("John", "Doe"), new Person("Jane", "Jo"));
            add(grid);

            // Simulate a lost push request
            getUI().get().getInternals().incrementServerId();
        });

        add(button, new Button("Visit the server"));
    }

}
```

When clicking on "add grid", a grid should be added. In the event handler, the server id is incremented to simulate the case where a push happens after the XHR but before the response has been written.

Expectation:
1. Click on the button
2. Wait for the client to timeout  as it never receives the push message
3. Client resynchronizes and the grid is shown

What happens:
1. Click on the button
2. Wait for the client to timeout  as it never receives the push message
3. Client resynchronizes and no data whatsoever is sent from the server. No grid is shown

**Comment by Legioth** [comment] 2020-02-14 11:38
To clarify, the problem is that the server-side resync is implemented to only mark all server-side components as dirty. Marking as dirty will just mean that changes will be collected for that component, which is typically a no-op because since there aren't any changes to collect.

What is really needed is to send the full initial state for all components as though they would have been detached and then become attached again. We should probably even run attach and detach handler so that any relevant `beforeClientResponse` initialization also happens again. 

Furthermore, UI-level metadata such as which dependencies have already been loaded needs to be cleared so that e.g. `gridConnector.js` will be loaded again even dependency was triggered to be loaded by the response that never reached the client.

**Comment by Legioth** [comment] 2020-02-14 19:34
It might be that the current implementation is enough (and probably even overkill) in cases when a request has never reached the server, whereas it's insufficient in cases when changes have been processed on the server (either as a request or through push) but the message with updates reached the client

**Closed** 2020-03-04 09:17 UTC
