### ISSUE TITLE
Binder can't update a field whose status is invalid

### ISSUE THREAD

**Issue by torok-peter** [vaadin/flow#2460] opened 2017-09-21 08:42 UTC
Found in vaadin/free-starter-flow. Reproducible for at least TextField and ComboBox. 
1. Open a review for editing
![image](https://user-images.githubusercontent.com/31210544/30686538-3d6c8546-9ec1-11e7-943e-589ddd69eff4.png)
2. Clear its fields in the dialog so that the values become invalid
3. Click Save - you get a notification about the invalid values
![image](https://user-images.githubusercontent.com/31210544/30686714-c9235e34-9ec1-11e7-97a2-00f908dc5267.png)
4. Click Cancel
5. Open another review for editing - the invalid fields retain the previous invalid values
![image](https://user-images.githubusercontent.com/31210544/30686753-e621faea-9ec1-11e7-950b-65f212492beb.png)

(instead of e.g. this:)
![image](https://user-images.githubusercontent.com/31210544/30686641-8faf398e-9ec1-11e7-94a0-fbc46e1893ff.png)

It seems to me that the status is properly updated on the server side, however the state change may not get propagated to the client side? I also noticed a `// TODO notify listeners` comment in `NodeMap.setChanged()`, line 274, which may or may not be related.

Related PR in FW8 is https://github.com/vaadin/framework/pull/9988 .

**Comment by mvysny** [comment] 2017-10-05 13:24
Can be reproduced easily with the Beverage Buddy - just click any Category to edit it. Since the TextField's initial value is "" (empty string) and is invalid (at least 3 characters are required), it is not filled in properly by Category's name.

**Comment by denis-anisimov** [comment] 2018-01-15 10:24
That's really weird issue related to "invalid" property.

For some reason client side engine is not able to update the `value` property when the `invalid` is `true`.
On the other hand it's possible to update the `value` property out of Flow client engine.

So here are some investigation details:
- Repeat the steps from above description (up to make the field invalid and save action).
- Open developer console and find/select the `text-field` element there (the invalid one).
- Close the dialog (via cancel).
- Check that the `text-field` element is still invalid.
- Make it valid (update the property via the developer console).
- Reopen the review editor.
- Now the issue is gone.

Also you can do another way:
- Open review editor.
- Update the value in the `text-field` to another but correct.
- Again open the dev console and select the `text-field`.
- Close it via cancel.
- Make the field invalid (update the property via the developer console).
- Reopen the review editor.
As a result: the value is not the expected one but it's the same as had been updated before cancel action.

So it's `invalid` property which somehow interfere the behavior.

I have a feeling that the behavior is the consequence of the nature of two aspects of `invalid` property.
This property is updated by the client in this specific case because there is a pattern for number used: `[0-9]*` (`TextField::setPattern`). So the client side checks the content of the textfieldand controls the `invalid`  behavior.
So when empty string is set as a value on the client side the property is updated to `false` on the client side.
But there is also the server side validation which also updates the property when the validation fails.
And this two aspects behavior may cause the issue.

**Comment by pleku** [comment] 2018-01-15 12:34
>This property is updated by the client in this specific case because there is a pattern for number used: [0-9]* (TextField::setPattern). So the client side checks the content of the textfieldand controls the invalid behavior

But for the category name editor there is no `pattern` as it is using only server side validation and setting the invalid flag and error message based on those.

What happens when the dialog is reopened, there is the following response sent to update tha value, clear error message and remove invalid flag:
```json
for(;;);[{"syncId":47,"clientId":47,"changes":[{"node":26,"type":"put","key":"click","feat":4,"value":"u/kIqMqY4tI="},{"node":28,"type":"put","key":"invalid","feat":1,"value":false},{"node":28,"type":"put","key":"errorMessage","feat":1,"value":""},{"node":28,"type":"put","key":"value","feat":1,"value":"Mineral Water"}],"execute":[[[0,32],"$0.open()"]],"timings":[914,0]}]
```

But immediately there is the following RPC to server:
```json
{"csrfToken":"496fb446-5857-4a5f-a891-76b00e81a1e1","rpc":[{"type":"mSync","node":28,"feature":1,"property":"value","value":""},{"type":"mSync","node":32,"feature":1,"property":"opened","value":true}],"syncId":47,"clientId":47}
```

And after that the server side sets the value empty and invalid again in the response: 
```json
for(;;);[{"syncId":48,"clientId":48,"changes":[{"node":28,"type":"put","key":"invalid","feat":1,"value":true},{"node":28,"type":"put","key":"errorMessage","feat":1,"value":"Category name must contain at least 3 printable characters"}],"timings":[915,1]}]
```

So the question is that what is making the `vaadin-text-field` discard the value and set it back to `"" ` and causing the field to go invalid.

**Comment by denis-anisimov** [comment] 2018-01-15 13:58
The issue is caused by https://github.com/vaadin/vaadin-text-field/issues/192.

Here is the description what happens in Flow:
- When dialog is closed with "cancel" button the field has `invalid` property value `true` and `value` property value `""`.
- When the dialog is reopened the `invalid` property value is set to `false`.
- At the same time new `value`  property is set to the value from the bean.
- On the client side both values are set to their `MapProperty` instances during message handling.
- The real client property update happens in the end of the request : at `flush`  time (so even though the `value` property has correct value in `StateTree`  it doesn't update the value in the element immediately).
- When `invalid`  property is updated the `text-field` element fires `value` change event in addition to `invalid` change event.
- As a result it leads to update of the `MapProperty` instance value for `value` property and an RPC request to the server to update property `value` to the client side value `""`.
- In the result the value is overridden from the client side old value even though the server side requested to set `value` property to some new value "after" update of `invalid` property.

This wouldn't happen if we updated the element properties immediately at the time when they are set fro the server. 
In this case even if the client side sends the update event for `value` property it will be overridden later on when `value`  is set if the property update happens _after_ `invalid` property update.
If `value` property update happens _before_ `invalid` then element already has correct `value` property value and there is no problem.

But we update element properties kind of "asynchronously" which allows such kind of issues.
Also issue wouldn't happen if `value` property was set before `invalid` because in that case `value` would be processed before `invalid`  and `value` already would been updated.

This specific issue can be solved in the client side element but I see a generic issue in Flow client engine : we are not protected from such situations which are technically are not errors on the client side.
I can imagine that there can be a property change which may lead to events for other properties as well.

**Comment by denis-anisimov** [comment] 2018-01-16 07:54
So this ticket is blocked by the ticket in the `vaadin-text-field` element's repository.

**Closed** 2018-01-18 09:39 UTC
Labels: UX, app starter, awaits another ticket, bug
