### ISSUE TITLE
BeforeLeaveEvent::proceed does NOT update URL

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#19786] opened 2024-08-14 06:27 UTC
### Description of the bug

Title says it all. calling `proceed()` does not update the URL.

### Expected behavior

User is redirected and the URL is updated correctly.

### Minimal reproducible example

```java

@Route(value = "leave-observer")
public class LeaveObserver extends VerticalLayout implements BeforeLeaveObserver {

  public LeaveObserver() {
    add(new NativeButton("Click me to leave page", e -> UI.getCurrent().navigate(LeaveTarget.class)));
  }

  @Override
  public void beforeLeave(BeforeLeaveEvent event) {
    var action = event.postpone();

    var dialog = new Dialog("Confirm Leave");
    dialog.getFooter().add(new NativeButton("Confirm leave", e -> {
      action.proceed();
      dialog.close();
    }));
    dialog.open();
  }
}

@Route(value = "leave-target")
public class LeaveTarget extends VerticalLayout {

  public LeaveTarget() {
    add(new Paragraph("Why is the URL not leave-target?"));
  }
}

```

1. Open `leave-observer`
2. Click Button
3. Confirm Leave
4. User is redirected to `leave-target` but URL stays as `leave-observer`

### Versions

- Vaadin / Flow version: 24.4.7

**Comment by tepi** [comment] 2024-08-22 06:40
Tested using Vaadin 24.4.7 and latest available Chrome browser on macOS. Could not reproduce the issue with either react router or vaadin router. URL is correctly updated to `leave-target` when clicking the confirm button in the dialog.

@knoobie Is this still an issue, or am I testing it wrong?

**Comment by knoobie** [comment] 2024-08-22 06:59
let me re-test with the latest version

**Comment by tepi** [comment] 2024-08-22 07:07
Thanks. Retested with latest 24.4.10 (with react and vaadin routing), seems to work fine there too.

**Comment by tepi** [comment] 2024-08-22 07:10
Thank you! I'll close this issue (and the linked one since that case seems to work too). Please open a new issue if the problem still persists in some circumstances.

**Closed by tepi** 2024-08-22 07:10 UTC
Labels: bug, routing, waiting for author, Impact: Low, Severity: Major
