### ISSUE TITLE
Add TSDoc comments to all public TS APIs in `@vaadin/form`

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#8554] opened 2020-06-11 18:07 UTC
When using the TypeScript Binder APIs in an IDE with IntelliSense-like features, I want all public APIs in the `@vaadin/form` package to have TSDoc comments so that I can see reference documentation inline in my IDE without having to look for docs elsewhere.

DoD:
 - all public TS APIs in `@vaadin/form` have TS doc comments

**Comment by haijian-vaadin** [comment] 2020-07-31 10:53
Close as a duplicate of https://github.com/vaadin/flow/issues/8719

**Closed by haijian-vaadin** 2020-07-31 10:53 UTC
Labels: DX, ccdm
