### ISSUE TITLE
An empty error box is shown when session expires

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4070] opened 2018-05-04 11:42 UTC
When the session expires, an empty error box is shown in the top right corner. Nothing else happens

<img width="389" alt="screen shot 2018-05-04 at 14 18 48" src="https://user-images.githubusercontent.com/260340/39626105-4af2f88c-4fa9-11e8-8dd7-6ac2225ec87d.png">

**Comment by AlexRoig** [comment] 2018-05-05 19:59
I'm experiencing the same with the Spring starter (beta 8). Moreover, whenever I change from a browser tab, wait 5 or 6 seconds and get back to the Vaadin App, the session expires immediately and doesn't reconnect.

**Comment by ZheSun88** [comment] 2018-05-08 10:04
what would be a fast way to reproduce this?

**Comment by pleku** [comment] 2018-05-14 07:52
>I'm experiencing the same with the Spring starter (beta 8). Moreover, whenever I change from a browser tab, wait 5 or 6 seconds and get back to the Vaadin App, the session expires immediately and doesn't reconnect.

Hi @AlexRoig, that sounds like another issue than one reported here. Can you please create a separate issue for it, please also include a way to reproduce it, thanks.

**Comment by pekam** [comment] 2018-05-14 11:10
The "session expired" message is not shown because of @Artur- changing the default value in https://github.com/vaadin/flow/pull/3665

So I'm not sure anymore what is the target of this ticket. Is the expected behavior for session expired:
1. Show the "session expired" message, which can be done by changing the flag back to `true`.
2. Not show the empty box at all since there is no message to be shown.
3. Reload the page as suggested by the description of Artur's PR.

I recall that there was some discussion whether the default value should have been changed at all after the PR was already merged.

**Comment by Artur-** [comment] 2018-05-14 11:35
The expected behavior is that when there is no message, then the sessionExpiredUrl is used instead of showing a popup. If the session expired URL is null, then a refresh is expected

**Closed** 2018-05-17 08:43 UTC
Labels: UX, bug
