### ISSUE TITLE
Reconsider the necessity of the browser agent CSS classes

### ISSUE THREAD

**Issue by jouni** [vaadin/flow#3702] opened 2018-03-14 08:03 UTC
All of these classes are unnecessary by default: `<body class="v-sa v-sa11 v-sa110 v-webkit v-ios v-ios11 v-touch v-generated-body">`

When creating an empty Flow application, I expect the generated HTML to be as simple as possible (or as close to a defacto standard empty HTML page that browsers render), so that I have the least possibilities for unexpected side-effects and the least amount of “cruft” in my HTML.

We could still offer a utility that would allow the developer to add those classes if they want to, but we should not force them by default. They might be needed to workaround browser quirks, but they are not a best practice we should encourage to use.

The `v-` prefix seems maybe slightly off, considering that the framework is now called “Flow”. I suppose the prefix should be configurable if we would have a utility for generating these as an opt-in feature.

**Comment by Legioth** [comment] 2018-03-14 08:26
Duplicate of #2844

**Closed by Legioth** 2018-03-14 08:26 UTC

**Comment by jouni** [comment] 2018-03-15 07:36
Thanks! Quickly searched for an existing issue, but didn’t succeed.

**Comment by Legioth** [comment] 2018-03-15 08:54
> Thanks! Quickly searched for an existing issue, but didn’t succeed.

It also took me three different queries to actually find the other ticket, and I kept trying variations only because I was 100% sure there was one to find.
