### ISSUE TITLE
Regression: Setting innerHTML in Angular template broken

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#2730] opened 2017-10-20 05:58 UTC
Hi all,

We noticed a regression in Angular templates so that using `innerHTML` does not work anymore:

In Angular template:
`<section class="blog-post-view__article-body" itemprop="articleBody" [innerHTML]="post.text"></section>`

Rendered in browser:
`<section class="blog-post-view__article-body" itemprop="articleBody"></section>`

As we are not using `innerHTML` for Polymer templates we cannot be sure if they are affected, too.

That worked with Flow 0.1.22 but not after upgrading to 1.0.0.alpha5.

**Comment by SomeoneToIgnore** [comment] 2017-10-20 06:04
May be caused by: https://github.com/vaadin/flow/pull/2375

**Comment by paulroemer** [comment] 2017-10-20 06:14
Did you change the JSoup version during the update or have you used a patched JSoup before?

**Comment by SomeoneToIgnore** [comment] 2017-10-20 06:15
It's both: we were using custom version before this change and updated to a stock one after it was released with the API we need.

**Comment by paulroemer** [comment] 2017-10-20 06:18
Ok, so no easy way back.

**Comment by SomeoneToIgnore** [comment] 2017-10-20 06:20
First of all, this may not be the case.

At second, we can try out the old version and see if it works (I'll release one for you)
If it does, we will sure roll back on the old one, since we're not supposed to break things for you.

**Comment by paulroemer** [comment] 2017-10-20 06:26
Found an interesting affect:

After JSoup.parse() parse the document I can see different handling for `innerHTML`:

That one is the one that is not working in the end. Note that it is *innerhtml* now.
`<section class="blog-post-view__article-body" itemprop="articleBody" [innerhtml]="post.text"></section>` 

That one still works.
`<p class="blog-post-view__author-description" itemprop="description" [innerHTML]="post.authorDescription"></p>`

Check https://preview.vaadin.com/blog/community-spotlight-august-2017

You will notice that the body of the blog is *not* displayed but the author*s description.

**Comment by heruan** [comment] 2017-10-20 06:28
BTW isn't Angular Template about to be removed?

**Comment by paulroemer** [comment] 2017-10-20 06:30
```
08:29:06 vaadin@tuxbook:~/repos/webpage/webpage-frontend> find src/main/resources/com/vaadin/site/view/ -type f|grep View|wc -l
99
```

Feel free :) We are always happy about PRs!

**Comment by SomeoneToIgnore** [comment] 2017-10-20 06:32
> BTW isn't Angular Template about to be removed?

Unfortunately, we have to stay with it for a little longer, due to internal dependencies, like the one @paulroemer is talking about :)
Paul, @heruan won't be able to fix those, he's an external contributor :)

> Found an interesting affect:

So, did I get it right that the issue is the lower case? Or is it still not displayed?

**Comment by paulroemer** [comment] 2017-10-20 06:37
@heruan Damn, I forgot that the repo is public nowadays. Sorry for that. But now you know that we have a big cleanup task before we can remove the support.

@SomeoneToIgnore 
As the replacing takes place on client side I cannot debug it that easy. But it's likely. The question is why JSoup makes it to lower case once but keeps the case for the other.

**Comment by SomeoneToIgnore** [comment] 2017-10-20 06:43
> But it's likely.

That sounds promising. I'll prepare a special version for you with the old dependency, but it would be super cool if you try to fix the case thing, since it's the way it's supposed to work officially.
And if you fail or there are way too much changes, we'll just fall back to the original version.

**Comment by paulroemer** [comment] 2017-10-20 06:44
At the moment I have no idea why JSoup is doing it the way it does. Of course, I would prefer fixing it without switching back again.

**Comment by paulroemer** [comment] 2017-10-20 08:56
Okay, using the ParserSettings to prevent JSoup from lower casing the tags did the trick.

**Comment by SomeoneToIgnore** [comment] 2017-10-20 08:56
So, we can close the issue? :)

**Comment by paulroemer** [comment] 2017-10-20 08:58
Nope, because I had to patch the angular template parser.

**Comment by paulroemer** [comment] 2017-10-20 09:08
https://github.com/vaadin/flow/pull/2734

**Comment by SomeoneToIgnore** [comment] 2017-10-20 10:38
Have released a supplementary version.

**Closed by SomeoneToIgnore** 2017-10-20 10:38 UTC
