### ISSUE TITLE
Offline page shown on mac os when trying to access localhost without a network connection

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13616] opened 2022-04-25 17:34 UTC
### Description of the bug

When you start an application and do not have a network connection. e.g. wifi is turned off, the application shows the "you are offline" page instead of the application

### Expected behavior

The application should be shown

### Minimal reproducible example

```
npx @vaadin/cli init off
cd off
mvn
# Verify it works
# ctrl-c
# disconnect from the network
mvn
```

### Versions

Vaadin: 23.1.0.alpha3
Flow: 23.1.0.alpha3
Java: Homebrew 17.0.1
OS: aarch64 Mac OS X 12.3.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Live reload: Java active (Spring Boot Devtools): Front end active

**Comment by nikbucher** [comment] 2022-04-28 21:41
I noticed this error too some time ago. Is there a workaround for this? Because I'd like to work offline but this bug prevents it.

Thanks in advance for fixing it soon.

**Comment by circlesmiler** [comment] 2022-07-16 06:43
I have the same issue on MacOS with Vaadin 23.1.1.

**Comment by circlesmiler** [comment] 2022-08-21 06:13
This is also a big problem, when you are running (headless) E2E tests on VMs with no internet connections. So, it would be nice, if I could activate/deactivate the detection for special situations.

**Comment by mshabarov** [comment] 2022-12-07 09:38
The issue was assigned to a developer and is currently being investigated.

**Comment by silvan-lincan** [comment] 2022-12-20 13:36
Same issue here with Vaadin 23.2.x

**Comment by silvan-lincan** [comment] 2022-12-20 15:38
The problem is, if this is deployed as a desktop application, with Electron and Jetty, the application will not work at all.
A solution / temporary workaround would be really appreciated.

**Comment by Artur-** [comment] 2022-12-22 14:37
The problem is https://github.com/vaadin/flow-hilla-common/blob/04f7eea1a5f243078a1596d767d465716d862b95/frontend/packages/common-frontend/src/ConnectionState.ts#L129 and that `navigator.online` is `false` for a mac when the network is disconnected, even if it can connect to the current url. If you change that code to e.g.

```
    const online = navigator.onLine || location.hostname === 'localhost';
    $wnd.Vaadin.connectionState = new ConnectionStateStore(online ? ConnectionState.CONNECTED : ConnectionState.CONNECTION_LOST);
```
then it works

**Comment by Artur-** [comment] 2022-12-22 15:38
At least when you do not have `@PWA` so no offline page, it should skip the whole logic

**Comment by Artur-** [comment] 2022-12-22 15:47
You can work around this by adding
```
(window.Vaadin as any).connectionState.connectionState='connected';
```
to e.g. the end of index.ts

**Comment by silvan-lincan** [comment] 2022-12-22 15:51
@Artur-  
nice, I was wondering where can I "force" that state for my scenario.
Thank you very much.

**Comment by silvan-lincan** [comment] 2022-12-22 16:14
Unfortunately is not working. I get the following error: 
`Property 'Vaadin' does not exist on type 'Window & typeof globalThis'`

**Comment by Artur-** [comment] 2022-12-22 16:20
Is that 23.3 + Vite or something else?

**Comment by silvan-lincan** [comment] 2022-12-22 16:26
Is it possible to set that state in another place, or do I really need to upgrade to 23.3.?

**Comment by Artur-** [comment] 2022-12-22 16:46
For me it works also in Vaadin 23.2.11 the same way. 
One potential workaround to the workaround would be to add
```
import '@vaadin/common-frontend/ConnectionIndicator.js'
```
to the beginning of index.ts. Then it should ensure the indicator is imported before index.ts is executed.

Otherwise there are the common workarounds of delaying using `requestAnimationFrame` e.g.
```
requestAnimationFrame(
  () => ((window as any).Vaadin.connectionState.connectionState = "connected")
);
```

or then `setTimeout`...

**Comment by silvan-lincan** [comment] 2022-12-22 16:55
Thank you very much, I will clean everything and try again.

**Comment by silvan-lincan** [comment] 2022-12-22 16:56
I have 23.2.8

**Comment by silvan-lincan** [comment] 2022-12-22 17:44
No matter what I do, upgrading to 23.2.11, clean, etc., I always have the same error.
I will keep trying, maybe is something on my side that I don't see it now.

**Comment by Artur-** [comment] 2022-12-22 17:47
ah but you are talking about a typescript error `Property 'Vaadin' does not exist on type 'Window & typeof globalThis'`

use `(window as any).Vaadin`

**Comment by silvan-lincan** [comment] 2022-12-22 17:55
Yeeey, sorry about that. Works like a charm now.
Thank you very much.

**Comment by silvan-lincan** [comment] 2022-12-22 17:59
:) I can sleep better now, that I have something I can use.
Now it is only a matter of time, depending when we will deploy this, if you manage to come with an official solution in the meantime.
Thank you again.

**Comment by TatuLund** [comment] 2022-12-28 06:55
My 5 cents is that we should not change current behavior, but introduce API to configure it work differently when needed.

**Comment by Legioth** [comment] 2022-12-28 08:26
One thought was to always assume being online for localhost if `@PWA` is not used, while looking at the `navigator.onLine` flag if `@PWA` is present.

**Comment by silvan-lincan** [comment] 2022-12-28 09:01
If I understood correctly the original intended behaviour, I like better this solution.

**Comment by Artur-** [comment] 2022-12-28 10:20
> My 5 cents is that we should not change current behavior, but introduce API to configure it work differently when needed.

What would be the case when you want to see an offline page on one platform and not on others even though the server can be reached? I don’t think there is anything to configure here - it is a bug in the connection indicator and should be fixed there. It uses a flag for something else than whatthe flag tells (is the server reachable vs is internet reachable)

Ignoring the offline page when you do not have `@PWA` sounds good for that case but the PWA case would still be broken and would need another fix

**Comment by MarcinVaadin** [comment] 2023-01-03 10:45
@Legioth @Artur- @TatuLund - do we have any conclusions?

Is I understand from above:
> introduce API to configure it work differently when needed

Implementing configuration property to disable offlinePage is pretty easy, but:

> I don’t think there is anything to configure here - it is a bug in the connection indicator and should be fixed there

How would connection indicator distinguish if we want to run app locally without internet connection? Server pinging? 

And what if:
> since one might still want a way to explicitly test the offline state of an application even when it's running on localhost. I assume the workaround would also affect cases when offline mode is explicitly toggled in the browser's developer tools?

**Comment by Artur-** [comment] 2023-01-03 11:21
There are no thought-out, ready solutions. If we have a service worker, can we e.g. know from that one if it reached the server for index.html or not?

**Comment by jflamy** [comment] 2023-02-02 20:13
I just got bit by this.  We use Vaadin as an Electron-killer connecting to localhost.  An explicit flag of whatever form to say PWA not wanted here, we're back to 2015, it's all good.  What is really counter intuitive is that things work if connected to a router that is not connected to the internet -- whatever black magic is used seems to be relying on an ip address being available other than local...

**Comment by Artur-** [comment] 2023-04-02 05:28
I pushed my original fix for this to https://github.com/vaadin/flow-hilla-common/pull/11

If I turn wifi off, the app shows on reload
If I set the browser to offline, the offline page shows

**Comment by Artur-** [comment] 2023-04-02 06:23
It might need an additional fix to Flow but it does not seem super relevant for the case of running on a machine without a network connection. If you are online and turn off wifi, then it will go into offline mode even when on localhost

**Closed** 2023-04-02 13:15 UTC
Labels: bug, BFP, workaround, Impact: High, Severity: Major

**Comment by alexanoid** [comment] 2023-05-26 14:36
@Artur- something is definitely wrong with the offline page for Vaadin Flow. Sometimes my applications get stuck on the offline page and are unable to reload themselves when the network connection is restored. Also one more related issue to offline page https://stackoverflow.com/questions/76331860/vaadin-24-offline-stub-in-iframe
