### ISSUE TITLE
Bundling has incorrect paths to external resources that don't go into bundle.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3322] opened 2018-01-16 10:52 UTC
@SomeoneToIgnore commented on [Fri Dec 01 2017](https://github.com/vaadin/flow-maven-plugin/issues/30)

Based on https://vaadin.slack.com/archives/C6X43FE8M/p1512127313000324

Have a non-inlinable resource referenced from any webpage, for instance, jpg file.
Verify that it is displayed correctly in development mode.

Bundle the project, run in the production mode.
Expected: image is referenced correctly.
Actual: image path gets prefix before it, fails to load.

**Comment by caalador** [comment] 2018-01-22 12:39
I'll add the case where we have a webJar resource targeted through the code:  `this.resolveUrl("images/${rankName}_of_${symbolName}s_fr.svg")`

This will lead the browser to request when bundled for instance: `http://localhost:8080/frontend-es6/frontend/bower_components/game-card/images/king_of_spades_fr.svg`

The file is no found as there is no `*/frontend/bower_components/game-card/images/*`

**Comment by pekam** [comment] 2018-01-24 17:23
Non-transpiled non-bundled resources were not even included in the war-file produced from production build, but this is now fixed: https://github.com/vaadin/flow/pull/3388

Now the images work at least with non-bundled production build, but when you enable bundling, the problem stated in the above comment remains:
When using `Polymer.ResolveUrl.resolveUrl` to find the images as in [here](https://github.com/Artur-/game-card/blob/master/game-card.html#L380), the web component's [baseURI](https://github.com/Polymer/polymer/blob/master/lib/utils/resolve-url.html#L41) is resolved to `http://localhost:8080/frontend-es6/frontend/bower_components/game-card/`. I've verified that without the `frontend/` part the url would work.

So seems the problem is in the web component's path, not the path of the resources.

**Comment by SomeoneToIgnore** [comment] 2018-01-25 07:32
> So seems the problem is in the web component's path, not the path of the resources.

Not sure about that, since the original Slack thread indicates that the issue can be reproduced without using external WebComponents.
As I've already told you, it might make sense to reproduce it this way, but up to you.

**Closed** 2018-01-29 06:34 UTC
Labels: app starter, investigation, maven-plugin
