### ISSUE TITLE
After using UI.navigate a server route issued by client don't work.

### ISSUE THREAD

**Issue by bogdanudrescu** [vaadin/flow#8148] opened 2020-04-24 05:21 UTC
1. From server view A, open server view B using UI.navigate(B.class).
2. Open back the server view A using a client link.

Expected: server view A is displayed.
Actual: server view B remains on screen but the url changes.

See https://drive.google.com/open?id=1ERksSp-9P3KNU52oKX6lk-KaDl5RUwCH

**Comment by haijian-vaadin** [comment] 2020-05-04 21:37
Closing this as it's a duplicate of https://github.com/vaadin/flow/issues/8071

**Closed by haijian-vaadin** 2020-05-04 21:37 UTC
Labels: Impact: Low, Severity: Major, bug, ccdm, routing
