### ISSUE TITLE
Exception loading sessions from persistent storage in dev mode with Spring Boot

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12193] opened 2021-10-29 13:10 UTC
### Description of the bug / feature
This happens on a daily basis when developing the Start project. It happens when restarting the server or when Spring Boot devtools restarts it. It does not happen every time..

```
2021-10-29 15:16:27.706  INFO 78384 --- [  restartedMain] c.v.f.s.f.s.FullDependenciesScanner      : Visited 115 classes. Took 8 ms.
Vaadin application has been deployed and started to the context path "/".
2021-10-29 15:16:27.739 ERROR 78384 --- [  restartedMain] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.io.EOFException: null
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:3338) ~[na:na]
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2572) ~[na:na]
	at java.base/java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:652) ~[na:na]
	at com.vaadin.flow.server.VaadinSession.readObject(VaadinSession.java:1057) ~[flow-server-9.0-SNAPSHOT.jar:9.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231) ~[na:na]
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2408) ~[na:na]
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2242) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1742) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[na:na]
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1587) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1040) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:218) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
```

### Expected behavior
The session is serializable as UIs are excluded in dev mode

### Versions:
Vaadin: 22.0.0.alpha9
Flow: 9.0-SNAPSHOT
Java: Oracle Corporation 17
OS: x86_64 Mac OS X 11.6
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36

**Comment by pleku** [comment] 2021-11-11 20:44
I was able to reproduce this immediately with `22.0.0.beta2` when running via `mvn spring-boot:run` and then once or twice afterwards again, but never when debugging via IDEA (debug as Application/ debug "mvn spring-boot:run") with break points.
Now I realize that IDEA was actually setup to use Java 16 and Maven was using Java 17 so I need to test again...

When stepping through the successful serialization, only thing I saw that caught my attention was the `ReentrantLock` from `AbstractRouteRegistry` that was being serialized for `SessionRouteRegistry` as it seems unnecessary to serialize a lock, but this should not be a problem anyway.

**Comment by pleku** [comment] 2021-11-12 07:17
Cannot reproduce with Java 17 when running via IDEA ("run Application").

While it should not happen, I didn't have any side effects to this error and it feels like a waste of time to work on this without a way to reproduce it reliably so it could be investigated. Closing

**Closed by pleku** 2021-11-12 07:17 UTC

**Comment by Artur-** [comment] 2021-11-12 07:27
I see it daily with Start and Java 17 when running using `mvn` in a terminal. If I manage to figure out how to reproduce or happen to catch it in a debugger, I will reopen
