### ISSUE TITLE
`flow-server` does not work when `vaadin-lumo-theme` is not in the classpath.

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#12606] opened 2021-12-18 08:37 UTC
When having a plain flow project without any flow-component (e.g. fusion-endpoints + TS views) the project does not start because `discoverTheme()` does not considers this case. I think that this might be a regression at some point because the way how theming was computed by using reflexion should consider the case when a theme for java is not available, although it should consider frontends themes (eg `@Theme(value = "my-theme")`? . 

I modified the method to see what happens, and the second problem is that the bundle does not compile because the theme generator should either: not add the line `import { applyTheme } from 'Frontend/generated/theme'`  to the bundle, or produce an empty `theme.js`

```
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.theme.lumo.Lumo
...
	at com.vaadin.flow.server.frontend.scanner.FullDependenciesScanner.discoverTheme(FullDependenciesScanner.java:299) ~[flow-server-10.0-SNAPSHOT.jar:10.0-SNAPSHOT]
``` 

This is a critical problem for Hilla projects, since they should not import anything but `flow-server`, `flow-client` and `fusion-endpoints`

**Comment by caalador** [comment] 2021-12-20 08:28
Custom theme always requires the Lumo theme to be available and is not usable without it.

**Comment by caalador** [comment] 2021-12-20 08:42
Could you add this plain flow project so that it could be investigated that what is the cause for this as applications should work fine without any Lumo on the classpath.

**Comment by haijian-vaadin** [comment] 2021-12-21 09:05
Thanks for the explanation @caalador. Exactly as you said, the root cause is that we were using a custom theme `@Theme('my-theme')` in the testing app. If I remove the `@Theme` annotation, then the application can start without the `vaadin-lumo-theme` dependency.

So I think we can close this ticket now.

**Closed by haijian-vaadin** 2021-12-21 09:05 UTC
Labels: bug
