### ISSUE TITLE
Failed RPC with distressed network causes application to stop functioning

### ISSUE THREAD

**Issue by epricer** [vaadin/flow#9778] opened 2021-01-08 19:42 UTC
### Description of the bug / feature
Flow application stops working when network exhibits high jitter & latency.

Logs include multiple instances of `Unexpected message id from the client. Expected sync id: X, got Y`, often in bursts over the course of a few seconds.

When digging into this, I came across this comment: https://github.com/vaadin/flow/blob/a45fe2ee201fe0587e381a11a6d38744403282c3/flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java#L293-L301 
I thought this bug report may provide the desired data. A network diagnosis at the user's site showed an average latency of 108ms and an average jitter of 157ms (very high). Network requests were taking as long as 2200 ttfb. Average bandwidth was about 10Mbps 

### Minimal reproducible example
Flow application - Push may be required.
### Expected behavior
I'm not sure. Perhaps it would be useful to track over time - if it's intermittent, then resync. If a client is experiencing this frequently, then a notification of an unreliable network - like one might see in a video call.
### Actual behavior
User is notified of an internal error. The application stops functioning.

### Versions:
    - Vaadin / Flow version: 14.4.0
    - Java version: openjdk 11.0.9.1
    - OS version: AWS Linux
    - Browser version (if applicable): Chrome on Windows 87.0.4280.141
    - Application Server (if applicable): Spring Boot
    - IDE (if applicable): N/A

**Comment by Legioth** [comment] 2021-01-11 11:31
We have had that comment there for quite a while without uncovering any new logic flaws or such that would lead to deterministic cases (there was a couple of them during the first year or so).

**Comment by epricer** [comment] 2021-01-14 18:43
Simulating the peculiar state of this network situation _may_ be enough to reliably reproduce this situation. I know the linux tc tool can simulate jitter, which I personally suspect is the culprit. If this is a thread the maintainers are willing to pull on, I'd be willing to put together a project and instructions/script for simulating the network conditions. On the other hand, if this seems far-fetched and isn't something you're interested in pursuing, then I won't bother.

**Comment by pleku** [comment] 2021-02-11 09:00
Hi and sorry for the delay in response - if there would be a reliable way to reproduce this I think we would be interested in taking a look at investigating it and improving the situation as we have reserved more time for maintenance and fixes during Q1-Q2.

**Comment by epricer** [comment] 2021-03-25 18:07
I will try to post something within a week.

**Comment by pleku** [comment] 2021-04-15 07:27
This issue is still waiting for the steps to reproduce the issue. If it no longer reproduces, when it can be closed.

**Comment by miguelatvaadin** [comment] 2021-05-20 08:08
I will close this issue as no answer since March, 25. Please feel free to post a comment or reopen when there is new info. Thanks

**Closed by miguelatvaadin** 2021-05-20 08:08 UTC
Labels: core, investigation, push, waiting for author

**Comment by thomaskiesl** [comment] 2021-12-27 08:30
I receive sometimes the same error message on my production system. But I do not have any idea when this happen:

`2021-12-27 07:27:43,174  INFO | https-jsse-nio-18443-exec-10 | com.vaadin.flow.server.communication.ServerRpcHandler   | Ignoring old duplicate message from the client. Expected: 1748, got: 1747`

```
2021-12-27 07:28:01,354  WARN | https-jsse-nio-18443-exec-5 | de.app.ApplicationVaadinServiceInitListener         | Unexpected error
java.lang.UnsupportedOperationException: Unexpected message id from the client. Expected sync id: 1751, got 1752. more details logged on DEBUG level.
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:310)
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1565)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:302)
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)

```
