### ISSUE TITLE
Issues with Polymer3 and flow: Couldn't find the definition of the element with tag 'top-bar' in any template file declared using '@JsModule' annotations

### ISSUE THREAD

**Issue by schaerl** [vaadin/flow#6066] opened 2019-07-15 07:44 UTC
I have issues getting a polymer template to work, and get the following error message:

`There was an exception while trying to navigate to 'test' with the exception message 'Error creating bean with name 'testView' defined in file[C:\dev\workspace\sample\target\classes\js\ui\TestView.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [js.ui.TestView]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'top-bar' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file'`

See more description in [this forum thread](https://vaadin.com/forum/thread/17757131/having-trouble-with-using-polymer3-and-jsmodule).

I'm using Java8, vaadin14.rc4, npm 6.9.0 and mvn 3.3.9

I have attached a simple project that exhibits the issue.
[problematic-js.zip](https://github.com/vaadin/flow/files/3391280/problematic-js.zip)

**Comment by denis-anisimov** [comment] 2019-07-15 09:49
I'm able to reproduce this with the project attached.
The same is with the platform SNAPSHOT .
But I also see a webpack error which means that this is may be a known issue : https://github.com/vaadin/flow/issues/6026

**Comment by Legioth** [comment] 2019-07-30 12:07
Duplicate of #6069 which is fixed in the latest snapshots but not yet released.

As an alternative, you can fix the issue by moving your `/frontend` folder to the root of the project instead of using `/src/main/resources/META-INF/resources/frontend`.

**Closed by Legioth** 2019-07-30 12:07 UTC
Labels: bug
