### ISSUE TITLE
UI.navigate(...) removes context path from URL (Vaadin 10.0.13) even it has been defined in application.properties

### ISSUE THREAD

**Issue by Andelous** [vaadin/flow#5434] opened 2019-04-08 17:15 UTC
Hello, I just updated a project I'm working on to the recently released Vaadin 10.0.13 version (I was in 10.0.12) and immediatly noticed something broke. I downloaded the starter for Vaadin Spring 10.0.13 and tried to replicate the behaviour in order to discard an error with my code but, to my surprise, I managed to replicate it.

**Description of the bug**
When trying to navigate to my `MainView` from other views, using the `UI.navigate(...)` method, the context path is removed from the URL.

The application doesn't crash, but in my specific use case, I have to reload the page automatically in certain situations, so, with the missing context path, the application simply can't be loaded.

**Minimal reproducible example**
Download attached source and import it in Eclipse as Maven Project. Then run `Application.java`.
[bugged-spring.zip](https://github.com/vaadin/flow/files/3055507/bugged-spring.zip)

**Steps to reproduce**
- Access to `OtherView` or `AnotherView` from the `MainView` (root).
- Then, try accessing to `MainView` from either of those.
- When you do it from the `Button`, the context path is removed from the URL. If you use the `RouterLink`, no problem happens.

_Expected behaviour_: Context path present in the URL when using `UI.navigate(...)`.
_Actual behaviour_: Context path removed from the URL when using `UI.navigate(...)`.

There's a comment in the POM to change the project's version to Vaadin 10.0.12.

When working with 10.0.12 the problem is not present.

Any help is appreciated. Thanks in advance.

**Comment by ZheSun88** [comment] 2019-04-09 06:44
Hi @Andelous ,

Thanks for reporting this issue. 

I have tested your project and i can confirm. between 10.0.12 and 10.0.13, flow had a fix on `UI.navigation()`, [commit](https://github.com/sahalsaad/flow/commit/8203d5590f359c8b2ed14c0cb83cbd598e354773). 

It looks this fix is not covering all the situations, like we have a defined context path in the `application.properties`.

**Comment by Andelous** [comment] 2019-04-09 15:12
Thanks. I'll stick with V10.0.12 in the meantime.

**Comment by zagy11** [comment] 2019-04-27 12:30
Would like to add, this is also reproducible in 13.0.4.

**Comment by JohnnyBeGood70** [comment] 2019-06-04 00:18
This annoying bug still exists in 10.0.16. I have spent several hours searching for some solution...

**Comment by matjeromin** [comment] 2019-06-25 08:11
same here (vaadin 13.0.8) *bump*

**Comment by iskankh1** [comment] 2019-07-04 17:11
It's very annoying... still exists in 13.0.10

**Comment by iskankh1** [comment] 2019-07-04 18:02
Navigation itself works fine, the problem starts in History::pushState method, which uses JS to pushState into browser history:

`
    public void pushState(JsonValue state, Location location) {
        // Second parameter is title which is currently ignored according to
        // https://developer.mozilla.org/en-US/docs/Web/API/History_API
        ui.getPage().executeJavaScript("history.pushState($0, '', $1)", state,
                location.getPathWithQueryParameters());
    }
`

Here we can see that the path being got from location via getPathWithQueryParameters() method:

`
    public String getPathWithQueryParameters() {
        String basePath = getPath();
        assert !basePath.contains(
                QUERY_SEPARATOR) : "Base path can not contain query separator="
                        + QUERY_SEPARATOR;

        String params = queryParameters.getQueryString();
        if (params.isEmpty()) {
            return !basePath.isEmpty() ? basePath : "/";
        }
        return basePath + QUERY_SEPARATOR + params;
    }
`
Browser cuts context-path because of provided '/' here:

`
        if (params.isEmpty()) {
            return !basePath.isEmpty() ? basePath : "/";
        }
`

I don't think that this condition should even exists here, because if you provide empty string as path to JS pushState function it will perfectly work and context-path won't be cut.

Example which you can try in your browser console:
`
window.history.pushState({}, '', '');
`

So here is my dirty hack solution to navigate to root path of your app, while this if-statement still exists in Vaadin:

`
        title.addClickListener(event -> {
            getUI().ifPresent(ui -> {
                Router router = VaadinService.getCurrent().getRouter();
                ui.getPage().executeJavaScript("history.pushState($0, '', $1)", null, "");
                router.navigate(ui, new Location(""), NavigationTrigger.PROGRAMMATIC);
            });
        });
`

**Comment by brp-mattias** [comment] 2019-09-17 08:00
+1, we´re also experiencing this issue. 
@iskankh1 Thanks for the workaround, works great.

**Comment by caalador** [comment] 2020-03-13 09:43
I retested this and it was failing in 13.0.10, but was fixed in 13.0.11. 
Also worked as expected in 14.1.19 which is at the moment the suggested version to use.

Closing issue as the problem has been fixed. Please create a new ticket if the issue resurfaces.

**Closed by caalador** 2020-03-13 09:43 UTC
Labels: Impact: High, Severity: Major, bug, routing
