### ISSUE TITLE
Hot Deploy - Template-bundle files are not regenerated

### ISSUE THREAD

**Issue by Lars-jnk** [vaadin/flow#6018] opened 2019-07-03 08:07 UTC
If you change something in the Polymer templates, the effects won't be seen. The js files are copied into `target\xxx-SNAPSHOT\frontend\src\views`, but the `vaadin-bundle.*.js` in `target\xxx-SNAPSHOT\WEB-INF\classes\META-INF\VAADIN\build\` is still the one from initial build.

vaadin version: 14 betaX and rc3
starter app on wildfly 14 with netbeans 8.

**Comment by pleku** [comment] 2019-08-09 08:12
Hello. Thanks for the report. Since RC3 we have fixed some issues regarding template changes not being visible immediately.

Using 14 RC9, I was not able to reproduce this with Netbeans 11.1 and 
- Payara server 5.192 installed and started with Netbeans
- Using Wildfly Maven plugin 2.0.1

With both the frontend changes were picked up by webpack immediately after saving the file in Netbeans and after refreshing the browser page the changes were visible.

Closing this issue as it is most likely fixed. Please comment here or open another issue if it still reproduces.

**Closed by pleku** 2019-08-09 08:12 UTC
Labels: bug

**Comment by Lars-jnk** [comment] 2019-08-09 10:03
With netbeans 8 and wildfly 14 it still doesn't work.

**Comment by pleku** [comment] 2019-08-09 18:44
>With netbeans 8 and wildfly 14 it still doesn't work.

Just to clarify, you tested with Vaadin `14.0.0.rc9` ? Can you provide the full server logs after the save operation / browser refresh.

I just downloaded Netbeans 8.2 and setup Wildfly 14.0.1 to it, same thing, editing a template, press save and webpack picks the changes and I see them in the browser after refreshing.
I'm using Java 8 (OpenJDK) and Windows 10.

**Comment by Lars-jnk** [comment] 2019-08-16 09:50
With 14.0.0 is works fine. Now are some new errors :D 

 Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/flow-component-renderer.js
  If the build fails, check that npm packages are installed.

and "Webpack Error":

｢wds｣: Content not from webpack is served from C:\_dev\vaadin\demo14_release\target\classes\META-INF\VAADIN, src/main/webapp
         Serving the 'stats.json' file dynamically.
× ｢wdm｣: Hash: 50499d91123d7d01e743
Version: webpack 4.30.0


my mvn version: 3.6.1; npm: 6.10.3
starter app JEE + one template
