### ISSUE TITLE
ERROR http-nio-8080-exec-17 c.v.f.s.DefaultErrorHandler:34

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/flow#7603] opened 2020-02-16 11:07 UTC
**Vaadin Version:** 14.1.17
**Browser:** Chrome Windows with the latest version
**Application Server:** Tomcat 9.0

**Error Log:**

16-02-2020 14:02:43:101| ERROR http-nio-8080-exec-17 c.v.f.s.DefaultErrorHandler:34 - |
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:299)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:262)
        at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
        at com.vaadin.flow.server.communication.UidlRequestHandler.commitJsonResponse(UidlRequestHandler.java:190)
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:109)
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:259)
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:163)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:105)
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:144)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1223)
        at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:743)
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:696)
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:686)
        at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:553)
        at org.apache.coyote.http11.filters.IdentityOutputFilter.flush(IdentityOutputFilter.java:117)
        at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:216)
        at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1149)
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:394)
        at org.apache.coyote.Response.action(Response.java:209)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:295)
        ... 34 common frames omitted

**16-02-2020 14:02:48:164|  WARN http-nio-8080-exec-20 c.v.f.s.c.ServerRpcHandler:322 - | Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues**

**Comment by denis-anisimov** [comment] 2020-02-17 08:40
I'm not sure what is the bug here in the report ?

Do you care about the exception stacktrace or another message ?
The exception in the stacktrace happened in the `UidlRequestHandler.commitJsonResponse` and the reason is : 
```
org.apache.catalina.connector.ClientAbortException : java.io.IOException: Connection reset by peer
```

It means that the client (the browser) close the connection unexpectedly .
This is not a bug: the browser may close the connection.

So please clarify what the ticket is about.

**Comment by allenvpn312** [comment] 2020-02-20 18:24
In my case, when attempting to upload and process a data file (CSV) the second time, I get this error.  Also, on the second file upload attempt, it seems the upload finished listener does not fire. The weird thing is I don't see this behavior when I run the app locally.  However, the issue surfaces on a cloud hosted server.  I will continue to test and see if I an consistently replicate this.

**Comment by pleku** [comment] 2020-03-09 12:53
@allenvpn312 @ugurdoksan can you please add code here to reproduce the issue ?

**Comment by allenvpn312** [comment] 2020-03-09 17:24
@pleku upgraded to 14.1.18 and I don't see the error no longer.

**Comment by mehdi-vaadin** [comment] 2020-04-06 11:40
I'm closing this ticket as not enough information on how to reproduce the issue has been provided. @ugurdoksan if you still have this problem please create a new issue with code and instructions to reproduce. You can also try the latest maintenance release of Vaadin 14.1, which is 14.1.23 at the moment, to see if it resolves your issue or not.

**Closed by mehdi-vaadin** 2020-04-06 11:40 UTC
Labels: waiting for author

**Comment by allenvpn312** [comment] 2020-04-06 15:07
@mehdi-vaadin upgrading to 14.1.23 seems to fix the problem.  Thanks.

**Comment by mehdi-vaadin** [comment] 2020-04-06 15:17
@allenvpn312 thanks for the update.
