### ISSUE TITLE
JavaScript crash in transpiled production mode with IE11 only

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#4338] opened 2018-06-28 06:39 UTC
A user has encountered a JavaScript crash with the error message `SCRIPT5045: Assignment to read-only properties is not allowed in strict mode` that only happens on IE11 in production-transpiled mode. No reproducable sample application (yet), but the non-minified JS dump is attached.
[crash_log.txt](https://github.com/vaadin/flow/files/2144058/crash_log.txt)
As far as I can tell, the error is on this line:
`this._inEffect &amp;&amp; (this._inEffect = !1, this._idle = !0, this._paused = !1, this._isFinished = !0, this._finishedFlag = !0, this._currentTime = 0, this._startTime = null, this._effect._update(null), b.applyDirtiedAnimation(this));`

**Comment by cedricaebi** [comment] 2019-03-19 09:34
Hi I have the same problem. Did anyone find a solution for this?

**Comment by web-padawan** [comment] 2019-03-19 11:39
@cedricaebi one case I'm aware of, which could cause this, it the following assignment:

```js
element.style = '';
```
The reason of error is most likely in the user code, we shouldn't have such code in our components.

Could you provide an example code causing this to happen for your project?

**Comment by cedricaebi** [comment] 2019-03-20 11:15
Thanks for the reply I have absolutely no clue where this comes from, since I cant find a element.style=““ The only thing I can say is that the error comes from SCRIPT5045 strict mode

**Comment by Legioth** [comment] 2019-03-21 07:44
It would be hugely helpful with an example project where the problem can be reproduced.

**Comment by cedricaebi** [comment] 2019-03-21 08:21
I've found my problem yesterday. I was using the addon right here [https://vaadin.com/directory/component/app-layout-add-on/2.0.8](url) 

I forgot to remove the dependency out of my pom.xml.

The addon is currently not supporting Vaadin Flow and IE11, so I assume that was the issue. Everything works fine now

**Comment by mehdi-vaadin** [comment] 2020-03-30 08:38
Since we don't have an example to reproduce this issue, I'm closing it. If you encounter this again please create a new issue and provide your example.

**Closed by mehdi-vaadin** 2020-03-30 08:38 UTC
Labels: bug, investigation
