### ISSUE TITLE
[Form] feature: transform the input

### ISSUE THREAD

**Issue by vicb** [vaadin/flow#10477] opened 2021-03-29 16:15 UTC
### Description of the feature

It would be great to be able to transform the input.

My use case is that I want to trim the input. 
I can not trim the input in validation it is runs on every single keystroke and "hello world" would be ok while "hello world " should be transformed (I want to keep the inner space char).

The transforms should only run on:
- focus lost,
- before submit (and before validation).

### Actual behavior

This would be a new feature.
I don't think there is an easy way to implement this today other than subclassing the Binder.

**Comment by pleku** [comment] 2021-04-09 10:27
Hello. How about using a converter in the binding for that and then enabling write back of value to presentation? This is how it works by default since Vaadin 19 and you switch a binding to this starting from upcoming 14.6 with the API https://vaadin.com/api/platform/14.6.0.alpha2/com/vaadin/flow/data/binder/Binder.Binding.html#setConvertBackToPresentation-boolean-

**Comment by vicb** [comment] 2021-04-09 15:31
@pleku I am not exactly sure as I use the Form framework standalone, without any Java backend.

But my guess is your proposal kind of defeat the purpose of client side validation ?

For example a `^\d+$` or `{Min,Max}Length` would not act as expected with regards to extra white spaces if the converter is on the backend side. The converter (trimming the inputs in my case) would need to run before the client-side validation.

**Comment by pleku** [comment] 2021-04-09 15:51
Ok thanks for the clarification - I misunderstood your intention and thought you meant the _server side Binder_ - so you can ignore what I said above. Too bad that the client side class got the same name as the Java one.

**Comment by Haprog** [comment] 2021-05-27 05:35
Is this a duplicate of https://github.com/vaadin/flow/issues/7931 ?

**Closed** 2021-05-27 14:09 UTC
Labels: fusion
