### ISSUE TITLE
Page refresh breaking UI in production mode

### ISSUE THREAD

**Issue by idonthaveusername9** [vaadin/flow#18860] opened 2024-03-01 10:16 UTC
### Description of the bug

I have some pages in my application, and now when i'm trying to add one more page my UI is breaking when i try to refresh that page. It happens only if i start application in production mode (mvn clean package -Pproduction). I can't understand why is this happening, because when i start application in development mode there is no any problems with page refresh.

Running in development mode:
  - I can open any page works fine
  - I can refresh any page works fine
 
![image](https://github.com/vaadin/flow/assets/160304548/7756be0a-2720-47c7-9dff-c0fcfac75c61)

Running in production mode:
  - I can open any page works fine
  - I can refresh any page except the last page i've created. UI is just breaking when i try to refresh that last page that i added.
  
![image](https://github.com/vaadin/flow/assets/160304548/e113d885-f986-42ed-b1c3-da3038231835)

And got this error in console

![image](https://github.com/vaadin/flow/assets/160304548/0de6264e-8567-475b-b5de-77c59ab6efb9)

### Expected behavior

There should be no errors with page refresh in production mode too.

### Minimal reproducible example

.

### Versions

- Vaadin / Flow version: 24.3.1
- Java version: 17

**Comment by mshabarov** [comment] 2024-03-05 14:30
@lazizbektulanov thanks for the issue and glad that with the eager loading the prod mode works for you.
However, we'd like to understand why doesn't it work with lazy bundle loading.

Do you use a reflection for components instantiating? Do you use Vaadin add-ons ? Anything special with how you configure a theme?

**Comment by idonthaveusername9** [comment] 2024-03-07 05:52
@mshabarov

- I did not use reflection
- The page is empty, and for navbar i used standart SideNav.
- For language select i used Component Renderer in order to display a flag image with lang name and Lumoutilities for styling
I think, that's it

**Comment by mshabarov** [comment] 2024-04-02 10:05
Thanks for the provided info. Could you please also try with the latest `24.3.8` version?

**Comment by mshabarov** [comment] 2024-04-02 10:07
Also, if you can provide a minimal reproducible example project, it would be helpful for us to figure out what is wrong with the prod bundle chunks and styling in overall.

**Comment by mshabarov** [comment] 2024-04-23 10:06
I'm closing this issue because of no reply during more than 2 weeks. Please comment in this ticket, if you still have issues with the latest Vaadin 24.3 versions.

**Closed by mshabarov** 2024-04-23 10:06 UTC
Labels: investigation, waiting for author
