### ISSUE TITLE
NPM: `frontend://` prefix doesn't work sometimes in JSModule annotation

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5615] opened 2019-05-06 10:18 UTC
Steps to reproduce:
check the PR: https://github.com/vaadin/vaadin-crud-flow/pull/131

Open `CrudInTemplate` class.
replace `@JsModule("src/crud-in-template.js")` to `@JsModule("frontend://src/crud-in-template.js")`

Run integration tests and go to `http://localhost:8080/crudintemplate`.
Exception is thrown: 

(works fine with `@JsModule("src/crud-in-template.js")`
```
java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'crud-app' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:119)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:187)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:94)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:107)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:122)
	at com.vaadin.flow.component.crud.examples.CrudInTemplate.<init>(CrudInTemplate.java:22)
	... 52 more
```

Acceptance criteria: 
- make sure that both annotation values are working.
- output a warning in case `frontend` is present in the value.

**Comment by Legioth** [comment] 2019-05-07 06:04
I don't think there's any technical reason ever for why `frontend://` should be used without Bower mode. Alternatively, we might want to interpret `frontend://` in a different way depending on which mode is used.

**Comment by denis-anisimov** [comment] 2019-05-07 06:07
May be.
I was asked to create this ticket.
I'm fine to close it if we don't want to support this.

**Comment by Legioth** [comment] 2019-05-07 06:51
Even if we don't want to support this, then we should still make it so that a developer can understand the cause and what they should do instead.

**Comment by pleku** [comment] 2019-05-08 07:59
Since `frontend://` is valid for eg. `@Javascript` we should handle misuse of it with `@JsModule` with a good error message that can help the users to fix things.

**Comment by Legioth** [comment] 2019-05-08 09:13
> Since `frontend://` is valid for eg. `@Javascript`

Is it really valid? The point of `frontend://` is to resolve to either `frontend-es5` or `frontend-es6` based on the output from Polymer CLI. My understanding is that we don't have anything such in npm mode, which means that `frontend://` might technically be valid, but it still doesn't serve any purpose.

**Comment by Artur-** [comment] 2019-05-08 09:17
If a project still goes into Bower mode when a frontend folder is found, then rather throw an exception telling where frontend files should be moved

**Comment by manolo** [comment] 2019-05-21 09:17
The implementation now says that 
- `@JsModule("frontend://src/crud-in-template.js")` is replaced by `./src/crud-in-template.js` and warns the user to modify its annotation
- `@JsModule("src/crud-in-template.js")` is replaced by `./src/crud-in-template.js` if the file is local and the user is warned to add the `./` prerix

**Comment by manolo** [comment] 2019-05-21 09:22
This should fix this https://github.com/vaadin/flow/pull/5705 but still the annotation should be fixed to have the `./` prefix

**Comment by pleku** [comment] 2019-05-28 11:04
Reported from 14 beta2:
```
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://gridConnector.js' to './gridConnector.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://contextMenuConnector.js' to './contextMenuConnector.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://comboBoxConnector.js' to './comboBoxConnector.js', please update your component.
```

These should not be visible for all the users as the default experience when using the platform.

**Comment by Legioth** [comment] 2019-05-28 12:12
I believe that those could be fixed simply by doing like it says in the warning message. Something like `@JavaScript("./gridConnector.js")` would be exactly what we want for npm mode. For Bower mode it would be interpreted as `frontend://./gridConnector.js` since that's the default protocol. That in turn would most likely do exactly the same as the current `frontend://gridConnector.js`.

**Comment by denis-anisimov** [comment] 2019-05-29 07:50
https://github.com/vaadin/flow/issues/5797

**Comment by manolo** [comment] 2019-05-29 18:47
`./my-connector.js` fails in bower-production-mode, it still does the request to the server and gets a 404 error.

**Closed** 2019-05-30 17:21 UTC
Labels: bug, npm
