### ISSUE TITLE
Spring Boot devtools reload loses routes

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#5940] opened 2019-06-19 02:04 UTC
Vaadin 14 beta 3. Created with `vaadin init --pre`

Problem description:
I have a view mapped to `grid` and I'm working on it. After a few spring boot devtools reloads, Vaadin says that the route is not found and only lists `<root>`. Restarting the server solves the issue.

**Comment by marcushellberg** [comment] 2019-06-19 13:43
@qtdzz mentioned in a slack comment that he has also experienced this occasionally

**Comment by denis-anisimov** [comment] 2019-06-22 06:13
I cannot reproduce that.
Could you please provide project/steps to reproduce that I can use to see the issue ?
I understand that this happens randomly but may be it's possible to achieve at least the behavior 
via soem variable scenario ?

**Comment by mtrojahn** [comment] 2019-06-24 20:08
I have this problem too at the point I just remove devtools from my project and restart manually... I'd like to add that sometimes just restarting the server does not fix it. Many times I had to clean and rebuild for it to work again.

As for Denis question, it's completely random... For example, I added a println to my code right now as I read your comment and pressed ctrl-f9 to compile and it happened. Also, I was only able to fix it by removing devtools from my POM. Cleaning and rebuilding didn't work.

**Comment by mehdi-vaadin** [comment] 2019-06-26 06:25
@marcushellberg It's really difficult to reproduce. I tried to find @qtdzz's comment in Slack but, I couldn't. Would you please share a link to the comment? Any more information that makes it easier to reproduce this issue is appreciated.

**Comment by mehdi-vaadin** [comment] 2019-07-01 07:37
Since this issue is really difficult to reproduce, some logging has been added to `VaadinServletContextInitializer` class in Spring add-on to see what's going on. 
I'm closing this for now. If it happens again, please add the log to this issue. See https://github.com/vaadin/spring/pull/460

**Closed by mehdi-vaadin** 2019-07-01 07:37 UTC
Labels: bug, investigation, npm
