### ISSUE TITLE
CSS not picked up when building in productionmode and component is only used in a dialog

### ISSUE THREAD

**Issue by ssindelar** [vaadin/flow#8380] opened 2020-05-19 09:34 UTC
### Description of the bug
When a component is just used in a dialog the css of the component is not included when the application is compiled for production. In my case this happend with a  @CssImport and a build in component (Tabs).
Adding the component to a dummy view fixes the problem and the component works fine in the dialog.
No error messages about missing files or else are shown. In the IDE (Eclipse) without production mode it works fine.

### Minimal reproducible example
Empty project with just a dialog which has a tabbar as content. 
### Expected behavior
All required CSS is included in production mode.
### Actual behavior
CSS of components that are only used in dialogs are missing.
### Versions:
    - Vaadin / Flow version: 14.1.28
    - Java version: 8
    - OS version: Windows 10
    - Browser version (if applicable): Firefox, Chrome
    - Application Server (if applicable): Embedded Tomcat
    - Build Tool: Gradle (offical vaadin gradle plugin)

**Comment by denis-anisimov** [comment] 2020-05-27 07:53
No steps to reproduce.

Based on the description I'm using my steps:

- Take https://github.com/vaadin/skeleton-starter-flow
- Modify the `MainView` class with the code below.
- Run the code in dev mode.
- Run code in production: no any difference.

>All required CSS is included in production mode.

Don't know which CSS should be loaded but since I don't see a difference between production mode and dev mode result I assume everything is loaded.

```
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Say hello", e -> {
            Dialog dialog = new Dialog();

            Tabs tabs = new Tabs();

            Tab tab = new Tab();
            Div div = new Div();
            div.setText("AAAAAAAAA");
            tab.add(div);

            tabs.add(tab);
            dialog.add(tabs);
            dialog.open();
        });

        add(button);
    }
}
```

**Comment by denis-anisimov** [comment] 2020-06-10 10:07
No any response in two weeks.
Closing.
Please create another ticket with detailed steps to reproduce if it's still valid or provide the steps to reproduce right here and I will reopen the ticket.

**Closed by denis-anisimov** 2020-06-10 10:07 UTC
Labels: Impact: High, Severity: Major, bug, waiting for author
