### ISSUE TITLE
Publish prereleases to Vaadin prereleases

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#2693] opened 2017-10-17 06:08 UTC
When using prereleases of Flow, I do not want to specify another repository than the Vaadin prerelease repository where prereleases of all other projects go: https://maven.vaadin.com/vaadin-prereleases

**Comment by pleku** [comment] 2017-10-17 12:00
Duplicate of #2489

**Closed by pleku** 2017-10-17 12:00 UTC
