### ISSUE TITLE
[Vaadin 19] Theming Embedded Applications with Custom Theme- theme is broken when embeded component opens Dialog

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#10132] opened 2021-02-25 21:09 UTC
### Description of the bug
In my app I have a lot of pseudo-components which extend vaadin components and add some global styling (background, layout, borders, paddings etc) by css. 
I have additionally a visual component which is exported via WebComponentExporter and embeded as web component in some static html/servlet. Because the content of a web component generated by WebComponentExporter was moved to the shadow DOM (from Vaadin 14.2) to get it work in Vaadin 19 I've used the new Custom Theme mechanism. It's great and it generally works but unfortunately doesn't work in one situation.
I've created my Custom Theme (properly) and add `@Theme` annotation to AppShellConfigurator and WebComponentExporter  component.

I've prepared a simple test app:  in simple visual component I add one of my pseudo-component (with its styling). Additionally, from this component I can open a Dialog via a button. This Dialog also has this pseudo-component added.

**What works:**  
When I route to my component directly (as a View) everything works. My pseudo-components added directly in the View and even in the Dialog are styled properly.
![image](https://user-images.githubusercontent.com/56316289/109215022-dbc5f600-77b2-11eb-9ea1-2b195600495e.png)

**What doesn't work:**
When the same visual component is exported via WebComponentExporter (of course with `@Theme` annotation) and embedded in some static html/servlet, my pseudo-component is styled properly only in web component. But when I open a Dialog with second pseudo-component styling is gone. 
![image](https://user-images.githubusercontent.com/56316289/109215486-82aa9200-77b3-11eb-8bc2-1f07371144c4.png)

It's because Dialog is openend as a separate div (component) in the body of static html/servlet in which my Theme is not visible.
Do I have to add to all my pseudo-components @CssImport annotation? But why if the application works without it when I'm using `@Theme` annotation in AppShellConfigurator :)
Or is there any other way?

### Minimal reproducible example
This is my simple test app (based on the Vaadin 19 example  taken from Vaadin site) : 
[my-app.zip](https://github.com/vaadin/flow/files/6045771/my-app.zip)

### Versions:
    - Vaadin / Flow version: 19.0.0.beta4

**Comment by rolfsmeds** [comment] 2021-03-01 16:36
Yes, I suppose this is caused by the teleporting of the dialog outside of the web component, so the styling applied by `@Theme `to the shadow root doesn't apply to it.

We don't really have a fix for this at this point, but if it's acceptable to have the styles in the document root rather than in the exported component's shadow dom, you could put them in a stylesheet called `document.css` instead -- that will be applied to the document root i.e. as part of the page's global css.

**Comment by darmro** [comment] 2021-03-01 17:56
Thank you @rolfsmeds for your answer. 
I'm developing an app which is a normal Vaadin app (has many views served via WWW) and additionaly has a few "widgets" ie. views exported as web components (via `WebComponentExporter`) adn later embedded in another application (CMS). 
On Vaadin 19 I used the new Custom Theme mechanism. So I have `@Theme` annotation on my `AppShellConfigurator ` and everything is ok for my normal views. 
Your suggestion is to add import to all my pseudo-component css'es in `document.css`. But `document.css` is a CSS that is always applied to the root of the page, not only for embedded apps but also for my normal Vaadin app. Is it ok that in this way all my pseudo-element css'es will be added to my app in two ways, once by `@Theme` annotation and second by `document.css`?
So far I have dealt with this by adding `@CssImport` annotation to my generic "widget View" (all my widgets are using this) which is served later via `WebComponentExporter`. And it works.

Apart from all that, I think it would be a good idea to add to the vaadin documentation a small description for a case where the web component opens Dialog (or other overlays component) that `@Theme` annotation alone on `WebComponentExporter` it is not enough :)

**Comment by taefi** [comment] 2021-03-02 10:02
Hi @darmro, thanks for creating this issue. The issue is reproducible, so it needs a deeper investigation. 

Some tips about configuring the new theming mechanism:
- It is recommended to have your styles for the views under `themes/your-theme` folder and then you can import them through `@Import` statements in the `styles.css` file (which is imported by default). Then, no need to use `@ImportCss` annotation in your views. 
- "documentCss" as the key inside `theme.json` is designed to be used when you want to use styles for the embedded components:
```JSON
{
  "documentCss": ["@fortawesome/fontawesome-free/css/all.css"]
}
```

**Comment by darmro** [comment] 2021-03-02 10:32
Thank you @taefi

> * It is recommended to have your styles for the views under `themes/your-theme` folder and then you can import them through `@Import` statements in the `styles.css` file (which is imported by default). Then, no need to use `@ImportCss` annotation in your views.

that's exactly what I have :)  I dont have `@ImportCss` in my pseudo-components and any views. All my styling is done by `@Theme` annotation and all css are under `themes/your-theme` folder.

> * "documentCss" as the key inside `theme.json` is designed to be used when you want to use styles for the embedded components:  
> ```json {
>   "documentCss": ["@fortawesome/fontawesome-free/css/all.css"]
> }
> ```

I meant `document.css` which is located in `themes/your-theme` folder. This file is a CSS that is always applied to the root of the page, not only for embedded apps. So by adding all my global styles to this `document.css` I have a situation in my normal vaadin app (normal Views, not emeded widgets), that my global styles are applied to the application twice, by `@Theme` annotation and by `document.css`. Probably it is not a problem in general but it is weird ;)

**Comment by pleku** [comment] 2021-03-31 08:35
Probably the only thing we can do is follow your suggestion by improving the embedding flow documentation on applying theming and using dialogs.
>Apart from all that, I think it would be a good idea to add to the vaadin documentation a small description for a case where the web component opens Dialog (or other overlays component) that @Theme annotation alone on WebComponentExporter it is not enough

Otherwise, I don't know what else could be done than making it possible to configure where the overlay is added in the DOM ? Would that be possible or even help @rolfsmeds ?

**Comment by rolfsmeds** [comment] 2021-04-01 07:41
I think our best bet is to wait for browser support for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog, and then refactor `vaadin-dialog` based on that. Really just WebKit dragging their feet at this point, as Chrome and Edge already have out-of-the-box support and FF has it behind a flag.

**Closed** 2021-04-23 12:10 UTC
Labels: Impact: Low, Severity: Major, bug, documentation, theming
