### ISSUE TITLE
Infinite Lambda Chaining in PendingJavaScriptInvocation (Memory Leak)

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/flow#17082] opened 2023-06-22 11:30 UTC
### Description of the bug

Consider the minimal reproducible example below.

Once a button is attached a JS is invoked via `Button#initDisableOnClick`. Since the button `b` is not visible, that pending JS invocation will be retained internally. For those invisible components/nodes the pending JS is retained but now with every interaction with the view you can get an infinite lambda chain.

Each time you click on button `a`, during `UidlWriter#createUidl` the `UIInternals#dumpPendingJavaScriptInvocations` method is executed, which at the end is calling `UIInternals#registerDetachListenerForPendingInvocation` for each retained pending JS invocation. Finally, `invocation.then(callback, callback)` is being called which then calls

`this.successHandler = combineHandlers(this.successHandler, successHandler);`

This is called because
- Initially, `sentToBrowser` is false because this invocation has not been sent yet since its node was not visible yet.
- and the invocation is not `canceled`
- and the provided successHandler from UIInternals is not null

The provided successHandler parameter is always the same:

```java
SerializableConsumer callback = unused -> listener.onInvocationCompleted(invocation)
```

Now, during the first call the `PendingJavaScriptInvocation#successHandler` is null, so combineHandlers will just return the provided not null successHandler and store that in the field.

But, each time you click now on button `a` in the browser, next combineHandlers will have both not null, the field successHandler as well as the param successHandler. This leads to combining both to a new lambda and storing that in the field successHandler. Next time you click again and again, so you get an endless chaining of lambdas.

<img width="935" alt="Screenshot 2023-06-22 at 1 09 47 PM" src="https://github.com/vaadin/flow/assets/1894101/1b763a7f-51e1-4ca6-aa19-f378b99e0ac9">

Remember that those chained lambda callbacks in the end are always the same ones provided by the calling method `UIInternals#registerDetachListenerForPendingInvocation`. The chaining would make sense if the callbacks were different ones, but in this case it's always the same callbacks each effectively doing a `onInvocationCompleted()` once called.

Assuming that an app has components that are initialized or implemented like in this minimal example, eventually this situation will make the app end up in an `OutOfMemoryError`, the more invisible components with pending JS there are the faster this will be reached.

### Expected behavior

There should be no memory leak in PendingJavaScriptInvocation via potential endless chaining of lambdas.

### Minimal reproducible example

```java
@Route("")
public class View extends Div {

  public View() {
    Button a = new Button("test");
    Button b = new Button("invisible");
    b.setVisible(false);
    add(a, b);
  }
}
```

Each time you click on button `a`, the `PendingJavaScriptInvocation#successHandler` gets a new lambda chain longer than the previous one.

### Versions

- Vaadin / Flow version: 14.10.1
- Java version: 17.0.6
- OS version: macOS

**Comment by knoobie** [comment] 2023-06-22 12:28
The problem is gone in 24.1 and onwards if you wanna upgrade.

**Comment by muhammetaltindal** [comment] 2023-06-23 04:12
**Note** (Steps to overcome this temporarily)
1. copy classes `PendingJavaScriptInvocation`, `UIInternals` into your own project under same package

2. add public marker interface
```java
public interface JsInvocationCompleteConsumer<T> extends SerializableConsumer<T> {
  // Marker interface
}
```

3. In `UIInternals` in method `registerDetachListenerForPendingInvocation` where `SerializableConsumer callback` is declared replace var type with `JsInvocationCompleteConsumer `

4. In `PendingJavaScriptInvocation` add field
```java
private boolean invocationCompleteConsumerRegistered = false;
```

6. In `PendingJavaScriptInvocation` in method `then` at end of method replace field assignments for `this.successHandler = ...` and `this.errorHandler = ...` with:
```java
boolean isInvocationCompleteConsumer = successHandler instanceof JsInvocationCompleteConsumer;
if (!isInvocationCompleteConsumer || !this.invocationCompleteConsumerRegistered) {
  this.successHandler = combineHandlers(this.successHandler, successHandler);
  this.errorHandler = combineHandlers(this.errorHandler, errorHandler);
}
if (isInvocationCompleteConsumer) {
  this.invocationCompleteConsumerRegistered = true;
}
```

This will make sure the `JsInvocationCompleteConsumer` lambda is attached only once.

**Comment by mcollovati** [comment] 2023-06-23 05:18
@muhammetaltindal thank you for the detailed issue and for the insights. We will start working on this shortly.

**Comment by kkleinwi** [comment] 2023-07-17 20:13
Has this fix been incorporated into any Vaadin 23.3 release yet? If not, are there plans to?

**Comment by knoobie** [comment] 2023-07-17 20:29
No 23.3 release containing the fix. The branch is updated but no release was cut.

**Comment by kkleinwi** [comment] 2023-07-17 20:34
I need this pretty badly. Upgrading to 24.x isn't a short-term option due to the need to switch to Jakarta Servlet. Who can we poke to get a 23.x release cut?

**Comment by mcollovati** [comment] 2023-07-18 06:41
The fix has been released in Flow 23.3.14, included in Vaadin platform since 23.3.15.
For some reason, it is not mentioned in the release notes

**Comment by mcollovati** [comment] 2023-07-27 15:49
Our tests show that this issues has been fixed in Flow 23.3.14 (Vaadin 23.3.15).
If you still see the problem and can provide information, or even better, a reproducible example, we can reopen the issue or create a new one

**Comment by kkleinwi** [comment] 2023-07-28 14:25
The issue DOES appear to be resolved in the code for flow-server-23.3.15, which is part of Vaadin 23.3.16, so I'm going to upgrade to that.

**Comment by mcollovati** [comment] 2023-07-28 14:35
My apologies, you're right.
Something weird happened with the release notes. The fix is tagged in 23.3.14, but how you noticed it is not in the artifact.
I'll check what happened.
Please let us know if the latest Flow version fixes the issue for you
Sorry again

**Comment by patanges** [comment] 2023-08-31 13:56
In my application, I was using Vaadin 23.3.4 when I upgraded it to 23.3.21, I Observed a page stuck issue. When I downgraded it to 23.3.10 the issue was resolved. When checking the changes of vaadin it is observed that after vaadin 23.3.11 the detach listener for PendingJavaScriptInvocations was added. Looks like that is the root cause of my issue. Also, the page that struck has a leaflet map. Is there any relation between leaflet map (0.5.0) and PendingJavaScriptInvocations? Can you please let me know when this issue gets resolved?

**Comment by mshabarov** [comment] 2023-09-01 07:50
Needs a further investigation of https://github.com/vaadin/flow/issues/17082#issuecomment-1701087697 .

**Comment by caalador** [comment] 2023-09-05 07:44
@patanges would you have a sample app with the view that does get stuck?
When you say leaflet map do you mean https://vaadin.com/directory/component/leafletmap-for-vaadin or something else?

**Comment by mshabarov** [comment] 2023-09-20 07:07
Closed, as we don't have a reproducible example. Please comment in this ticket or open a new one if the issue is still valid for you.

**Closed by mshabarov** 2023-09-20 07:07 UTC
Labels: bug, BFP, waiting for author, Impact: High, Severity: Blocker, Released with Vaadin 24.2.0.alpha1, prerelease version for Vaadin 24.2.0, Released with Vaadin 14.10.3, Released with Vaadin 22.1.1
