### ISSUE TITLE
Spring with web.xml no longer supported in Vaadin 22

### ISSUE THREAD

**Issue by unb** [vaadin/flow#12605] opened 2021-12-18 01:48 UTC
(Originally from https://stackoverflow.com/q/70210023/4795356 )

In Vaadin 18, it is possible to integrate Vaadin with vanilla Spring and web.xml, as shown in the attached maven project.
To verify:

    > jar xvf webxmltest-0.1-src.zip
    > cd webxmltest-0.1
    > mvn jetty:run

and open http://localhost:8080/app in a browser.

This no longer works in Vaadin 22. It fails with:
 
    java.lang.IllegalStateException: The application Lookup instance is not found in the interface com.vaadin.flow.server.VaadinContext instance. It means that the container has not executed Lookup initialization code: so either the container is not Servlet 3.0 compatible or project configuration is broken.
        at com.vaadin.flow.server.startup.ApplicationConfiguration.lambda$get$0 (ApplicationConfiguration.java:58)
        at com.vaadin.flow.server.VaadinServletContext.getAttribute (VaadinServletContext.java:73)
        at com.vaadin.flow.server.startup.ApplicationConfiguration.get (ApplicationConfiguration.java:50)
        at com.vaadin.flow.server.DeploymentConfigurationFactory.createPropertyDeploymentConfiguration (DeploymentConfigurationFactory.java:82)
        at com.vaadin.flow.server.startup.ServletDeployer$StubServletConfig.createDeploymentConfiguration (ServletDeployer.java:185)
        at com.vaadin.flow.server.startup.ServletDeployer.lambda$getServletConfigurations$0 (ServletDeployer.java:278)
        at java.util.Optional.ifPresent (Optional.java:159)
        at com.vaadin.flow.server.startup.ServletDeployer.getServletConfigurations (ServletDeployer.java:277)
        at com.vaadin.flow.server.startup.ServletDeployer.contextInitialized (ServletDeployer.java:194)
        at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized (ServletContextListeners.java:44)

To verify, edit pom.xml and replace: 

    <vaadin.version>18.0.6</vaadin.version>
with:

    <vaadin.version>22.0.0</vaadin.version>

What is required to integrate Vaadin 22 with web.xml and Spring?
[webxmltest-0.1-src.zip](https://github.com/vaadin/flow/files/7738533/webxmltest-0.1-src.zip)

**Comment by caalador** [comment] 2021-12-21 10:56
I expect that the ticket #11904 is the reason. This needs to be fixed and a test added to not break the functionality again.

**Comment by joheriks** [comment] 2021-12-30 14:31
This is due to an [earlier refactoring](https://github.com/vaadin/flow/pull/9727) and affects already V19. The issue is that `Lookup` must be initialized by the `SpringLookupInitializer$SpringApplicationContextInit` `ApplicationContextAware` but that step is missing in this project setup: the application configuration needed is in https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinApplicationConfiguration.java

Try an `applicationContext.xml` with the following contents:
```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context-3.0.xsd">
    <context:annotation-config/>
    <bean class="com.vaadin.flow.spring.VaadinApplicationConfiguration"></bean>
</beans>
```
(alternatively `<bean id="vaadinApplicationContextInitializer" class="com.vaadin.flow.spring.SpringLookupInitializer.SpringApplicationContextInit">` but I do not recommend it as `SpringApplicationContextInit` is internal to Vaadin)

While this is technically a regression this project setup has not been officially supported, and I do not see how it could work out of the box. Hence closing the ticket.

**Closed by joheriks** 2021-12-30 14:31 UTC
Labels: bug, spring, Impact: Low, Severity: Major, regression

**Comment by unb** [comment] 2022-01-02 05:31
Thanks very much. Your solution works for me.

**Comment by echarlus** [comment] 2022-03-11 10:43
Hi,
I'm facing the same issue (now with Vaadin 23.0.1). I've created the applicationContext.xml  as explained and added a step to package it into the war file : 
` <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <webResources>
                        <resource>
                            <directory>src/main</directory>
                            <targetPath>WEB-INF</targetPath>
                            <filtering>true</filtering>
                            <includes>
                                <include>applicationContext.xml</include>
                            </includes>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>`
The file is included in the war in WEB-INF but I'm still getting the same error at startup. 
Where should this file be placed ?
Thanks

**Comment by rkovarik** [comment] 2022-03-22 09:40
Hey @echarlus , 

I have added this to web.xml:
```
  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>/WEB-INF/applicationContext.xml</param-value>
  </context-param>
  <listener>
    <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
  </listener>
```

Hope that helps
Roman

**Comment by echarlus** [comment] 2022-03-22 10:10
@rkovarik thanks for pointing me to this solution. I'll try it.

**Comment by archiecobbs** [comment] 2022-04-09 20:00
FYI [this stackoverflow question](https://stackoverflow.com/questions/70210023/vaadin-22-with-web-xml-and-spring/71811465) may also may be helpful.
