### ISSUE TITLE
$0.$connector is undefined

### ISSUE THREAD

**Issue by us31t** [vaadin/flow#5001] opened 2019-01-29 19:17 UTC
Hello 

This is a request for a better Exception. I do not even say it is a bug, but a really bad and time consuming Exception!

Occurs: 
As JS Exception in the Browser Console and triggers a "v-system-error" in the DOM with the text: "$0.$connector is undefined". 

I am working with: 

```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-bom</artifactId>
    <version>12.0.4</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

This exception occurs when:
 + You have a component of com.vaadin.flow.component.dialog.Dialog
 + You are in the @UIScope 
 + You add the Dialog to a component on one place (in my case Menu of a AppLayout)
 + And on a different place "just" call Dialog#open()
 + Happens if you open() the bound Dialog first and then try to open() the unbound instance

Resolved when:
 + You always add the Dialog to a component and not just call open() 

Because the Dialog shows up properly, even if you have not added it to a component, and the error disappears if you add it. I do not know if you call this a bug or not. 

I think this might happen, because of something like:
The Bean got properly initialized by the first call and then on the second call, the Dialog DOM element gets added to a (new/different?) parent DOM element. Then the (proper) initialized JS throws the Error because it is still bound to the initial parent DOM element?

Please improve exception handling! (e.g. raise a Java Exception)

Thanks you very much!

**Comment by ujoni** [comment] 2019-01-30 09:02
Would you be able to provide a small code snippet highlighting the erroneous behavior?

**Comment by us31t** [comment] 2019-01-30 12:02
Thank you for the reply! 

I could not reproduce the error in a stand alone example. So it  seems my suggestion was wrong. 

Here is the full JS Stacktrace. Can you suggest anything  why this could happen?

```
Exception is thrown during JavaScript execution. Stacktrace will be dumped separately. client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972:237
jt
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972:237
it
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:928:276
gt
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:564:57
Pq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:479:18
mr
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:19000
aA
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:863:192
Rq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:975:582
gr
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:18673
Bj
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:410:27
Jq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:976:941
Kq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:961:368
Ys
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:22011
FA
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:34071
si/c.onreadystatechange<
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:569:61
sb
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:420:27
vb
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:847:56
ub/<
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:604:46
(TypeError) : $0.$connector is undefined client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197:18
vB
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:197:18
cn
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:955:293
bn
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:732:80
dn
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:585:58
jt
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:972:357
it
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:928:276
gt
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:564:57
Pq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:479:18
mr
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:19000
aA
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:863:192
Rq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:975:582
gr
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:18673
Bj
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:410:27
Jq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:976:941
Kq
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:961:368
Ys
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:22011
FA
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:980:34071
si/c.onreadystatechange<
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:569:61
sb
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:420:27
vb
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:847:56
ub/<
http://josephine:8080/VAADIN/static/client/client-D1AD34905AC1AA5B4DBECA8FB0306D92.cache.js:604:46

```

Thank you very much!

**Comment by us31t** [comment] 2019-01-30 12:21
The error seems to be correlated to a specific component I use in the Dialog. Not the Dialog itself. I have testet multiple Dialog implementations now and it only shows up in some of them. 

I saw googling that the ComboBox#setItems causes issues sometimes. I use a ComboBox in the mentioned Dialogs (and a Datepicker).

**Comment by us31t** [comment] 2019-01-30 12:31
I am now quite certain that its the ComboBox. 

If I only update the values in the Dataprovider once (e.g. in the Constructor) it works. 

If I update the Compbobox on open() it fails. I will try to make a standalone example.

**Comment by us31t** [comment] 2019-01-30 12:47
I could resolve this in my project, by providing all values for all ComboBoxes in the Constructor and not using a setter. 
My Dialog extension still has the annotation @SpringComponent and @UIScope.

**Comment by bogdanudrescu** [comment] 2019-01-31 12:33
It might be that the comboBoxConnector was not initialised. This was fixed by https://github.com/vaadin/vaadin-combo-box-flow/pull/188, which will be soon released.

Could you please confirm if the problem persist after using this fix?

**Comment by bogdanudrescu** [comment] 2019-01-31 12:33
Possible duplicate of https://github.com/vaadin/vaadin-combo-box-flow/issues/169

**Comment by us31t** [comment] 2019-01-31 12:50
Yes of course. In what Vaadin release will it be?

**Comment by bogdanudrescu** [comment] 2019-02-01 09:18
Platform 13 beta and ComboBox 2.1.0.beta1, they're due for next week.

But even now it is possible to use the snapshot release. You need to update your pom.xml with snapshot dependency and repository:

```
...
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-combo-box-flow</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
...
        <repository>
            <id>vaadin-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
        </repository>
...
```

**Closed** 2019-02-01 13:46 UTC
Labels: bug

**Comment by us31t** [comment] 2019-02-05 14:04
Hello bogdanudrescu

Sorry for the late reply, but I was busy.

I can approve that this SNAPSHOT resolves the issue in my case!
Thank you very much!
