### ISSUE TITLE
Client side components break on Spring Boot devtools reload

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#6420] opened 2019-09-09 16:14 UTC
Vaadin 14.0.3
Java 11
SpringBoot starter 
Started with `mvn spring-boot:run`

With the following code:

```java
@Route
public class MainView extends Div {
    public MainView() {
        add(new Button("Button 1"));
    }
}
```

Changing the caption to "Button 2" and pressing build in IntelliJ causes spring-boot devtools to reload. The browser displays the updated caption as plain text, the button is missing. Sometimes it works, but usually by the second change, it breaks.

The project I had issues with:
[layouts.zip](https://github.com/vaadin/flow/files/3591520/layouts.zip)

**Comment by caalador** [comment] 2019-09-11 08:30
I couldn't reproduce this in Windows10 + Chrome/Brave/Edge/Opera/Firefox browser 

Platform 14.0.4
Java 11.0.4_10

Could this be a *nix environment problem?

**Comment by denis-anisimov** [comment] 2019-09-11 09:01
I can try it with Mac OS.

**Comment by denis-anisimov** [comment] 2019-09-11 09:33
I cannot reproduce this either on Mac OS.
I don't have InetlliJ but I've used running Java main class in Eclipse.
Dev tools works in this case similarly. 
The button is not broken after several reloads.

Two things to note:
- it would be good to have reliable steps to reproduce of course
- `The browser displays the updated caption as plain text, the button is missing.` This is just a visual effect. There should be reasons why it happens. It might be that : styles are missed, the HTM L element is not defined/loaded (doubt since it has a text), something else. May there is an error in the console. If we don't have steps to reproduce reliably then  at least this information may help to understand the issue.

**Comment by pleku** [comment] 2019-10-04 05:22
Since there haven't been any similar reports for over three weeks, I'm closing this issue as there is nothing we can do at this point when we cannot replicate the issue.

**Closed by pleku** 2019-10-04 05:22 UTC
Labels: bug, waiting for author
