### ISSUE TITLE
Vaadin for TypeScript: enable multi-module project support for TS generation

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9010] opened 2020-09-15 08:21 UTC
Current implementation (as of V17) scans the main module sources for `@Endpoint`, and expects the pojos to be in the same module. This is not always the case in a complex project setups. I see several possible approaches:

#### Effort: medium

In addition to project directory, use sources from JARs. This will require that the modules have enabled `maven-source-plugin` in their `pom.xml`.

Challenges:
- Typical project have lots of dependencies, scanning (and parsing) them all would take too much time. We should either scan the current module for endpoints, but still support POJOs in other modules, or allow user to specify modules (or packages) to scan.

Cons:
- Only Java language
- No fallback in case `maven-source-plugin` is not enabled (or `mvn install` didn't happen)

#### Effort: high

Use bytecode to generate structure, then enrich with JavaDoc obtained from project sources or source JARs produced by `maven-source-plugin`. If sources are not available for whatever reason, generated TS won't have JSDoc.

Challenges:
- Requires a complete rewrite of parser
- Typical project have lots of dependencies, scanning (and parsing) them all would take too much time. We should either scan the current module for endpoints, but still support POJOs in other modules, or allow user to specify modules (or packages) to scan. (same is for 1)

Pros:
- Any JVM language (read: Kotlin)
- Works even if sources are not available

#### Effort: high

Instead of scanning classes, we can hook at the `@Endpoint` annotation during the compilation process and generate an intermediate result, that could be later used in prepare front-end build step.

Challenges:
- Non-trivial support for endpoints defined in one module and POJOs in another.
- We need to aggregate generated intermediates from JARs during the prepare front-end build step.

Pros:
- Doesn't require `maven-source-plugin`

Cons:
- Only Java language
- Annotation processing needs to be explicitly enabled in gradle
- Annotation processing could be disabled in IDE.

**Comment by igormilina** [comment] 2020-09-17 06:48
I also run into this problem (tested with 17.0.2). As I can see, endpoint class can use pojos from another module as parameters and return vaues, and TS files will be generated for those pojos. The problem is, generated files don't have docs nor validation constraints (in model class).

**Comment by Legioth** [comment] 2020-09-17 07:01
I'd consider the lack of validation constraints for external data types to be a bug. The lack of documentation is expected and shouldn't affect actual functionality.

**Comment by Legioth** [comment] 2021-04-19 10:30
We should preferably have baseline "JVM" support that just uses bytecode even though you might get ugly parameter names in generated TS.

On top of that, we can have optimizations for common cases based on e.g. parsing sources, reading `@Named` annotations or the optional presence of parameter names in the bytecode (i.e. `-parameters`).

**Comment by eiswind** [comment] 2021-04-19 11:18
This is already of interest for those of us who like to write thier backend with Kotlin.

**Comment by eiswind** [comment] 2021-08-09 11:29
Is there anything happening at this point?

**Comment by haijian-vaadin** [comment] 2021-09-07 11:38
Decided to go with the ` Operate on compiled classes` approach, we are currently doing some research on it.

**Comment by haijian-vaadin** [comment] 2021-12-03 08:29
This was an investigation ticket, and we decided to go with alternative #2, and the foundation is done in https://github.com/vaadin/fusion/pull/110, there is some remaining work to be done which is collected in [this Epic](https://app.zenhub.com/workspaces/fusion-5d413125e27a7b3dba911156/issues/vaadin/fusion/123), so closing this ticket now.

@thron7 using an annotation to limit the scan is actually a very good idea, thanks for the suggestions, I will make a separate enhancement ticket to the Epic.

**Closed by haijian-vaadin** 2021-12-03 08:29 UTC
Labels: enhancement, investigation, fusion
