### ISSUE TITLE
Vaadin 24.4.1 - GradlePlugin has Spring dependencies

### ISSUE THREAD

**Issue by subITCSS** [vaadin/flow#19573] opened 2024-06-13 09:30 UTC
### Description of the bug

We wanted to upgrade from the latest VaadinFlow 24.3.X to the 24.4.1. But we discovered a dependency issue for non Spring projects. 
As you can see here the GradlePlugin references the HillaGradlePlugin - which needs Spring as reference. [https://mvnrepository.com/artifact/com.vaadin/vaadin-gradle-plugin/24.4.1](https://mvnrepository.com/artifact/com.vaadin/vaadin-gradle-plugin/24.4.1) . 

This causes that our dependencies are not found and we cannot upgrade to this version cause we don´t have any Spring-References in our non spring project.

![image](https://github.com/vaadin/flow/assets/155952489/41cee961-c54c-4e82-93c2-217faa8219f7)

### Expected behavior

There is no dependency of Hilla/Spring e.g. which causes any dependency issue for a non spring project.

### Minimal reproducible example

[https://mvnrepository.com/artifact/com.vaadin/vaadin-gradle-plugin/24.4.1](https://mvnrepository.com/artifact/com.vaadin/vaadin-gradle-plugin/24.4.1)

### Versions

- Vaadin / Flow version: 24.4.0 and 24.4.1
- Java version: 17

**Comment by mshabarov** [comment] 2024-06-13 09:41
This is a severe bug and should be fixed in the upcoming patch release. 
Until then, the workaround is to use `flow-gradle-plugin` instead of `vaadin-gradle-plugin` with the Vaadin Flow versioning, i.e. currently it's 24.4.0 latest version.

**Comment by subITCSS** [comment] 2024-06-13 10:04
Why only in the next patch release and not as a hotfix - we had a BFP and are therefore waiting for the 24.4.x version to use it. The Workaround is causing issues for ourself - cause the dependencies are not found correctly.

**Comment by mshabarov** [comment] 2024-06-13 11:23
The fix is under development, we'll make the release once it's resolved.

**Comment by mshabarov** [comment] 2024-06-14 07:17
@subITCSS Vaadin 24.4.0 version is broken in a way that it uses pre-release version of Hilla (24.4.0.rc2), that might be the reason of failures.

Could you please try to use Vaadin version `24.4.1` and flow gradle plugin version `24.4.0`. Do you have still any errors in that cases? If yes, could you please share them?

**Comment by caalador** [comment] 2024-06-17 07:20
Adding this into build.gradle will remove hilla from the plugin path:
```
buildscript {
    configurations.classpath {
        exclude group: 'com.vaadin', module: 'hilla-engine-core'
    }
}
```

Gradle buildEnvironment without the exclusion:
```
classpath
+--- com.vaadin:vaadin-gradle-plugin:24.4.2
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.20
|    |    \--- org.jetbrains:annotations:13.0
|    +--- com.vaadin:hilla-engine-core:24.4.1
|    |    +--- com.vaadin:flow-server:24.4.1
...
```

Gradle buildEnvironment without the exclusion, and no hilla in the output:
```
classpath
+--- com.vaadin:vaadin-gradle-plugin:24.4.2
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.20
|    |    \--- org.jetbrains:annotations:13.0
|    +--- com.vaadin:flow-gradle-plugin:24.4.1
|    |    \--- com.vaadin:flow-plugin-base:24.4.1
...
```

Hope this helps while we search for a solution.

**Comment by tepi** [comment] 2024-06-17 08:20
Yes, that was one of the first things I tried. It fixes the dependency issue but introduces other issue(s). At least `./gradlew tasks` does not work anymore since the Hilla tasks code is still there but dependencies are not found:

```
tepi@kurki-mbp base-starter-gradle-24 % ./gradlew tasks
> Task :tasks FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':hillaGenerate'.
   > Could not create task of type 'EngineGenerateTask'.
      > Could not generate a decorated class for type EngineGenerateTask.
         > com/vaadin/hilla/engine/GeneratorException

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 575ms
1 actionable task: 1 executed

```

**Comment by caalador** [comment] 2024-06-17 08:57
Interesting. I don't have a problem if I run `gradlew build` nor `gradlew appRun` for the base-starter-gradle with the hilla exclusion, but `gradlew tasks` does fail. 
What does tasks actually execute?

**Comment by mcollovati** [comment] 2024-06-18 14:07
I can only reproduce if the Java version available on PATH is 11 instead of 17.
The screenshot also reports 

```
Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
```

**Closed** 2024-06-19 08:06 UTC
Labels: bug, waiting for author, Impact: High, Severity: Blocker

**Comment by subITCSS** [comment] 2024-06-19 09:27
So does version 24.4.3 fix this issue?

**Comment by mshabarov** [comment] 2024-06-19 09:41
No, the patch will be released with the hot-fix 24.4.4 version.

**Comment by subITCSS** [comment] 2024-06-25 15:14
Are there any time updates on this? - when this version will be released

**Comment by caalador** [comment] 2024-06-26 03:49
Version 24.4.4 (latest) was released yesterday 25 June 2024.
Documentation on the usage can be seen here https://github.com/vaadin/docs/pull/3499/files

**Comment by subITCSS** [comment] 2024-06-26 09:53
@mshabarov @caalador 
So i updated all the dependencies to Vaadin 24.4.4 but again i receive hilla dependencies which are referencing spring in a non spring project.
![image](https://github.com/vaadin/flow/assets/155952489/e4e5734e-a717-4039-80dc-9a1bdf27a67e)

**Comment by mshabarov** [comment] 2024-06-26 09:58
@subITCSS have you applied also the exclusions documented [here](https://vaadin.com/docs/latest/upgrading#hilla-react-dependencies) for Gradle, also the `hilla.active=false` parameter ?

**Comment by subITCSS** [comment] 2024-06-27 10:15
@mshabarov We discoverd another problem with the new verson:
To create our sbom we check the npm references and getting this error:
```
npm error code ELSPROBLEMS
npm error invalid: @open-wc/dedupe-mixin@1.4.0 /node_modules/@open-wc/dedupe-mixin
```

The Issue we discovered is that the vaadin-bundles requires the fixed version of 1.3.1 for it
![image](https://github.com/vaadin/flow/assets/155952489/00c39b49-f9e5-4e15-8f4c-e9f0185d3c0d)

while all components require the ^1.3.0 and as there is an 1.4.0 the system updates the dependency to 1.4.0 which clashes with the upper fixed definition.
![image](https://github.com/vaadin/flow/assets/155952489/8bfff365-13b7-44fb-9b19-5d5988243219)

So based on this the Versions should be both fix or flexible using the ^.

**Comment by mshabarov** [comment] 2024-06-27 11:11
@subITCSS thanks for discovering this 👍 

Looks like a completely different issue, could you please create a new ticket in [Vaadin Platform repo](https://github.com/vaadin/platform/issues/new/choose) as I'm not sure where the bug is, in [vaadin-bundles](https://github.com/vaadin/bundles/) or components or somewhere else.

**Comment by subITCSS** [comment] 2024-06-27 11:15
The new issue is defined under https://github.com/vaadin/platform/issues/6549
