### ISSUE TITLE
Error handling with HasErrorParameter is broken

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#4549] opened 2018-08-22 09:40 UTC
Any error will cause an Internal Error message to be show on the web page instead of calling the respective error handler. The console log shows 
"client-CAF80B1F92BD4481C6D5EC01BC2D55AE.cache.js:197 Internal error
uB @ client-CAF80B1F92BD4481C6D5EC01BC2D55AE.cache.js:197"

Small example:
```
package com.foo.routing;

import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.BeforeEnterEvent;
import com.vaadin.flow.router.ErrorParameter;
import com.vaadin.flow.router.HasErrorParameter;

public class MyErrorView extends Div implements HasErrorParameter<ArithmeticException>{
	@Override
	public int setErrorParameter(BeforeEnterEvent arg0, ErrorParameter<ArithmeticException> arg1) {
		setText("Nope!");
		return 400;
	}
	
}
----
package com.foo.routing;

import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.HasComponents;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends Div implements HasComponents {
	
	public MainView() {
		
		Button b = new Button( "Test");
		b.addClickListener( new ComponentEventListener<ClickEvent<Button>>() {
			
			@Override
			public void onComponentEvent(ClickEvent<Button> arg0) {
//cause ArithmeticException
				int x = 1/0;
				System.out.println(x);
			}
		});
		add(b);
	}
	
}


```

**Comment by mehdi-vaadin** [comment] 2020-03-30 12:17
I would say this is not a bug and as @Legioth commented it works like this by design. #4715 is an enhancement issue about this. So, I'm closing this issue. Please follow up/comment on #4715 if you need to.

**Closed by mehdi-vaadin** 2020-03-30 12:17 UTC
Labels: bug
