### ISSUE TITLE
Failed to load static resources

### ISSUE THREAD

**Issue by SpicyBoyd** [vaadin/flow#11198] opened 2021-06-10 04:50 UTC
### Description of the bug / feature
Failed to load static resources when loading the webpage.
### Minimal reproducible example

1. project link: [vaadin-flow-issue](https://github.com/SpicyBoyd/vaadin-flow-issue/tree/11198/)
2. Add more than two static resources to `/src/main/resources/META-INF/resources/`
2. Production Mode build
3. _Clear browser cache_
4. Deploy the project to Tomcat

### Expected behavior
Load static resources successfully.
### Actual behavior
Failed to load static resources _sometimes_.

![Screenshot 2021-06-10 124442](https://user-images.githubusercontent.com/29849204/121466458-106c5f00-c9ea-11eb-910c-190a358ff7f1.png)

### Versions:
    - Vaadin / Flow version: 14.6.2 (brokenness starts with 14.6.2)
    - Java version: 11
    - OS version: Windows 10
    - Browser: Chrome, Firefox, and Edge

**Comment by pleku** [comment] 2021-06-10 09:18
Didn't test yet, but probably a duplicate of #11144 and #11197 ? Releases with the fix for those is on the way.

**Comment by pleku** [comment] 2021-06-10 12:25
I tested that the Flow 2.6.3 fixes the issue with the provided project. Vaadin 14.6.3 is available now, so please update to that.

**Closed by pleku** 2021-06-10 12:25 UTC
