### ISSUE TITLE
Validation fixes in Flow 24.3.5 cause breaking changes

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#18789] opened 2024-02-23 03:39 UTC
### Description of the bug

It seems that the validation fixes introduced in https://github.com/vaadin/flow/pull/18535 cause breaking changes in Flow 24.3.5. When a single field is changed, all bindings are validated. Previously, only the binding for the changed field is validated.

### Expected behavior

Changing the value of a field should only validate that field, not all bindings.

### Minimal reproducible example

https://github.com/oliveryasuna/vaadin-validation-fixes-bug

The project is set to Platform 24.3.5.
1. Start the application, modify any of the fields, and observe that all other fields are validated.
2. Change the Platform version to 24.3.3, do the same, and observe that only the modified field is validated.

### Versions

Platform version: 24.3.4/5
Flow version: 24.3.5

**Comment by mcollovati** [comment] 2024-02-23 05:52
Closing as duplicate of #18735, fixed by #18760 and back-ported to 24.3.
Fix will be included in the next Flow/Vaadin releases

**Closed by mcollovati** 2024-02-23 05:52 UTC
Labels: duplicate
