### ISSUE TITLE
Navigating after going to not-found address under /frontend breaks URL

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#5975] opened 2019-06-26 08:34 UTC
Vaadin 13.0.9, also reproduces in 14.0.0.rc1
I have a class that `implements HasErrorParameter<NotFoundException>` to handle all URLs under the base root that don't have registered routes and redirects them to the main view with `UI.navigate("main")`. This works ok for normal cases and takes me to `[urlbase]/main` and shows the error message, but if I try to navigate to a URL that has `frontend` after the base, the navigation will take me to `[urlbase]/frontend/main`.

Sample project to reproduce:
[v13-demo.zip](https://github.com/vaadin/flow/files/3328808/v13-demo.zip)
Run the project locally and try opening the browser at e.g. `localhost:8080/frontend/xyz`; you will end up at `localhost:8080/frontend/main` when it should be `localhost:8080/main` as you will if you use e.g `localhost:8080/xyz`.

Related issue: https://github.com/vaadin/flow/issues/5775

**Comment by denis-anisimov** [comment] 2019-07-10 10:34
That happens because we were deploying one more `VaadinServlet` to with `/frontend` mapping.
This is unnecessary at all in case if root mapping and even if it's done the static resources servlet shouldn't do any navigation at all.
So this is a duplicate of: https://github.com/vaadin/flow/issues/5775 and will be fixed by
https://github.com/vaadin/flow/pull/6040

**Closed by denis-anisimov** 2019-07-10 10:34 UTC
