### ISSUE TITLE
Vaadin 14.0.11 application doesn't start on WAS 9.0.0.9

### ISSUE THREAD

**Issue by malborali** [vaadin/flow#7202] opened 2019-12-19 10:42 UTC
**Hello, I tried to start an application on WAS 9.0.0.9 but I got the error below (the same application run started correctly on Tomcat 8.5):**

[12/12/19 12.18.32:074 CET] 000001cf AdminHelper  A  ADMN1008I: Tentativo di avvio dell'applicazione sivwebTST_war. (ID utente = RealmFederato/waslocaladmin)

[12/12/19 12.18.32:424 CET] 000001cf CompositionUn A  WSVR0190I: Avvio unità di composizione WebSphere:cuname=sivwebTST_war in BLA WebSphere:blaname=sivwebTST_war.

[12/12/19 12.18.33:191 CET] 000001cf ApplicationMg A  WSVR0200I: Avvio dell'applicazione: sivwebTST_war

[12/12/19 12.18.33:192 CET] 000001cf ApplicationMg A  WSVR0204I: Applicazione: sivwebTST_war livello di build dell'applicazione: sconosciuto

[12/12/19 12.18.41:113 CET] 000001cf webapp       I com.ibm.ws.webcontainer.webapp.WebGroupImpl WebGroup SRVE0169I: Caricamento del modulo web in corso: sivweb.

[12/12/19 12.18.41:142 CET] 000001cf WASSessionCor I SessionProperties shouldSetAndDoLogging SESN0169I: Il gestore sessione ha rilevato la proprietà personalizzata InvalidateOnUnauthorizedSessionRequestException con valore true.

[12/12/19 12.18.41:143 CET] 000001cf WASSessionCor I SessionContextRegistry getSessionContext SESN0176I: Verrà creato un nuovo contesto di sessione per la chiave dell'applicazione webtst.gruppoveronesi.com/sivweb-ui

[12/12/19 12.18.44:963 CET] 000001cf webapp       E com.ibm.ws.webcontainer.webapp.WebApp notifyServletContextDestroyed SRVE0285E: Eccezione rilevata in fase di eliminazione del contesto: {0}

                                java.lang.NullPointerException

 at org.jboss.weld.servlet.WeldInitialListener.contextDestroyed(WeldInitialListener.java:119)

 at com.ibm.ws.webcontainer.managedobject.ManagedObjectListenerWrapper.contextDestroyed(ManagedObjectListenerWrapper.java:138)

 at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextDestroyed(WebApp.java:1909)

 at com.ibm.ws.webcontainer.webapp.WebApp.destroy(WebApp.java:3376)

 at com.ibm.ws.webcontainer.webapp.WebAppImpl.destroy(WebAppImpl.java:1574)

 at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:97)

 at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171)

 at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904)

 at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789)

 at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427)

 at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)

 at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1248)

 at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1575)

 at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:704)

 at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1150)

 at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:800)

 at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplicationDynamically(ApplicationMgrImpl.java:1450)

 at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2311)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436)

 at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$1.run(CompositionUnitMgrImpl.java:654)

 at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5574)

 at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5700)

 at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:668)

 at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCompositionUnit(CompositionUnitMgrImpl.java:612)

 at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:1340)

 at sun.reflect.GeneratedMethodAccessor1014.invoke(Unknown Source)

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)

 at java.lang.reflect.Method.invoke(Method.java:508)

 at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:83)

 at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)

 at java.lang.reflect.Method.invoke(Method.java:508)

 at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:287)

 at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1263)

 at java.security.AccessController.doPrivileged(AccessController.java:673)

 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

 at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1257)

 at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1096)

 at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:831)

 at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:813)

 at com.ibm.ws.management.AdminServiceImpl$1.run(AdminServiceImpl.java:1350)

 at com.ibm.ws.security.util.AccessController.doPrivileged(AccessController.java:118)

 at com.ibm.ws.management.AdminServiceImpl.invoke(AdminServiceImpl.java:1243)

 at com.ibm.ws.management.connector.AdminServiceDelegator.invoke(AdminServiceDelegator.java:181)

 at com.ibm.ws.management.connector.ipc.CallRouter.route(CallRouter.java:247)

 at com.ibm.ws.management.connector.ipc.IPCConnectorInboundLink.doWork(IPCConnectorInboundLink.java:360)

 at com.ibm.ws.management.connector.ipc.IPCConnectorInboundLink$IPCConnectorReadCallback.complete(IPCConnectorInboundLink.java:602)

 at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)

 at com.ibm.ws.tcp.channel.impl.WorkQueueManager.requestComplete(WorkQueueManager.java:558)

 at com.ibm.ws.tcp.channel.impl.WorkQueueManager.attemptIO(WorkQueueManager.java:608)

 at com.ibm.ws.tcp.channel.impl.WorkQueueManager.workerRun(WorkQueueManager.java:985)

 at com.ibm.ws.tcp.channel.impl.WorkQueueManager$Worker.run(WorkQueueManager.java:1074)

 at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)

[12/12/19 12.18.44:972 CET] 000001cf webapp       E com.ibm.ws.webcontainer.webapp.WebGroupImpl WebGroup SRVE0015E: Impossibile inizializzare l'applicazione Web sivweb

[12/12/19 12.18.44:976 CET] 000001cf DeployedAppli W  WSVR0206E: Il modulo sivweb.war dell'applicazione sivwebTST_war.ear/deployments/sivwebTST_war non è stato avviato

[12/12/19 12.18.44:977 CET] 000001cf ApplicationMg W  WSVR0101W: Si è verificato un errore durante l'avvio, sivwebTST_war

[12/12/19 12.18.44:978 CET] 000001cf ApplicationMg A  WSVR0217I: Arresto dell'applicazione: sivwebTST_war

[12/12/19 12.18.45:095 CET] 000001cf ApplicationMg A  WSVR0220I: Applicazione arrestata: sivwebTST_war

[12/12/19 12.18.45:109 CET] 000001cf CompositionUn E  WSVR0194E: Impossibile avviare l'unità di composizione WebSphere:cuname=sivwebTST_war in BLA WebSphere:blaname=sivwebTST_war.

**Comment by Marco-gv** [comment] 2019-12-27 15:29
news?

**Comment by TatuLund** [comment] 2019-12-31 10:05
This seems to be the same exception as is mentioned here: https://vaadin.com/forum/thread/17163074/can-t-start-application-on-websphere-9

**Comment by malborali** [comment] 2019-12-31 10:25
Yes!

**Comment by pleku** [comment] 2020-01-02 09:10
>news?

This is currently on position #2 in the bug queue and I would expect it to be started by next week. There has been a lot of holidays in the past two weeks so queue wait has increased for a moment.

**Comment by caalador** [comment] 2020-01-03 08:59
What tech stack does the failing project use?
Could we geta simple project that fails on WebSphere 9.0.0.9 as I ran the base-starter and it worked as expected without any Null Pointer Exceptions.

**Comment by malborali** [comment] 2020-01-07 11:15
Hi,
we tried to start the application in debug mode on WAS and we found an attempt to get an attribute by a Vaadin session not yet instantiated: so we added a test in our code and the application ran! 
This error was not evidentiated by using tomcat, so we doesn't get it before.

**Comment by caalador** [comment] 2020-01-09 09:39
Closing this issue. If there is still some problem please open a new ticket with more information and steps to reproduce.

**Closed by caalador** 2020-01-09 09:39 UTC
Labels: bug
