### ISSUE TITLE
client-side function is executed twice when using callFunction from beforeClientResponse

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/flow#2988] opened 2017-11-20 15:14 UTC
This happens when using `callFunction` in `beforeClientResponse` from a `Component` injected with `@Id`.

This is related to #2873 and #2817, verified with flow 1.0.0.alpha10

To reproduce this issue you need a simple Component with some client-side API:
```
@Tag("example-component")
@HtmlImport("ExampleComponent.html")
public class ExampleComponent extends Component {
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        attachEvent.getUI().beforeClientResponse(this, () -> greet());
    }
    public void greet() {
        getElement().callFunction("greet");
    }
}
```
```
<dom-module id="example-component">
    <template>
    </template>
    <script>
        class ExampleComponent extends Polymer.Element {
            static get is() {
                return 'example-component'
            }
            greet(){
              window.alert('👋');
            }
        }
        customElements.define(ExampleComponent.is, ExampleComponent);
    </script>
</dom-module>
```

And a simple `PolymerTemplate` view including that component and injecting it by `@Id`
```
@Tag("example-template")
@HtmlImport("template/ExampleTemplate.html")
@Route("template")
public class TemplateView extends PolymerTemplate<TemplateModel> {
    @Id("component-id")
    private ExampleComponent component;
}
```

```
<dom-module id="example-template">
    <template>
      <example-component id="component-id"></example-component>
    </template>
    <script>
        class ExampleTemplate extends Polymer.Element {
            static get is() {
                return 'example-template'
            }
        }
        customElements.define(ExampleTemplate.is, ExampleTemplate);
    </script>
</dom-module>
```

Expected result when navigating to the `template` route is to only see the result of `alert('👋')` once, but instead the greet is done twice.

**Comment by denis-anisimov** [comment] 2017-11-27 09:54
This has easy reason:
- technically the code is not entirely correct. You want to call JS only once then you should use either `getStateNode().runWhenAttached()` or introduce a flag in your class which is set once `onAttach`  is called and checked each other time. It happens because the component may be attached-detached multiple times (added, removed, added one more time,...)
- Exactly this happens in this situation but that's an implementation issue. We are using two maps for the node: one preliminary until we get a confirmation and then a permanent map once the attachment is confirmed. So the node is moved from one map to another and that causes two attach events (and yes, it's an issue in our implementation).

We are going to completely reimplement the features: "inject by id"  and "template in template".
That should fix this issue and another similar.
This ticket is investigation ticket and I will close it.
Instead I will create another two tickets for reimplementing the features.

**Closed by denis-anisimov** 2017-11-27 09:54 UTC
Labels: 0-team, app starter, bug, investigation

**Comment by alvarezguille** [comment] 2017-11-27 10:05
@denis-anisimov, can you elaborate a bit on how to solve this while it's not reimplemented?
Where in the Component should the `getStateNode().runWhenAttached()` be added?
Also, can you link the related issues?

**Comment by Legioth** [comment] 2017-11-27 10:13
@alvarezguille `runWhenAttached` can be used from e.g. the constructor. `getStateNode()` is defined on the component's `getElement()` instance.

On the other hand, I don't think using `runWhenAttached` will be enough. It still also necessary to actually rerun the JS if the element has been fully destroyed and recreated on the client even though the server-side instance is the same.

**Comment by denis-anisimov** [comment] 2017-11-27 11:10
@alvarezguille 
I'm working on creating the issues right now.
See Leif's comment about `runWhenAttached()`.

The issue #3057 is created for `@Id`.
I will create one more for template-in-template.
Will add the reference here as well.

**Comment by denis-anisimov** [comment] 2017-11-27 11:14
#3058 is about template-in-template.

**Comment by alvarezguille** [comment] 2017-11-27 11:38
I'll subscribe to those, doing `getElement().getNode().runWhenAttached(ui -> greet());` fixes the issue with the duplicate, but fails in the template in template case (#2987). 
Looking forward to the reimplementation, thanks!

**Comment by denis-anisimov** [comment] 2017-11-27 11:44
Yes, #2987 is completely broken.
And it's not about your JS call.
You can comment out this and you will see an exception something about "Cannot call 'root' on undefined" (at least in console). 
It happens inside our internal code which also calls JS. So it's fundamentally broken.
