### ISSUE TITLE
Create full component on the server-side first

### ISSUE THREAD

**Issue by amahdy** [vaadin/flow#3651] opened 2018-03-06 15:51 UTC
I have a use case where the component must be initialized like this:
`<my-component prop='the value'></my-component>`

I wrote this code:
```java
MyComponent lt = new MyComponent();
lt.getElement().setAttribute("prop", "the value");
add(lt);
```

But it does not behave as expected. Flow first injects `<my-component></my-component>` in the dom tree, which invokes the `ready()` function inside the front-end component, then in a second server round it injects the `prop` attribute.

I have few issues with this concept:

1. The logic of execution is different from what I wrote in Java, `add(..)` is the last line of the code so I expect it to happen last.
2. It prevents me from injecting a custom element with attributes, like preventing me from having a constructor with parameters and all constructors must be empty. Sometimes I can modify my own client-side components but this is not a solution for any generic component that I may want to use.
3. Comparing with normal JS code, I would be able to create element and setAttributes, before injecting it in the dom. I need to have similar capability in Flow.

**Comment by mstahv** [comment] 2018-03-07 06:25
Broken abstraction. This combined to the non-deterministic client side execution causes some true WTF moments for end users (like me :-) ) when building components or just using web components. If these are design issues that can't be fixed (as I have understood), and things don't work intuitively, we should do everything we can to educate users how the beast actually works. We needs some detailed documentation and flow charts and examples.

**Comment by Legioth** [comment] 2018-03-07 07:03
Duplicate of https://github.com/vaadin/flow/issues/481

**Closed** 2018-03-07 07:03 UTC

**Comment by Legioth** [comment] 2018-03-07 07:09
The property is still set without an additional round trip to the server, but it does indeed still happen after `ready()`.

Fixing this in Flow is not in any way impossible, but the invalid logic is quite deeply integrated into the framework which means that we have a quite extensive refactoring project ahead of us. There are plans for what a more suitable architecture could look like, and it also seems like the actual work on it might quite soon be starting.
