### ISSUE TITLE
Focused Button with ClickShortcut triggers twice (even with disableOnClick=true)

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#8037] opened 2020-04-11 06:32 UTC
## Description of the bug

Button with ClickShortcut triggers click twice when the Button has focus while pressing the shortcut. 

## Minimal reproducible example

* (1) Open the view 
* (2) Use TAB to focus the button 
* (3) Press ENTER

## Expected behaviour

* (4) Log Message is shown once, focus-ring on button stays visible

## Actual behaviour

* (4) Log Message is shown twice, focus-ring is gone
* ?

## Versions
* Vaadin / Flow version: 14.1.25
* OS version: ubuntu lts
* Browser version: 
  * Firefox 76 | Chromium -> it happens always

## Source Code to reproduce
```java
@Route(value = "bug-shortcut")
public class BugShortcutView extends VerticalLayout {

  public BugShortcutView() {
    Button save = new Button("Use Enter to trigger me twice");
    save.setDisableOnClick(true); // this should disable the button on FIRST interaction?
    save.addClickShortcut(Key.ENTER);
    save.addClickListener(e -> {
      System.out.println("I was pressed!");
      e.getSource().setEnabled(true); // enable after application processed the call
    });
    add(save);
  }
}
```

**Comment by denis-anisimov** [comment] 2021-03-03 12:19
This is not a bug.
Not sure what's the code that is reported as unexpected though: `disableOnClick` or just the adding of the shortcut.
In both cases the behavior is quite expected and pretty much explainable.

If shortcut ENTER is removed from the code then click listener is still invoked in the described scenario.
This shows that ENTER is the default browser handler for the button when it's focused.
As a result the shortcut registration simply collides with the default browser behavior.

So it's absolutely expected that the click listener is invoked twice: one time it's a browser handler, another time it's a shortcut.
`disableOnClick`  doesn't help here: because it disables the component only in the next round of UI dispatch loop.
When ENTER is pressed the event is already happened and now it's just a question to let all the registered listeners know that event has fired. 
Only next click will be disabled: this one will be handled by any registered event listener.

This is a standard JS behavior: the same can be seen if you register a KeyDown event listener for ENTER on the pure client side : the listener also will be invoked twice. Since there is no any magic on the server side: everything just goes as is to the client side the behavior is just exactly the same: it's how DOM works generally.

So it's the developer responsibility to prevent collisions.
In this case the default browser behavior should be disallowed.
So the code needs to be fixed this way:
```
save.addClickShortcut(Key.ENTER).setBrowserDefaultAllowed(false);
```

**Closed by denis-anisimov** 2021-03-03 12:19 UTC
Labels: BFP, Impact: Low, Severity: Major, bug

**Comment by knoobie** [comment] 2021-03-03 13:20
@denis-anisimov Thanks Denis! Make sense but should probably documented or cookbooked.

**Comment by cdir** [comment] 2022-02-23 20:15
Thank you for the detailed explanation. Of course it is not a bug from this point of view. The behavior is logical and understandable. But apart from that, it's still not the expected behavior when I put an ENTER key shortcut on a button. And I think this is the most common usecase for a key shortcut.

The multiple duplicate issues seem to confirm that different users have a problem with this behavior.

The workaround setBrowserDefaultAllowed(fals) causes no change event to be fired if the focus is still in a text field. So it is not an alternative and makes the problem worse rather than better.

I think the idea of Vaadin is to build a meaningful abstraction over browser, JS and behavior in the DOM, especially when using Vaadin's Java API. From that point of view, it's simply a bug because it's not meaningful behavior.

**Comment by willemv** [comment] 2022-07-20 11:09
As reported in #14187 , the advice of calling `setBrowserDefaultAllowed(false)` no longer works
