### ISSUE TITLE
Configurable error description on session loss

### ISSUE THREAD

**Issue by MichaelPluessErni** [vaadin/flow#18491] opened 2024-01-19 15:30 UTC
### Describe your motivation

When we lose the session the FlowClient displays a _"Invalid JSON from server: 1|X"_ error.

This error message is confusing for our users.

### Describe the solution you'd like

We would like to be able to be able to hide or customize this error message, such that we are able to tell our users to refresh the page.

### Describe alternatives you've considered

Naturally we'd like to prevent the session error that causes the error message in the first place. However it's not always possible to keep the sessions open. 

### Additional context

Screenshot of occurence:

![17-01-2024_12-26-29](https://github.com/vaadin/flow/assets/144342931/5224d403-d276-459f-8387-2d5fe6b8ed47)

**Comment by mshabarov** [comment] 2024-01-23 14:46
This message is displayed when an invalid content (not JSON) is sent from server to client via push connection.
What is the Vaadin version used in your project ? 
Also, if you could give us the minimal reproducible example, that would be fine.
Removed the enhancement label, as it looks like a bug in intercommunication.

**Comment by melsanharawi** [comment] 2024-01-26 16:09
Hi,

Got the bug in vaadin 24.2.4.

**Comment by MichaelPluessErni** [comment] 2024-01-29 10:54
Hi

My versions were:
Vaadin: 24.3.3
Spring Boot: 3.2.2

It is possible that the bug is related to the network architecture. But since it is not certain that we can ameliorate this issue, we would like to change what's displayed to the user.

**Comment by Legioth** [comment] 2024-02-13 15:31
This might very well work automatically if the response code would be 401 to indicate that this is a problem with permissions instead of 405 which indicates that the request is sent in the wrong way.

There's also the magic `Vaadin-Refresh` token that can be included in those types of error responses to make Vaadin reload the page if it's encountered in an unexpected response. I'm not sure if that logic is used also for push connection responses or if it's only for regular UIDL requests?

**Comment by mcollovati** [comment] 2024-03-04 11:26
Probably related to https://github.com/Atmosphere/atmosphere/issues/2503

**Comment by Artur-** [comment] 2024-03-12 13:43
This is fixed in #18946

**Closed by Artur-** 2024-03-12 13:43 UTC
Labels: investigation
