### ISSUE TITLE
Grid component column within Board exception

### ISSUE THREAD

**Issue by martindowney** [vaadin/flow#5610] opened 2019-05-03 14:32 UTC
If a `Board` contains a non-empty `Grid` and the `Grid` has a column that was created via `addComponentColumn()` and that column contains a component such as a `Button` or an `Icon` the following failure occurs, consistently, when the user selects another layout then returns to the `Board` layout:

```
java.lang.IllegalArgumentException: Not in the list
    at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:123)
    at com.vaadin.flow.dom.Node.removeChild(Node.java:332)
    at com.vaadin.flow.dom.Element.removeFromParent(Element.java:576)
    at com.vaadin.flow.dom.Node.insertChild(Node.java:249)
    at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
    at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:128)
    at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:80)
    at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47)
    at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:656)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
    at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
    at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:613)
    at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:556)
    at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:473)
    at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$1(DataCommunicator.java:421)
    at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:350)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:347)
    at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:334)
    at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:179)
    at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:119)
    at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
    at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
    at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
    at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
```

- VAADIN Flow v13.0.5
- FireFox v54.0
- Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by denis-anisimov** [comment] 2019-10-14 08:29
I see a number of components mentioned:
`Board` , `Grid` , `Button`  , `Icon`.
Is it a general issue or an issue with a specific component ?
What is the `Board` ?
Could you please provide a code which we may use to reproduce the issue ?

**Comment by pleku** [comment] 2019-11-11 08:56
Hi. Since there has not been a response in 4 weeks after we requested more details, we are closing this issue.

Please reopen this issue with a short self-contained example included or make a new issue to the correct component repository. Thanks

**Closed by pleku** 2019-11-11 08:56 UTC
Labels: waiting for author
