### ISSUE TITLE
Bug/Improvement: Disabling component/element/field is too strong

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow#8514] opened 2020-06-08 08:05 UTC
Dear Vaadin,

It seems there is so different handling of "enable/disable"  flag as in legacy Vaadin version.
But it seems that such current behavior is not so correct.

a) why disabling of field's remove invalid-looks (such "red background" one)
b) why disabling of field's hides set error message
c) why disabling of component block showing of "title" so hard to signal to user what is possibly 
  wrong 

Even overriding of onEnabledStateChanged(boolean enabled) does not help as field has possibly some "extra parts" that it is not controlled (or maybe I do know about such way) and share disable state from field's parent.

So suggested solution:
At least any possibility to realized a-c) or in worst case to realize c)

**Comment by pleku** [comment] 2020-11-24 11:53
This issue is too unclear for several reasons. What "legacy Vaadin version" ? What inconsistencies - please show the code so we can determine if there are bugs or just intended behavior that should be perhaps better documented. 

Closing the issue as it is too vague. Please create a new issue with code to reproduce the issue(s) and better descriptions on what happens.

**Closed by pleku** 2020-11-24 11:53 UTC
Labels: element API, investigation

**Comment by netbeansuser2019** [comment] 2020-12-03 10:12
@pleku 
@mshabarov 

If you read a description you have it all and just usage of any of your examples from vaadin side can lead to this.
There is nothing custom, but it seems that it is Vaadin team standard way to closing issues without action.
Frankly speaking you should valued that anybody take a time a report a issues to be improved your product.

a) why disabling of field's remove invalid-looks (such "red background" one)
- just use any form field and make it invalid (so set any value that it is invalid for any vaadin validator) 
- set that disabled
b) why disabling of field's hides set error message
- follow a)
- ensure that it is set any error any message 
c) why disabling of component block showing of "title" so hard to signal to user what is possibly
wrong
- set attribute title

**Comment by pleku** [comment] 2020-12-03 10:50
>Frankly speaking you should valued that anybody take a time a report a issues to be improved your product.

Yes we do value good input. But we also ask you to value our time and report issues in a manner that does not waste anybody's time - by providing examples with code and screenshots when necessary, specially when it is about something that is very hard to be described in written format in understandable English. For example:

>why disabling of field's remove invalid-looks (such "red background" one)

is close to gibberish.
