### ISSUE TITLE
ComponentRenderer in Grid should take focus from the cell and put in on the component inside the cell

### ISSUE THREAD

**Issue by bennewi** [vaadin/flow#4191] opened 2018-05-29 06:55 UTC
Currently if a component has focus you can tab through all the components in the Grid with the keyboard. But if you reach the end the focus leaves the Grid, and then when it returns to the Grid only the Grid cells are navigable with the keyboard. This means it's possible to start tabbing but you are not able to return to the original position using the keyboard, which should be the expectation.

**Comment by pleku** [comment] 2018-05-29 07:33
Actually space does not work (there was another interaction happening on the demo) ...

Closing this as a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/122

**Comment by pleku** [comment] 2019-02-15 19:49
Reported by user to still reproduce - the tabbing doesn't work when the `flowcomponent-renderer` is used: the focus doesn't go into the first component inside the cell.

**Comment by Klaudeta** [comment] 2019-02-26 09:56
The standard focus navigation workflow for the grid is so that when grid first receives focus through tabbing, the first header's cell is focused, tabbing again moves the focus to the first row first cell and after that user can use keyboard to move focus between cells.

A solution to focus a component inside a cell is when the cell is focused, user to press `Enter` to focus the component inside. 
Actually this is the normal behavior when components are directly added inside the `vaadin-grid-cell-content` (client side use of vaadin-grid). 
The reason why it is not working the same with Flow is because of `flow-component-renderer` wrapper not delegating focus inside the shadowDOM. Fixing `flow-component-renderer` fixes the issue.

**Comment by ZheSun88** [comment] 2019-02-28 14:51
I am going to reopen this ticket, as there is still a PR regarding this which hasn't gotten merged.

**Closed** 2019-02-28 14:51 UTC
Labels: BFP, bug, components
