### ISSUE TITLE
Cannot update a combobox in a dialog on tablet/phone

### ISSUE THREAD

**Issue by jcgueriaud** [vaadin/flow#3774] opened 2018-03-27 15:19 UTC
Hello,

When I click on a combobox inside a dialog with my android tablet or my android phone (I use Google Chrome), I can't select a element.

The same combobox outside the dialog is working. I don't have any problem on computer.

See my example below.
Steps to reproduce:
- Click on OPEN button.
- Click inside the combobox (not on the arrow)
---> The keyboard is opened
- select an element
--> This element is not selected and the keyboard is closed

    /*** The main view contains a button and a template element.
     */
    @BodySize(height = "100vh", width = "100vw")
    @HtmlImport("styles/shared-styles.html")
    @Route("")
    @Theme(Lumo.class)
    public class MainView extends VerticalLayout {
    
    
        private ComboBox<String> comboBox;
    
        private Dialog editPopup;
        private Button openButton;
    
        public MainView() {
    
            comboBox = new ComboBox<>("Test");
            String[] data = {"Label 1","Label 2","Label 3","Label 4"};
            comboBox.setItems(data);
            editPopup = new Dialog();
            editPopup.add(comboBox);
            openButton = new Button("Open");
            openButton.addClickListener(event -> editPopup.open());
    
            add(openButton);
    
            setClassName("main-layout");
        }
    
    }

**Comment by pleku** [comment] 2018-03-28 05:44
Hello and thanks for the report. From looking at the code, I think the issue is with the web component and how it works inside a `vaadin-dialog`, thus I'm moving it to the web component repository.

**Comment by pleku** [comment] 2018-03-28 05:44
Issue moved to [vaadin/vaadin-combo-box #634](https://github.com/vaadin/vaadin-combo-box/issues/634) via [**ZenHub**](https://www.zenhub.com/)

**Closed by pleku** 2018-03-28 05:44 UTC
