### ISSUE TITLE
HasUrlParameter.setParameter is executed twice with vaadin.eagerServerLoad=true

### ISSUE THREAD

**Issue by alexanoid** [vaadin/flow#16046] opened 2023-02-26 13:39 UTC
### Description of the bug

I have a View which  `implements HasUrlParameter<String>`. 

Also I configured:

`vaadin.eagerServerLoad=true` (for IndexHtmlRequestListener)

with such setup, `HasUrlParameter.setParameter()` method is executed twice during the first page load

### Expected behavior

`HasUrlParameter.setParameter()` method is executed only one time during the first page load with `vaadin.eagerServerLoad=true`

### Versions

- Vaadin / Flow version: 23.3.6

**Comment by alexanoid** [comment] 2023-02-28 20:54
the same relates to `BeforeEnterObserver.beforeEnter()` https://stackoverflow.com/questions/75166305/vaadin23-vaadin-eagerserverload-true-and-beforeenterobserver

**Comment by alexanoid** [comment] 2023-03-01 17:48
My biggest issue with this is that I have some pretty expensive business logic triggered by `HasUrlParameter.setParameter()` and thus - I access the database twice, which impacts the performance of the application :(

**Comment by knoobie** [comment] 2023-03-01 21:03
If you know it's always two times called (has to be checked), just a add counter or AtomicBoolean as class field that checks if this is the second call as temporary workaround?

**Comment by alexanoid** [comment] 2023-03-01 21:24
Thank you for your reply. The problem with the proposed counter is that the `setParameter()` method is called twice only on the very first page load... then when the UI loaded and I use the router navigation, eg leave this page and come back - this is correctly called only once.

**Comment by alexanoid** [comment] 2023-03-02 00:24
@knoobie thank you very much! Your workaround with `AtomicBoolean `did the trick, thanks!

**Comment by alexanoid** [comment] 2023-03-03 00:01
@knoobie There is one side effect with this approach  - the Router links don't work after the page is loaded. For example, I have a Product Catalog View with multiple pages. When I'm on the page #2 or more, it is very convenient  to click on the Product catalog router link to quickly return to the page #1. The `view.seParameter()` method is executed correctly, but because of the `AtomicBoolean  == true`, the logic inside is skipped, and the page is not updated in this case.

I'll really appreciate if you could fix this issue on your end.

**Comment by alexanoid** [comment] 2023-03-15 22:26
Just FYI - I don't know is it related somehow, but during initial start up of the application I may very often see resync issue:

`2023-03-16T00:23:51.078+02:00  WARN 21484 --- [  XNIO-1 task-6] c.v.f.s.communication.ServerRpcHandler   : Resynchronizing UI by client's request. A network message was lost before reaching the client and the client is reloading the full UI state. This typically happens because of a bad network connection with packet loss or because of some part of the network infrastructure (load balancer, proxy) terminating a push (websocket or long-polling) connection. If you are using push with a proxy, make sure the push timeout is set to be smaller than the proxy connection timeout`

**Comment by alexanoid** [comment] 2023-03-31 11:43
any chance to fix this problem soon?

**Comment by knoobie** [comment] 2023-03-31 12:00
I don't think it has any priority at the moment looking at the impact because it occurs only with eagerServerLoad=true which in turn is a rarely used feature.

**Comment by Artur-** [comment] 2023-03-31 13:16
I tried a fix for this but there seems to be another underlying problem of the eagerly provided UIDL not being used at all..

**Comment by alexanoid** [comment] 2023-03-31 13:21
> I tried a fix for this but there seems to be another underlying problem of the eagerly provided UIDL not being used at all..

thank you! I'll really appreciate if you could fix it. It causes a lot of issues to me right now (

**Comment by knoobie** [comment] 2023-03-31 13:28
@Artur- https://github.com/vaadin/flow/issues/13421 this is the cause of the usage of eager=true if you wanna try to fix this instead.. it would probably help more people as well 😅

**Comment by Artur-** [comment] 2023-03-31 14:02
Sure, if you tell how. If the routing happens only on the second request, it is a bit too late to write the response code for the first..

**Comment by alexanoid** [comment] 2023-04-01 10:12
@Artur- I see the number of associated commits, what a great news, thank you! Does this mean that potentially this issue will be fixed with help of them? If so, will it be included into Vaadin Flow 24.0.3?

**Comment by Artur-** [comment] 2023-04-02 14:44
#16498 fixes this indeed. It will not make it to 24.0.3 but hopefully the following release

**Comment by alexanoid** [comment] 2023-04-02 14:56
Awesome news! Thank you very much!

**Closed** 2023-04-04 12:55 UTC
Labels: bug, Impact: Low, Severity: Major

**Comment by alexanoid** [comment] 2023-04-11 19:15
Hi @Artur- I just updated to Vaadin 24.0.4 Looks like the fix still hasn't been added there?

**Comment by knoobie** [comment] 2023-04-11 19:37
It's not backported

**Comment by alexanoid** [comment] 2023-04-11 19:48
Sorry to bother you with this, but do you have any information on when this will be released? I'm just waiting for this fix more than my own birthday :)
