### ISSUE TITLE
Vaadin application failed to start as Maven WAR build with dedicated Tomcat Server in the dev environment

### ISSUE THREAD

**Issue by karstenlehmann** [vaadin/flow#13619] opened 2022-04-26 08:53 UTC
### Description

Deploy our Vaadin application in development mod on tomcat server failed with the current exception since Vaadin 23.0.3:

```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/tms-we]]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)

...

Caused by: java.lang.IllegalStateException: Failed to determine project directory for dev mode. Directory 'C:\Users\klehmann\Desktop' does not look like a Maven or Gradle project. Ensure that you have run the prepare-frontend Maven goal, which generates 'flow-build-info.json', prior to deploying your application
	at com.vaadin.base.devserver.startup.DevModeInitializer.getBaseDirectoryFallback(DevModeInitializer.java:383)
	at com.vaadin.base.devserver.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:211)
	at com.vaadin.base.devserver.DevModeHandlerManagerImpl.initDevModeHandler(DevModeHandlerManagerImpl.java:80)
```

Debugging the start process shows that with version 23.0.2 the project.basedir in DevModeInitialializer is set and with newer version it is null:

DevModeInitialializer line 208
`
String baseDir = config.getStringProperty(FrontendUtils.PROJECT_BASEDIR,
                null);
`

### Expected outcome

Vaadin application start in development mod without any exceptions

### Minimal reproducible example

No specific vaadin code required

### Steps to reproduce

1. Setup simple vaadin project, maven build, packagin war
2. Run project on dedicated apache tomcat server in development mod

### Environment

Vaadin version(s): Vaadin 23.0.3|4|5|6 (23.0.2 still working)
OS: Windows
IDE: Eclipse
Webserver: Tomcat 9.0.43 (managed in eclipse)
Springboot: no
Buildsystem: maven
Packaging: war

**Comment by web-padawan** [comment] 2022-04-26 09:01
This issue isn't component-specific, so I transferred it to the Flow repo. Possibly related to #13302

**Comment by karstenlehmann** [comment] 2022-04-28 06:42
A Workaround is to set the working directory of the tomcat server to the dedicated web project. It seems that this directory is the fallback if the `project.basedir` is not set. The only problem is when we change the deployed web project we have to adjust the server configuration or we have to create different configurations for every web project we want to deploy.

![image](https://user-images.githubusercontent.com/42135618/165692253-4eaced20-03a9-4a4a-86f7-c793db442430.png)

**Comment by Artur-** [comment] 2022-04-28 07:10
Sounds like this is caused by #13302 as it will no longer automatically run `prepare-frontend` that would create the metadata file with among other things the project folder. Maybe we need to revert that then. Any comments @caalador ?

**Comment by caalador** [comment] 2022-04-28 07:33
Sounds like an issue caused by 13302 as running `mvn prepare:frontend` always sets the project directory.

**Closed** 2022-04-28 08:04 UTC

**Comment by RalfNaujokat** [comment] 2023-09-29 10:29
I have exactly the same error with
Vaadin 24.1.10 and 24.2.0-beta1
and
Eclipse 2023-09 running on Linux
Shouldn't that fix be active in 24.*?

**Comment by mrts** [comment] 2023-11-26 19:10
@RalfNaujokat, running `mvn package` manually once should fix it.

**Comment by Artur-** [comment] 2024-06-28 14:03
I wonder if this one works nowadays without running `prepare-frontend` so we could reapply #13302, because having Eclipse and VS Code run `prepare-frontend` automatically seems to cause other issues
