### ISSUE TITLE
ClickShortcut fired when the lifecycle owner is invisible 

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#11523] opened 2021-08-05 15:04 UTC
The documentation of `ShortcutRegistration` mentions that:
https://github.com/vaadin/flow/blob/4220766d85217be5b9d457181613f5637f722ccc/flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java#L125-L128

which is implemented as:
https://github.com/vaadin/flow/blob/4220766d85217be5b9d457181613f5637f722ccc/flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java#L541-L542

It's not clear whether "invisible component" means that the component is _not visible_ or just `!component.isVisible()`

In the following example (14.6.7), the lifecycle owner is "invisible" (it cannot be seen because the container is hidden). The click shortcut, however, is allowed to execute. If this is the expected behavior, maybe the documentation should clarify it.

```
    Button b = new Button();
    b.addClickListener(ev -> Notification.show("Button is visible: "+b.isVisible()));
    b.addClickShortcut(Key.ENTER);
    HorizontalLayout hl = new HorizontalLayout(b);
    add(hl);
    hl.setVisible(false);
```

**Comment by denis-anisimov** [comment] 2021-08-06 06:15
Duplicate of #7033

**Closed by denis-anisimov** 2021-08-06 06:15 UTC
