### ISSUE TITLE
Running V14 rc9 starter application fails if there are spaces in classpath jar locations

### ISSUE THREAD

**Issue by paivisoinio** [vaadin/flow#6204] opened 2019-08-09 06:53 UTC
Download any application from start.vaadin.com
Sometimes running it (tested with Eclipse and IntelliJ) fails with following error note. 
Does not happen every time, but I was able to reproduce this 5 times. 
Also Marta reported similar error note with starters. 

```

Example Project
Install

Webpack Error
ℹ ｢wds｣: Project is running at http://localhost:52908/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/paivi/eclipse-workspace/exampleproject (1)/target/classes/META-INF/VAADIN, src/main/webapp
         Serving the 'stats.json' file dynamically.
✖ ｢wdm｣: Hash: 2c7cdea488ad99f0799c
Version: webpack 4.30.0
Time: 14290ms
Built at: 2019-08-08 22:48:18
                                                                 Asset       Size      Chunks                    Chunk Names
                     build/vaadin-bundle-f93a8670f692cc42d0d0.cache.js   9.24 MiB      bundle  [emitted]  [big]  bundle
                 build/vaadin-bundle.es5-372b15a68f85ddcac5e4.cache.js   9.83 MiB  bundle.es5  [emitted]  [big]  bundle.es5
                                      build/webcomponentsjs/LICENSE.md   1.52 KiB              [emitted]         
                                       build/webcomponentsjs/README.md   10.9 KiB              [emitted]         
                     build/webcomponentsjs/bundles/webcomponents-ce.js   16.7 KiB              [emitted]         
                 build/webcomponentsjs/bundles/webcomponents-ce.js.map    112 KiB              [emitted]         
               build/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js    108 KiB              [emitted]         
           build/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js.map    653 KiB              [emitted]         
                  build/webcomponentsjs/bundles/webcomponents-sd-ce.js   80.9 KiB              [emitted]         
              build/webcomponentsjs/bundles/webcomponents-sd-ce.js.map    527 KiB              [emitted]         
                     build/webcomponentsjs/bundles/webcomponents-sd.js   65.1 KiB              [emitted]         
                 build/webcomponentsjs/bundles/webcomponents-sd.js.map    415 KiB              [emitted]         
                  build/webcomponentsjs/custom-elements-es5-adapter.js  924 bytes              [emitted]         
build/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index.js  656 bytes              [emitted]         
       build/webcomponentsjs/entrypoints/webcomponents-bundle-index.js   1.66 KiB              [emitted]         
           build/webcomponentsjs/entrypoints/webcomponents-ce-index.js  672 bytes              [emitted]         
        build/webcomponentsjs/entrypoints/webcomponents-sd-ce-index.js  851 bytes              [emitted]         
     build/webcomponentsjs/entrypoints/webcomponents-sd-ce-pf-index.js   1.19 KiB              [emitted]         
           build/webcomponentsjs/entrypoints/webcomponents-sd-index.js  761 bytes              [emitted]         
                                    build/webcomponentsjs/package.json      3 KiB              [emitted]         
                         build/webcomponentsjs/webcomponents-bundle.js    109 KiB              [emitted]         
                     build/webcomponentsjs/webcomponents-bundle.js.map    655 KiB              [emitted]         
                         build/webcomponentsjs/webcomponents-loader.js   6.13 KiB              [emitted]         
Entrypoint bundle [big] = build/vaadin-bundle-f93a8670f692cc42d0d0.cache.js
Entrypoint bundle.es5 [big] = build/vaadin-bundle.es5-372b15a68f85ddcac5e4.cache.js
[../node_modules/@vaadin/vaadin-app-layout/theme/lumo/vaadin-app-layout.js] 80 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-app-layout/theme/lumo/vaadin-app-layout.js] 80 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-button/theme/lumo/vaadin-button.js] 72 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-button/theme/lumo/vaadin-button.js] 72 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-charts/vaadin-chart.js] 73 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-charts/vaadin-chart.js] 73 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox.js] 76 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox.js] 76 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-context-menu/theme/lumo/vaadin-context-menu.js] 204 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-context-menu/theme/lumo/vaadin-context-menu.js] 204 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-grid/theme/lumo/vaadin-grid-column-group.js] 47 bytes {bundle.es5} [built]
[../node_modules/@vaadin/vaadin-grid/theme/lumo/vaadin-grid-column-group.js] 47 bytes {bundle} [built]
[../node_modules/@vaadin/vaadin-grid/theme/lumo/vaadin-grid-column.js] 41 bytes {bundle.es5} [built]
[../target/frontend/generated-flow-imports.js] 1.94 KiB {bundle.es5} [built]
[../target/frontend/generated-flow-imports.js] 1.95 KiB {bundle} [built]
    + 599 hidden modules

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector-es6.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 29:0-59

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector-es6.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 29:0-59

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 34:0-55

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 34:0-55

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 18:0-58

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 18:0-58

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector-es6.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 24:0-52

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector-es6.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 24:0-52

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 33:0-48

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 33:0-48

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 16:0-68

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js' in '/Users/paivi/eclipse-workspace/exampleproject (1)/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 16:0-68
ℹ ｢wdm｣: Failed to compile.
Users
745
Current users in the app
Events
54.6k
Events from the views
Conversion
18%
User conversion rate
Use regions/landmarks to skip ahead to chart and navigate between data series
Monthly visitors per city
Long description.
No description available.
Structure.
Bar chart with 4 data series.
The chart has 1 X axis displaying categories.
The chart has 1 Y axis displaying Values.
Chart graphic.
Values
Monthly visitors per city
Tokyo
New York
London
Berlin
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
0
50
100
150
200
250
Service health
Use regions/landmarks to skip ahead to chart and navigate between data series
Response times
Long description.
No description available.
Structure.
Line chart with 2 lines.
The chart has 1 X axis displaying categories.
The chart has 1 Y axis displaying Values.
Chart graphic.
Values
Response times
Tokyo
London
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
0
5
10
15
20
25
30
(TypeError) : Cannot read property 'initLazy' of undefined
(TypeError) : Cannot read property 'reset' of undefined
(TypeError) : Cannot read property 'setSelectionMode' of undefined
(TypeError) : Cannot read property 'setSelectionMode' of undefined
(TypeError) : Cannot read property 'updateSize' of undefined
(TypeError) : Cannot read property 'set' of undefined
(TypeError) : Cannot read property 'confirm' of undefined
```

**Comment by paivisoinio** [comment] 2019-08-09 07:33
https://drive.google.com/file/d/1jnQ5l9Xvpd8I1dhRozWHAYacuVpCn3E4/view

**Comment by pleku** [comment] 2019-08-09 08:46
I've been able to reproduce this only once, in a project where I had local node installed and then deleted it and tried to start the server with global node instead.

Before the error message for missing modules, in server start up console there is the following:
```
[PathWatcher@362fbd98] INFO dev-updater - Visited 10 jar files. Took 13 ms.
[PathWatcher@362fbd98] WARN dev-updater - Use the './' prefix for files in JAR files: 'flow-component-renderer.js', please update your component.
[PathWatcher@362fbd98] INFO dev-updater - 
  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/ironListConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/ironListConnector-es6.js
      - @vaadin/flow-frontend/ironListStyles.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
      - @vaadin/flow-frontend/selectConnector.js
  If the build fails, check that npm packages are installed.
```

After cleaning the project (`mvn clean`)  the error doesn't reproduce for me anymore.

**Comment by martaolszewskatusiek** [comment] 2019-08-09 09:39
I re-run my test. 

Steps to reproduce:
1. Take the Simple app with plain Java from vaadin.com/start
2. Go according to the steps in README.md
3. Got the error:
``` Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/ironListConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/ironListConnector-es6.js
      - @vaadin/flow-frontend/ironListStyles.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
      - @vaadin/flow-frontend/selectConnector.js
  If the build fails, check that npm packages are installed.'''
4. Removed node_modules folder
5. Run: jetty:run
6. Got the error
```Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/ironListConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/ironListConnector-es6.js
      - @vaadin/flow-frontend/ironListStyles.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
      - @vaadin/flow-frontend/selectConnector.js
  If the build fails, check that npm packages are installed.```
7. Run as maven clean
8. Run as maven install
9. Run as jetty:run (on UI)
10. Got an error
```  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/ironListConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/ironListConnector-es6.js
      - @vaadin/flow-frontend/ironListStyles.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
      - @vaadin/flow-frontend/selectConnector.js
  If the build fails, check that npm packages are installed.```
System properties:
* Win10 OS
* Eclipse 4.11

**Comment by Legioth** [comment] 2019-08-12 07:08
Seems like this is always caused by having a space or some other special character in the location of the jar files used by the application, which depending on the running mode is either the project directory or taken from `~/.m2/`.

Should be fixed by https://github.com/vaadin/flow/pull/6209

**Closed** 2019-08-14 06:21 UTC
