### ISSUE TITLE
Vaadin 12 pass object to JavaScript's function: Can't encode class

### ISSUE THREAD

**Issue by alexei-28** [vaadin/flow#5404] opened 2019-04-03 08:35 UTC
Vaadin 12, Kotlin project

In my **myPage.html** I has javascript:

```
 myObject.redirectToCheckout({
                    sessionId: "1111_2222",
                }).
```
So I need to call javaScript function `redirectToCheckout `from Vaadin 12 and pass correct param as object. So here my Vaadin snippet:

```
import com.vaadin.flow.component.dependency.HtmlImport
import com.vaadin.flow.component.dependency.JavaScript
import com.vaadin.flow.component.html.Div
import com.vaadin.flow.router.Route
import com.vaadin.flow.server.VaadinRequest
import java.io.Serializable

@Route(value = "redir")
@HtmlImport("styles/myPage.html")
class RedirectForm : Div() {
    init {
        val request = VaadinRequest.getCurrent()
        val paramGoto = request.getParameter("goto")
        val redirect = Redirect("$paramGoto")
        UI.getCurrent().getPage().executeJavaScript("myObject.redirectToCheckout($0)", redirect) // **error here**
    }

    inner class Redirect : Serializable {
        var sessionId: String

        constructor(sessionId: String) {
            this.sessionId = sessionId
        }
    }
}
```
but I get error:

```
Caused by: java.lang.IllegalArgumentException: Can't encode class com.myproject.view.RedirectForm$Redirect to json
    at com.vaadin.flow.internal.JsonCodec.encodeWithoutTypeInfo(JsonCodec.java:165)
    at com.vaadin.flow.internal.JsonCodec.encodeWithTypeInfo(JsonCodec.java:80)
    at com.vaadin.flow.component.page.Page.executeJavaScript(Page.java:338)
    at com.myproject.view.RedirectForm.<init>(RedirectView.kt:28)
    ... 50 common frames omitted
```

**Comment by Legioth** [comment] 2019-04-09 05:51
This works as intended. `executeJavaScript` is a low-level feature that is explicitly defined to only support a limited set of primitive data types.

There are two basic approaches for dealing with this. 
1. Modify the JS expression to construct the object on the client, e.g. `executeJavaScript("myObject.redirectToCheckout({sessionId: $0})", paramGoto)`.
2. Manually create a `elemental.json.JsonObject` instance that can be passed to the method:
```
JsonObject redirect = Json.createObject();
redirect.put("sessionId", paramGoto);
page.executeJavaScript("myObject.redirectToCheckout($0)", redirect);
```

It's a good question whether the method should be enhanced to also support more complex types.

**Comment by lmdic** [comment] 2019-04-09 07:03
> This works as intended. `executeJavaScript` is a low-level feature that is explicitly defined to only support a limited set of primitive data types.
> 
> There are two basic approaches for dealing with this.
> 
> 1. Modify the JS expression to construct the object on the client, e.g. `executeJavaScript("myObject.redirectToCheckout({sessionId: $0})", paramGoto)`.
> 2. Manually create a `elemental.json.JsonObject` instance that can be passed to the method:
> 
> ```
> JsonObject redirect = Json.createObject();
> redirect.put("sessionId", paramGoto);
> page.executeJavaScript("myObject.redirectToCheckout($0)", redirect);
> ```
> It's a good question whether the method should be enhanced to also support more complex types.

here my solution

```
import com.vaadin.flow.component.UI
import com.vaadin.flow.component.dependency.HtmlImport
import com.vaadin.flow.component.dependency.JavaScript
import com.vaadin.flow.component.html.Div
import com.vaadin.flow.router.Route
import com.vaadin.flow.server.VaadinRequest
import elemental.json.Json

@Route(value = "myPage")
@HtmlImport("html/myProfile.html")
class MyForm : Div() {

    init {
        val request = VaadinRequest.getCurrent()
        val myParam= request.getParameter("my_param")
        val json = Json.createObject()
        json.put("param", "$myParam")
        UI.getCurrent().getPage().executeJavaScript("stripe.redirectToCheckout($0)", json)
    }

}
```

**Comment by pleku** [comment] 2019-10-14 10:50
Related to or similar to #4731

**Comment by Legioth** [comment] 2020-02-26 11:34
Duplicate of #4731

**Closed by Legioth** 2020-02-26 11:34 UTC
Labels: enhancement
