### ISSUE TITLE
Navigating to the current route but with different query params does not update the URL when using @PreserveOnRefresh

### ISSUE THREAD

**Issue by jameskerrtaskize** [vaadin/flow#19701] opened 2024-07-17 13:34 UTC
### Description of the bug

In my repro example there is a route called TreeView ("/tree"). It contains 3 buttons. If you click the first button it navigated to /tree?param=one. If you click the second, it navigates to /tree?param=two etc.

My demo app has @PreserveOnRefresh on the TreeView route. When clicking the buttons, the URL does not update.
If you remove @PreserveOnRefresh, the buttons do cause the URL to update.

The actual navigation is fine but the URL does not change correctly.

We had previously worked around this by calling ui.getPage().getHistory().replaceState(..) to set the correct URL. However, we are now unable to upgrade to 24.4 due to https://github.com/vaadin/flow/issues/19613
I don't really want to be calling replaceState so I'd like to get this bug fixed so we don't have to.

### Expected behavior

URL should change when the buttons are pressed

### Minimal reproducible example

[preserveonrefresh-nav-issue.zip](https://github.com/user-attachments/files/16266332/preserveonrefresh-nav-issue.zip)

### Versions

- Vaadin / Flow version: 24.4 (was present in 23)
- Java version: 17
- OS version: osx

**Comment by mcollovati** [comment] 2024-07-19 05:58
It looks like a regression introduced by https://github.com/vaadin/flow/pull/15331
For programmatic navigation, Push history is refreshed only if the trigger is `UI_NAVIGATE`. The mentioned PR added a new trigger `REFRESH` for preserve on refresh, to allow distinguishing navigation events.

If you replace the buttons with `RouterLink`s you get the expected behavior.

**Comment by mcollovati** [comment] 2024-07-19 06:20
The issue was triaged and currently added to the backlog priority queue for further investigation

**Comment by mcollovati** [comment] 2024-07-24 05:33
The issue was assigned to a developer and is currently being investigated

**Closed** 2024-07-24 08:20 UTC
Labels: bug, BFP, workaround, Impact: Low, Severity: Minor, preserve-on-refresh, navigation

**Comment by mcollovati** [comment] 2024-07-24 15:52
The PR fixing the issue was merged and changes will be delivered in the following versions: Flow 24.4.5 (Vaadin 24.4.8), 24.3.14 (Vaadin 24.3.17)
