### ISSUE TITLE
Button in grid stops working after URL manipulation

### ISSUE THREAD

**Issue by pbzdok** [vaadin/flow#17609] opened 2023-06-15 14:51 UTC
### Description

I have a component that is a grid with buttons in each row. These buttons open up a dialog that pushes state to the browser history and a back button which navigates back and closes the dialog.
However, after the dialog closes the buttons in the grid stop working. After a page refresh everything works again.
When there is no history manipulation the grid works just fine after closing the dialog.

### Expected outcome

I would expect that the buttons continue working after the dialog is closed, unrelated to the history manipulation / navigation.

### Minimal reproducible example

```kotlin
@Route("test")
class TestPage(grid: GridComponent) : VerticalLayout() {

	init {
		add(grid)
	}
}

/**
 * This is a minimal example of a component that we use for the URL manipulation.
 * It sets the URL to /home
 */
class RouteChangingDialog : Dialog() {

	init {
		val backButton = Button("Back") {
			UI.getCurrent().page.history.back()
			close()
		}
		add(backButton)

		addOpenedChangeListener {
			if (it.isOpened) UI.getCurrent().page.history.pushState(null, "home")
		}
	}
}

@SpringComponent
@UIScope
class GridComponent : Grid<Int>() {

	init {
		setItems(0, 1)
		addComponentColumn { Button("Test Button") { RouteChangingDialog().open() } }
	}
}
```

### Steps to reproduce

1. Paste the example into a Vaadin Application
2. Navigate to `/test`
3. Click on a button in the grid
4. Close the dialog with the button
5. Try to click another button

### Environment

- Vaadin / Flow version: 23.3.12
- Java version: 17.0.3
- OS version: MacOS 13.4 (22F66)
- Browser version (if applicable): Chrome 114.0.5735.106
- Application Server (if applicable): Jetty 9.4.51
- IDE (if applicable): IntelliJ 2023.1.2 (Ultimate Edition)

### Browsers

Chrome

**Comment by mshabarov** [comment] 2023-09-12 13:30
Also did the same for Flow CRM tutorial example, see https://github.com/vaadin/flow-crm-tutorial/tree/reproduce-17609.
Couldn't reproduce with it either.

**Comment by mshabarov** [comment] 2023-09-26 11:15
Closed as it has no reply within two weeks. Please comment in this ticket or create a new one if this issue is valid for you.

**Closed by mshabarov** 2023-09-26 11:15 UTC
Labels: waiting for author
