### ISSUE TITLE
Vaadin 19: file-loader does not work for assets referenced in css file loaded manually with @CssImport

### ISSUE THREAD

**Issue by xdenser** [vaadin/flow#10421] opened 2021-03-25 16:10 UTC
In Vaadin 18.0.1 it worked with addtional WebPack config, but now filter here
https://github.com/vaadin/flow/blob/master/flow-server/src/main/resources/webpack.generated.js
line 257
forces to use theming or npm dependency for this to work.
And I am not sure if it is safe to override this filter in webpack.config.

**Comment by pleku** [comment] 2021-03-26 12:54
Hi. Without the code example, I'm not entirely sure what is not working anymore, but based on
> forces to use theming or npm dependency for this to work.

It sounds like if you had css loaded with `@CssImport` referencing something inside `node_modules` and it worked, it was (I think) just a coincidence. I would suggest switching to the new theming API in this case.

Otherwise you try can try to use the webpack configuration file to "pop" out and replace the right plugin config with suitable configuration for you. But this is very hacky and might break later on, so I'm not going to even try to create a code example for this...

**Comment by xdenser** [comment] 2021-03-26 15:51
Refer to some css file in frontend folder with @CssImport
.something {
  background-image: url("./image.png)";
}
and try to refer to some background image with url in the same folder.
This does not work. In our app we refer to some font, but with image this will be the same.

**Comment by pleku** [comment] 2021-03-26 16:49
> I.e, why it is supported to @CssImport from frontend folder, but not loading assets from the same folder?

Ok, I misunderstood that you meant that the css referenced resources were in `node_modules`. This also shows why it is important to give out all the details and **code** that reproduces the issue so there is nothing misunderstood and the issue can be reproduced.

So it seems like this is a regression, but since there are no reduced example app that reproduces the issue and there is a workaround available, it might not be looked at too soon.

**Comment by caalador** [comment] 2021-04-21 06:49
Could you post the addtional WebPack config that you used.

In case you don't use the Custom Theme feature you can just override the filter without any side effects.

**Comment by pleku** [comment] 2021-06-15 12:32
No steps and code to reproduce the issue so closing it. In case this is still a problem, please open a new issue with those provided.

**Closed by pleku** 2021-06-15 12:32 UTC
Labels: Impact: High, Severity: Major, bug, theming, waiting for author, workaround
