### ISSUE TITLE
ComboBox “addCustomValueSetListener” does not trigger event when custom value is cleared

### ISSUE THREAD

**Issue by MatthieuSKRZYPCZAK** [vaadin/flow#19698] opened 2024-07-12 08:50 UTC
### Description of the bug

When using “addCustomValueSetListener” with a “ComboBox” in Vaadin 24.4.3, no event is triggered when the custom value in the “ComboBox” is cleared. This behavior prevents detecting the clearing of the custom value.

### Expected behavior

An event should be triggered by the “CustomValueListener” when the custom value in the “ComboBox” is cleared, allowing proper handling of this action.

### Minimal reproducible example

```java
@Id("combo")
private ComboBox<String> combo;

combo.addCustomValueSetListener(event -> {
    filter(event.getDetail());
});
```

1. Type a custom value in the “ComboBox” => filter is triggered
2. Clear the content of the “ComboBox” => nothing happened

### Versions

- Vaadin / Flow version: 24.4.3
- Java version: 21
- Browser version: Version 126.0.6478.127 (Build officiel) (64 bits)

**Comment by mcollovati** [comment] 2024-07-12 09:23
@MatthieuSKRZYPCZAK is this the same issue as https://github.com/vaadin/flow-components/issues/6442?
I transferred it to the flow-components repository because it about `ComboBox`

**Comment by mcollovati** [comment] 2024-07-12 09:32
Closing as duplicate of https://github.com/vaadin/flow-components/issues/6442

**Closed by mcollovati** 2024-07-12 09:32 UTC
