### ISSUE TITLE
Radiobutton value is not updated when radiobutton is inside a popup

### ISSUE THREAD

**Issue by jcgueriaud** [vaadin/flow#3983] opened 2018-04-24 10:06 UTC
Hello,

When I bind a bean (with a radiobutton) and show it on a dialog, the radiobutton value is set the first time and never changed.

See my example below.
Steps to reproduce:
Click on "Bind 1"
Click on Open
 "label 1" is selected for radio and combobox
Close the dialog
Click on "Bind 2"
Click on Open
"label 1" is selected for radio (WRONG) and "label 2" is selected for  combobox (OK)

    /**
     * The main view contains a button and a template element.
     */
    @BodySize(height = "100vh", width = "100vw")
    @HtmlImport("styles/shared-styles.html")
    @Route("")
    @Theme(Lumo.class)
    public class MainView extends VerticalLayout {

        private ComboBox<Integer> comboBox;

        private RadioButtonGroup<Integer> radioButtonGroup;

        private Dialog dialog;
        private Button openButton;
        private Button bindButton1;
        private Button bindButton2;

        private final Integer[] data = {0,1,2,3};
        private final String[] dataLabel = {"Label 1","Label 2","Label 3","Label 4"};
        private MyItem item1 = new MyItem(0,0);
        private MyItem item2= new MyItem(1,1);

        private Binder<MyItem> binder = new Binder<>();

        public MainView() {
            dialog = new Dialog();

            radioButtonGroup = new RadioButtonGroup<>();
            radioButtonGroup.setItems(data);
            radioButtonGroup.setRenderer(new ComponentRenderer<>(integer -> new Text(dataLabel[integer])));
            comboBox = new ComboBox<>("Test");
            comboBox.setItems(data);
            comboBox.setItemLabelGenerator(integer -> dataLabel[integer]);
            bindButton1 = new Button("Bind 1");
            bindButton1.addClickListener(event -> {binder.setBean(item1);});

            bindButton2 = new Button("Bind 2");
            bindButton2.addClickListener(event -> {binder.setBean(item2);});

            dialog.add(radioButtonGroup, comboBox);
            openButton = new Button("Open");
            openButton.addClickListener(e -> dialog.open());
            add(bindButton1, bindButton2,openButton);

            binder.bind(comboBox,MyItem::getCombobox,MyItem::setCombobox);
            binder.bind(radioButtonGroup,MyItem::getRadioButtonGroup,MyItem::setRadioButtonGroup);
            setClassName("main-layout");
        }

        private class MyItem {
            private Integer combobox;
            private Integer radioButtonGroup;

            public MyItem(Integer combobox, Integer radioButtonGroup) {
                this.combobox = combobox;
                this.radioButtonGroup = radioButtonGroup;
            }

            public Integer getCombobox() {
                return combobox;
            }

            public void setCombobox(Integer combobox) {
                this.combobox = combobox;
            }

            public Integer getRadioButtonGroup() {
                return radioButtonGroup;
            }

            public void setRadioButtonGroup(Integer radioButtonGroup) {
                this.radioButtonGroup = radioButtonGroup;
            }
        }
    }

**Comment by denis-anisimov** [comment] 2018-05-31 06:32
I cannot reproduce it with the latest rc1 build.
I'm closing it. If you still see this issue please reopen and add more information: which components version you use.

**Closed by denis-anisimov** 2018-05-31 06:32 UTC
Labels: bug, components
