### ISSUE TITLE
NPE Exception in Development Mode on Startup (Random)

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#11961] opened 2021-10-01 09:47 UTC
### Description of the bug / feature

We sometimes get the following exception, just randomly after re-starting a spring boot application with Vaadin 21.x

```log
2021-10-01 11:35:35.604 ERROR 693647 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing /

java.lang.NullPointerException: null
	at com.vaadin.flow.server.VaadinSession.lock(VaadinSession.java:685)
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:212)
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3034)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2747)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

### Versions:
    - Vaadin / Flow version: 21.0.2
    - Java version: 8/11
    - OS version: Ubuntu
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Tomcat
    - IDE (if applicable): IDEA

**Comment by denis-anisimov** [comment] 2021-10-01 10:11
This looks similar to https://github.com/vaadin/flow/issues/11569 and most likely is caused by the https://github.com/vaadin/flow/pull/11304/.
And the latter changes are redone here https://github.com/vaadin/flow/pull/11647.

I don't see how this exception may happen if the environment is not "dirty": most likely you have somewhere serialized the old version of the class and it causes the issues on deserialization.

Clean up the project, make sure nothing from the previous version is used and check it again.
If it happens again I would like to see the exact steps to reproduce: better to use https://github.com/vaadin/skeleton-starter-flow since it will definitely won't contain any collisions.

**Comment by knoobie** [comment] 2021-10-01 10:26
Thanks for looking into this Denis! Sadly it's totally random.. it happens sometimes.. but not really reproducible. I had the same feeling that it could be related to the removal of the serializable behavior of the Vaadin Session. 

I was wondering; is this exception necessary or could there be a missing null check for the newly created session from de-serialization? There is no harm; the application works normally.

**Comment by denis-anisimov** [comment] 2021-10-01 12:30
The deserialized session has no _any_ difference now from the normal session except `UI`s.

The original impl made by Artur made a fake session which dropped and replaced a new "real" session.
That introduced a problem with this fake session since it had no valid state like locks and so on.
That was a hack and it's totally removed.

Now there is no any fake session anymore. The only thing which is done : the `UI`s are not serialized if deserialization option is set.
Since the session is not fake the lock must be set exactly in the same way as it has been done previously.
So there can't be any regression since the behavior is not changed anyhow comparing the previous versions.
The only thing which happens is : `UI`s are either serialized or not. And this may not throw anyhow NPE.

NPE may happen if your project somehow deserialized the old `VaadinSession` object which has been serialized by some other Flow version where Artur's fix has been implemented.
But I don't see what we can do here since we may not control the existing (somewhere cached) old serialized object on your box.

It might be that this caching is done by IDEA so I would recommend to run the project without IDEA, via maven.
Or remove the project from IDE , remove all the cache and reimport it back.
We had a similar report internally and it wasn't an issue in the result: most like caching issue.

**Comment by Artur-** [comment] 2021-10-01 13:51
I also see this from time to time with Vaadin 22. It happens when starting the server
```
2021-10-01 16:45:22.803  WARN 3460 --- [alina-utility-1] com.vaadin.flow.server.VaadinSession     : A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
2021-10-01 16:45:22.812  WARN 3460 --- [alina-utility-1] o.apache.catalina.core.StandardContext   : Exception processing manager [StandardManager[StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]] background process

java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.Lock.lock()" because the return value of "com.vaadin.flow.server.VaadinSession.getLockInstance()" is null
	at com.vaadin.flow.server.VaadinSession.lock(VaadinSession.java:677) ~[flow-server-9.0.vite-SNAPSHOT.jar:9.0.vite-SNAPSHOT]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:204) ~[flow-server-9.0.vite-SNAPSHOT.jar:9.0.vite-SNAPSHOT]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:608) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
```

Not sure if it always starts with `A VaadinSession instance not associated to any service is getting unbound`.

My hunch would be that this is a problem that has "always" been there but it has never surfaced because in most cases the UI has not been serializable and thus deserialization has never ever taken place.

**Comment by denis-anisimov** [comment] 2021-10-01 15:11
OK..........

Then it happens for the session which is deserialized but Servlet container decides that it's expired even before it's used.

And there is in fact already a log message added by you Artur here : https://github.com/vaadin/flow/pull/10458


```
if (service == null) {
            getLogger().warn(
                    "A VaadinSession instance not associated to any service is getting unbound. "
                            + "Session destroy events will not be fired and UIs in the session will not get detached. "
                            + "This might happen if a session is deserialized but never used before it expires.");
```
The `service==null` should just return without any other action.

**Closed** 2021-10-05 08:08 UTC
Labels: bug, Impact: High, Severity: Minor, groomed
