### ISSUE TITLE
Add setEnabled feature for component containers

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#3546] opened 2018-02-13 11:31 UTC
The old framework versions allowed you to e.g. disable a complete form with one call to setEnabled on the layout. V10 doesn't currently allow this, but it would be a great usability feature.

**Comment by pleku** [comment] 2018-02-15 09:24
Duplicate of https://github.com/vaadin/flow/issues/2277

**Closed by pleku** 2018-02-15 09:24 UTC
