### ISSUE TITLE
Cannot invalidate HTTP session from SessionDestroyListener

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#6959] opened 2019-11-15 13:27 UTC
In #6763 it's suggested that HttpSession can be invalidated from Vaadin SessionDestroyListener, however, when the listener is executed the wrapped session is null.

- Expected behavior:
  I should be able to invalidate the HttpSession after some period of inactivity.
- Actual behavior
  The HttpSession is not available after the Vaadin session has been destroyed.

Vaadin 14.0.11

[Example application](https://github.com/vaadin/flow/files/3851644/v14.zip)

The SessionDestroyListener is:
```
	public void serviceInit(ServiceInitEvent event) {
		event.getSource().addSessionDestroyListener(ev->{
			System.out.println("Vaadin session destroyed");
			VaadinSession vsession = ev.getSession();
			WrappedSession wsession = vsession.getSession();
			if (wsession==null) {
				System.out.println("wrapped session is null");
			} else {
				wsession.invalidate();
			}
		});
	}
```

**Comment by denis-anisimov** [comment] 2019-11-18 07:20
That's unfortunately true, the wrapped session in destroyed listener is `null`.
You may use `VaadinRequest.getCurrent().getWrappedSession()` to access it instead.
But this bug is valid anyway.

I would avoid using Spring to reproduce.

Here is my code which I use to reproduce the issue without Spring:

```
@WebServlet(asyncSupported = true, urlPatterns = { "/*" }, initParams = {
        @WebInitParam(name = "closeIdleSessions", value = "true"),
        @WebInitParam(name = "heartbeatInterval", value = "10") })
public class MyServlet extends VaadinServlet {

}

public class VaadinServiceInitListenerImpl
        implements VaadinServiceInitListener {

    @Override
    public void serviceInit(ServiceInitEvent event) {
        event.getSource().addSessionInitListener(
                ev -> ev.getSession().getSession().setMaxInactiveInterval(30));
        event.getSource().addSessionDestroyListener(ev -> {
            System.out.println("Vaadin session destroyed");
            VaadinSession vsession = ev.getSession();
            WrappedSession wsession = vsession.getSession();
            if (wsession == null) {
                System.out.println("wrapped session is null");
            } else {
                wsession.invalidate();
            }
        });
    }

}
```

Also you need `src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener`
file with the content:
`com.vaadin.starter.skeleton.VaadinServiceInitListenerImpl` (I'm using plain `skeleton-starter` project)

**Comment by denis-anisimov** [comment] 2021-07-12 10:18
The provided fix for the PR introduced a regression : Vaadin service tries to remove Vaadin session from HTTP session when HTTP session is invalidated manually.
As a result there is an exception on attribute access ( remove attribute) for the invalidated HTTP session.

So I'm going to revert the fix, reopen the ticket.

After some analysis I can say that the ticket is in fact is kind of invalid:
the scenario is semantically wrong.

The example application in the description closes HTTP  session after 1 minute timeout :
`server.servlet.session.timeout=60`

And the listener for Vaadin session is called _because_ HTTP session is _already_ invalidated.
As a result : there is no reason to invalidate it one more time in the code snippet for `VaadinServiceInitListener`.
Moreover I'm not sure whether this is even correct : call `invalidate` on invalidated HTTP session.
At least `setAttribute`/`removeAttribute` can't be called on invalidated session : it causes an exception.
As a result invalidated HTTP session object is useless : some methods just can't be called at all (otherwise they cause an exception) other methods has no sense to call.

That's why it''s totally OK to return `null` for the `WrappedSession` instance from Vaadin session : the `WrappedSession` is invalidated and it has no any sense to give this invalid object.

So : 
- in this specific scenario the HTTP session is already invalidated and it has no sense to invalidate it one more time. So it has no sense to get HTTP Session object .
- Some methods for invalidated HTTP Session can't be called at all: they throw an exception
- the above code snippet makes sense _ONLY_ if Vaadin session is closed somehow (not HTTP session): in this case HTTP session stays still active and may be closed . But the attached project demoes a different scenario . And I don't see any reason to have `null` for `WrappedSession` when HTTP session is not invalidated but only Vaadin session is closed: the HTTP `session` object is set to `null` in `valueUnbound` method which means that HTTP Session is invalidated.

As a result: the issue demoes semantically incorrect scenario: no need to invalidate already invalidated session.
I agree that the issue exists: you don't expect `null` for HTTP session in vaadin session destroy listener method.
And this should be fixed: javadocs should be updated to say that `VaadinSession::getSession` may return `null` if HTTP session is invalidated to avoid inconsistent API behavior for the invalidated instance.
I will make a PR wit this.

**Closed** 2021-07-20 04:57 UTC
Labels: Impact: Low, Severity: Minor, bug, core
