### ISSUE TITLE
Please provide means to bind sub-properties

### ISSUE THREAD

**Issue by SebastianDietrich** [vaadin/flow#11972] opened 2021-10-03 20:17 UTC
### Description of the bug / feature
When binding domain-objects to the UI, one often needs to bind referred objects as well. This is especially the case when binding embedded @Embeddables.
To achieve this, there are several possibilities as pointed out in [this question](https://vaadin.com/forum/thread/17017417/binder-and-embedded-jpa-valueobjects). None of these possibilities are elegant solutions since they need a lot of (duplicated) boilerplate code (unless one already uses a DTO approach).
A much better solution would be possible if the `@PropertyId` annotation would understand sub-properties using e.g. a "property.sub-property" notation. Right now this does not work (although it does not lead to an error).

### Minimal reproducible example
```
@Entity
public class Person() {
   @NotNull
   private String name;
   @Embedded
   private Address address;
   ...
}

@Embeddable
public class Address() {
   private String city;
   private String country;
   ...
}

public class PersonDialog extends Dialog {
   private TextField name = new TextField("Name");
   @PropertyId("address.city")
   private TextField city = new TextField("City");
   @PropertyId("address.country")
   private TextField country = new TextField("Country");
   ...
   BeanValidationBinder<Person> binder = new BeanValidationBinder<>(Person.class);
   binder.bindInstanceFields(this);
   binder.setBean(person);
   ...
```

### Expected behavior
I would expect all attributes to be bound, also those of the referred address.

### Actual behavior
Only Person.name is bound, neither Person.address.city, nor Person.address.country
No exception or any other indication, that "address.city" and "address.country" could not be bound.

### Versions:
    - Vaadin / Flow version: latest
    - Java version: latest
    - OS version: whatever
    - Browser version (if applicable): whatever
    - Application Server (if applicable): whatever
    - IDE (if applicable): whatever

**Comment by denis-anisimov** [comment] 2021-10-04 07:29
`PropertyId` should work with subproperties.
And we have tests which proves that it works.

As I understand the issue in your example (and issue which is hidden in your request) is: subproperty _may not_ be set if there is no instance of subbean.

In your example  I believe the `Address` instance is `null`  in the `Person` instance.
And binder is unable to instantiate the `Address`  just because there are plenty ways of doing this and they depend every time on the class (yes, in many cases there is a default constructor which can be used to do this but this is not always a case and even in this case the instatiation using this CTOR is not the only way: sometimes it should be initialized in addition).
That's why the subproperty is not bound: the subproperty doesn't exist since the bean which owns the property doesn't exist.

You should set the `Address`  instance by hand and then it should work.

So:
- your current issue is not valid (please confirm). Subproperties can be bound (assuming the limitation described above)
- Yes, it's not really convenient to care about bean instances. You expect that it just work. But this is not a bug and the design is required: there should be a generic SPI/API which allows to instantiate sub-beans _in every possible case_. So if you have very specific need then it should be possible to set some specific instance of "Bean Instantiator" which matches your need. And there can be a default strategy to instantiate the beans (e.g. using a default CTOR via reflection). But this requires an exact design and I would like to see it written. Otherwise the issue will be hanging forever without such design.

**Comment by denis-anisimov** [comment] 2021-10-04 07:30
I also recommend to close this ticket and make a new enhancement with proper description of the design as described in the latest item above.

**Comment by SebastianDietrich** [comment] 2021-10-04 09:15
Hmm - I do already set the Address instance by hand. Even before binding. But maybe I did something wrong since I found no documentation on subproperties with PropertyId:

```
   private TextField name = new TextField("Name");
   @PropertyId("address.city")
   private TextField city = new TextField("City");
   @PropertyId("address.country")
   private Person newPerson = new Person();
   ...
   newPerson.setAddress(new Address());
   ...
   BeanValidationBinder<Person> binder = new BeanValidationBinder<>(Person.class);
   binder.bindInstanceFields(this);
   binder.setBean(newPerson);
   ...
   personRepository.save(newPerson);
```
Unfortuntely only the name is set in the person.

**Comment by SebastianDietrich** [comment] 2021-10-04 09:27
Ahh - sorry, just found the solution.
Binder must be set to scan sub-properties:
`BeanValidationBinder<Person> binder = new BeanValidationBinder<>(Person.class, true);`

**Comment by SebastianDietrich** [comment] 2021-10-04 09:29
So IMHO I can close the ticket. But anyways I would ask you to improve the documentation on binding sub-properties. Should I open a new ticket for that?

**Comment by denis-anisimov** [comment] 2021-10-04 10:48
Yes, please make a ticket in the docs repo: https://github.com/vaadin/docs
This repo contains the documentation and the issue should be addressed there.

**Closed by denis-anisimov** 2021-10-04 10:48 UTC
Labels: waiting for author, groomed

**Comment by SebastianDietrich** [comment] 2021-10-04 15:36
The followup ticket for the docs see https://github.com/vaadin/docs/issues/788
