### ISSUE TITLE
Refreshing data provider of hidden grid corrupts its display

### ISSUE THREAD

**Issue by RazvanML** [vaadin/flow#4536] opened 2018-08-16 23:32 UTC
Vaadin 10.0.3

Have a grid with one or more ComponentColumn. Hide the grid. Issue a data provider  refresh. Show the grid. The grid is rendered in a corrupted fashion. Hide and show the grid again, and it will recover, with the exception of some rows heights. Hide and show again and it will recover completely.

Same behavior is observed if a single item in the data provider is refreshed.

It is essential to have the grid hidden. If the grid is visible, refresh works just fine.

This is how it shall be rendered:
![image](https://user-images.githubusercontent.com/15074581/44240147-d079c480-a18a-11e8-8eb6-48afb1c1d1bd.png)

This is how is being rendered when corrupted:
![image](https://user-images.githubusercontent.com/15074581/44240215-19317d80-a18b-11e8-8f22-5879c9024cf1.png)

Project (maven file and one Java class, minimal code) attached.
[bug.zip](https://github.com/vaadin/flow/files/2295509/bug.zip)

**Comment by denis-anisimov** [comment] 2018-08-17 06:11
Thank you for reporting and short project to reproduce.

I can reproduce it with `10.0.3` but can't reproduce it with SNAPSHOT.
There were a number of recent fixes. And fix for this issue is among of them.

The new platform is not yet released (`10.0.4`) : will be released next week.
Either wait for the next release or SNAPSHOT or use Flow release directly (`1.0.4` is already avaialble).

**Closed by denis-anisimov** 2018-08-17 06:11 UTC
