### ISSUE TITLE
Vaadin Starter not working (Failed to find the following imports in the `node_modules` tree)

### ISSUE THREAD

**Issue by rehoehle** [vaadin/flow#15256] opened 2022-11-23 20:57 UTC
I want to try Vaadin and test it out. But the problem is i have downloaded the starter and some other examples from the documentation and all of them have the same problem.

```
Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/cookieConsentConnector.js
      - @vaadin/flow-frontend/datepickerConnector.js
      - @vaadin/flow-frontend/comboBoxConnector.js
      - @vaadin/flow-frontend/ironListConnector.js
      - @vaadin/flow-frontend/contextMenuTargetConnector.js
      - @vaadin/flow-frontend/loginOverlayConnector.js
      - @vaadin/flow-frontend/messageListConnector.js
      - @vaadin/flow-frontend/ironListStyles.js
      - @vaadin/flow-frontend/notificationConnector.js
      - @vaadin/flow-frontend/selectConnector.js
      - @vaadin/flow-frontend/dialogConnector.js
      - @vaadin/flow-frontend/lit-renderer.ts
      - @vaadin/flow-frontend/lumo-includes.ts
      - @vaadin/flow-frontend/vaadin-big-decimal-field.js
      - @vaadin/flow-frontend/gridProConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/dndConnector-es6.js
      - @vaadin/flow-frontend/menubarConnector.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
      - @vaadin/flow-frontend/confirmDialogConnector.js
      - @vaadin/flow-frontend/virtualListConnector.js
  If the build fails, check that npm packages are installed.

  To fix the build remove `package-lock.json` and `node_modules` directory to reset modules.
  In addition you may run `npm install` to fix `node_modules` tree structure.
```

So i have deleted the files and the node folder and run it again and npm was working well with no errors. After running die Application the same error appears again. 

Vite is started and then there are a lot of dependencies that are not found. 

```
The following dependencies are imported but could not be resolved:
    
@vaadin/flow-frontend/vaadin-dev-tools.js (imported by /Users/rene.hoehle/IdeaProjects/testcenter/my-todo/frontend/generated/vaadin.ts)
...

ERROR(TypeScript)  Cannot find module '@vaadin/flow-frontend/Flow' or its corresponding type declarations.
17 | import { Flow } from '@vaadin/flow-frontend/Flow';

```

I run a Macbook Pro with M1 Pro.
NodeJS 18.12.1 LTS with the NPM version
MacOS 13.0.1
Java 11 or 17 both doesn't work

Is this a OSX problem? Or can anyone toll me how i can run the application?

**Comment by caalador** [comment] 2022-11-24 06:00
I got this once in the morning, but at that time npm didn't install anything to node_modules which is the reason why it didn't work, but I couldn't see what happened as the log was longer than the commandline buffer.
There have been some outage reports on npm repository yesterday/during the night, but can't say if they could be the issue.

Does it work today or if you drop from 23.2.9 to 23.2.8?

**Comment by rehoehle** [comment] 2022-11-24 08:46
I have started this before some days and have this problem since 2 days now. I have tried it now and have the same problem. 

`Failed to find the following imports in the `node_modules` tree:`

There is something a bit broken. 

After downgrade to 23.2.8. He was updating npm but same error.

**Comment by caalador** [comment] 2022-11-24 09:10
Is there some error output right in the beginning after `Running 'npm install' ...`?
Does the `node_modules` folder get generated and populated at all?
We have at least one snapshot build (9.0) that is getting lots of file missing like `npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/.../node_modules/lodash/uniqWith.js'` which would point to a broken npm archives.

But not seeing that for any of the 23 series snapshots.

**Comment by mshabarov** [comment] 2022-11-24 10:36
@rehoehle thanks for the issue!
Running a fresh starter from start.vaadin.com for Vaadin 23 gave the the following output, nothing suspicious I could see so far:
```
2022-11-24 12:25:34.100  INFO 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2022-11-24 12:25:34.165 DEBUG 6600 --- [onPool-worker-1] c.v.flow.server.frontend.FrontendTools   : Using node 18.9.0 located at XXX/.nvm/versions/node/v18.9.0/bin/node
2022-11-24 12:25:34.391  INFO 6600 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2022-11-24 12:25:34.400 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Atmosphere available, initializing
2022-11-24 12:25:34.400 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Checking if springServlet is a Vaadin Servlet
2022-11-24 12:25:34.400 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Initializing Atmosphere for Vaadin Servlet: springServlet
2022-11-24 12:25:34.400 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Creating AtmosphereFramework for springServlet
2022-11-24 12:25:34.460 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Created AtmosphereFramework for springServlet
2022-11-24 12:25:34.460 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.JSR356WebsocketInitializer     : Checking if dispatcherServlet is a Vaadin Servlet
2022-11-24 12:25:34.489  INFO 6600 --- [  restartedMain] c.v.f.s.DefaultDeploymentConfiguration   : 
Vaadin is running in DEVELOPMENT mode - do not use for production deployments.
2022-11-24 12:25:34.514 DEBUG 6600 --- [  restartedMain] c.v.f.s.c.PushRequestHandler             : Using pre-initialized Atmosphere for servlet springServlet
2022-11-24 12:25:34.515 DEBUG 6600 --- [  restartedMain] c.v.flow.server.VaadinServletService     : Using 'com.vaadin.flow.server.communication.IndexHtmlRequestHandler' in client mode bootstrapping
2022-11-24 12:25:34.519 DEBUG 6600 --- [  restartedMain] com.vaadin.flow.server.VaadinService     : The application has the following routes: 
2022-11-24 12:25:34.526 DEBUG 6600 --- [  restartedMain] com.vaadin.flow.server.VaadinService     : RouteData{parentLayout=class com.example.application.views.MainLayout, url='about', parameters={}, navigationTarget=class com.example.application.views.about.AboutView, routeAliases=[]}
2022-11-24 12:25:34.528 DEBUG 6600 --- [  restartedMain] com.vaadin.flow.server.VaadinService     : RouteData{parentLayout=class com.example.application.views.MainLayout, url='hello', parameters={}, navigationTarget=class com.example.application.views.helloworld.HelloWorldView, routeAliases=[RouteData{parentLayout=class com.example.application.views.MainLayout, url='', parameters={}, navigationTarget=class com.example.application.views.helloworld.HelloWorldView}]}
2022-11-24 12:25:34.531  INFO 6600 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-11-24 12:25:34.541  INFO 6600 --- [  restartedMain] com.example.application.Application      : Started Application in 2.83 seconds (JVM running for 3.225)
2022-11-24 12:25:34.910  INFO 6600 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-11-24 12:25:34.910  INFO 6600 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-11-24 12:25:34.911  INFO 6600 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-11-24 12:25:36.337 DEBUG 6600 --- [onPool-worker-1] c.v.flow.server.frontend.FrontendTools   : Using npm 8.19.1 located at XXX/.nvm/versions/node/v18.9.0/bin/npm
2022-11-24 12:25:37.179 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : 
XXX/.nvm/versions/node/v18.9.0/bin/npm \ 
    --no-update-notifier --no-audit \ 
    --scripts-prepend-node-path=true --ignore-scripts \ 
    install 

2022-11-24 12:25:37.179  INFO 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : using 'XXX/.nvm/versions/node/v18.9.0/bin/npm --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
2022-11-24 12:25:37.179  WARN 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : package-lock.json is missing from this project. This may cause the npm package installation to take several minutes. It is recommended to keep the package-lock.json file persistently in your project. Please stand by...
2022-11-24 12:25:37.183 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : Output of `XXX/.nvm/versions/node/v18.9.0/bin/npm --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install`:
2022-11-24 12:26:15.518 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : 
2022-11-24 12:26:15.518 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : added 560 packages in 38s
2022-11-24 12:26:15.518 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : 
2022-11-24 12:26:15.518 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : 66 packages are looking for funding
2022-11-24 12:26:15.518 DEBUG 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      :   run `npm fund` for details
2022-11-24 12:26:15.543  INFO 6600 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : Frontend dependencies resolved successfully.
```

So does the project run well on your side now, since `npm` now says `added 559 packages, and audited 560 packages in 15s` ?

**Comment by rehoehle** [comment] 2022-11-24 10:47
@mshabarov no thats the interest think i have done this some times but it's not working. Now i have removed the complete ".npm" folder to test. I run NPM 9.1.2 (suggestion to install because it was outdated). So i have reinstalled the complete node runtime from the website. Now i have NPM 8.19.2 with node 8.19.2 and it's working. So NPM 9.x seems to be the problem. 

**Summary:** Vite has some problems with NPM 9.x?

Thanks for your help now i can make some tests and play with it.

**Comment by mshabarov** [comment] 2022-11-24 11:57
@rehoehle thanks for summary. Indeed, we had an issues recently running our builds with npm 9 . Please use npm 8, while we figure out what we need to run well on 9. By the way, if you don't have Node installed globally, Vaadin will install and use it in a background, so the auto-installed version guarantee that the project builds and run as expected.

**Comment by tepi** [comment] 2022-12-22 07:19
Retested on macOS using Vaadin 23.3.1 and NPM 9.2.0, no issues running the starter either in development or production mode.

**Comment by tepi** [comment] 2023-01-10 13:30
Closing this as not reproducible. Please re-open the ticket if the issue persists.

**Closed by tepi** 2023-01-10 13:30 UTC
Labels: waiting for author, node/npm/pnpm
