### ISSUE TITLE
expose theme in components API when the element extends ThemableMixin

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3663] opened 2018-03-08 07:17 UTC
For setting the theme of a component using java, you need to use `component.getElement.setAttribute("theme", "foo")` without knowing whether the element supports theming. It would be nice if themable elements have a `component.setTheme("foo")` method.

**Comment by Legioth** [comment] 2018-03-09 08:41
Duplicate of https://github.com/vaadin/flow/issues/3520

**Closed by Legioth** 2018-03-09 08:41 UTC
