### ISSUE TITLE
Regression: Combobox setValue not working when combobox not displayed

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2930] opened 2017-11-15 12:18 UTC
The bug described at the issue #2547 is back in Flow, and the internal tests didn't catch it.

A fix for the element was released as part of https://github.com/vaadin/vaadin-combo-box/issues/554 , but somehow the bug is still present when using the Flow component.

**Comment by asashour** [comment] 2017-11-28 09:21
I guess it is because `selectedItem` is set before `items`.  Should this be fixed by the the web component, `Flow` or `ComboBox`? Should we have property rank?

**Comment by asashour** [comment] 2017-12-08 18:30
A PR was raised to fix this in https://github.com/vaadin/vaadin-combo-box/pull/585

The Flow test case is below, if I correctly understand:

```
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("AAA", "CCC", "BBB");
        comboBox.setValue("CCC");
        addCard("String selection", comboBox);

        NativeButton div = createMessageDiv("myDiv");
        div.addClickListener(event -> comboBox.setValue("BBB"));
        add(div);

```

**Comment by pleku** [comment] 2018-01-11 09:39
There is _soon_ a new `vaadin-combo-box` release that will have this fix.

**Comment by denis-anisimov** [comment] 2018-01-13 09:30
I cannot reproduce this.
Neither of two code snippets below reproduces the issue:
```
ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("a", "b");

        comboBox.setValue("b");
        NativeButton button = new NativeButton("Show Combo",
                event -> add(comboBox));
        add(button);
```

```
ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("a", "b");

        comboBox.setValue("b");
        add(comboBox);
```

In both cases I see "b" as a selected item in the combo-box.

**Comment by denis-anisimov** [comment] 2018-01-13 09:30
If the issue is still there please reopen with exact code snippet to reproduce.

**Comment by denis-anisimov** [comment] 2018-01-13 09:33
Technically this is the issue in the combo-box and it's the duplicate of vaadin-combo-box-flow#37.
So I'm closing this issue as a duplicate and copy my comments there.

**Comment by manolo** [comment] 2018-01-19 10:10
This should be reopened, the problem is not only in combo-box, it is also in date-picker, hence it should be an issue in flow

You can reproduce it by checking out bakery:

```
git clone git@github.com:vaadin/bakery-app-starter-flow-spring.git
mvn clean spring-boot:run
```

Then edit a order like it's shown in the screenshot, and you can see that date-picker and combo-boxes are correctly updated when the dialog is attached to the dom

![1](https://user-images.githubusercontent.com/161853/35145734-33ab0a0e-fd09-11e7-845a-9a861f5723f8.gif)


Then comment out the workarounds in `DatePickerForBinder.java` and `ComboBoxForBinder` as it's shown in the next image

![2](https://user-images.githubusercontent.com/161853/35145750-4288a478-fd09-11e7-9d2e-d7e30e946017.gif)

Reload the app, and try to edit again an order, and you can see that neither date-picker or combo-boxes values are set.

![3](https://user-images.githubusercontent.com/161853/35145759-4767f2b4-fd09-11e7-9794-d535910751e8.gif)

**Comment by caalador** [comment] 2018-01-24 12:02
Does not reproduce after update to Vaadin-Platform version 10.0.0.alpha14

Also theming was kept almost as was after replacing all 'valo' names with 'lumo' and adding `@Theme(Lumo.class)` to BakeryApp

**Closed by caalador** 2018-01-24 12:02 UTC
Labels: app starter, bug, components, duplicate, external dependency

**Comment by manolo** [comment] 2018-01-24 13:08
we are in the process of upgrading the platform, I'll check after that.
Thanks also for the Theme tip.

**Comment by manolo** [comment] 2018-02-01 10:49
works in master, thanks
