### ISSUE TITLE
Unable to navigate to a route containing a space

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7454] opened 2020-01-31 09:39 UTC
```
@Route
public class MainView extends VerticalLayout {

    public MainView(@Autowired GreetService service) {
        add(new RouterLink("Space man", SpaceMan.class));
    }

}
```
```
@Route("space man")
public class SpaceMan extends VerticalLayout {

    public SpaceMan() {
        add(new Button("Space man"));
    }
}
```

If you open http://localhost:8080/ and click on the link, you end up on 
```
Could not navigate to 'space%20man'

Available routes:
<root>
space man
```

If you refresh, the view is shown correctly

**Comment by denis-anisimov** [comment] 2020-08-04 11:12
Confirmed.
Interestingly the reload doesn't help me in `4.0`.

**Comment by bogdanudrescu** [comment] 2020-09-21 08:32
Duplicate of https://github.com/vaadin/flow/issues/3462

**Comment by denis-anisimov** [comment] 2020-10-02 07:34
There is a PR for this which is failing.
I'm going to  close it since I don't understand how to fix this.
Even though the fix itself is very easy but the code is extremely not localized and it's not clear where the fix should be done.
Every time when I try to fix some test sone other is failing.

Here are the issues with the code:
- It's not clear whether the path and parameter which are passed into Location CTOR are encoded or not (it seems both cases are possible: as a result decoding can't be done unconditionally).
- we have almost contradictory tests : RouterTest::resolveNavigation_pathContainsDots_dotSegmentIsNotParentReference_noException and RouterTest::resolveNavigation_pathContainsDots_pathIsRelative_noException checks that URL with dots is working but on the other hand LocationTest has tests which test opposite things. The reason is : `Router::getLocationForRequest`  which constructs `Location` twice. One CTOR may fail but another encodes the URL. As a result I don't understand assumptions about how Location CTOR is called.
- the PR tries to call Location CTOR without decoding in the special case but overall fails in IT `FaultyLocationIT`. It turns out that `JavaScriptBootstrapUI`  uses direct Location CTOR without any encoding. And some `JavaScriptBootstrapUI` methods are called on router navigation.

So for me it looks like Location contract is very messy , not localized (encode/decode is called from various parts of the code without any connection between each other) .
I don't understand how to fix it properly without introducing regressions.

I would say that Location contract has to be clarified: it should be obvious when it's called with encoded data and when it's called with decoded (or raw data). Technically it relates to the fact that navigation can be done programmatically  (and then ANY string may be passed as an argument to the Location CTOR) and when navigation is done being initiated from the browser (in this case everything is encoded).

And it should be absolutely clear when one or another Location CTOR should be called. Also encoding/decoding should not be spread out all over the code in different classes but should be inside one class: Location.

**Closed** 2022-12-13 09:41 UTC
Labels: bug, Impact: Low, Severity: Minor
