### ISSUE TITLE
Vaadin Flow 24.3.2 - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dbMe1** [vaadin/flow#18541] opened 2024-01-26 05:01 UTC
### Description of the bug

Intermittently when I sort my grid, or drag a column of my grid I get:

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$getJsonItems$7(DataCommunicator.java:1441) ~[flow-data-24.3.2.jar:24.3.2]
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[na:na]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[na:na]
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:1443) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:1381) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.provider.DataCommunicator.performUpdate(DataCommunicator.java:1261) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1215) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$7258256f$1(DataCommunicator.java:1120) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$2(StateTree.java:397) ~[flow-server-24.3.2.jar:24.3.2]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:392) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:394) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:170) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.communication.UidlRequestHandler.createUidl(UidlRequestHandler.java:155) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:145) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1573) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.3.2.jar:na]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.17.jar:6.0]

### Expected behavior

Vaadin should never throw an IndexOutOfBoundsException

### Minimal reproducible example

It is intermittent

### Versions

- Vaadin / Flow version: 24.3.2
- Java version: 17
- OS version: Windows 10
- Browser version (if applicable): Chrome Version 120.0.6099.227 (Official Build) (64-bit)
- Application Server (if applicable): Spring Boot 3.2.1
- IDE (if applicable): Intelli-J

**Comment by mshabarov** [comment] 2024-01-30 11:15
Thanks for the issue!
We have a bunch of similar issues in Flow. Last time we couldn't reliably reproduce it and, thus, closed.
Let us revisit this problem again and at least add some logging for better debugging.

**Comment by mcollovati** [comment] 2024-02-08 12:09
@dbMe1 I'm currently not able to reproduce the issue. Could you provide some additional details about your configuration?
For example, it would be helpful to know the Grid configuration (sharing the code if possible), how you load data into (e.g. which kind of DataProvider), if you enabled PUSH updates on the DataCommunicator, etc.

**Comment by dbMe1** [comment] 2024-02-08 23:57
Thanks for trying to help.
For me it happens if I try to sort a column on the grid, extremely rapidly by clicking the column's sort link repeatedly as quickly as I can.
Once it happens I get the standard "box" error in the UI (it says to click the box to continue, which I do, and the box goes away).
And after that it does not happen again for that grid of data.

So I see it only with new grids, and then only if I click like crazy as I described.

I used the Vaadin doc examples for my grid code (I have DataCommon which is a POJO object) and it works fine with thousands of rows of data.
The issue comes only if I try to hammer the sorting on a freshly populated grid (like 2 rows of data).

Some of the relevant code from my app:

`
Grid<DataCommon> grid = new Grid<>(DataCommon.class, false);
grid.setPageSize(80);
grid.setMultiSort(true);

DataProvider<DataCommon, DataCommon> dataProvider = DataProvider.fromFilteringCallbacks(

        query -> { // this is the CallbackDataProvider.FetchCallback (it gives a page of data)

          Pageable page = getPage(query);

          Collection<DataCommon> data = CollectionUtil.cast(dataService.find(gridFilter, page),
              DataCommon.class);

          return data.stream();

        },

         query -> { // this is the CallbackDataProvider.CountCallback
          // (it gives the total count across all pages)
		return dataService.getCount(gridFilter);
         }
);

ConfigurableFilterDataProvider<DataCommon, Void, DataCommon> dp = dataProvider.withConfigurableFilter();
dp.setFilter(gridFilter);
grid.setDataProvider((DataProvider<T, ?>) dp);

`

I do not have @Push or any other push enabled that I know of.

**Comment by dbMe1** [comment] 2024-02-09 01:26
I can add that this happens even if I am running locally, using localhost to access, and using in-memory DB (also happens in PROD where app and DB are in different data centers both in same state, but is different state than where I am).

So I don't think it has much to do with latency.

**Comment by mcollovati** [comment] 2024-02-09 07:09
@dbMe1 Thanks for info. Do you mind sharing also the `dataService.find(...)` and `dataService.getCount(...)` implementation?
I could reproduce the issue, but only implementing a buggy DataProvider that returns an empty stream for a valid fetch request.

**Comment by mcollovati** [comment] 2024-02-09 08:51
I see that in the callback, you are using a filter to a `gridFilter` object.
Could you try to get the value for the `query` instance (`query.getFilter()`) and see if something changes?

**Comment by dbMe1** [comment] 2024-02-11 07:12
here is the find method, probably not for the faint of heart:

``'java
public Collection<DataCommon> find(DataCommon probe, Pageable page) {
  
    Example example = Example.of(probe, probe.getExampleMatcher());
    Criteria crit = Criteria.byExample(example);
    MatchOperation matchOperation = match(crit);
    Sort sortOrig = page.getSort();
    SortOperation sortOperation = Aggregation.sort(sort); 

    SkipOperation skipOperation =
          page.isPaged() ? skip((long) page.getPageNumber() * page.getPageSize()) : null;

      LimitOperation limitOperation = page.isPaged() ? limit(page.getPageSize()) : null;

     Collection<AggregationOperation> aggOpsSortAndPage = CollectionUtil.ofList(
            sortOperation
          , skipOperation
          , limitOperation
      );

      FacetOperation facet = facet()
          .and(aggOpsSortAndPage.toArray(new AggregationOperation[0]))
          .as(FIELD_NAME_FACET_PAGE_OF_RESULTS);

     ProjectionOperation projections =  project()

          .and(FIELD_NAME_FACET_PAGE_OF_RESULTS)
          .as(PROJECTION_NAME_RESULTS);

    TypedAggregation aggregation = Aggregation.newAggregation(probe.getClass()
          , matchOperation
          , facet
          , projections);

      AggregationResults<Map> aggResults = mongoTemplate.aggregate(aggregation, Map.class);

      Map<String, Object> map = aggResults.getMappedResults().get(0);

      for (Map.Entry<String, Object> entry : map.entrySet()) {
        String key = entry.getKey();
        if (PROJECTION_NAME_RESULTS.equals(key)) {
          return (Collection<DataCommon>) entry.getValue();
      }
    }

    return null;
    
}
'''

and the getCount method:

```java
 public long count(T probe) {
    Criteria crit = getCritMatching(probe);
    return mongoTemplate.count(Query.query(crit), probe.getClass());
  }
```

**Comment by dbMe1** [comment] 2024-02-11 07:30
I tried using query.getFilter instead of usind the gridFilter directly and while that works fine too, it did not fix the issue.
In fact to me it seemed to make it occur sooner.

For clarity here is the error I get in the UI:

![image](https://github.com/vaadin/flow/assets/151983573/2da2c3a5-b3a2-4018-aea8-e0cbaf76a0b2)

**Comment by mcollovati** [comment] 2024-02-11 09:19
What I can see from Flow code is that the error may happen when the count query returns a number greater than zero, but the fetch query returns an empty stream.

At a first look, I can't see nothing suspicious on your code.

Could you please add some logs in your fetch and count callbacks, to ensure the values are consistent?

If the data is correct we need to further investigate, because I am currently unable to reproduce the issue.

**Comment by dbMe1** [comment] 2024-02-12 18:33
Thanks, this gives me a trail to follow.
I'll update here if it leads to anything worth knowing.

Matt M.

**Comment by dbMe1** [comment] 2024-02-16 03:44
I got this fixed thanks to your tip.
I had been storing the 1st page of results in a ThreadLocal and pulling that to save a DB round-trip.
I changed to save it into the request scope and now the issue seems to have gone away.
I never did see any proof in my logs to support what you thought might be happening (non-zero for record count, but zero records returned)  but your input definitely helped me shake this one loose.

Thanks again!

**Comment by dbMe1** [comment] 2024-02-16 03:46
BTW I used to do lots of this sort of prod support (a servlet/JSP Engine actually) and as I'm sure you suspect, I definitely was not showing you all the crazy stuff I am doing in my code.
Haha!

**Comment by mcollovati** [comment] 2024-02-16 08:02
@dbMe1 I'm glad you were able to fix the problem.
I created a PR that will add a log message if there are data size inconsistency during flush operation.
I'll close the issue.

**Closed by mcollovati** 2024-02-16 08:02 UTC
Labels: data provider, investigation, waiting for author

**Comment by dbMe1** [comment] 2024-02-26 01:57
I had some thoughts about why changing my app to cache data inside the request object/scope instead of inside a java language ThreadLocal has fixed this issue.
I think it might mean that when Vaadin invokes the 2 lambda's I provide in my DataProvider (1 to get the count and the other to get a page worth of data)... Vaadin, it seems to me is sometimes using separate threads to invoke each lambda.

I'm not saying that both threads would ever be going at the same time b/c u have to know the count before you can ask for the 1st page, but I do suspect that once Vaadin knows the count, it may sometimes use a different thread to ask for the 1st page of data.

I'm thinking that is the only explanation why myThreadLocal approach would sometimes fail. 
I was assuming that whatever thread Vaadin uses to ask for the count, it would surely use the same one to ask for the 1st page of data... but maybe not.

**Comment by mcollovati** [comment] 2024-02-26 07:19
Having count and fetch executed in different threads happens with `enablePushUpdates` active.

**Comment by dbMe1** [comment] 2024-02-29 01:44
Very interesting.
enablePushUpdates... would that be like if I had @Push in my app (which I do)?
As I understand I need @Push in order to inject Javascript into the client from java (which I do).
Regardless it just sounds like my hunch was correct.

Storing my cached data into the ServletRequest scope works fine b/c multiple threads will see the same data in that scope.
My issue was that I was caching data in a java language ThreadLocal which only the thread that inserted the data there can also see/read it. So 1 thread would write it the cache and the different thread could never see it, hence the issue.

Once again the problem is what the dude was doing inside your stuff (not your stuff).
I know that dance too well.

Take care.

**Comment by mcollovati** [comment] 2024-02-29 06:31
Usually, updates on the UI happens as consequence of a client request. You need `@Push` when you want the server to update the client autonomously, without the need of a client request.
