### ISSUE TITLE
Project goes into bower mode for no apparent reason

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#6038] opened 2019-07-08 20:44 UTC
Vaadin 14 rc3
OpenJDK 11
Plain Java starter from vaadin.com/start

I imported the project, ran `mvn clean package`, added a design with a Java companion file
When starting the project, I get
```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'hello-world' in any template file declared using @'HtmlImport' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
```

The app is running in bower mode and fails. 

Restarting the app without any changes made it run in npm mode.

**Comment by mehdi-vaadin** [comment] 2019-07-09 15:24
I couldn't reproduce it. Would you please share more details about what you did? Sharing the code would be helpful.

**Comment by pleku** [comment] 2019-08-21 08:50
No updates for a while so closing this issue. Please reopen & comment if this still occurs.

**Closed by pleku** 2019-08-21 08:50 UTC
Labels: waiting for author
