### ISSUE TITLE
Maven Install Does not build a successfull executable jar

### ISSUE THREAD

**Issue by webnazar** [vaadin/flow#6789] opened 2019-10-26 06:32 UTC
Sir/Madam,

When I am trying to build maven install of spring boot application, It generates jar but when i click on jar instead of running it busy in supporting file downloads and then nothing will happen.

it working fine up to Vaadin 14.0.8, but not working 14.0.9, and 14.0.10 etc....

**Comment by mehdi-vaadin** [comment] 2019-11-22 13:38
@webnazar Would you please test your app with Vaadin 14.0.13 and see if the problem is solved?

**Comment by mehdi-vaadin** [comment] 2019-11-27 14:58
@webnazar I'm afraid I have to close this as we didn't receive any response from you. Please reopen it if you could give us more info.

**Closed by mehdi-vaadin** 2019-11-27 14:58 UTC
Labels: waiting for author
